### ISSUE TITLE
Feature: swipeDirection

### ISSUE THREAD

**Issue by sitefinitysteve** [telerik/nativescript-ui-feedback#1]
per: http://www.telerik.com/forums/prevent-swipe-direction

On the listview mode the ability to specify swipe direction as a quick XML setting

``` xml
swipeDirection="Any"
swipeDirection="Right"
swipeDirection="Left"
```

**Comment by ginev** [comment]
This is done via the swipe limits API: http://docs.telerik.com/devtools/nativescript-ui/api/classes/swipelimits.html
