### ISSUE TITLE
How to hide scroll indicator in horizontal scroll radlistview nativescript angular?

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [telerik/nativescript-ui-feedback#1007]
Iam working application for android and ios.Iam using radlistview for showing list items horizontally.While scrolling horizontally the scroll indicator was not hide in ios platform but in android it was hide.How to fix the issue for ios?

**Comment by tsonevn** [comment]
Duplicate of https://github.com/telerik/nativescript-ui-feedback/issues/752
