### ISSUE TITLE
Angular + NativeScript + RadListView + Rotating Device = crash

### ISSUE THREAD

**Issue by zurie** [telerik/nativescript-ui-feedback#1014]
I have a RadListView +  ( RadSideDrawer + RadListView)

When I rotate my iOS device and trigger an orientation change the application crashes.

### Which platform(s) does your issue occur on?
_iOS/ 5.1.1 RadListView - 5.1.0 SideDrawer -   5.1.1 NS    -   7.2.0 angular

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** (the version of nativescript-telerik-ui/-pro in the `package.json`)
    "nativescript-ui-listview": "^5.1.1",
    "nativescript-ui-sidedrawer": "^5.1.0",

- **CLI:** (run `tns --version` to fetch it)
5.1.1

- **Cross-platform modules:** (the version of tns-core-modules in the `package.json`)
    "tns-core-modules": "^5.2.0",

- **Runtime(s):** (the `"tns-android"` and `"tns-ios"` properties in the `package.json`)
    "tns-android": {
      "version": "5.1.0"
    },
    "tns-ios": {
      "version": "5.1.1"
    }

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application ..
2. Rotate a large list of UIView Items with a template selector, and a sidebar with a RadListView

```
CONSOLE LOG file:///app/tns_modules/@angular/core/bundles/core.umd.js:16863:24: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x10f536d3b NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool, bool)
2   0x10f564e80 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x10fe81656 ffi_closure_unix64_inner
4   0x10fe8207a ffi_closure_unix64
5   0x1115d7961 -[TKListViewCell preferredLayoutAttributesFittingAttributes:]
6   0x11363598d -[UICollectionReusableView _preferredLayoutAttributesFittingAttributes:]
7   0x113600a26 -[UICollectionView _checkForPreferredAttributesInView:originalAttributes:]
8   0x113607880 -[UICollectionView _updateVisibleCellsNow:]
9   0x113607fe9 -[UICollectionView _updateVisibleCellsNow:]
10  0x113607fe9 -[UICollectionView _updateVisibleCellsNow:]
11  0x113607fe9 -[UICollectionView _updateVisibleCellsNow:]
12  0x113607fe9 -[UICollectionView _updateVisibleCellsNow:]
13  0x113607fe9 -[UICollectionView _updateVisibleCellsNow:]
14  0x113607fe9 -[UICollectionView _updateVisibleCellsNow:]
15  0x113607fe9 -[UICollectionView _updateVisibleCellsNow:]
16  0x113607fe9 -[UICollectionView _updateVisibleCellsNow:]
17  0x113607fe9 -[UICollectionView _updateVisibleCellsNow:]
18  0x113607fe9 -[UICollectionView _updateVisibleCellsNow:]
19  0x113607fe9 -[UICollectionView _updateVisibleCellsNow:]
20  0x113607fe9 -[UICollectionView _updateVisibleCellsNow:]
21  0x113607fe9 -[UICollectionView _updateVisibleCellsNow:]
22  0x113607fe9 -[UICollectionView _updateVisibleCellsNow:]
23  0x113607fe9 -[UICollectionView _updateVisibleCellsNow:]
24  0x113607fe9 -[UICollectionView _updateVisibleCellsNow:]
25  0x113607fe9 -[UICollectionView _updateVisibleCellsNow:]
26  0x113607fe9 -[UICollectionView _updateVisibleCellsNow:]
27  0x113607fe9 -[UICollectionView _updateVisibleCellsNow:]
28  0x113607fe9 -[UICollectionView _updateVisibleCellsNow:]
29  0x113607fe9 -[UICollectionView _updateVisibleCellsNow:]
30  0x113607fe9 -[UICollectionView _updateVisibleCellsNow:]
31  0x113607fe9 -[UICollectionView _updateVisibleCellsNow:]
JavaScript stack trace:
1   measureCell@file:///app/tns_modules/nativescript-ui-listview/ui-listview.js:1633:38
2   layoutCell@file:///app/tns_modules/nativescript-ui-listview/ui-listview.js:1619:50
3   systemLayoutSizeFittingSize@file:///app/tns_modules/nativescript-ui-listview/ui-listview.js:810:46
4   UIApplicationMain@[native code]
5   start@file:///app/tns_modules/tns-core-modules/application/application.js:275:26
6   run@file:///app/tns_modules/tns-core-modules/application/application.js:303:10
7   bootstrapNativeScriptApp@file:///app/tns_modules/nativescript-angular/platform-common.js:188:26
8   bootstrapApp@file:///app/tns_modules/nativescript-angular/platform-common.js:106:38
9   bootstrapModule@file:///app/tns_modules/nativescript-angular/platform-common.js:90:26
10  anonymous@file:///app/main.js:6:57
11  evaluate@[native code]
12  moduleEvaluation@[native code]
13  promiseReactionJob@[native code]
JavaScript error:
file:///app/tns_modules/nativescript-ui-listview/ui-listview.js:1633:38: JS ERROR RangeError: Maximum call stack size exceeded.
```

**Comment by NickIliev** [comment]
@zurie I've tested the scenario via [this test app](https://github.com/NickIliev/NS-Issues-2019-I/tree/master/nativescript-ui-feedback/issue-1014) but was not able to reproduce the issue. Please use the linked app as a reference and let us know if there is additional code that needs to be introduced to hit this one (or provide your own sample app).

**Comment by fhackenb** [comment]
@zurie Did you figure out what was happening? I'm experiencing a similar issue on a RadListView page. Other pages w/o RadListView are not crashing when rotating

**Comment by zurie** [comment]
I know that I was using async,  and a template to drive 2 seperate types of Cell.  One with an image and one without.   When I downloaded @NickIliev template I was unable to make his crash.  I started to merge over my code piece by piece and try to crash it but I ran into trouble with the templates and for some reason wasn't able to get my template code to work and it was taking alot of time so i paused there and ended up getting sucked into another project, but if anyone wants to experiment with async and multiple templates? 

the other thing was that I was displaying 2 RadListViews (both with the same data) think Launchscreen and SideMenu with the RadSideDrawer.   so when I rotated, i was rotating 2 RadListViews (one in the sidebar, one in the main view).  Main view used a template switcher .  both were async.

I had crashes with that.   Does your code share any similarities?  Do you have a RadListDrawer? Do you have 2 radlists? do you have async? do you have templates?   perhaps that is the issue?

you can download the sample and try to make it crash putting in your code.   I am almost certain its something with the JS maxing out, but I wasn't 100% sure if it was my bad code or not.

**Comment by yugank1991** [comment]
@zurie I also have same issue when use RadListView. Have you got any solution for it?

**Comment by RacknerFrank** [comment]
Upgrade to nativescript-ui-listview@6.4.2 https://github.com/NativeScript/nativescript-ui-feedback/issues/1056
