### ISSUE TITLE
[RadListView] LoadOnDemand breaks when second call is called in iOS on a Modal Window

### ISSUE THREAD

**Issue by relez** [telerik/nativescript-ui-feedback#1018]
Hi guys, I am trying to create a list of items to select one of them inside a Modal Window using LoadOnDemand for performance and before the second page is loaded it does not bring anything and the loading icon doesnt hide.
I make sure that `listView.notifyLoadOnDemandFinished();` is called too.
It works on Android as expected.

![simulator screen shot - iphone xs - 2019-02-13 at 15 15 25](https://user-images.githubusercontent.com/3420851/52743264-a3766500-2fa7-11e9-96cd-21d2d8540348.png)

Can you take a look at it? 

Thanks!

**Comment by tsonevn** [comment]
Hi @relez,
Can you send us a sample project, that can be used for recreating the issue?

**Comment by relez** [comment]
Hello @tsonevn, sorry for the delay, I have created a sample app so you can see the issue. It works perfect on Android, not in iOS.

[https://github.com/relez/ns-radlistview-ng.git](https://github.com/relez/ns-radlistview-ng.git)

Thanks.

**Comment by tsonevn** [comment]
Hi @relez,
Thank you for the project.
I reviewed it and found that you need to call `notifyLoadOnDemandFinished` with some delay after adding the new items in the array. For example:
```
setTimeout(() => {
            listView.notifyLoadOnDemandFinished(); 
        }, 1000);
```
This will hide the activity indicator and you will be able to load more items when you reach the bottom of the ListView.
