### ISSUE TITLE
Drag and Drop Border

### ISSUE THREAD

**Issue by NathanaelA** [telerik/nativescript-ui-feedback#102]
Anyway to customize the element when it gets picked up.   My client would like a thick border added on the top/bottom.

**Comment by ginev** [comment]
@NathanaelA , can you please specify which component are you using? In case you are targeting the item-reorder feature on RadListView, I suggest you try using the `itemReorderStarted` and `itemReordered` events and modify the appearance there. We also have an example in the Markeplace demo where the appearance of the item being reordered is modified:

https://github.com/NativeScript/nativescript-marketplace-demo/tree/release/app/examples/listview/reorder

You can specifically take a look at the model class where the `itemReorderStarted` and `itemReordered` events are handled. A flag on the business object is raised when the item is reordered, this flag is then used to update the way the container looks:

https://github.com/NativeScript/nativescript-marketplace-demo/blob/release/app/examples/listview/reorder/listview-reorder-model.ts#L76

I hope this helps.

**Comment by NathanaelA** [comment]
This is the ListView; I'll check those docs and examples and see if I can get this part done for one of my clients.  ;-)
