### ISSUE TITLE
when navigate back RadAutoCompleteTextView suggestionview still opened it is not closing

### ISSUE THREAD

**Issue by ahamedmulaffer** [telerik/nativescript-ui-feedback#1023]
i am using setLoadSuggestionsAsync it shows the suggesstions but while suggestions opened if i navigate back suggesstion still appears in the navigated page

```
const jsonUrl = 'https://raw.githubusercontent.com/telerik/nativescript-ui-samples/master/examples-data/airports.json'
                this.$refs.bank.setLoadSuggestionsAsync((text) => {
                    const promise = new Promise((resolve, reject) => {
                        http.getJSON(jsonUrl).then((r) => {
                            const airportsCollection = r.airports
                            const items = new Array()
                            for (let i = 0; i < airportsCollection.length; i++) {
                                if (airportsCollection[i].FIELD2.includes(text.charAt(0).toUpperCase())) items.push(new TokenModel(airportsCollection[i].FIELD2, null))
                            }
                            resolve(items)
                        }).catch((err) => {
                            const message = `Error fetching remote data from ${jsonUrl}: ${err.message}`
//                            console.log(message)
                            reject()
                        });
                    });

                    return promise
                })
```
-

**Comment by tsonevn** [comment]
Hi @ahamedmulaffer,
Can you provide more info about your environment(CLI, tns-core-modules, tns-android, tns-ios, nativescript-ui-autocomplete versions) as well as a sample project, that can be used for reproducing the issue?

**Comment by ahamedmulaffer** [comment]
"nativescript": {
    "id": "org.nativescript.application",
    "tns-android": {
      "version": "5.1.0"
    },
    "tns-ios": {
      "version": "5.1.1"
    }
  },
"dependencies": {
    "@vue/devtools": "5.0.0-beta.3",
    "nativescript-cardview": "^3.1.1",
    "nativescript-fonticon": "^2.0.0",
    "nativescript-popup": "^1.5.0",
    "nativescript-ripple": "^2.1.0",
    "nativescript-socket.io": "^0.9.0",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-toast": "^1.4.6",
    "nativescript-ui-autocomplete": "^3.11.0",
    "nativescript-vue": "^2.0.0",
    "nativescript-vue-devtools": "^1.0.0",
    "tns": "^0.2.0",
    "tns-core-modules": "^5.1.2",
    "vuex": "^3.0.1"
  },
"devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@babel/preset-env": "^7.0.0",
    "babel-loader": "^8.0.2",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "clean-webpack-plugin": "^0.1.19",
    "copy-webpack-plugin": "^4.5.2",
    "css-loader": "^1.0.0",
    "lazy": "1.0.11",
    "nativescript-dev-webpack": "next",
    "nativescript-vue-template-compiler": "^2.0.0",
    "nativescript-worker-loader": "~0.9.0",
    "node-sass": "^4.9.2",
    "sass-loader": "^7.1.0",
    "terser-webpack-plugin": "^1.1.0",
    "vue-loader": "^15.2.6",
    "webpack": "^4.16.4",
    "webpack-bundle-analyzer": "~2.13.1",
    "webpack-cli": "^3.1.0"
  }
project link
https://drive.google.com/open?id=1kwbRwN_aWhwsE-eyLg2oySaVUodadGMN

Thanks @tsonevn

**Comment by tsonevn** [comment]
Hi @ahamedmulaffer,
Thank you for the provided project. I was able to recreate the problem and will mark the issue as a bug. We will investigate further the case. For now, I would suggest keeping track on the issue for further info.

**Comment by ahamedmulaffer** [comment]
i fixed it by the below code but it should not be this way it should be handled in the library itself
when we navigate back blur event of autocomplete will be triggered so i handled there by setting suggestionview height to zero (0)

radAutoCompleteListView.android.setSuggestionViewHeight(0)
