### ISSUE TITLE
RadListView: Can't split Android screen without crash

### ISSUE THREAD

**Issue by jpierront** [telerik/nativescript-ui-feedback#1029]
### Did you verify this is a real problem by searching the [NativeScript Forum]
Yes

### Tell us about the problem
If I split Android screen with a displayed RadListView, it crash with the error `Cannot read property '_context' of null`

It's seem to be a bug here (this.owner is empty):
```
ListViewLinearLayout.prototype.getLayoutManager = function() {
    Return new android.support.v7.widget.LinearLayoutManager(this.owner._context);
}; 
```

### Which platform(s) does your issue occur on?
Tested on Android (8.0, 8.1)

### Please provide the following version numbers that your issue occurs with:
- **nativescript-ui-listview:** 5.1.1
- **CLI:** 5.1.1
- **Cross-platform modules:** 5.1.2
- **Runtime(s):** 5.1.0

### Please tell us how to recreate the issue in as much detail as possible.
Just add a RadlistView on a page and split the screen when you are on this page.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
https://play.nativescript.org/?template=play-ng&id=wfMogr

**Comment by tsonevn** [comment]
Hi @jpierront 
Make sure that you have added `keyboard|smallestScreenSize|screenLayout|locale|uiMode` options in the `configChanges` in your AndroidManifest.xml file.

For example:
```
android:configChanges="keyboard|keyboardHidden|orientation|screenSize|smallestScreenSize|screenLayout|locale|uiMode"
```
[Archive.zip](https://github.com/NativeScript/android-runtime/files/2850690/Archive.zip)

**Comment by jpierront** [comment]
Perfect ! Thx !
