### ISSUE TITLE
[Feature] Listview - Add .android & .ios to itemTap / longTap events

### ISSUE THREAD

**Issue by NathanaelA** [telerik/nativescript-ui-feedback#103]
This is a trivially simple feature request; in the listview.android.js code; add to the args that are passed to the itemTap and itemLongClick events, please expose the raw motionEvent data.

listview.android.js
Line 195, Add `.android: motionEvent`
Line 207: Add `.android: motionEvent`

listview.ios.js
Line 568: Add `.ios: touches`

Unfortunately you aren't exposing the touches into the long click delegate event, so that delegate would have to change to have that value exposed to the delegate around line 356.

But I would be pretty happy just with the tap event getting these values.   There is no way to determine where the click occurred in the listview without this info.

**Comment by ginev** [comment]
Hello @NathanaelA,

We will make sure to extend the API as per your request. When we mark this case as `done`, you will be able to access the bits via the @next tag for experimental purposes.
