### ISSUE TITLE
RadCartesianChart and RadPieChart don't update when an item has changed.

### ISSUE THREAD

**Issue by tsonevn** [telerik/nativescript-ui-feedback#1030]
_From @Walon1998 on February 21, 2019 20:37_

**Environment**
 - CLI: 5.2.0
 - Cross-platform modules: 5.3.0
 - Android Runtime: 5.3.0
 - iOS Runtime: 5.2.0
 - Plugin(s):
 nativescript-ui-chart:  3.11.1    
 nativescript-angular:  7.2.2

**Describe the bug**
On Nativescript with Angular the RadCartesianChart and RadPieChart don't update when an item has changed. I want the user to be able to change the properties dynamically. On other components like RadListView or ListView it works as expected.

**To Reproduce**
Build a component with a RadCartesianChart or a RadPieChart and change one property of an item.

**Expected behavior**
RadCartesianChart and RadPieChart should update dynamically if a property of an item has changed. A cool additional feature would be animations, for example to see the bars grow or shrink if valueProperty of an item has changed.

**Sample project**
https://play.nativescript.org/?template=play-ng&id=S5YtL2&v=2
Click on the change button and see how nothing changes!

**Additional context**
I could only test it with Angular and Android. I don't know if other platforms are affected as well.

_Copied from original issue: NativeScript/NativeScript#6957_

**Comment by tsonevn** [comment]
Hi @Walon1998,
In your case, you can replace the Chart source with new ObservableArray, which includes the data with the needed changes. Check out the example [here](https://play.nativescript.org/?template=play-ng&id=S5YtL2&v=5).

**Comment by Walon1998** [comment]
Thank you very much. @tsonevn 
Is it also possible to adjust the colors dynamically?

**Comment by tsonevn** [comment]
Hi @Walon1998,
You can try creating a new `ObservableArray` for the palette entries. Check out the sample [here](https://play.nativescript.org/?template=play-ng&id=S5YtL2&v=6).
