### ISSUE TITLE
RadDataForm: SegmentedEditor ignores initial value

### ISSUE THREAD

**Issue by tgpetrov** [telerik/nativescript-ui-feedback#1031]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
_Yes_

### Tell us about the problem
_If the valueProvider is provided with keys and labels SegementedEditor will not load the correct value_

### Which platform(s) does your issue occur on?
_Android_

### Please tell us how to recreate the issue in as much detail as possible.
1. Run [this playground](https://play.nativescript.org/?template=play-js&id=0NqLMI&v=6)
2. Observe that on Android the first item is selected (default), while on iOS the second item is selected (correct based on the provided value

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
 [this playground](https://play.nativescript.org/?template=play-js&id=0NqLMI&v=6)

**Comment by saobernardo** [comment]
This problem was resolved? I'm using Dataform 6.1.1 and still have this issue
