### ISSUE TITLE
Pull-to-refresh feature is a bit clumsy in RadListView

### ISSUE THREAD

**Issue by Natalia-Hristova** [telerik/nativescript-ui-feedback#104]
from @NordlingArt

>**Platform:** iOS
>**TNS:** 2.4.0
>
>If I pull down so the loading indicator reveals, the RadListView will refresh and pull itself up while I >haven't let go of my finger yet. The list should only refresh once I have let go of the finger. This >kind of kills the user experience as it is refreshing before I even have a chance to regret my >command whether to refresh or not.
>
>Also if I scroll down to the bottom of a RadListView and pulls up as fast as I can so that the >bouncing effect goes beyond the pull-to-refresh trigger, it also refreshes the list. I don't think that >should happen as well because, again, it wasn't in my command to refresh the list.

**Comment by Natalia-Hristova** [comment]
telerik/nativescript-ui-feedback#15

**Comment by tgpetrov** [comment]
I could not reproduce the issue with [nativescript-ui-listview@3.7.2](https://www.npmjs.com/package/nativescript-ui-listview)
