### ISSUE TITLE
RadListView ScrollToIndex with grouping  Crashes ios

### ISSUE THREAD

**Issue by dottodot** [telerik/nativescript-ui-feedback#1043]
I know this has been raised before but I cannot get scrollToIndex to work without my app crashing.

Even settimeout doesn't work for me. 

If I have a list of 20 items (3 of which are visible on the screen at once) anything upto the index of 4 is ok anything above that the app crashes. 

If it's any help `scrollByAmount` is fine for example

```
scrollWithAmount(index * height)
```
trouble is my items all have different heights so it would not be accurate doing this.

I think the problem is that the indexing is getting affected by the grouping.

If you look at the following example

https://play.nativescript.org/?template=play-ng&id=JwNDWX&v=2

Try to scroll to index 10 and you'll get an error or ERROR: ERROR Error: attempt to scroll to invalid index path change it to something lower such as 4 and it works.

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:**  5.2.0
- **CLI:** 5.2.1
- **Cross-platform modules:** 5.2.2
- **Runtime(s):** 5.2.0

**Comment by tsonevn** [comment]
Hi @dottodot,
Thank you for the provided sample project. I was able to recreate the issue. I will mark it as a bug and we will investigate it further.

**Comment by dottodot** [comment]
OK thanks, I'm not sure if it related but `tkListViewHeader` doesn't display when grouping is enabled, it seems like grouping has a few strange side effects. I've updated the sample project so you can see that as well. And there is this issue regarding it https://github.com/telerik/nativescript-ui-feedback/issues/950

**Comment by elena-p** [comment]
Fixed with [6.2.0](https://github.com/telerik/nativescript-ui-feedback/blob/master/releases/listview.md#620-2019-april-19)
