### ISSUE TITLE
[RadListView] itemSwipeProgressChanged keeps getting fired when the user has released the item

### ISSUE THREAD

**Issue by mmeven** [telerik/nativescript-ui-feedback#1045]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
I'm using the example found [here](https://docs.nativescript.org/angular/ui/professional-ui-components/ng-ListView/swipe-actions) as a base, the one where the user swipes an item and releases it to trigger an action. 
After the user swiped after a certain threshold, the action should be fired, but if the user swipes back before the threshold, we should be able to cancel the action. To do this, I added a piece of code that checks the swipe progress, so if the user swipes back to where the item was initially, the boolean used to trigger the action is set back to false. 
This part works correctly, but now, when the user swipes to actually trigger the action, when the item is released and goes back to his initial position, the `itemSwipeProgressChanged` event keeps getting fired and the event `itemSwipeProgressEnded` occurs after the item has finished moving, so the action is cancelled even though the user released the item after the threshold<;

### Which platform(s) does your issue occur on?
Android mostly. 
iOs seems to behave differently : the event `itemSwipeProgressChanged` is still fired after the user released it, but it's X value is directly 0, so the `itemSwipeProgressEnded` and the actions are triggered correctly.

### Please provide the following version numbers that your issue occurs with:
- Progress NativeScript UI version: 5.2.0
- CLI: 5.2.1
- Cross-platform modules: 5.2.2
- Runtime(s): 5.2.0

### Please tell us how to recreate the issue in as much detail as possible.
Get the sample for the swipe action and add a debug log on the `itemSwipeProgressChanged` event

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

Here is the code I used to check the swipe progress and cancel the action if needed.

```
if (event.data.x > 0) {
    if (event.data.x > swipeView.getMeasuredWidth() / 4 && !this.leftThresholdPassed) {
        console.log("Notify perform left action");
        this.leftThresholdPassed = true;
    } else if (event.data.x < swipeView.getMeasuredWidth() / 4 && this.leftThresholdPassed) {
        console.log("Cancel perform left action");
        this.leftThresholdPassed = false;
    }
} else {
    if (event.data.x < -swipeView.getMeasuredWidth() / 4 && !this.rightThresholdPassed) {
        console.log("Notify perform right action");
        this.rightThresholdPassed = true;
    } else if (event.data.x > -swipeView.getMeasuredWidth() / 4 && this.rightThresholdPassed) {
        console.log("Cancel perform right action");
        this.rightThresholdPassed = false;
    }
}
```

**Comment by tsonevn** [comment]
Hi @mmeven,
I checked your case with the [/nativescript-ui-samples-angular/listview](https://github.com/telerik/nativescript-ui-samples-angular/tree/master/listview/app/examples/group-swipe-load-pull) while reusing the provided code, however, was unable to reproduce the problem. Regarding that, can you give us a sample project, that can be used for recreating the issue?

**Comment by mmeven** [comment]
Hi @tsonevn ,
I created a playground project to reproduce the issue : [playground](https://play.nativescript.org/?template=play-ng&id=3cvkfM). When you slide an item of the list, you'll see in the logs that the action is cancel after you've released the item. 

Thanks in advance

**Comment by tsonevn** [comment]
HI @mmeven,
You can additionally check  inside the `onCellSwiping` for the right->left swipe(event.data.x < 0). This should solve your case. Example:
```
onCellSwiping(event) {
        const swipeLimits = event.data.swipeLimits;
        const swipeView = event['swipeView'];
        const mainView = event['mainView'];
        const leftItem = swipeView.getViewById('left-view');
        const rightItem = swipeView.getViewById('right-view');


        if (event.data.x > 0) {
            if (event.data.x > swipeView.getMeasuredWidth() / 4 && !this.leftThresholdPassed) {
                console.log("Notify perform left action");
                this.leftThresholdPassed = true;
            } else if (event.data.x < swipeView.getMeasuredWidth() / 4 && this.leftThresholdPassed) {
                console.log("Cancel perform left action");
                this.leftThresholdPassed = false;
            }
        } else if(event.data.x < 0){
            if (event.data.x < -swipeView.getMeasuredWidth() / 4 && !this.rightThresholdPassed) {
                console.log("Notify perform right action");
                this.rightThresholdPassed = true;
            } else if (event.data.x > -swipeView.getMeasuredWidth() / 4 && this.rightThresholdPassed) {
                console.log("Cancel perform right action");
                this.rightThresholdPassed = false;
            }
        }

        if (event.data.x > 0) {
            const leftDimensions = View.measureChild(
                leftItem.parent,
                leftItem,
                layout.makeMeasureSpec(Math.abs(event.data.x), layout.EXACTLY),
                layout.makeMeasureSpec(mainView.getMeasuredHeight(), layout.EXACTLY));
            View.layoutChild(leftItem.parent, leftItem, 0, 0, leftDimensions.measuredWidth, leftDimensions.measuredHeight);
        } else {
            const rightDimensions = View.measureChild(
                rightItem.parent,
                rightItem,
                layout.makeMeasureSpec(Math.abs(event.data.x), layout.EXACTLY),
                layout.makeMeasureSpec(mainView.getMeasuredHeight(), layout.EXACTLY));

            View.layoutChild(rightItem.parent, rightItem, mainView.getMeasuredWidth() - rightDimensions.measuredWidth, 0, mainView.getMeasuredWidth(), rightDimensions.measuredHeight);
        }
    }
```

**Comment by mmeven** [comment]
Hi @tsonevn 

Thanks for your answer, unfortunately it doesn't change anything. There's still no difference between manually dragging back the item to cancel an action, and the item going back to it's initial position after being released - the action is cancelled anyway. I tested this on different Android devices (Huawei P20 and Samsung Galaxy S6).

Maybe this is exactly how it should behave ? In that case I'll understand that cancelling an action is not possible, but it seems impractical.
