### ISSUE TITLE
plugins updated to v 4.0.0/6.0.0 in app: build exception

### ISSUE THREAD

**Issue by gbonline** [telerik/nativescript-ui-feedback#1054]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
_Yes/No_

### Tell us about the problem
_Please, ensure your title is less than 63 characters long and starts with a capital
letter._
can't build application after update plugin to latest version
### Which platform(s) does your issue occur on?
_iOS/Android/Both (if applicable tell us the specific version of the platform)_
android
### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** (the version of nativescript-telerik-ui/-pro in the `package.json`)
- **CLI:** (run `tns --version` to fetch it)
- **Cross-platform modules:** (the version of tns-core-modules in the `package.json`)
- **Runtime(s):** (the `"tns-android"` and `"tns-ios"` properties in the `package.json`)
nativescript-ui-autocomplete, claendar, chart, gauge v 4.0.0
nativescript-ui-dataform v 3.10.1
nativescript-ui-listview, sidedrawer v 6.0.0
core-modules 5.2.2
tns-android 5.2.1

### Please tell us how to recreate the issue in as much detail as possible.
1. update the plugins: tns plugin update nativescript-ui-*/
2. removed the platforms/android folder
3. tns build android
exception:
```
Exception in thread "main" java.io.IOException: File already exists. This may lead to undesired behavio
r.
Please change the name of one of the extended classes.
File:/Users/nemesix/Sviluppo/NativeScript5/NS_Login_section/platforms/android/app/src/main/java/com/tns
/gen/com/telerik/widget/autocomplete/AutoCompleteAdapter_autocomplete_63_32_AutoCompleteAdapter.java Cl
ass: 
        at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:82)
        at org.nativescript.staticbindinggenerator.Main.main(Main.java:47)

```

downgrading to previous version as read on my package.json, the build complete successfully
```
 "nativescript-ui-autocomplete": "3.11.0",
        "nativescript-ui-calendar": "3.10.0",
        "nativescript-ui-chart": "3.11.1",
        "nativescript-ui-dataform": "3.10.0",
        "nativescript-ui-gauge": "3.8.0",
        "nativescript-ui-listview": "5.1.1",
        "nativescript-ui-sidedrawer": "5.1.0",
```

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
_(You can paste entire code snippets or attach a runnable project)_

**Comment by tgpetrov** [comment]
Hi @gbonline,
The nativescript-ui-dataform@3.10.1 has a dependency of nativescript-ui-autocomplete ^3.10.0.

You have also added a reference to nativescript-ui-autocomplete@4.0.0 which leads to duplication of the code of the autocomplete. 

We will soon release nativescript-ui-dataform@4.0.0 which will be compatible with the latest version of autocomplete. Until then you should keep both autocomplete and dataform to 3.\*.\* versions.
