### ISSUE TITLE
RadDataForm: accept empty for email field with editor and validator if not required

### ISSUE THREAD

**Issue by gbonline** [telerik/nativescript-ui-feedback#1079]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

## Please, provide the details below:
I have a field declared as
```
      <TKEntityProperty tkPropertyGroupProperties name="second_email_address" >
          <TKPropertyEditor tkEntityPropertyEditor type="Email" ></TKPropertyEditor>
          <TKEmailValidator tkEntityPropertyValidators errorMessage="Email format issue."></TKEmailValidator>
          <TKMinimumLengthValidator tkEntityPropertyValidators errorMessage="" length="0"></TKMinimumLengthValidator>
		
      </TKEntityProperty>
```
And the user can leave it empty, but the presence of validator make the field required.
I tried adding a second validator with Minlenght=0 but the type email validator always wins.
I would like to accept an empty field if I don't set the required property
although the regex validator can be set

### Tell us about the problem
_Please, ensure your title is less than 63 characters long and starts with a capital
letter._
The email validator makes the field mandatory also if "required" property is not set.

### Which platform(s) does your issue occur on?
_iOS/Android/Both (if applicable tell us the specific version of the platform)_

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI plugin version:** (the version of nativescript-ui-* in the `package.json`)
- **CLI:** (run `tns --version` to fetch it)
- **Cross-platform modules:** (the version of tns-core-modules in the `package.json`)
- **Runtime(s):** (the `"tns-android"` and `"tns-ios"` properties in the `package.json`)
  "nativescript-ui-dataform": "^4.0.0",
 "tns-android": {
            "version": "5.3.1"
        },
        "tns-ios": {
            "version": "5.3.1"
        }
### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application ..
2. ...

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
_(You can paste entire code snippets, link to playground demo or attach a runnable project)_

**Comment by tsonevn** [comment]
Hi @gbonline,
In your scenario, you can create a custom validator, which matches your conditions for the email input. You can check the example [here](https://github.com/telerik/nativescript-ui-samples-angular/tree/master/dataform/app/examples/validation/custom-validator).

Hope this helps
