### ISSUE TITLE
Angular AoT support

### ISSUE THREAD

**Issue by ginev** [telerik/nativescript-ui-feedback#108]
Migrated from: https://github.com/telerik/nativescript-ui-samples/issues/161

**Comment by VladimirAmiorkov** [comment]
This issue has been resolved in version ^2.0.0. For more information please refer [this article](http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/getting-started#using-the-ngmodule-of-the-plugins-ui-components).
