### ISSUE TITLE
[Autocomplete] add ItemSelected feature 

### ISSUE THREAD

**Issue by kefahB** [telerik/nativescript-ui-feedback#1080]
Hi,

There is way to add event itemSelected (like a ListView) ? I mean is like google places predictions, when selected get the item ?

Thanks

**Comment by AgustinV08** [comment]
AutocompleteSelected(args) {
        const autocomplete: RadAutoCompleteTextView = args.object;

        for (const i in autocomplete.filteredItems) {
            if (autocomplete.filteredItems[i].text === args.text) {
                  // code here
            }
        }
    }

You could use this as a temporaly solution
