### ISSUE TITLE
Classnotfoundexception Class: com.telerik.widget.calendar.RadCalendarView.OnCellClickListener

### ISSUE THREAD

**Issue by msl2000** [telerik/nativescript-ui-feedback#1082]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Tell us about the problem
Initiating a RadCalendar in a nativescript angular app leads to the following error
Exception in thread "main" java.lang.ClassNotFoundException: Class: com.telerik.widget.calendar.RadCalendarView.OnCellClickListener

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
  "nativescript": {
    "id": "com.genisys.dribl",
    "tns-ios": {
      "version": "5.0.0"
    },
    "tns-android": {
      "version": "5.2.1"
    }
  },
### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application 
2. Initiate RadCalendar

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
calendar.html
` <RadCalendar></RadCalendar>`

calendar.module.ts
`import { NgModule, NO_ERRORS_SCHEMA } from "@angular/core";
import { NativeScriptCommonModule } from "nativescript-angular/common";

import { CalendarRoutingModule } from "./calendar-routing.module";
import { CalendarComponent } from "./calendar";
import { MatchViewRootComponent } from "./events/match/matchview-root";
import { MatchViewComponent } from "./events/match/matchview";
import { NativeScriptUICalendarModule } from "nativescript-ui-calendar/angular";

@NgModule({
    imports: [
        NativeScriptCommonModule,
        CalendarRoutingModule,
        NativeScriptUICalendarModule,
    ],
    declarations: [
        CalendarComponent,
        // MatchViewComponent,
        MatchViewRootComponent,
    ],
    entryComponents: [MatchViewRootComponent],
    schemas: [
        NO_ERRORS_SCHEMA
    ]
})
export class CalendarModule { }
`

**Comment by nitish1986** [comment]
How did you solved this? I'm also getting the same error.
