### ISSUE TITLE
Chart: axis bounds not respected

### ISSUE THREAD

**Issue by tgpetrov** [telerik/nativescript-ui-feedback#1086]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Tell us about the problem
When Chart Axis is replaced, axis bounds are not respected. Here's a [Playground link](https://play.nativescript.org/?template=play-ng&id=MDCTKy). On the Playground, the chart updates correctly, but if downloaded and `-chart` updated to 4.0.1, the horizontal axis continually grows as visible [here](https://i.imgur.com/VAJtIY4.gifv).

### Which platform(s) does your issue occur on?
_iOS_

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
Here's a [Playground link](https://play.nativescript.org/?template=play-ng&id=MDCTKy).

**Comment by zbranzov** [comment]
Released in nativescript-ui-chart@4.0.2
