### ISSUE TITLE
Styling border of selected date in RadCalendar not working good for iOS

### ISSUE THREAD

**Issue by cindy-m** [telerik/nativescript-ui-feedback#113]
Hey, 
currently I am using RadCalendar within my native script with angular2 project. I tried to style only the selected date with a different border color (with a border width of 2) that fits more with the whole colouring of the app. For android, it works perfectly, but for iOS not. The first time selecting a date works good, but when selecting another date, than one side of the border is still left behind. Colouring the borderlines of all dates seems to avoid this issue, but than again, I really wanted to have no left and right border for the iOS app as that seems to me more standard.

**Comment by ginev** [comment]
Hello @cindy-m,

Thanks for reporting this issue. We're putting it on the TODO list for fixing. Stay tuned here.

**Comment by ginev** [comment]
@cindy-m - this issue will be addressed in our upcoming 3.0 release due to by the end of June.

**Comment by Natalia-Hristova** [comment]
@cindy-m ,

If you want to test it out before the official release you can use the "next" version of the nativescript-telerik-ui-pro plugin. Simply install that version of the plugin: ``` tns plugin add nativescript-telerik-ui-pro@next``` .
