### ISSUE TITLE
How RadListView support Gesture

### ISSUE THREAD

**Issue by ginev** [telerik/nativescript-ui-feedback#118]
_From @ryc16 on September 20, 2016 21:48_

Does RadListView support Gesture like pan? For example, I want to detect RadListView scrolling down but can't find any event support it. Try to manually register "pan" but doesn't work. 

_Copied from original issue: telerik/nativescript-ui-samples#127_

**Comment by ginev** [comment]
Hello @ryc16 ,

currently there's no API to detect scrolling. Could you please describe in more details the scenario you would like to implement?

Thanks!

**Comment by ginev** [comment]
_From @ryc16 on September 29, 2016 10:30_

@ginev, one simple case, if I want to show a "go to top" button while RadListView scroll down RadListView. This is very common and can implement transitional ListView with pan event.  I was trying to use itemLoadingEvent to see if it works similar like pan but it is not exactly. Normally on pan event, it return the "relative" deltaY for every pan but itemLoadingEvent has "absolute" item index.

**Comment by tsonevn** [comment]
In this case, could be used [scrollStartEvent](http://docs.telerik.com/devtools/nativescript-ui/api/classes/radlistview.html#scrollstartedevent) and [scrollEndedEvent](http://docs.telerik.com/devtools/nativescript-ui/api/classes/radlistview.html#scrollendedevent). Those events will help for handling the begin and end of the scroll
