### ISSUE TITLE
[RadListView] Swipe Actions worknig only when backgroundColor is set for tkListItemTemplate

### ISSUE THREAD

**Issue by NickIliev** [telerik/nativescript-ui-feedback#124]
To use the swipe actions the user should explicitly set a background color for **_tkListItemTemplate_** or otherwise, the swipe action layouts are not rendered as expected (not hidden by default)

How to reproduce this issue:
- open [this example](https://github.com/telerik/nativescript-ui-samples-angular/tree/release/sdkAngular/app/listview/swipe-actions)
- remove the background color from [here](https://github.com/telerik/nativescript-ui-samples-angular/blob/release/sdkAngular/app/listview/swipe-actions/listview-swipe-actions.component.css#L2)
- the result is as follows 
![swipeactions](https://cloud.githubusercontent.com/assets/18008302/23845850/1b6e4ec8-07d3-11e7-98f5-46d9eadd5904.png)

temporary workaround (given to t.1097385)
- provide backgroundColor for the container element of your **_tkListItemTemplate_**
- the result is now as expected (the swipe action layouts are hidden by default)

**Comment by ginev** [comment]
@NickIliev Should we consider this as an issue? We cannot implicitly provide a background color to the View supplied by inflating the item template. This may override other user settings.

**Comment by NickIliev** [comment]
@ginev I see your point - marked this one  as a documentation add so we can provide it as a mandatory thing to do in order to use swipe actions.

**Comment by jsandrea88** [comment]
![radlistwiew](https://user-images.githubusercontent.com/21974052/34566321-13edd3c4-f12c-11e7-94df-bbeec734351f.JPG)
I had the same isssue, I'm using nativescript core with javascript, in my case, the solution was add style="background-color: white;" in GridLayout tag as I show on the attach,  thank you so much.

`

**Comment by noumaans** [comment]
Please add this to documentation. Ran into this particular issue on Android (iOS didn't need background color specified) and spent quite some time trying to figure out the root-cause.

**Comment by tgpetrov** [comment]
The requested information has been added to the Swipe Actions documentation in the articles for both [NativeScript Core](http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/ListView/swipe-actions) and [NativeScript with Angular](http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/ListView/swipe-actions).

**Comment by Xsmael** [comment]
I run into the same problem, but the background color set to white didnt fix it, the items are not swiping, there is no overlap of text though.

here is my code:

   <lv:RadListView id="listview" items="{{ items }}" class="list-group" swipeActions="true" pullToRefresh="true" pullToRefreshInitiated="pullToRefreshInitiated">

		<lv:RadListView.itemTemplate>
			<GridLayout class="list-group-item" rows="auto" columns="auto, *" backgroundColor="white" >
				
				<StackLayout row="0" col="1" >
					<Label text="{{ itemName }}" class="list-group-item-heading" />
					<Label text="{{ itemDesc }}" class="list-group-item-text" />
				</StackLayout>
			</GridLayout>
		</lv:RadListView.itemTemplate>


		<lv:RadListView.itemSwipeTemplate>
			<GridLayout columns="auto, *, auto" >
				<StackLayout col="0" class="save-btn" tap="onLeftSwipe" orientation="horizontal">
					<Label text="Save" verticalAlignment="center" horizontalAlignment="center"/>
				</StackLayout>
				<StackLayout col="2" class="delete-btn" tap="onRightSwipe" orientation="horizontal">
					<Label text="Delete" verticalAlignment="center" horizontalAlignment="center" />
				</StackLayout>
			</GridLayout>
		</lv:RadListView.itemSwipeTemplate>
	</lv:RadListView>

**Comment by OPADA-Eng** [comment]
Hi, 
I ran into this issue in the past. and setting background color to white solve it.
But now after supporting dark theme I can not set the background color to white because in dark mode nothing will be shown after switching text color to white.
I hope you find another solution. 
Thanks.
