### ISSUE TITLE
[RadListView] Cannot set CSS from file to header- or footerItemTemplate

### ISSUE THREAD

**Issue by NordlingArt** [telerik/nativescript-ui-feedback#127]
**Platform:** iOS
**TNS:** 2.5.1

CSS won't apply to header- or footerItemTemplate if it's written from a css file. This means I must apply inline-style directly onto each element in the XML.

Height seems to apply from the file, but nothing else what I've noticed.

**Comment by tsonevn** [comment]
The issue is not reproducible with the latest version of UI for NativeScript 3.2
