### ISSUE TITLE
The specified child already has a parent. You must call removeView() on the child's parent first.

### ISSUE THREAD

**Issue by tsonevn** [telerik/nativescript-ui-feedback#128]
_From @initialcatalog on March 15, 2017 11:42_

Hi,

I use telerik guage in  first page.
When I switch to another page from this page by pressing "backspace" key, I see this error message: 

`java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.`

Could you help me please?

_Copied from original issue: NativeScript/NativeScript#3797_

**Comment by tsonevn** [comment]
Hi @initialcatalog,
Thank you for reporting this issue,
I tested your case I was able to reproduce this behavior on my side on Android.
I am also attaching sample project, where this could be reproduced.

For further info about the problem, you could keep track on the issue.
[Archive.zip](https://github.com/telerik/nativescript-ui-feedback/files/844834/Archive.zip)

**Comment by initialcatalog** [comment]
Hi, I have tested the  project which attached you uploaded. I see also same error message.  :(

**Comment by ginev** [comment]
Hi @initialcatalog,

This issue will be released in the upcoming release of NS UI due to in a couple of weeks.
