### ISSUE TITLE
Crash RadListView on swipe delete (iOS)

### ISSUE THREAD

**Issue by kssfilo** [telerik/nativescript-ui-feedback#129]
1. Enable swipe (and add delete code)
2. Bind RadListView to a empty ObservableArray
3. Insert some item to FIRST of the ObservableArray x 3 times
4. Swipe & delete first line x 3times

-> Crash (error message is below)

file:///app/tns_modules/nativescript-telerik-ui/listview/listview.js:301:71: JS ERROR TypeError: undefined is not an object (evaluating 'this._owner._realizedCells.get(cell.tag).view')

I found that the cause is following line on listview.ios.js .

> tableCell.tag = indexPath.row + 1;

If a cell are inserted to head of list, tableCell.tag conflict to another cells.  Finally, I am using the patch below to avoid this problem. This is for your information.

```
--- nativescript-telerik-ui/listview/listview.ios.js.org	2017-03-16 00:11:38.000000000 +0900
+++ nativescript-telerik-ui/listview/listview.ios.js	2017-03-16 00:49:32.000000000 +0900
@@ -583,6 +583,7 @@
     function RadListView() {
         _super.call(this);
         this._realizedCells = new Map();
+        this._nextCellTag = 1;
         this._heights = new Array();
         this._ios = TKListView.new();
         this._ios.autoresizingMask = 2 /* FlexibleWidth */ | 16 /* FlexibleHeight */;
@@ -1073,7 +1074,7 @@
     };
     RadListView.prototype.prepareLoadOnDemandCell = function (tableCell, indexPath) {
         if (tableCell.tag === 0) {
-            tableCell.tag = indexPath.row + 1;
+            tableCell.tag = this._nextCellTag++
         }
         this._realizedCells.set(tableCell.tag, tableCell);
         if (tableCell.view === undefined) {
@@ -1097,7 +1098,7 @@
     };
     RadListView.prototype.prepareHeaderFooterCell = function (cell, viewType, indexPath) {
         if (cell.tag === 0) {
-            cell.tag = indexPath.row + 1;
+            cell.tag = this._nextCellTag++;
         }
         this._realizedCells.set(cell.tag, cell);
         if (cell.view === undefined || cell.view.parent === undefined) {
@@ -1118,7 +1119,7 @@
     RadListView.prototype.prepareCell = function (tableCell, indexPath) {
         var cell = tableCell;
         if (cell.tag === 0) {
-            cell.tag = indexPath.row + 1;
+            cell.tag = this._nextCellTag++;
         }
         this._realizedCells.set(tableCell.tag, cell);
         if (cell.view === undefined) {
```

**Comment by ginev** [comment]
@kssfilo, you are correct. When inserting items at the beginning of the array the `row` value will be the position where the item is inserted which might already exist in the `realizedCells` map. Storing the `tag` value in a separate field is smarter. We will log this in our TODO list and will address it for the upcoming release.

**Comment by ginev** [comment]
@kssfilo, this issue will be resolved in the upcoming release of NS UI due to in a couple of weeks.

**Comment by topclaudy** [comment]
Still happening.

**Comment by Ericky14** [comment]
Happened to me too

**Comment by Ericky14** [comment]
Actually, you can work-around this error by simply passing a `filteringFunction` that returns true tp the RadListView. So the code that makes it crash will not get run based on the conditional implemented there.
