### ISSUE TITLE
ListView runtime error

### ISSUE THREAD

**Issue by wenhsiaoyi** [telerik/nativescript-ui-feedback#134]
Nativescript 2.5.0

>>build warnning message:
Merged dex #50 (1 defs/1.4KiB)
Merged dex #51 (2243 defs/3738.4KiB)
Result is 2293 defs/2808.0KiB. Took 0.2s
:buildMetadata
Skip com.telerik.widget.list.DeckOfCardsLayoutManager
	Error: java.lang.NullPointerException
Skip com.telerik.widget.list.FadeItemAnimator
	Error: java.lang.NullPointerException
Skip com.telerik.widget.list.ItemAnimatorSet
	Error: java.lang.NullPointerException
Skip com.telerik.widget.list.ListViewItemAnimator
	Error: java.lang.NullPointerException
Skip com.telerik.widget.list.ListViewItemAnimator$ChangeInfo
	Error: java.lang.NullPointerException
Skip com.telerik.widget.list.ListViewItemAnimator$MoveInfo
	Error: java.lang.NullPointerException
Skip com.telerik.widget.list.RadListView
	Error: java.lang.NullPointerException
Skip com.telerik.widget.list.ScaleItemAnimator
	Error: java.lang.NullPointerException
Skip com.telerik.widget.list.SlideItemAnimator

>>Runtime Error Report:
com.tns.NativeScriptException: 
Calling js method onCreateView failed
Error: java.lang.NoClassDefFoundError: com.telerik.widget.list.RadListView
    java.lang.Class.classForName(Native Method)
    java.lang.Class.forName(Class.java:324)
    java.lang.Class.forName(Class.java:285)
    com.tns.Runtime.getClassForName(Runtime.java:1107)
    com.tns.ClassResolver.resolveClass(ClassResolver.java:57)
    com.tns.Runtime.resolveClass(Runtime.java:649)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
    com.tns.Runtime.callJSMethod(Runtime.java:1047)
    com.tns.Runtime.callJSMethod(Runtime.java:1028)
    com.tns.Runtime.callJSMethod(Runtime.java:1018)
    com.tns.FragmentClass.onCreateView(android.app.Fragment.java)
    android.app.Fragment.performCreateView(Fragment.java:2220)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
    android.app.BackStackRecord.run(BackStackRecord.java:793)
    android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
    android.app.FragmentManagerImpl$1.run(FragmentManager.java:482)
    android.os.Handler.handleCallback(Handler.java:739)
    android.os.Handler.dispatchMessage(Handler.java:95)
    android.os.Looper.loop(Looper.java:168)
    android.app.ActivityThread.main(ActivityThread.java:5845)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
File: "file:///data/data/tw.com.umaker.app.ss3c.dashboard/files/app/tns_modules/nativescript-telerik-ui/listview/listview.js, line: 168, column: 24
StackTrace: 
	Frame: function:'RadListView._createUI', file:'file:///data/data/tw.com.umaker.app.ss3c.dashboard/files/app/tns_modules/nativescript-telerik-ui/listview/listview.js', line: 168, column: 25
	Frame: function:'View._onContextChanged', file:'file:///data/data/tw.com.umaker.app.ss3c.dashboard/files/app/tns_modules/tns-core-modules/ui/core/view.js', line: 202, column: 14
	Frame: function:'View._onAttached', file:'file:///data/data/tw.com.umaker.app.ss3c.dashboard/files/app/tns_modules/tns-core-modules/ui/core/view.js', line: 153, column: 14
	Frame: function:'eachChild', file:'file:///data/data/tw.com.umaker.app.ss3c.dashboard/files/app/tns_modules/tns-core-modules/ui/core/view.js', line: 158, column: 23
	Frame: function:'LayoutBase._eachChildView', file:'file:///data/data/tw.com.umaker.app.ss3c.dashboard/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 144, column: 22
	Frame: function:'View._onAttached', file:'file:///data/data/tw.com.umaker.app.ss3c.dashboard/files/app/tns_modules/tns-core-modules/ui/core/view.js', line: 165, column: 18
	Frame: function:'eachChild', file:'file:///data/data/tw.com.umaker.app.ss3c.dashboard/files/app/tns_modules/tns-core-modules/ui/core/view.js', line: 158, column: 23
	Frame: function:'ContentView._eachChildView', file:'file:///data/data/tw.com.umaker.app.ss3c.dashboard/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 65, column: 13
	Frame: function:'View._onAttached', file:'file:///data/data/tw.com.umaker.app.ss3c.dashboard/files/app/tns_modules/tns-core-modules/ui/core/view.js', line: 165, column: 18
	Frame: function:'eachChild', file:'file:///data/data/tw.com.umaker.app.ss3c.dashboard/files/app/tns_modules/tns-core-modules/ui/core/view.js', line: 158, column: 23
	Frame: function:'ContentView._eachChildView', file:'file:///data/data/tw.com.umaker.app.ss3c.dashboard/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 65, column: 13
	Frame: function:'Page._eachChildView', file:'file:///data/data/tw.com.umaker.app.ss3c.dashboard/files/app/tns_modules/tns-core-modules/ui/page/page-common.js', line: 317, column: 41
	Frame: function:'View._onAttached', file:'file:///data/data/tw.com.umaker.app.ss3c.dashboard/files/app/tns_modules/tns-core-modules/ui/core/view.js', line: 165, column: 18
	Frame: function:'View._addViewCore', file:'file:///data/data/tw.com.umaker.app.ss3c.dashboard/files/app/tns_modules/tns-core-modules/ui/core/view.js', line: 126, column: 18
	Frame: function:'View._addView', file:'file:///data/data/tw.com.umaker.app.ss3c.dashboard/files/app/tns_modules/tns-core-modules/ui/core/view-common.js', line: 1163, column: 14
	Frame: function:'onFragmentShown', file:'file:///data/data/tw.com.umaker.app.ss3c.dashboard/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 40, column: 11
	Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'file:///data/data/tw.com.umaker.app.ss3c.dashboard/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 612, column: 13
	Frame: function:'FragmentClass.onCreateView', file:'file:///data/data/tw.com.umaker.app.ss3c.dashboard/files/app/tns_modules/tns-core-modules/ui/frame/fragment.js', line: 23, column: 38
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
	at com.tns.Runtime.callJSMethod(Runtime.java:1047)
	at com.tns.Runtime.callJSMethod(Runtime.java:1028)
	at com.tns.Runtime.callJSMethod(Runtime.java:1018)
	at com.tns.FragmentClass.onCreateView(android.app.Fragment.java)
	at android.app.Fragment.performCreateView(Fragment.java:2220)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
	at android.app.BackStackRecord.run(BackStackRecord.java:793)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:482)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:168)
	at android.app.ActivityThread.main(ActivityThread.java:5845)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
Caused by: java.lang.NoClassDefFoundError: com.telerik.widget.list.RadListView
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:324)
	at java.lang.Class.forName(Class.java:285)
	at com.tns.Runtime.getClassForName(Runtime.java:1107)
	at com.tns.ClassResolver.resolveClass(ClassResolver.java:57)
	at com.tns.Runtime.resolveClass(Runtime.java:649)
	... 20 more

**Comment by VladimirAmiorkov** [comment]
Hi @wenhsiaoyi ,

Can you share with use more details of your project, like:

- Version of nativescript-telerik-ui
- Are you using Nativescript + Angular or pure NativeScript
- Any code that involves the view in which the RadListView is declared


Some frequently used troubleshooting actions that can be used when experiencing such issues is to:

1. Clean the project but deleting the platforms and node_modules folders
2. Removing the previously installed app on the device or emulator

**Comment by ginev** [comment]
@wenhsiaoyi please make sure that you reference the RecyclerView component to use RadListView. We have received similar reports previously and it came out that this reference was missing from the project. Did you change the Gradle references in your project?

**Comment by ginev** [comment]
@wenhsiaoyi this is FYI: we have identified the reason for this glitch and will issue a fix in the upcoming release of UI for NS.

**Comment by ginev** [comment]
A new version of NS UI Free has been uploaded that addresses this: 1.6.2

**Comment by Natalia-Hristova** [comment]
#131
