### ISSUE TITLE
[Bug] Charts issue while changing the majorStep

### ISSUE THREAD

**Issue by tsonevn** [telerik/nativescript-ui-feedback#136]
While changing the `majorStep` from `Year` to `Month` the Chart will not be shown properly on iOS device and Simulator.
Attaching sample image, where the issue has been shown.
![screen shot 2017-03-22 at 5 50 15 pm](https://cloud.githubusercontent.com/assets/17448734/24207271/21423726-0f29-11e7-9f85-3eeb3b6094b2.png)

**Comment by ginev** [comment]
@tsonevn can you attach the project to reproduce please?

**Comment by VladimirAmiorkov** [comment]
Related to #321
