### ISSUE TITLE
JS ERROR Error: Property showOverNavigation already registered for type RadSideDrawer

### ISSUE THREAD

**Issue by simonettoa** [telerik/nativescript-ui-feedback#137]
It appeared in my app few days before, the only think I have done is an update of nativescript and the cli. But I am not sure this is the cause. Anyway I created a new clean app just with the RadSideDrawer and the error appears again. It works with simulators (both iOS and Android), also with real Android device but not with real iPhone.

The error is the one below:

> Found peer TypeScript 2.1.6
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x100639e20 -[TNSRuntime executeModule:referredBy:]
2   0x1000e5324 main
3   0x18932c5b8 <redacted>
JavaScript stack trace:
1   @file:///app/tns_modules/tns-core-modules/ui/core/dependency-observable.js:73:28
JavaScript error:
file:///app/tns_modules/tns-core-modules/ui/core/dependency-observable.js:73:28: JS ERROR Error: Property showOverNavigation already registered for type RadSideDrawer.

I created a repository to test the problem.
https://github.com/simonettoa/nativescript-RadSideDrawer

tns info:
 native script            --> 2.5.3
 tis-core-modules   --> 2.5.2
 tis-android              --> 2.5.0
 tns-ios                     --> 2.5.0

Node version: v6.9.1
npm version: 3.10.9
IOS device version: 10.1.1

**Comment by ginev** [comment]
@simonettoa this issue is fixed in the upcoming release of NativeScript and NativeScript UI.

**Comment by simonettoa** [comment]
thanks @ginev, have you any idea when it will be available? Or at least a sort of newsletter where I could be informed about that?

**Comment by ginev** [comment]
@simonettoa , we plan to upload the Release Candidate bits by the end of the next week. That will be the NativeScript UI 3.0 which comes after NativeScript 3.0. You can subscribe for news on the NativeScript website: http://docs.nativescript.org/
