### ISSUE TITLE
ListViewStaggeredLayout - colspan?

### ISSUE THREAD

**Issue by s-georgiev** [telerik/nativescript-ui-feedback#14]
I am currently using ListViewStaggeredLayout with three columns. I want to have an element that spans accross all three columns and then continue with staggeredlayout. Something like this: 

![staggeredlayout](https://cloud.githubusercontent.com/assets/6524783/16734691/1bb18c74-478f-11e6-95e8-dd7aedf46714.jpg)

Is it possible with Telerik UI and ListViewStaggeredLayout?

**Comment by ginev** [comment]
Hello @s-georgiev,

this is currently not possible in RadListView.

This will be a feature candidate once the data operations are implemented in RadListView which enable you to group the source (and thus display group items).

**Comment by s-georgiev** [comment]
Thanks @ginev !
Can you suggest any kind of layout (combination of layouts) that I can use to make this possible?

**Comment by ginev** [comment]
@s-georgiev, you can use a Linear Layout with item template which has three layout elements that are horizontally positioned to mimic the staggered layout. This, however, will not be a 100% staggered layout as items will be vertically aligned according to the tallest item within a row. For Group items you can simply use a property on the data object to hide the three elements and display one which is stretched to the whole width of the item representing the group header.
