### ISSUE TITLE
Gauge to Angular2

### ISSUE THREAD

**Issue by cmdaniel** [telerik/nativescript-ui-feedback#141]
Hi,

I'm trying the nativescript-ui-pro and I didn't found at the sample code the Gauge to Angular2.
Does the Gauge works to angular2?

Tks,
Daniel

**Comment by NickIliev** [comment]
@cmdaniel at this very moment [this is the list](http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/overview) of supported controls with Angular.
```
RadListView
RadSideDrawer
RadCalendar
RadCartesianChart
RadPieChart
RadDataForm
```

**Comment by ginev** [comment]
@cmdaniel, I just want to point out that we have the Gauge on our short-term TODO list for Angular so stay tuned.
