### ISSUE TITLE
Property 'Bindable' does not exist | NativeScript 3.0@RC Upgrade

### ISSUE THREAD

**Issue by felipebernardes** [telerik/nativescript-ui-feedback#142]
Hello,

After upgrading to NS 3.0@RC I'm getting these errors from listview/chart:

```
Project successfully created.
Executing before-prepare hook from <path>/hooks/before-prepare/nativescript-dev-typescript.js
Found peer TypeScript 2.2.2

node_modules/nativescript-telerik-ui-pro/chart/index.d.ts(5,10): error TS2305: Module '"<path>/node_modules/tns-core-modules/ui/core/bindable/bindable"' has no exported member 'Bindable'.

node_modules/nativescript-telerik-ui-pro/listview/index.d.ts(302,56): error TS2339: Property 'Bindable' does not exist on type 'typeof "<path>/node_modules/tns-core-modules/u...'.

TypeScript compiler failed with exit code 1
```

I'm using bar series chart and RadListView components in my app.

I've read [NS@RC upgrade guide](https://github.com/NativeScript/NativeScript/blob/31063ee732256d306b172a1ad48d4c17399c809a/Modules30Changes.md) and it says 'Bindable' isn't part of class hierarchy anymore:
![screen shot 2017-03-31 at 10 24 42](https://cloud.githubusercontent.com/assets/7507797/24552414/b3a5b352-15fc-11e7-90b1-dd7feb4abb0c.png)

How can I get through this?

**Comment by ginev** [comment]
Hello @felipebernardes,
The RC of NativeScript UI which targets NativeScript 3.0 is not yet available and will be out in the beginning of the next week. Stay tuned.

**Comment by felipebernardes** [comment]
Hey @ginev , thanks for your quick feedback! It solves my issue.

**Comment by ginev** [comment]
@felipebernardes  you can now use the rc tag to install the preview version of UI for NativeScript which targets NativeScript 3.0. Note that the public npmjs.com version of UI for NativeScript Pro displays a trial message but is not limited in functionality so you can use it for testing and prototyping until the official release is out.
