### ISSUE TITLE
[iOS RadChart] Property majorTickInterval not working

### ISSUE THREAD

**Issue by NickIliev** [telerik/nativescript-ui-feedback#143]
The property [majorTickInterval](http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/Chart/Axes/categorical#features) does not work for iOS.
Tested on both NativeScript Core and Angular enabled projects.

Steps to reproduce:
- open the nativescript-ui-samples application (or nativescript-ui-samples-angular)
- navigate to [this page](https://github.com/telerik/nativescript-ui-samples/blob/release/sdk/app/chart/series/area/area-series.xml#L7) (located in **chart/series/area**)
- add `majorTickInterval="2"` at the selected line

Result: Nothing changes for iOS. 
For Android, it will show the 1st,3rd and 5th values in the categorical axis 

reported via t.1101344

Note: currently [majorTickInteravl is read-only property](http://docs.telerik.com/devtools/ios/api/Classes/TKChartCategoryAxis.html#//api/name/majorTickInterval) which prevents the manual setting of different values for TKChartCategoricalAxis .The issue is discussed [here](http://www.telerik.com/forums/can-no-longer-set-majortickinterval-on-tkchartcategoryaxis)

**Comment by ginev** [comment]
@NickIliev - this issue will be resolved in the next official release of NS UI (post 3.1.0). It is currently fixed in the @next version of the plugin.

**Comment by Natalia-Hristova** [comment]
Will be available in the next official release.

**Comment by topclaudy** [comment]
The problem persists for DateTimeCategoricalAxis.
