### ISSUE TITLE
NativeScript 3.0 RC support

### ISSUE THREAD

**Issue by Cae2** [telerik/nativescript-ui-feedback#145]
hello guys,

I never used or even installed nativescuor-ui plugin before, but when I tried today I got the error
![1](https://cloud.githubusercontent.com/assets/24416663/24701273/336bdf40-19d0-11e7-895c-951663a0c67f.jpg)

That means that the plugin isnt ready for NS 3.0 yet?

Thanks

**Comment by Natalia-Hristova** [comment]
Hello @Cae2 ,

NS 3.0 is not released yet but there is RC and nativescript-ui plugin supports it.
Which version of the NativeScript do you use?
Have in mind that if you use **NativeScript RC** you need to use the **RC of the nativescript-ui plugin too**.

**Comment by Cae2** [comment]
@Natalia-Hristova wow, thank you for the quick reply!

you're right, now I added nativescript-telerik-ui@rc and it compiles without problem.

have a nice day!

**Comment by Natalia-Hristova** [comment]
@Cae2 You're welcome! I'm happy this helped.

If you have any other problems, questions or suggestions, fill free to share them with us.

Have a nice day too :)
