### ISSUE TITLE
3.0.0RC -- Failed to find module : "ui/core/proxy"

### ISSUE THREAD

**Issue by SamuelGRwebfab** [telerik/nativescript-ui-feedback#147]
I updated to 3.0.0RC today and ran into this major issue. Even in nativescript-telerik-ui@3.0.0-2017.3.27.1. ui/core/proxy is being called. This, as we all know, has been removed.

Do we know when telerik-ui will be updated to work with 3.0.0RC?

**Comment by Natalia-Hristova** [comment]
Hello @SamuelGRwebfab ,

If you use NativeScript RC you should use nativescript-telerik-ui RC too. You can install it using rc tag:
npm i -g nativescript-telerik-ui@rc 

the version that this installs is 1.7.0-2017.4.4.1
