### ISSUE TITLE
[Feature request] RadCalendar - set language of the labels used in the calendar

### ISSUE THREAD

**Issue by wvegteren** [telerik/nativescript-ui-feedback#148]
The language of (month, day, etc.) labels used in the calendar is linked to the device language setting. It would be great to have the ability to set the language from code so the labels match the language selected in the {N} app.  
<img width="377" alt="agenda" src="https://cloud.githubusercontent.com/assets/3630285/24741591/e098352a-1aa6-11e7-83e3-f5ece2ec40de.png">

**Comment by Natalia-Hristova** [comment]
The feature is implemented and will be available in 1.7.0 :)

**Comment by wvegteren** [comment]
Cool, thanks !
