### ISSUE TITLE
Pull to refresh is too sensitive

### ISSUE THREAD

**Issue by Daxito** [telerik/nativescript-ui-feedback#15]
I think the pull to refresh is very very sensitive, I pull down just little little bit and it triggers, I think ti should be like this plugin for instance: https://www.npmjs.com/package/nativescript-pulltorefresh

Or maybe a way to add the sensitivity level?

Thanks!

**Comment by ginev** [comment]
Hi @Daxito,

Are you targeting the iOS or Android?

Thanks!

**Comment by Daxito** [comment]
@ginev Right now iOS, I feel it is too sensitive also because say I am scrolling from the bottom to the top, well, if I scroll to the top a little little too much then the Refresh is triggered.

**Comment by Cae2** [comment]
any updates about this? we need a trigger to pull...

using the swipe to action, we can use a `if (args.data.x > 150)` to setup a trigger, but not found anything like that on Pull to Refresh

**Comment by manojdcoder** [comment]
On android `pullToRefreshInitiated` event is triggered only when user releases the pull ui, but on iOS it happens as soon he pulls the ui and even before releasing it, can we fix this behavior?

**Comment by ginev** [comment]
@Cae2, @manojdcoder - we are going to revisit the PTR logic both on Android and iOS and will make sure to align the behavior and expose API for fine-tuning.

**Comment by vswee** [comment]
Setting the child container to 100% height makes the pull threshold respond as expected.
