### ISSUE TITLE
Navigating back using angular `location.back()` results in: java.lang.NullPointerException:

### ISSUE THREAD

**Issue by dgomezs** [telerik/nativescript-ui-feedback#153]
I'm experiencing exactly the same issue as it was reported on this [link](https://github.com/NativeScript/nativescript-angular/issues/437)

I couldn't find the original issue posted in this feedback. Any workaround for this? 

Thank you in advanced

**Comment by ginev** [comment]
@dgomezs, this repository is dedicated to UI for NativeScript - are you using one of the components from the suite while experiencing this issue?

**Comment by dgomezs** [comment]
@ginev yes I'm. I solved the issue this morning I had a ScrollView in the parent element and I think that was causing the issue. Everything working now
