### ISSUE TITLE
pullToRefresh="true" stop working if I go to another page and back

### ISSUE THREAD

**Issue by Cae2** [telerik/nativescript-ui-feedback#154]
Hello, Im testing a simple RadListView with pull and it works fine when I start the app, but if I navigate to another page and come back (using either the hard back button in android or `this.location.back();` for example, the pull didnt work anymore (doesnt trigger the animation or `(pullToRefreshInitiated)`).

Im testing NativeScript 3.0 rc along with nativescript-telerik-ui@rc

`<RadListView id="listView" [items]="ultimosProdutos" pullToRefresh="true" (pullToRefreshInitiated)="onPullToRefreshInitiated($event)" class="list-group" itemSwipe="true" selectionBehavior="None" (itemSwipeProgressStarted)="onSwipeCellStarted($event)"
    (itemSwipeProgressChanged)="onCellSwiping($event)" (itemSwipeProgressEnded)="onSwipeCellFinished($event)">`

**Comment by Cae2** [comment]
downgraded to NS 2.5.4 (using telerik-ui-feedback 1.6.2) and pull is working properly again!

**Comment by ginev** [comment]
@Cae2, we could not reproduce this issue on our side. Would it be possible if you sent is a ZIP with your project for further investigation. You can do this via DropBox or e-mail so that you don't attach it here.

**Comment by Cae2** [comment]
@ginev sadly I already modified a lot the project, and since I downgraded nativescript its working normally... if that happens again after the upgrade to 3.0 I will try to provide more info to this issue, thank you
