### ISSUE TITLE
Chart Label Format

### ISSUE THREAD

**Issue by initialcatalog** [telerik/nativescript-ui-feedback#157]
Hi,
How can I printout linear aixvalues and label values  of chart object formatted?

The value I see : 12500.00 but I want it as 12.500

Thank you.

**Comment by Natalia-Hristova** [comment]
Hello @initialcatalog , 

For the **axis labels** you can use ```axis.labelFormat = "%.3f"```
http://testdocs.telerik.com/devtools/nativescript-ui/api/classes/linearaxis.html#labelformat

for the **series labels** you can set _textFormat_ in the _PointLabelStyle_
http://testdocs.telerik.com/devtools/nativescript-ui/api/classes/pointlabelstyle.html#textformat
e.g.
```xml
        <chart:RadCartesianChart.series>
            <chart:BarSeries showLabels="true" items="{{ sourceItems1 }}" categoryProperty="{{ categoryProperty1 }}" valueProperty="{{ valuePropertySales1 }}">
                 <chart:BarSeries.labelStyle>
                     <chart:PointLabelStyle margin="10" fillColor="Green" textFormat="%.3f"/>
                 </chart:BarSeries.labelStyle>
            </chart:BarSeries>
        </chart:RadCartesianChart.series>
```

**Comment by initialcatalog** [comment]
@Natalia-Hristova  Thank you for reply.
