### ISSUE TITLE
Header and Footer of RadListView don't execute angular directives (Only in IOS)

### ISSUE THREAD

**Issue by dgomezs** [telerik/nativescript-ui-feedback#158]
I'm trying to use angular directives inside header and footer of the RadListView component. This works fine in Android but not in IOS. 

I created an example to highlight the issue [Test mobile app](https://github.com/dgomezs/test-mobile-app) 

On android the app shows the footer even with the *ngIf directive. On IOS this does not work properly as the footer does not show. 

Any ideas on a workaround?

**Comment by ginev** [comment]
@dgomezs please refer to #152 for more information.
