### ISSUE TITLE
[Bug] issue with Chart's zoom and pan gestures, while using `router-outlet`

### ISSUE THREAD

**Issue by tsonevn** [telerik/nativescript-ui-feedback#159]
An issue with Chart's `zoom` and `pan` gestures, while using `router-outlet`. After he makes navigation to another page and returns back those gestures will stop working. This case is reproduced only for Android.

I am attaching sample project, which could be debugged locally.
[Archive.zip](https://github.com/telerik/nativescript-ui-feedback/files/942621/Archive.zip)

**Comment by ginev** [comment]
This will be addressed in the upcoming NativeSciprt UI 2.0 release.

**Comment by Christopotamus** [comment]
Hi @ginev,

Is there any update on when Nativescript UI 2.0 will be released? I know you have the milestone set with a due date of May 4th so I'm assuming 2.0 is coming soon, but I hit this bug in the middle of a project.

Is there any chance of a hotfix while we wait for UI 2.0?

**Comment by ginev** [comment]
@Christopotamus, the plugin is already live. Check it out!
