### ISSUE TITLE
Change ListViewGridLayout property spanCount dynamically

### ISSUE THREAD

**Issue by Daxito** [telerik/nativescript-ui-feedback#16]
Is there a way to change the spanCount of the rad list view dynamically? I have it set to 3 in portrait, but what about landscape? I need to reset it to something like 5, is there a way to do that?

Thanks

**Comment by ginev** [comment]
@Daxito, in this case I would recommend resetting the `listViewLayout` property to a new value of `ListViewGridLayout` with the corresponding new value for `spanCount`.

**Comment by Daxito** [comment]
Thank you @ginev , I will give it a try, thank you!
