### ISSUE TITLE
metadata properties documentation

### ISSUE THREAD

**Issue by vcooley** [telerik/nativescript-ui-feedback#164]
I really appreciate the metadata way of creating forms, however, I think it could use some documentation. Currently it is difficult to dig through and find out what properties are valid properties. For instance when using metadata with groups on android, an `EntityProperty` will not be grouped properly. After some guessing I figured out that you can use the `group: groupName` in the metadata, which was a very clean solution for me, but would have saved me some time with proper documentation.

**Comment by tgpetrov** [comment]
Thanks for the info. We will extend the EntityProperty article in [our documentation](http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/DataForm/dataform-entity-property) to include the acceptable values in the data form metadata.

**Comment by NickIliev** [comment]
Requested also via t. 1106493

**Comment by tgpetrov** [comment]
@vcooley The list with acceptable properties have been added in these articles:
The list with acceptable keys in JSON Metadata is now added in these articles:
[EntityProperty in NativeScript Core](http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/DataForm/dataform-entity-property#adjusting-the-editors-with-json)
[EntityProperty in NativeScript with Angular](http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/DataForm/dataform-entity-property#adjusting-the-editors-with-json)

**Comment by vcooley** [comment]
@tgpetrov Looks good, except that I believe `groupName` does not work in the metadata, it should be `group` unless that has changed since the update.

**Comment by tgpetrov** [comment]
@vcooley Both `groupName` and `group` are acceptable and should be handled identically by the DataForm in Android. Can you confirm that are getting a different result with `groupName`? Is so, what's your setup?

**Comment by vcooley** [comment]
I'm having trouble reproducing. Perhaps I had something else wrong as well when I was using the `groupName` property. Thanks!
