### ISSUE TITLE
Cannot install nativescript-telerik-ui with npm

### ISSUE THREAD

**Issue by TheLox95** [telerik/nativescript-ui-feedback#17]
Hello, since I do not know where to look for help with this issue I will put it here. Right now I have troubles installing `nativescript-telerik-ui` with npm. When I run `npm install nativescript-telerik-ui --save` npm hung up a while and then show this 
`npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "nativescript-telerik-ui" "--save"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9`

`npm ERR! shasum check failed for C:\Users\Leonardo\AppData\Local\Temp\npm-3072-abbc073c\registry.npmjs.org\nativescript-telerik-ui\-\nativescript-telerik-ui-1.4.1.tgz
npm ERR! Expected: ff8ee68337fdf928721cd0ab30e57de7287539e5
npm ERR! Actual:   9dac597bb317345ba37a9fdc967c4ab4fb3ae3c6
npm ERR! From:     https://registry.npmjs.org/nativescript-telerik-ui/-/nativescript-telerik-ui-1.4.1.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>`

`npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp2\htdocs\programmingChallenges\npm-debug.log`

I already have tried running `rm -fr node_modules/` and `npm cache clean` plus I restarted my computer but nothing of that worked. I'm able to install all my others modules without problem `nativescript-telerik-ui` is the only one that gives me problems

**Comment by VladimirAmiorkov** [comment]
Hi @TheLox95 ,

The correct way of installing the [nativescript-telerik-ui](https://www.npmjs.com/package/nativescript-telerik-ui) is with the use of the:

- `tns plugin add nativescript-telerik-ui` or `tns plugin add nativescript-telerik-ui-pro`

You can "uninstall" or remove them via:

- `tns plugin remove nativescript-telerik-ui` or `tns plugin remove nativescript-telerik-ui-pro`

The add command will add the nativescript-telerik-ui plugin to your {N} project's dependencies.
