### ISSUE TITLE
RadListView swipeLimit 0 ignored on Android

### ISSUE THREAD

**Issue by edoardocavazza** [telerik/nativescript-ui-feedback#171]
Setting `0` to swipeLimit (left or right) is ignored by Android.

```js
onSwipeCellStarted(args: listViewModule.ListViewEventData) {
        let swipeLimits = args.data.swipeLimits;
        let swipeView = args['object'];
        let rightItem = swipeView.getViewById('actions-view');
        swipeLimits.threshold = rightItem.getMeasuredWidth() / 2;
        swipeLimits.left = 0; // <- here
        swipeLimits.right = rightItem.getMeasuredWidth();
}
```

Since I wanted to enable swipe actions only on the right I need to set `0` to swipeLimit left (workarounded with `0.1`).

**Comment by ginev** [comment]
@edoardocavazza, are you using the Swipe Actions feature or the old Swipe to Execute? There were some issues with the Swipe to Execute implementation and therefore we implemented a better approach with Swipe Actions: http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/ListView/swipe-actions
