### ISSUE TITLE
RadListView swipeLimit inverted on Android

### ISSUE THREAD

**Issue by edoardocavazza** [telerik/nativescript-ui-feedback#172]
Setting different values for swipeLimit.left and swipeLimit.right I notice that they are inverted on Android (works on iOS).

It could be useful too to have more samples in the documentation with different (and not only specular) actions.

**Comment by ginev** [comment]
@edoardocavazza, can you please confirm that you are using the [Swipe Actions](http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/ListView/swipe-actions) feature instead of Swipe to Execute as this is the preferred way to do this?

**Comment by edoardocavazza** [comment]
Yes, I am using SwipeActions with actions only on swipe left (if you have actions on both side you will not notice this behaviour)
