### ISSUE TITLE
[DataForm] feature request: validation via regular expressions

### ISSUE THREAD

**Issue by felix-idf** [telerik/nativescript-ui-feedback#173]
It would be great to have a validator that can check, if the content of a text PropertyEditor matches a given regular expression. In some scenarios, you want to allow only letters, numbers and certain special characters in your input text, so the existing validators right now wouldn't be suitable enough.

And if it doesn't match, an error message should be shown just like it is already done with the existing validators.

**Comment by NickIliev** [comment]
+1  Requested via t.1107450

**Comment by Natalia-Hristova** [comment]
This is implemented and it will be available in our next official release.
