### ISSUE TITLE
[DataForm] feature request: combined (grouped) validation of two form fields (for confirmation)

### ISSUE THREAD

**Issue by felix-idf** [telerik/nativescript-ui-feedback#174]
One possible scenario: 
You have one input field for your email address and a second input field to confirm your email address. 
You need to check if both fields contain a valid email (using the existing _EmailValidator_ or probably a regexp-validator), but you also need to validate, if _both fields contain the same email address_. 
If not, there should be shown an error message, maybe at the second form field if you assume, that the first field contains the correct one that should be confirmed.

**Comment by NickIliev** [comment]
+1  Requested via t.1107450

**Comment by vcooley** [comment]
I want to echo this feature request, but I personally would prefer a more general customization of validators. For example, create the ability to attach a function to the editor that gets called as per the `validationMode` property and can cause the entity to become invalid based on it's return value.

**Comment by VladimirAmiorkov** [comment]
@vcooley This is am awesome idea for a way to create a custom Validator. On the other hand this issue is to provide a built-in specific Validator which does not exclude the possibility of providing a way that you can write your own Validators.

**Comment by Natalia-Hristova** [comment]
This is implemented and it will be available in our next official release.
