### ISSUE TITLE
[DataForm] Question: boolean validator 'isChecked'

### ISSUE THREAD

**Issue by felix-idf** [telerik/nativescript-ui-feedback#176]
Hello,
is there already a way to validate, if a switch (checkbox) is activated?
In one of our forms the user needs to accept our terms of use using a switch and I tried to find a suitable validator [here](http://docs.telerik.com/devtools/nativescript-ui/api/classes/propertyvalidator.html). Is there another way to validate that?

Best regards,
Felix

**Comment by tgpetrov** [comment]
@felix-idf Another great suggestion! This type of validation is a must and we will ensure to include it when working on your other requests for the validation in DataForm. Thank you!

**Comment by felix-idf** [comment]
Sounds great, thank you!

**Comment by Natalia-Hristova** [comment]
This is implemented and it will be available in our next official release.
