### ISSUE TITLE
[Feature] DataForm - ability to setup specific width for every `Entity`

### ISSUE THREAD

**Issue by tsonevn** [telerik/nativescript-ui-feedback#179]
It would be useful to have a property, which allows setting a specific width for the `EntityProperty`. For example:
```
<df:EntityProperty width="20" name="phone" displayName="" imageResource="res://ic_dataform_phone" hintText="phone" index="1" >
                <df:EntityProperty.editor>
                    <df:PropertyEditor type="Phone"/>
                </df:EntityProperty.editor>
            </df:EntityProperty>
```
This could also allow us to set the Image width, while using `Image Labels`. At the moment the input fields is still 50% of the display width on iOS. 
![dataform-image-labels-ios](https://cloud.githubusercontent.com/assets/17448734/25885711/b2f5d22c-3562-11e7-98a6-1a472eea7a38.png)

Requested via -> t.1108053

**Comment by lattice-it** [comment]
- Hi 
Is there any timeframe on adding this feature?

Thank you.

**Comment by VladimirAmiorkov** [comment]
Hi @lattice-it ,

Currently we cannot provide you with a time frame for this specific feature request. We will do our best to implement this functionality as soon as possible in the the nativescript-telerik-ui plugin.

**Comment by Natalia-Hristova** [comment]
Hello @lattice-it and @tsonevn ,

This feature is implemented and will be available in our next official release (in week or two). If you want to test it out before that you can use the "next" version of the nativescript-telerik-ui-pro plugin. Simply install that version of the plugin: ``` tns plugin add nativescript-telerik-ui-pro@next``` .
