### ISSUE TITLE
[RadListView] setting args.returnValue in itemSelecting event is not working

### ISSUE THREAD

**Issue by NickIliev** [telerik/nativescript-ui-feedback#181]
Using [itemSelectingEvent](http://docs.telerik.com/devtools/nativescript-ui/api/classes/radlistview.html#itemselectingevent) as described in the API references

> This event is fired before an item to be selected. Return value indicates whether the specified item should be selected. The event exposes an instance of the ListViewEventData class.

However setting **returnValue** to true or false is not respected and in **[itemSelectedEvent](http://docs.telerik.com/devtools/nativescript-ui/api/classes/radlistview.html#itemselectedevent)** the **returnValue** is always **undefined**.

This results that the cell can not be marked as non-selectable and the default styles for selection are always applied. 

Reproduced with 2.0.1 and reported via t 1107869.  

Possible workaround to overwrite the default selecting styles and disable the selection for specific cells can be found [here](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/others/t_1107869)

**Comment by manojdcoder** [comment]
Issue seems reproduced on Playground with plugin version 6.3.0 - https://play.nativescript.org/?template=play-ng&id=pQyVZE
