### ISSUE TITLE
DataForm's TKEntityProperty readOnly doesn't bind properly in Angular on iOS

### ISSUE THREAD

**Issue by abhayastudios** [telerik/nativescript-ui-feedback#183]
### Tell us about the problem
DataForm's TKEntityProperty readOnly doesn't bind properly in Angular on iOS when binding to a variable `[readOnly]="activeStep"` instead of static `readOnly="true"`

### Which platform(s) does your issue occur on?
iOS only (Android seems to work fine):

```
CONSOLE ERROR file:///app/tns_modules/@angular/core/./bundles/core.umd.js:1091:24: ERROR Error: Uncaught (in promise): TypeError: undefined is not an object (evaluating 'this.ios.updateEditorForProperty')
	onPropertyPropertyChanged@file:///app/tns_modules/nativescript-telerik-ui-pro/dataform/dataform.js:531:25
	entityPropertyChangedHandler@file:///app/tns_modules/nativescript-telerik-ui-pro/dataform/dataform.js:354:49
	notify@file:///app/tns_modules/tns-core-modules/data/observable/observable.js:103:31
	set@file:///app/tns_modules/tns-core-modules/ui/core/properties/properties.js:92:32
	setPropertyInternal@file:///app/tns_modules/nativescript-angular/view-util.js:196:17
	setProperty@file:///app/tns_modules/nativescript-angular/view-util.js:155:37
	setProperty@file:///app/tns_modules/nativescript-angular/renderer.js:133:41
	setProperty@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:13296:34
	setElementProperty@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:9549:30
	checkAndUpdateElementValue@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:9468:31
	checkAndUpdateElementInline@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:9402:50
	checkAndUpdateNodeInline@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:12117:50
	debugCheckAndUpdateNode@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:12722:64
	debugCheckRenderNodeFn@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:12701:36
```

### Please provide the following version numbers that your issue occurs with:
UI Pro version 2.0.1
NS 3.0.0

```
$ tns info
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬─────────────┐
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 3.0.0           │ 3.0.0          │ Up to date  │
│ tns-core-modules │ 3.0.0           │ 3.0.0          │ Up to date  │
│ tns-android      │ 3.0.0           │ 3.0.0          │ Up to date  │
│ tns-ios          │ 3.0.0           │ 3.0.0          │ Up to date  │
└──────────────────┴─────────────────┴────────────────┴─────────────┘
```

```
{
  "description": "Test App",
  "license": "SEE LICENSE IN LICENSE",
  "readme": "NativeScript Application",
  "nativescript": {
    "id": "com.abhayastudios.testapp",
    "tns-ios": {
      "version": "3.0.0"
    },
    "tns-android": {
      "version": "3.0.0"
    }
  },
  "dependencies": {
    "@angular/animations": "~4.1.0",
    "@angular/common": "~4.1.0",
    "@angular/compiler": "~4.1.0",
    "@angular/core": "~4.1.0",
    "@angular/forms": "~4.1.0",
    "@angular/http": "~4.1.0",
    "@angular/platform-browser": "~4.1.0",
    "@angular/router": "~4.1.0",
    "nativescript-angular": "~3.0.0",
    "nativescript-telerik-ui-pro": "file:./nativescript-ui-pro/nativescript-ui-pro.tgz",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-toasts": "^1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.3.0",
    "tns-core-modules": "~3.0.0"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.1.0",
    "@ngtools/webpack": "1.3.0",
    "babel-traverse": "6.22.1",
    "babel-types": "6.22.0",
    "babylon": "6.15.0",
    "copy-webpack-plugin": "~4.0.1",
    "extract-text-webpack-plugin": "~2.1.0",
    "htmlparser2": "~3.9.2",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-typescript": "~0.4.0",
    "nativescript-dev-webpack": "^0.4.0",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.0.2",
    "typescript": "^2.3.2",
    "webpack": "~2.3.3",
    "webpack-sources": "~0.2.3",
    "zone.js": "~0.8.2"
  },
  "scripts": {
    "ns-bundle": "ns-bundle",
    "start-android-bundle": "npm run ns-bundle --android --start-app",
    "start-ios-bundle": "npm run ns-bundle --ios --start-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app"
  }
}

```

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
```
<GridLayout rows="auto, *, auto">
      <RadDataForm row="1" tkExampleTitle tkToggleNavButton [source]="test">
        <TKEntityProperty tkDataFormProperty index="0" name="testId" displayName="ID" [readOnly]="activeStep">
          <TKPropertyEditor tkEntityPropertyEditor type="Number"></TKPropertyEditor>
        </TKEntityProperty>
      </RadDataForm>
    </GridLayout>
```

```
export class TestComponent implements OnInit {
  public activeStep:boolean = true;
  public test:any = { "testId": 1000 };

 constructor() {
  }
```

Is there any work around available until this is fixed?

Thanks!

**Comment by VladimirAmiorkov** [comment]
Hi @abhayastudios ,

I tried to reproduce the described issue but to not avail. Using our sdkAngular repository and the "Editors" example under RadDataForm I did the following changes to the current example:

- Added the `public activeStep:boolean = true;` property to [dataform-editors.component.ts](https://github.com/telerik/nativescript-ui-samples-angular/blob/release/sdkAngular/app/dataform/editors/dataform-editors.component.ts)
- Added the `[readOnly]="activeStep" `binding to the html of [dataform-editors.component.html](https://github.com/telerik/nativescript-ui-samples-angular/blob/release/sdkAngular/app/dataform/editors/dataform-editors.component.html) and change the TKPropertyEditor `type="Number"`

Running that code on iOS 10.3 works as expected. Can you give us more details about your environment like on what iOS version are you experiencing the issue?

**Comment by abhayastudios** [comment]
Hi @VladimirAmiorkov,

Thanks for your reply and sorry for my delay in replying. If you have a look at this [test project](https://github.com/abhayastudios/testapp), you will see that it throws the error I mentioned above (I hope).

I am running it on the iOS simulator with Xcode 8.3.2 (latest AFAIK) running iOS 10.3. Please let me know if you need any additional info.

Thanks!

**Comment by VladimirAmiorkov** [comment]
@abhayastudios Thank you for clarifying this, I was able to observe the mentioned error in the provided test project.

The good news is we have already resolved this issue and a fix for it is available in the "next" version of the nativescript-telerik-ui-pro plugin where you can test it out. Simply install that version of the plugin: `tns plugin add nativescript-telerik-ui-pro@next` . Note that the next version is a version of the plugin that is updated on daily/hourly basis from our current development brach which makes it not a good option for production applications but it is a great way to verify fixes and test new functionality.

**Comment by abhayastudios** [comment]
Thanks @VladimirAmiorkov! Any idea when this fix will reach a released version?

**Comment by VladimirAmiorkov** [comment]
@abhayastudios Our next release of nativescript-telerik-ui-pro (3.0.0) is planned for the mid of next month.

**Comment by abhayastudios** [comment]
Thanks!
