### ISSUE TITLE
Running Progress NativeScript UI Sample App Build Failed

### ISSUE THREAD

**Issue by rlee2015** [telerik/nativescript-ui-feedback#187]
I tried to run the sample app (https://github.com/telerik/nativescript-ui-samples). I got the following build failed. The tns version is 3.0.0.

....
....
:asbg:runAstParser UP-TO-DATE
:asbg:generateBindings UP-TO-DATE
:generateF0F1F2F3DebugResValues UP-TO-DATE
:generateF0F1F2F3DebugResources UP-TO-DATE
:mergeF0F1F2F3DebugResources UP-TO-DATE
:processF0F1F2F3DebugManifest UP-TO-DATE
:processF0F1F2F3DebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processF0F1F2F3DebugResources'.
> Error: more than one library with package name 'com.telerik.android.common'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by surpi** [comment]
Did you solve the problem? Can you tell me how? Facing the same issue atm
