### ISSUE TITLE
RadListView list scroll to end effect

### ISSUE THREAD

**Issue by tigrenok00** [telerik/nativescript-ui-feedback#193]
Hi,
I'm using Angular and the question is:
When I scroll the list **fast** till the end, there is a highlight effect visible when the list bumps the end on last item. However, when I'm already at the end of the list and attempt to scroll futher down, there is no effect. How can I recreate the highlight at this point, or even better, to create the effect of pulling the list up showing a white background, like the standart listview does in some apps?
Thank you!

**Comment by ginev** [comment]
@tigrenok00, can you please use the template to submit an issue as we would need more information to reproduce the scenario?

**Comment by tigrenok00** [comment]
### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.0.1
- Cross-platform modules: 3.0.0
- Runtime(s): 3.0.0
- Plugin(s): "nativescript-telerik-ui": "2.0.1"

**Comment by ginev** [comment]
@tigrenok00,we cannot reproduce this glitch on our side. Can you please share a project that we can use to reproduce it?

**Comment by tigrenok00** [comment]
Hi,

Unfortunately, I cannot post the project right now, however, here is a simplified html of how the view looks.
The relevant ListView is orderLinesView. I kept all its settings and events here.
Hope it could help.

Am I correct to assume that the effect of pulling down at end of list exists in RadListView like in the regular ListView? Do you know what am I talking about?

Thank you!


```
<GridLayout rows="auto, *, auto, auto">

    <SearchBar row="0"></SearchBar>

    <RadListView row="1" *ngIf="isNewOrder" id="orderLinesView" tkExampleTitle tkToggleNavButton [items]="displayProductList"
        selectionBehavior="Press" multipleSelection="false" swipeActions="true" (itemSwipeProgressEnded)="onSwipeCellFinished($event)"
        (itemSwipeProgressStarted)="onSwipeCellStarted($event)" (itemSwipeProgressChanged)="onCellSwiping($event)" class="list-group"
        (itemSelected)="onItemSelected($event)" pullToRefresh="true" (pullToRefreshInitiated)="onPullToRefreshInitiated($event)">
        <ng-template tkListItemTemplate let-item="item">
            <StackLayout>
				<StackLayout class="list-group-item" backgroundColor="white">
					<Label [text]="item.itemDescr" textWrap="true" class="list-group-item-heading"></Label>
					<StackLayout class="hr-light"></StackLayout>
				</StackLayout>
            </StackLayout>
        </ng-template>
        <GridLayout *tkListItemSwipeTemplate columns="auto, *, auto">
            <StackLayout id="plus-view" col="0" class="plusViewStackLayout" (tap)="onLeftSwipeClick($event)">
                <Label text="" verticalAlignment="center"></Label>
                <Label class="fa swipe-label" [text]="'fa-plus-circle' | fonticon" verticalAlignment="center" horizontalAlignment="center"></Label>
            </StackLayout>
            <StackLayout id="minus-view" col="2" class="minusViewStackLayout" (tap)="onRightSwipeClick($event)">
                <Label text="" verticalAlignment="center"></Label>
                <Label class="fa swipe-label" [text]="'fa-minus-circle' | fonticon" verticalAlignment="center" horizontalAlignment="center"></Label>
            </StackLayout>
        </GridLayout>
    </RadListView>

    <StackLayout row="2" class="hr-light"></StackLayout>

    <RadListView row="3" #catListView tkExampleTitle tkToggleNavButton [items]="categories">
            <ng-template tkListItemTemplate let-item="item">
                <Button class="btn btn-rounded-sm btn-primary category-btn"
                text="{{item.orderCategoryDescr}} [{{countItemsInCategory(item)}}]"></Button>
            </ng-template>
            <ListViewLinearLayout tkListViewLayout scrollDirection="Horizontal"></ListViewLinearLayout>
    </RadListView>

</GridLayout>
```

**Comment by ginev** [comment]
@tigrenok00 - still not able to reproduce the issue :(
The most productive way to investigate this would be to directly take a look at a project that reproduces the glitch to see what exactly causes it. By the way, which Android API Level are you testing on?

**Comment by bhavincb** [comment]
hii @ginev 
i'm also having some issue
