### ISSUE TITLE
RadSideDrawer only showing up only once on iOS

### ISSUE THREAD

**Issue by RyamBaCo** [telerik/nativescript-ui-feedback#197]
### Tell us about the problem
Hey there,

in my App, I'm using a RadSideDrawer, which is fading in from the bottom when I click on an entry of a RadListView. Before upgrading to NativeScript 3.0 everything worked fine. But after upgrading Telerik UI to 2.0.1 I'm experiencing strange behavior on iOS: The first time I call showDrawer() everything works as expected, but when I want to call showDrawer() again it doesn't work any longer. Also this issue only occurs, when I set the drawer position to bottom or right (on left and top it works as expected). 

### Which platform(s) does your issue occur on?
> iOS

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 2.0.1
- **CLI:** (run `tns --version` to fetch it) 3.0.2
- **Cross-platform modules:** 3.0.1
- **Runtime(s):** tns-android: 3.0.0, tns-ios: 3.0.1
- **Other Plugin(s):** "dependencies": {
    "@angular/animations": "~4.1.0",
    "@angular/common": "~4.1.0",
    "@angular/compiler": "~4.1.0",
    "@angular/core": "~4.1.0",
    "@angular/forms": "~4.1.0",
    "@angular/http": "~4.1.0",
    "@angular/platform-browser": "~4.1.0",
    "@angular/platform-browser-dynamic": "~4.1.0",
    "@angular/router": "~4.1.0",
    "@ngx-translate/core": "^6.0.1",
    "nativescript-angular": "~3.0.0",
    "nativescript-background-http": "^3.0.0",
    "nativescript-camera": "^3.0.0",
    "nativescript-imagepicker": "^3.0.1",
    "nativescript-iqkeyboardmanager": "^1.0.1",
    "nativescript-orientation": "github:nathanaela/nativescript-orientation#pull/14/head",
    "nativescript-permissions": "^1.2.3",
    "nativescript-telerik-ui": "^2.0.1",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-toasts": "^1.0.3",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.3.0",
    "tns-core-modules": "~3.0.1",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.24.1",
    "babel-types": "6.24.1",
    "babylon": "6.17.1",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.4.0",
    "typescript": "~2.2.1"
  }

### Please tell us how to recreate the issue in as much detail as possible.
> 1. Click on a RadlistView-Entry
> 2. RadSideDrawer shows up
> 3. Click on a RadlistView-Entry again
> 4. RadSideDrawer hides
> 5. Click on a RadlistView-Entry
> 6. RadSideDrawer is no longer showing up

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
html:
```
<media-upload-actionbar [title]="parentList.name" [iconVisibility]="actionbarIconVisibility"></media-upload-actionbar>
<RadSideDrawer drawerLocation="Bottom" drawerContentSize="150">
    <StackLayout tkDrawerContent class="sidedrawer-center sidedrawer-center-playlist">
        <StackLayout class="sidedrawer-content sidedrawer-content-playlist">
            <StackLayout class="sidedrawer-list-item" orientation="vertical" (tap)="onUploadTap()">
                <Label class="sidedrawer-list-item-icon sidedrawer-list-item-playlist font-awesome" text="&#xf03e;"></Label>
                <Label class="sidedrawer-list-item-text sidedrawer-list-item-playlist" text="{{ 'actionMediathek' | translate }}"></Label>
            </StackLayout>
            <StackLayout class="sidedrawer-list-item" orientation="vertical" (tap)="onPictureTap()">
                <Label class="sidedrawer-list-item-icon sidedrawer-list-item-playlist font-awesome" text="&#xf030;"></Label>
                <Label class="sidedrawer-list-item-text sidedrawer-list-item-playlist" text="{{ 'actionTakePicture' | translate }}"></Label>
            </StackLayout>
            <StackLayout class="sidedrawer-list-item" [visibility]="selectedItemIndex >= 0 ? 'visible' : 'collapse'" orientation="vertical"
                (tap)="onDeleteTap()">
                <Label class="sidedrawer-list-item-icon sidedrawer-list-item-playlist font-awesome" text="&#xf1f8;"></Label>
                <Label class="sidedrawer-list-item-text sidedrawer-list-item-playlist" text="{{ 'actionDeletePlaylistEntry' | translate }}"></Label>
            </StackLayout>
            <StackLayout class="sidedrawer-list-item" [visibility]="selectedItemIndex < 0 ? 'visible' : 'collapse'" orientation="vertical"
                (tap)="reloadPlaylistItems($event)">
                <Label class="sidedrawer-list-item-icon sidedrawer-list-item-playlist font-awesome" text="&#xf021;"></Label>
                <Label class="sidedrawer-list-item-text sidedrawer-list-item-playlist" text="{{ 'actionRefreshPlaylistEntry' | translate }}"></Label>
            </StackLayout>
        </StackLayout>
    </StackLayout>
    <GridLayout tkMainContent class="page">
        <RadListView id="playlistItems" [items]="playlistItemList" class="list-group" pullToRefresh="true" (pullToRefreshInitiated)="reloadPlaylistItems($event)"
            itemReorder="true" (itemReorderStarted)="reorderStarted($event)" (itemReordered)="reorderPlaylistItems($event)" itemDeleteAnimation="Fade"
            multipleSelection="false" selectionBehavior="Press">
            <ng-template tkListItemTemplate let-item="item">
                <StackLayout orientation="vertical">
                    <GridLayout columns="auto, *, auto" [class]="item.selected ? 'list-group-item playlist-item-selected' : 'list-group-item'">
                        <Image col="0" [src]="item.thumbnail_url" [visibility]="item.content_type !== 'playlist' && item.content_type !== 'external_media' ? 'visible' : 'collapse'"
                            height="60" width="106" class="img-rounded"></Image>
                        <StackLayout col="0" height="60" width="106" horizontalAlignment="center" verticalAlignment="center" [visibility]="item.content_type === 'playlist' ? 'visible' : 'collapse'">
                            <Label class="playlist-item-icon text-center font-awesome" text="&#xf0ca;"></Label>
                        </StackLayout>}
                        <StackLayout col="0" height="60" width="106" horizontalAlignment="center" verticalAlignment="center" [visibility]="item.content_type === 'external_media' ? 'visible' : 'collapse'">
                            <Label class="playlist-item-icon text-center font-awesome" text="&#xf08e;"></Label>
                        </StackLayout>
                        <StackLayout col="0" height="60" width="106" horizontalAlignment="center" verticalAlignment="center" [visibility]="item.content_type === 'channel' && !item.thumbnail_url ? 'visible' : 'collapse'">
                            <Label class="playlist-item-icon text-center font-awesome" text="&#xf09e;"></Label>
                        </StackLayout>
                        <StackLayout col="1" orientation="vertical" class="m-10">
                            <Label [text]="item.name"></Label>
                            <Label class="footnote font-awesome" [text]="item.infoText"></Label>
                        </StackLayout>
                        <StackLayout col="2" horizontalAlignment="center" verticalAlignment="center" (tap)="itemSelected($event)">
                            <Image src="res://icon_playlistitem_options" width="30" height="60"></Image>
                        </StackLayout>
                    </GridLayout>
                    <StackLayout class="hr-light"></StackLayout>
                </StackLayout>
            </ng-template>
        </RadListView>
        <ActivityIndicator [busy]="playlistItemLoading" [visibility]="playlistLoading ? 'visible' : 'collapse'" horizontalAlignment="center"
            verticalAlignment="center"></ActivityIndicator>
    </GridLayout>
</RadSideDrawer>
```

itemSelected-Event (showDrawer gets called but doesn't show the drawer after executing for the second time):
```
itemSelected(args) {
		this.playlistItemList.forEach((item, index) => {
			if(args.object.bindingContext === item) {
				item.selected = true;
				this.selectedItemIndex = index;
			} else {
				item.selected = false;				
			}
		});
    this.drawerComponent.sideDrawer.showDrawer();
	}
```

**Comment by VladimirAmiorkov** [comment]
Hi @RyamBaCo ,

I tried to reproduce this issue in our sdk examples but to no avail. Opening the RadSideDrawer on a tap event of its ng-template elements with drawerLocation set to Bottom to any other value works as expected in the latest 2.0.1 version.

Could you share with us a runnable project that reproduces this issue so that we can take a further look at it. The project that I used to test this case can be found here: https://github.com/telerik/nativescript-ui-samples

**Comment by RyamBaCo** [comment]
Hi there!

thank you for response! I created a small project reproducing this issue and pushed it to my github account:
https://github.com/RyamBaCo/RadSideDrawerExample

I added two dummy list entries. When I click the dots of one entry the drawer appears. When I click on the dots of the second entry, the drawer will no longer appear (showDrawer() is called in the itemSelected-function). As I already told this issue seems to be new since NS3.0, because with NS2.5 this issue didn't occur to me.

**Comment by VladimirAmiorkov** [comment]
@RyamBaCo thank you for providing the sample project. I was able to run it but I am a bit confused on the exact issue. Here is what I observe:

- Initially press the dots
- The drawer is opened
- Press the second item's dots
- The drawer is closed. This is expected as the the RadSideDrawer is designed to close when the "fade" layer (out side of the drawer content) is interacted with. Also note that with this action the `itemSelected()` handler is not called meaning the `showDrawer()` is also not called.
- Again press the second dots
- The drawer is opened as normal

This is the case of any of the drawerLocation. Am I missing something ?

**Comment by RyamBaCo** [comment]
You are right. The example works like a charm on Android. But the iPhone emulator is causing the issues I mentioned.

**Comment by VladimirAmiorkov** [comment]
@RyamBaCo thank you for clarifying this. I was able to observe the mentioned issue and indeed it looks like to be an issue in the RadSideDrawer in this specific scenario. The cause of the issue is the implementation of the "selected item" via `[class]="item.selected ? 'list-group-item playlist-item-selected' : 'list-group-item'"`. If you remove the `playlist-item-selected` class from that conditional binding for the `class` you can observe that the issue is resolved. Another way to reproduce this issue is by manually changing the `borderWidth` of that GridLayout without the use of css.

We are currently investigating why this conditional class setting may be causing such issue.

**Comment by RyamBaCo** [comment]
Alright, thanks for pointing that out! What I had to do after upgrading to NS3.0 was to set the border-width CSS property of the sidedrawer items to zero as I was getting weird borders around the button texts:

```
.sidedrawer-list-item-text {
  border-width: 0;
}
```
Maybe this is somehow related as setting the border-width of the selected list item is causing that issue.

**Comment by VladimirAmiorkov** [comment]
@RyamBaCo We have already addressed this issue in our internal code and the fix will be available in our next official 3.0.0 version.

You can test the fix in our "next" version by installing it via: `tns plugin add nativescript-telerik-ui@next` or `tns plugin add nativescript-telerik-ui-pro@next`. Note the "next" version is a plugin version that is considered not stable for release as it is constantly being updated on hourly/daily basis. It is provided for testing of new features and verification of bug fixes.

**Comment by RyamBaCo** [comment]
Awesome, thanks! :)
Unfortunately I cannot test it as it is for instance crashing on Android (maybe because of cross references from nativescript-imagepicker), but as long as this fix appears in the next release it is good enough for me.

**Comment by sudhanshu-15** [comment]
Thank you for sharing this information.
I am also facing a similar issue when I am using RadSideDrawer for TabView navigation. My implementation uses Typescript without Angular, but it seems like a similar issue. It is working perfectly on Android but on iOS it works only once. Here are some sample code snippets:

```
changeTab(args) {
        let page = <Page>topmost().currentPage;
        var tabViewInside: tab.TabView = <tab.TabView>page.getViewById("tabView1");
        let pageName:string = args.view.text.toLowerCase();
        if (pageName.localeCompare('notifications')) {
            tabViewInside.set('selectedIndex', 1);
        }else if (pageName.localeCompare('requests')) {
            tabViewInside.set('selectedIndex', 0);
        }
        appViewModel.set("selectedPage", tabViewInside.selectedIndex);
    }
```

```
<grid-layout class="drawer-content">
  <stack-layout>
    <Image src="res://acicon" class="drawer-image" />
    <label text="Notifications" tap="navigate" class="{{ selectedPage == 0 ? 'selected' : '' }}" />
    <label text="Requests" tap="navigate" class="{{ selectedPage == 1 ? 'selected' : '' }}" />
  </stack-layout>
</grid-layout>
```

```
.drawer-content {
  background-color: #7D110C;
  color: white;
  padding-top: 20;
}

.drawer-content label {
  font-size: 20;
  margin: 10 0 15 25;
}

.selected {
  color: #e4ba4e;
}
```
Will wait for the new release.

**Comment by sudhanshu-15** [comment]
Verified the issue was resolved in new release.
