### ISSUE TITLE
Relative path in Chart brakes build

### ISSUE THREAD

**Issue by Crevil** [telerik/nativescript-ui-feedback#20]
When using the `nativescript-ui-pro` package with a `Chart` component the build brakes when resolving a relative path: `./../` in the `chart-directives.js` module.

```
file:///app/bundle.js:139015:93: JS ERROR Error: Cannot find module "./../"
```

Adding `chart` to the path fixes the issue, so the `require` becomes:

```
var chartModule = require('./../chart');
```
## Info

NativeScript 2.3.0
nativescript-angular 1.1.0
nativescript-telerik-ui-pro 1.4.1

Using webpack for the build:

```
tns run ios --emulator --bundle
```

**Comment by VladimirAmiorkov** [comment]
Hi @Crevil ,

Are you by any chance trying to webpack an NativeScript + Angular application in your builds? If that is the case note that the 1.4.1 version does not support webpack. Support for webpack is coming with our next official release 1.5.0 which is due for release by the end of the week.

In the meanwhile you can test our "development" plugin via the npm "tags" system, simply change the version of the `nativescript-telerik-ui-pro to **next**:

`"nativescript-telerik-ui-pro": "next"`

**Comment by Crevil** [comment]
We are using webpack, yes. We look forward for webpack support in the next release.
