### ISSUE TITLE
RadListView item update

### ISSUE THREAD

**Issue by tigrenok00** [telerik/nativescript-ui-feedback#200]
Hi,
I have a component which holds a RadListView of items. When an item is clicked, the component fires an event, which opens a modal in a parent component and there changes the item qty parameter. The problem is that after the modal is closed, the item in the list is not updated, it only gets updated when I begin scrolling the list.
I've tried to call a list refresh method, but this causing the list to rewind to starting position, and when I use the goToIndex method, it is not the same as keeping the exact Y location in the list.
How can I achieve the immediate item redraw after changing the data, or alternatively, scroll to exact position of the list?
I'm using Angular and seeking for a solution for both Android and iOS.
Thank you!

**Comment by ginev** [comment]
@tigrenok00, you should make sure your business objects inherit from Observable: https://docs.nativescript.org/api-reference/classes/_data_observable_.observable.html

**Comment by tigrenok00** [comment]
@ginev Hi, inheritance from Observable did not work in my case. However, I just found a solution which worked:
`changeDetection: ChangeDetectionStrategy.Default`
(instead of OnPush)

Do you happen to have an advice on the subject of scrolling to exact Y position of the list? We could use this feature in other situations as well.
Thank you!

**Comment by ginev** [comment]
@tigrenok00, there's no ability to scroll by pixels currently. You can scroll to a given item. We will log this in our TODO list for future releases.

**Comment by ginev** [comment]
@tigrenok00 the API for scrolling with a given amount of pixels will be part of our upcoming release.

**Comment by Natalia-Hristova** [comment]
@tigrenok00 
You can use the "next" version of the nativescript-telerik-ui-pro plugin to try the new added method ```scrollWithAmount(amount:number, animated: boolean)``` that allows you to scroll with a given amount of pixels.

As @ginev mentioned this will be available in our next official release (end of June).

**Comment by tigrenok00** [comment]
@Natalia-Hristova Thank you, can you please advice what is the parallel method to *get* the amount of pixels needed to scroll?

**Comment by ginev** [comment]
@tigrenok00 - can you please elaborate a bit: do you need API for accessing the current scroll offset or something else?

**Comment by tigrenok00** [comment]
@ginev If the user scrolls a list and switches to some other screen, I need the ability to recreate the exact same scroll position of the list when he goes back. If current scroll offset returns the number of pixels that is the input to the new scrollWithAmount method, than that would be the solution.

**Comment by ginev** [comment]
@tigrenok00 - we will provide API for reading the current scroll offset of the list as well.

**Comment by tigrenok00** [comment]
@ginev perfect, thanks!

**Comment by andrewm-mitchells** [comment]
Hello, I'm having a similar issue where I'd love to have the ability to persist scroll/list position when new items are added to the top of the list. Looks like `scrollPosition` is could've been what I need if used with `scrollToIndex` and set to 'top' but according to plugin files (`index.d.ts`) it's deprecated now and does not allow setting scroll position.
