### ISSUE TITLE
Calendar selection day style issue

### ISSUE THREAD

**Issue by cindy-m** [telerik/nativescript-ui-feedback#204]
### Tell us about the problem
The background for the selected item is set, but when the item is selected, only part of the cell is painted in the set background color. the rest of the cell has the same color as the border lines. It looks like the set color that is actually ment for background, it used to paint a thick border, which is then not thick enough to fill the whole cell.

### Which platform(s) does your issue occur on?
> Both, sind nativescript 3.0, in iOS it is less visible

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 2.0.1
- **CLI:** 3.0.0
- **Cross-platform modules:** (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- **Runtime(s):** (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- **Other Plugin(s):** (the `dependencies` and `devDependencies` in the `package.json` file of your project)

### Please tell us how to recreate the issue in as much detail as possible.
> I downloaded https://github.com/telerik/nativescript-ui-samples to test it if the problem also is there, installed it on an android emulator and selected: Calendar -> Calendar Styling. If you then select a date, you see that only part of the cell is coloured in another color

**Comment by Natalia-Hristova** [comment]
Hi @cindy-m 

> only part of the cell is painted in the set background color. the rest of the cell has the same color as the border lines. 

- that's because there is **[selectionShape](http://docs.telerik.com/devtools/nativescript-ui/api/modules/selectionshape.html)** "above" the cell and its default value is Square.

if you set it to **None** ```<rc:CalendarMonthViewStyle selectionShape="None" >``` and set ```cellBackgroundColor``` to the ```selectedDayCellStyle``` the cells should have only one color.

Hope this helps. I'll close the issue. 
Indeed the team is planning to refactor calendar's styling soon. Stay tuned.
