### ISSUE TITLE
RadDataForm throws when only one Group is set but not all Entities are in [iOS] 

### ISSUE THREAD

**Issue by NickIliev** [telerik/nativescript-ui-feedback#206]
When there is only one group set the application is throwing with:
```
null is not an object (evaluating 'group.collapsible')
```
Reproducible only in iOS (works as expected in Android)

Steps to reproduce:
- open [this example](https://github.com/telerik/nativescript-ui-samples-angular/blob/release/sdkAngular/app/dataform/groups/dataform-groups.component.html)
- comment one of the two groups and [leave uncommented only one](https://github.com/telerik/nativescript-ui-samples-angular/blob/release/sdkAngular/app/dataform/groups/dataform-groups.component.html#L15-L25)
- rebuild the application and start the example

Result: app throws the error above.

Note: this appears to be connected with the fact that the view model is [passing 6 entity properties](https://github.com/telerik/nativescript-ui-samples-angular/blob/release/sdkAngular/app/dataform/groups/dataform-groups.component.ts#L16) while we are grouping **only 3** of them (when the code for one of the groups is commented). If all of the entity properties passed are part of a single group the code will execute as expected.

e.g. for one group (based on the same sdk example)
```
<RadDataForm #myRuntimeDataFormComp tkExampleTitle tkToggleNavButton [source]="person" row="1">
	<!-- This will work  -->
	<TKPropertyGroup tkDataFormGroups collapsible="true" name="Main Info" hidden="false">
		<TKEntityProperty tkPropertyGroupProperties name="name">
			<TKPropertyEditor tkEntityPropertyEditor type="Text"></TKPropertyEditor>
		</TKEntityProperty>
		<TKEntityProperty tkPropertyGroupProperties name="age">
			<TKPropertyEditor tkEntityPropertyEditor type="Number"></TKPropertyEditor>
		</TKEntityProperty>
		<TKEntityProperty tkPropertyGroupProperties name="email">
			<TKPropertyEditor tkEntityPropertyEditor type="Email"></TKPropertyEditor>
		</TKEntityProperty>
		<TKEntityProperty tkPropertyGroupProperties name="city">
			<TKPropertyEditor tkEntityPropertyEditor type="Text"></TKPropertyEditor>
		</TKEntityProperty>
		<TKEntityProperty tkPropertyGroupProperties name="street">
			<TKPropertyEditor tkEntityPropertyEditor type="Text"></TKPropertyEditor>
		</TKEntityProperty>
		<TKEntityProperty tkPropertyGroupProperties name="streetNumber">
			<TKPropertyEditor tkEntityPropertyEditor type="Number"></TKPropertyEditor>
		</TKEntityProperty>
	</TKPropertyGroup>
</RadDataForm>
```

**Comment by Natalia-Hristova** [comment]
This issue is fixed and it will be available in our next official release. If you want to test it out before that you can use the "next" version of the nativescript-telerik-ui-pro plugin. Simply install that version of the plugin: ``` tns plugin add nativescript-telerik-ui-pro@next``` . 

**NOTE** that the next version is updated on daily/hourly basis from our current development brach which makes it not a good option for production applications but it is a great way to verify fixes and test new functionality.
