### ISSUE TITLE
[iOS] RadSideDrawer w/ drawerContentSize not working as expected for drawerLocation= "right"

### ISSUE THREAD

**Issue by NickIliev** [telerik/nativescript-ui-feedback#208]
When setting **drawerContentSize** and the drawer location is set to **right** the drawer is not showing as expected (showing only partially). Reproducible in iOS only (works as expected in Android).

Reproducible with [this example](https://github.com/telerik/nativescript-ui-samples-angular/tree/release/sdkAngular/app/sidedrawer/position)
- set the drawerContentSize [here](https://github.com/telerik/nativescript-ui-samples-angular/blob/release/sdkAngular/app/sidedrawer/position/position.component.html#L2) (e.g. with value 300)
- open the drawer with the default position (left)
- open the drawer with the right position (right)
- repeat the steps above and the drawer will show up only partially when positioned from the **right**

Reported via t.1112653

**Comment by Jaishankarb** [comment]
+1

**Comment by suresh-selvaraj** [comment]
Any update on this issue?. Its so critical for our project

**Comment by VladimirAmiorkov** [comment]
@suresh-selvaraj We have already addressed this issue in our internal code and the fix will be available in our next official 3.0.0 version.

You can test the fix in our "next" version by installing it via: `tns plugin add nativescript-telerik-ui@next` or `tns plugin add nativescript-telerik-ui-pro@next`. Note the "next" version is a plugin version that is considered not stable for release as it is constantly being updated on hourly/daily basis. It is provided for testing of new features and verification of bug fixes.
