### ISSUE TITLE
Bug: [iOS]  nativescript-telerick-ui sidedrawer crashes when built with Xcode8/iOS10

### ISSUE THREAD

**Issue by ahalls** [telerik/nativescript-ui-feedback#21]
> Error: Building UI from XML. @file:///app/views/picks/picks.xml:11:3
>  ↳Module '/Users/ahalls/Library/Developer/CoreSimulator/Devices/E89EFB76-561E-41EA-9668-22805675AD96/data/Containers/Bundle/Application/FD302A46-DCEE-4730-A9B7-BA21161FE653/OFPMobile.app/app/tns_modules/nativescript-telerik-ui/sidedrawer' not found for element 'nativescript-telerik-ui/sidedrawer:RadSideDrawer'.
>    ↳UIScreen.mainScreen is not a function. (In 'UIScreen.mainScreen()', 'UIScreen.mainScreen' is an instance of UIScreen)

```
│ Component        │ Current version       │ Latest version │ Information │
│ nativescript     │ 2.5.0-2016-11-01-6980 │ 2.3.0          │ Up to date  │
│ tns-core-modules │ 2.5.0-2016-11-01-4636 │ 2.3.0          │ Up to date  │
│ tns-android      │ 2.3.0                 │ 2.3.0          │ Up to date  │
│ tns-ios          │ 2.5.0-2016-11-1-1     │ 2.3.0          │ Up to date  │
```

"nativescript-telerik-ui": "^1.5.0-2016.10.31.2",

**Comment by VladimirAmiorkov** [comment]
Hi @ahalls ,

We have resolved similar issues and the fix is available in the latest 1.5.1 version of the [nativescript-telerik-ui](https://www.npmjs.com/package/nativescript-telerik-ui) plugin. Could you give it a try and let me know if the issue persists?
