### ISSUE TITLE
[DataForm] Setting up Editor type to List will not work properly on iOS

### ISSUE THREAD

**Issue by tsonevn** [telerik/nativescript-ui-feedback#217]
When the Editor type is setup to `List` and try to tap on the field, the available options will not be displayed. This issue is reproducible only on iOS. Attaching sample project.
[Archive.zip](https://github.com/telerik/nativescript-ui-feedback/files/1084487/Archive.zip)

**Comment by davorpeic** [comment]
+1 Have the same issue, NS3 + angular

**Comment by jovanymezura** [comment]
+1

**Comment by Natalia-Hristova** [comment]
This issue is fixed and it will be available in our next official release. If you want to test it out before that you can use the "next" version of the nativescript-pro-ui plugin. Simply install that version of the plugin: ``` tns plugin add nativescript-pro-ui@next``` .

**Comment by Nogostradamus** [comment]
I have that issue with nativescript-ui-dataform 3.6.0, typescript 4 and angular 5.2. I can't get out from not text based inputs, so list pickers, date picker, time picker. This issue only on iOS. Android is fine.
