### ISSUE TITLE
[Feature] RadDataFrom - Support custom editors

### ISSUE THREAD

**Issue by NickIliev** [telerik/nativescript-ui-feedback#22]
> I am using the radDataForm.
> I have my own lookup control that I want to use.
> I would like the field to look like the Picker field on the screen.
> (ie it has the little dropdown arrow next to the field or 3 dots)
> but when I tap on the field I would like to call my own code which display my own list 
> When I am finished selecting from my own list, I then want to be able to update the field.
> I'm thinking soething like this:

```
<df:EntityProperty name="city" displayName="City" index="2" tap="{{lookupCity}}">
        <df:EntityProperty.editor>
            <df:PropertyEditor type="Lookup" />
        </df:EntityProperty.editor>
    </df:EntityProperty>
```

**Comment by NicoleZA** [comment]
Often it is necessary to have other kinds of entry controls. The current dataform does not allows for customizing controls. Even having a display field where a tap event can be captured would be useful.
This way methods can be called to display popup forms etc.

**Comment by VladimirAmiorkov** [comment]
Hi,

This is an interesting feature that has been discussed internally between the development team. We are always doing our best to improve the quality and usability of the components in the nativescript-telerik-ui/pro plugin, currently I imagine something of this sort when using such "custom editors":

- declare the PropertyEditor's custom template:

```
<Page xmlns:df="nativescript-telerik-ui-pro/dataform"
            xmlns="http://www.nativescript.org/tns.xsd">
    <df:RadDataForm id="myDataForm" source="{{ person }}">
        <df:RadDataForm.properties>
            <df:EntityProperty valuesProvider="{{ address }}">
                <df:EntityProperty.editor>
                    <df:PropertyEditor type="custom" value="{{ street }}">
                         <df:PropertyEditor.template>
                             <GridLayout rows="auto, *, auto">
                                 <Label text="Choose a street:"/>
                                 <TextView id="streetTextView"/>
                                 <Button text="Choose" tap="onChooseStreetTap"/>
                             </StackLayout>
                         </df:PropertyEditor.template>
                     </df:PropertyEditor>
                </df:EntityProperty.editor>
            </df:EntityProperty>
        </df:RadDataForm.properties>
    </df:RadDataForm>
</Page>
```

- and manually handle the updating of the editor's value (input):

```
var frameModule = require("ui/frame");

export function onChooseStreetTap(args) {
    var model = args.bindingContext; // the 'PropertyEditor'
    var streetVal = frameModule.topmost().getViewById("streetTextView")
    model.value = streetVal; // updates the editor's value
}
```

How does this approach sound to you, if you have any notes, concerns or requirements please share them here.

**Comment by NickIliev** [comment]
+1 for custom editors - A user of telerik-ui-pro also wanted some additional control of the editors. For example, if we have an **MultilineText** editor wth labelHidden="true" you can control the offset of the editor but you can not control the width and the height of that component (thus the result is that only half screen is taken for the editor value). With custom editors and editor's template, this will be easily achieved.
