### ISSUE TITLE
RadDataFrom readOnly mode should have distinguish styles for true and false values

### ISSUE THREAD

**Issue by NickIliev** [telerik/nativescript-ui-feedback#220]
When setting **readOnly** for RadDataForm editor to **true** the styles applied are hardly different from the default **false** value (both have lightgray text color). Observed with 2.0.1

Create more distinguish styles when an editor **readOnly** mode is set to **false**.
For iOS also consider removing the ">" symbol when **readOnly** is set to **true** 0 it appears that the editor can be interacted with when the symbol remains..

**Comment by NickIliev** [comment]
requested via t.1116128

**Comment by Natalia-Hristova** [comment]
This issue is fixed and it will be available in our next official release. If you want to test it out before that you can use the "next" version of the nativescript-telerik-ui-pro plugin. Simply install that version of the plugin: ``` tns plugin add nativescript-telerik-ui-pro@next``` .
