### ISSUE TITLE
[ui-pro][RadListView] more than one view found in list template at nesting level 0

### ISSUE THREAD

**Issue by echap** [telerik/nativescript-ui-feedback#222]
Hi,

I was previously using the RadListView component for my {N} + A version 2.5.5 app, and it worked very well. As of now, I'm trying to migrate the app to {N} V 3, and as I progress through debugging, I am encountering a very disturbing error.

I am using the telerik UI pro for nativescript, and the root of the problem lies with the ng-template. I am using a standard listview, populated with an ObservableArray of elements.

    <RadListView  [items]="items">
         <ng-template tkListItemTemplate let-item="item">
              <StackLayout>
              </StackLayout>
         </ng-template>
    </RadListView>
However, when I navigate to my component and load the data, my app crashes and displays a Stacktrace:

Error: More than one view found in list template! Nesting level: 0
I already encountered these errors in the past when I tried to put several views at the root of the ng-template, but this time, I made sure to have only one view at the root of the template. I tried to search for a fix on the internet, unsuccessfully yet.

Do you have an idea of what may be causing the problem ?

Here is my config BTW:

nativescript-telerik-ui-pro,
version: 2.0.1

│ Component │ Current version │ Latest version │ Information │
│ nativescript │ 3.1.1-2017-06-26-9274 │ 3.0.3 │ Up to date │
│ tns-core-modules │ 3.1.0 │ 3.0.1 │ Up to date │
│ tns-android │ 3.1.0 │ 3.0.1 │ Up to date │
│ tns-ios │ 3.1.0 │ 3.0.1 │ Up to date │

Thanks

**Comment by ginev** [comment]
@echap this has been internally addressed in our codebase and will make it into the upcoming release. It was an incompatibility with the newer version of the NativeScript Angular renderer. The release of the fixed version is due to a couple of days so stay tuned for announcement on nativescript.org.

**Comment by echap** [comment]
Hey,

Thank you very much for that ! we will keep on waiting for the next release

**Comment by Natalia-Hristova** [comment]
@echap you can get the new released plugin 3.0.0  :)

**Comment by joey0xx** [comment]
Will the `@progress` scope be updated soon?

**Comment by ginev** [comment]
@joey0xx - if you have a valid license you can directly download from npmjs.org: https://www.npmjs.com/package/nativescript-telerik-ui-pro. We stopped uploading a Trial version there and are now uploading a complete working Dev version of the plugin.

Is that alright with you?

**Comment by joey0xx** [comment]
@ginev Sounds good thanks.

**Comment by ginev** [comment]
@joey0xx closing this as fixed. Feel free to reopen in case of need.
