### ISSUE TITLE
DataForm bound valuesProvider crashes when values change

### ISSUE THREAD

**Issue by RobertGardner** [telerik/nativescript-ui-feedback#224]
(Haven't found anything through numerous searches.)

I am trying to change the values in one Picker based on the selection in another Picker. When I change the values I get a crash `Service exited due to Segmentation fault: 11` with no further information.

### Which platform(s) does your issue occur on?
This occurs on iOS. I have not been able to try it on Android.

### Version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 2.0.1.043
- **CLI:** 3.0.3
- **Cross-platform modules:** 3.0.1
- **Runtime(s):** 3.0.1

### Please tell us how to recreate the issue in as much detail as possible.
Create a form with the following properties:
```
    <TKEntityProperty tkPropertyGroupProperties name="brand" [valuesProvider]="brands">
      <TKPropertyEditor tkEntityPropertyEditor type="Picker"></TKPropertyEditor>
    </TKEntityProperty>
    <TKEntityProperty tkPropertyGroupProperties name="model" [valuesProvider]="models">
      <TKPropertyEditor tkEntityPropertyEditor type="Picker"></TKPropertyEditor>
    </TKEntityProperty>
```
(Note: Some attributes are set through metadata)
Respond to propertyChanged events with:
```
  valueChanged(event: DataFormEventData): void {
    if (event.propertyName === "brand") {
      let value = JSON.parse(event.object.editedObject);
      this.updateModels(value.brand);
    }
  }

  private updateModels(brand: string): void {
    this.models = this.getModels(brand);
  }
```
(Note that updateModels is also called after the object is read from database.)

The form initially loads correctly with the brands and models values properly set up.

When you select a new brand (with immediate commit mode) the valueChanged event gets called and this.models is properly updated. The app then almost immediately crashes, with no log information about what happened.

Note that very occasionally after changing brands, the model Picker values update properly, everything runs smoothly and I don't get the crash until again selecting another brand. Most of the time, though, it crashes almost immediately.

**Comment by tgpetrov** [comment]
Hi @RobertGardner,
Thank you for the detailed report.
I managed to reproduce the described issue and I have to confirm that it currently exists in DataForm on iOS.
Since it is a common scenario we will review the issue with high priority and the fix will be contained with our next release (in about 6 weeks).

**Comment by Natalia-Hristova** [comment]
This issue is fixed and it will be available in our next official release. If you want to test it out before that you can use the "next" version of the nativescript-telerik-ui-pro plugin. Simply install that version of the plugin: ``` tns plugin add nativescript-telerik-ui-pro@next``` .
