### ISSUE TITLE
RadListView crush after 3.0.1 upgrade

### ISSUE THREAD

**Issue by tigrenok00** [telerik/nativescript-ui-feedback#227]
Hi,
After the upgrade, there is an error I'm getting on using previous code with RadListView:
**Right-hand side of 'instanceof' is not an object**:

![image](https://user-images.githubusercontent.com/23075641/27780168-18c6a17a-5fd0-11e7-887c-ab9a0ed601a9.png)
![image](https://user-images.githubusercontent.com/23075641/27780172-24280b12-5fd0-11e7-9e33-ae0c438dff34.png)
![image](https://user-images.githubusercontent.com/23075641/27780180-36478138-5fd0-11e7-9f5c-25a5161638f2.png)

Which platform(s) does your issue occur on?
Android
Please provide the following version numbers that your issue occurs with:
"tns-android":  "version": "3.1.1"
 "tns-core-modules": "3.1.0"  
Plugin(s): "nativescript-telerik-ui": "3.0.1"

**Comment by ginev** [comment]
Hello @tigrenok00 ,

Can you please check which version of the nativescript-angular plugin are you using? You should be using: 
    "nativescript-angular": "~3.1.0"

Make sure this is the configuration in your package.json file.

**Comment by tigrenok00** [comment]
@ginev Yes, it worked! Thank guys, you are awesome. And thanks for all the new scroll features for listview.

**Comment by ginev** [comment]
@tigrenok00, happy to hear you are happy with the new APIs. Let us know should you have additional feedback.
