### ISSUE TITLE
[BUG] Issue while using TrackBall in a Chart with DateTimeContinuousAxis

### ISSUE THREAD

**Issue by tsonevn** [telerik/nativescript-ui-feedback#243]
While using TrackBall in Chart with DateTimeContinuousAxis and select some of the values from the Chart the app will crash with the following error. This problem is reproducible only on Android. Also tested with @next UI for NatieScript 

![screenshot_2017-07-17-10-58-31](https://user-images.githubusercontent.com/17448734/28259584-a2d913d8-6adf-11e7-90e8-8e7354f49660.png)

Attaching project, where the problem could be reproduced
[Archive.zip](https://github.com/telerik/nativescript-ui-feedback/files/1151894/Archive.zip)

**Comment by ginev** [comment]
@tsonevn - the fix for this is waiting for approval and will soon be available via @next.

**Comment by sgotliv** [comment]
Thanks for the quick response!!!
