### ISSUE TITLE
[Feature] RadDataForm - add `isValid` property for DataForm component

### ISSUE THREAD

**Issue by tsonevn** [telerik/nativescript-ui-feedback#25]
Adding  `isValid`  property, which checks, whether all values inside the EntityProperties contains valid data.
At the moment the only way is to use `propertyValidatedEvent` and to check for every EntityProperty manually. 

The `isValid` property can return `true` if  all values contain valid data in the `DataForm` or `false` if it is not.

**Comment by VladimirAmiorkov** [comment]
Hi @tsonevn ,

Indeed being able to check if the entire RadDataForm (all of its validators) is valid via an property or other easy to use mechanism will be beneficial to the component. 

We will do our best to provide this feature as soon as possible.
