### ISSUE TITLE
[Feature][Chart] Exposing the setLastLabelVisibility for the nativescript component

### ISSUE THREAD

**Issue by tsonevn** [telerik/nativescript-ui-feedback#253]
Exposing this functionality will resolve the issue with cutting the last label in the Chart 
![3e0aa025-c7a7-4267-a27f-626489bdf4b8_daychart_more_data](https://user-images.githubusercontent.com/17448734/28462135-8fc76e20-6e22-11e7-82b9-a29e14d0df9d.png)

**Comment by VladimirAmiorkov** [comment]
This functionionality has been implemented and example can be found here:

- {N} + Angular - https://github.com/telerik/nativescript-ui-samples-angular/tree/master/sdkAngular/app/chart/axes/label-visibility
- {N} with TypeScript - https://github.com/telerik/nativescript-ui-samples/tree/master/sdk/app/chart/axes/label-visibility
