### ISSUE TITLE
[Feature][Chart] Exposing the setMaxBarWidth for the nativescript component

### ISSUE THREAD

**Issue by tsonevn** [telerik/nativescript-ui-feedback#254]
Exposing the `setMaxBarWidth` for the nativescript component will allow setting up the bar width for the Series

**Comment by Natalia-Hristova** [comment]
@tsonevn, this is implemented and you can set ```minBarSize``` and ``maxBarSize``` . It will be available in our next official release. If you want to test it out before that you can use the "next" version of the nativescript-telerik-ui-pro plugin. Simply install that version of the plugin: ``` tns plugin add nativescript-telerik-ui-pro@next``` .
