### ISSUE TITLE
Custom PieChart Palette:The colors return to the default ones on selected slice 

### ISSUE THREAD

**Issue by gbonline** [telerik/nativescript-ui-feedback#258]
Hi, I'm developing an app with some graphs.
Now I'm playing with the PieChart and I tried to customize the color palette.
The Palette is assigned correctly, but when I select a slice, the shifted slice is showed with his original default color.
I attach my demo app that show the issue
[Archivio.zip](https://github.com/telerik/nativescript-ui-feedback/files/1174016/Archivio.zip)

regards
Giorgio

**Comment by Natalia-Hristova** [comment]
Hi @gbonline ,

This is expected - the shifted slice is showed with his original default color because you should first set the colors you want for the selected slice setting ```seriesState="Selected"``` to the Palette e.g. This 

```html
        <Palette tkPiePalette seriesName="pie" seriesState="Selected">
	    <PaletteEntry tkPiePaletteEntry fillColor="Yellow"></PaletteEntry>
            <PaletteEntry tkPiePaletteEntry fillColor="Blue"></PaletteEntry>
            <PaletteEntry tkPiePaletteEntry fillColor="Red"></PaletteEntry>
            <PaletteEntry tkPiePaletteEntry fillColor="Pink"></PaletteEntry>
            <PaletteEntry tkPiePaletteEntry fillColor="Magenta"></PaletteEntry>
        </Palette>  
```

**Comment by ginev** [comment]
Here's more information on styling: http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/Chart/Series/styling

**Comment by gbonline** [comment]
I apologize, I did not read the documentation page down to the bottom,
But since I reported other problems with the charts, I also believed that this behavior was a mistake.
regards
G.
