### ISSUE TITLE
[Feature] RadDataForm - Add additional common built-in PropertyEditors

### ISSUE THREAD

**Issue by NicoleZA** [telerik/nativescript-ui-feedback#26]
Is it possible to have the following Editors. 

Button - Displays a button (text could come from a source property). Allows user to call a function when pressed.

Lookup - Text with button on right. This can be a new editor or just a new option to display a button on the right side of existing text editor.

Label - Display non editable multiline data.

Currency - Display numbers with 2 decimal places (with or without currency symbol) - 1 and 1.1 should display as 1.00 and 1.10 respectively. or $1.00 and $1.10 when using symbol.

**Comment by VladimirAmiorkov** [comment]
Hi @NicoleZA ,

Those are so great ideas for additional built-in editors in the RadDataForm. As I see you are aware of this https://github.com/telerik/nativescript-ui-feedback/issues/22 feature request, which when implemented will allow for custom editors that could easily implement some of the above mentioned editors.

I have edited the title of this issue to better illustrate the desired feature and not overlap with the others.

**Comment by ginev** [comment]
This is now logged in our TODO list.

Please use the github.com/telerik/nativescript-ui-feedback for any future issues.
