### ISSUE TITLE
App is being rejected by Apple

### ISSUE THREAD

**Issue by manojdcoder** [telerik/nativescript-ui-feedback#264]
I'm using only the `SideDrawer` and `ListView` in my app. But apple rejects the app with error description below.

```
Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSCalendarsUsageDescription key with a string value explaining to the user how the app uses this data.
```

I found that `TelerikUI.framework` uses / defines `EventKit` usage which is why app is being rejected. I understand this could be fixed by adding description in `info.plist`. But is it possible to conditionally include frameworks to avoid this situation.

**Comment by ginev** [comment]
@manojdcoder - currently you will have to add the description in your info.plist. It won't affect your app as you are never using the corresponding APIs that would trigger the request for usage-permission, i.e. your users will not notice. We are considering to separate the components into different libraries but this is not yet confirmed and planned.

**Comment by manojdcoder** [comment]
@ginev Thanks! I have added description in my info.plist. I guess having separate components / libraries will be a nice choice.

**Comment by shiv19** [comment]
After the recent NativeScript Pro UI big breakup, I'm sad that this problem still exists.

I am only using side drawer and list view from pro ui. Installed dedicated packages for them.

Not using any other pro ui component packages.

But I'm still having to add NSCalendarsUsageDescription to info.plist

**Comment by manojdcoder** [comment]
@shiv19 Yesterday only I migrated to separate plugins, I have removed `NSCalendarsUsageDescription` already and published to TestFlight. It didn't trow any error as  it used to with pro ui plugin.

**Comment by shiv19** [comment]
I deleted my comment because I noticed that nativescript-pro-ui folder was still present in my node_modules folder. Which is why I was facing that issue. 
Problem solved
