### ISSUE TITLE
Possibility to disable newsletter prompt

### ISSUE THREAD

**Issue by surdu** [telerik/nativescript-ui-feedback#265]
Whenever I do a clean-up of my project (`rm -rf platforms/ hooks/ node_modules/`) the build process is paused by this prompt:

```
Leave your e-mail address here to subscribe for NativeScript newsletter and UI for 
NativeScript product updates, tips and tricks (press Enter for blank):
```

For now, it's just an annoyance, but thinking ahead, this might cause a big problem in a CI environment.

Is there an option to disable this prompt ?

**Comment by ginev** [comment]
@surdu - you can suppress this prompt by setting the NSUI_NOPROMPT environmental variable to 1. Is that alright with you?

**Comment by surdu** [comment]
@ginev For people who know about it (now it includes me, thank you!), yes. 

But I'm questioning if here (at build time) it's a good place to ask if a user wants to subscribe to a newsletter (something totally unrelated to the build process). It's the first time I'm seeing this.

**Comment by ginev** [comment]
@surdu - the script is run during the `postinstall` phase of the plugin installation procedure. If you take a look at the package.json you will notice that:

"scripts": {
        "preinstall": "node ./scripts/eula-prompt.js",
        "postinstall": "node ./scripts/email-prompt.js dev_uins_pro"
    },

As a matter of fact, building a CI and having such interruptions is not a good option and we will reconsider this behavior. 

Thanks for the feedback.
