### ISSUE TITLE
[Feature] RadDataForm - Allow multiple editors on a single line

### ISSUE THREAD

**Issue by NicoleZA** [telerik/nativescript-ui-feedback#27]
Often it is necessary to put multiple editors on a single line

In this example, from an existing project, 
I have;
A text field to enter an amount
A dropdown to pick a tax rate
A switch to "charge debtor"

![image](https://cloud.githubusercontent.com/assets/6543549/20052990/2ee3b396-a4df-11e6-9332-d6fce42a5f21.png)

**Comment by tgpetrov** [comment]
This can be achieved by using grid layout for groups as shown [here](http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/DataForm/dataform-layouts#using-the-grid-layout)
