### ISSUE TITLE
[Feature][RadSideDrawer]Enable drawer over status bar

### ISSUE THREAD

**Issue by MIYankov** [telerik/nativescript-ui-feedback#275]
This is done in most Google apps on iOS 10. Check out Google Drive or Keep. This feature request came out from a UX review for the {N} templates.

Here is also a SO question for React Native that better explains the feature request: https://stackoverflow.com/questions/42459081/how-do-i-render-a-view-in-front-of-the-ios-status-bar-in-react-native

**Comment by toddanglin** [comment]
Any detail on how this request was resolved? Is there another open issue we can track? Or does support for this scenario (drawer over status bar) now exist?
