### ISSUE TITLE
RadListView scrollToIndex on iOS

### ISSUE THREAD

**Issue by tigrenok00** [telerik/nativescript-ui-feedback#276]
Hi,
I'm gaving a problem on iOS when trying to scrollToIndex in a RadListView to a specific item.
On Android it is working perfectly, but on iOS it does not seem to work.
I understand that on iOS scrollPosition should be set in order to bring the item into the view. 
So I set scrollPosition="Top" and then use scrollToIndex(), and expecting the item to appear on top of the list. The result is that is sometimes the item appears in the bottom of the screen or does not appear on the screen at all.
Is there anything else I should be doing for this to work on iOS?

These are the versions I'm using:
iOS 10.3
Progress NativeScript UI version: "3.1.0-2017-7-31-6",
CLI: 3.1.1
Cross-platform modules: 3.1.0
Runtime(s): 3.1.1

**Comment by ginev** [comment]
Hello @tigrenok00 - can you share some code? The `scrollToIndex` method is used as demonstrated here:
https://github.com/telerik/nativescript-ui-samples/blob/master/sdk/app/listview/scroll-to-index/scroll-to-index-vertical.ts#L30

**Comment by tigrenok00** [comment]
Ok, I think I got it working with the following specific code:

`setTimeout(() => {
                        this.productListViewComponent.listView.scrollPosition = 'Top';
                        this.productListViewComponent.listView.scrollToIndex(itemIndex, false, ListViewItemSnapMode.Start);
                    }, 100);`

I did not have to use ListViewItemSnapMode on Android. There I could just do scrollToIndex(index) and it was enough.
