### ISSUE TITLE
RadListView PullToRefresh not working on iOS

### ISSUE THREAD

**Issue by tigrenok00** [telerik/nativescript-ui-feedback#278]
Hi,
I'm using a RadListView with PullToRefresh enabled. Here is a small code sample which works fine on Android:

```
public onPullToRefreshInitiated(args: ListViewEventData) {
        this.refreshInitiated.emit(); // this changes the items source
        let listview = args.object as RadListView;
        listview.notifyPullToRefreshFinished();
   }
```

However, on iOS when the list is pulled, after it refreshes there is an empty space at the top of the list (about 2cm) and the list becomes completely unscrollable (also the pull to refresh cannot be triggered again by pulling).

Is this a known issue?
Thanks,

These are the versions I'm using:
Angular
iOS 10.3
Progress NativeScript UI version: "3.1.0-2017-7-31-6",
CLI: 3.1.1
Cross-platform modules: 3.1.0
Runtime(s): 3.1.1

**Comment by EddyVerbruggen** [comment]
Can you try wrapping `listview.notifyPullToRefreshFinished();` in a little `setTimeout`?

**Comment by tigrenok00** [comment]
Thanks!! It solved the issue.

**Comment by divyachandana** [comment]
Thanks alot @EddyVerbruggen this solved my issue
```
          setTimeout(()=>{
            listView.notifyPullToRefreshFinished();
        },500)
```

**Comment by markosole** [comment]
It's old post but same problem 2 years after. Maybe it has something with new iOS.
I can't see spinner on iOS and ListView bounce down 1-2cm. Solution for bounce problem is adding margin via class only for iOS:
`pullToRefresh="true" pullToRefreshInitiated="refreshList" class="ios-pull-margin"  `
And than use this in app.ios.scss:
    .ios-pull-margin {
       margin-top: 0.001;

    }

I still can't see spinning animation but refresh works fine. I may add different animation on top just to simulate it in the View.

**Comment by Stanteq** [comment]
I have the same issue until now.

**Comment by a-camacho** [comment]
> As a work around you can use `scrollToIndex(0, true)` on the RadListView
> or better `scrollWithAmount(-listView.getScrollOffset(), true);` in case you have a header

This workaround works for me ! Thanks !
