### ISSUE TITLE
[iOS] AutoComplete Tokens not working with Chinese symbols

### ISSUE THREAD

**Issue by NickIliev** [telerik/nativescript-ui-feedback#280]
When using Chinese text in auto-complete tokens the application is throwing with
```
JS ERROR TypeError: null is not an object (evaluating `args.token.text`)
```

Reproducible on **iOS** (working as expected on Android)
Steps to reproduce:
- use [this example](https://github.com/telerik/nativescript-ui-samples/tree/release/sdk/app/autocomplete/events)
- change the [token items](https://github.com/telerik/nativescript-ui-samples/blob/release/sdk/app/autocomplete/events/autocomplete-events-model.ts#L8-L12) to the following:
```
var countries = [
            "How I Met Your Mother S01E01",
            "How I Met Your Mother S01E02",
            "How 老爸老媽浪漫史 S01E01",
            "老爸老媽浪漫史 S01E02",
        ];
```

- select a token that contains Chinese symbols (e.g start typing _**How**_)
Result  The application throws the error above when [`onTokenAdded` is triggered](https://github.com/telerik/nativescript-ui-samples/blob/release/sdk/app/autocomplete/events/autocomplete-events-model.ts#L39-L41).

reported via t.1127766

```
// output from console.dir(args) in onTokenAdded

CONSOLE LOG file:///app/autocomplete/events/autocomplete-events-model.js:41:20: [object Object]
        _object: RadAutoCompleteTextView<autocmp>@file:///app/autocomplete/events/autocomplete-events.xml:5:9;
        _eventName: tokenAdded
        _token: null
        _text: How ËÄÅÁà∏ËÄÅÂ™ΩÊµ™Êº´Âè≤ S01E01
        eventName: tokenAdded
        text: How ËÄÅÁà∏ËÄÅÂ™ΩÊµ™Êº´Âè≤ S01E01
        token: null
```
Observed with Japanese symbols as well.

**Comment by Natalia-Hristova** [comment]
Fixed in the latest version of the plugin **3.1.0**.
