### ISSUE TITLE
[Feature][AutoComplete] Visual notification for hidden items

### ISSUE THREAD

**Issue by rdlauer** [telerik/nativescript-ui-feedback#281]
It would be great if there could be some visual hint that there are multiple items selected in an AutoCompleteTextView. In this example, the second item is effectively hidden after being selected. You wouldn't know that you have multiple items unless you removed the first one:

![giphy](https://user-images.githubusercontent.com/1918280/29940051-9857662a-8e53-11e7-8e63-a9dd6549e03c.gif)

**Comment by tgpetrov** [comment]
Hi @rdlauer,

Yes, definitely it should be clear that there are more than one items selected. 
From this example from the SDK the selection indeed seems visible:
![sep-01-2017 10-54-23](https://user-images.githubusercontent.com/6085251/29960411-2d57c868-8f04-11e7-8e60-249be8772528.gif)

Can you share more how I can reproduce this - is it with `Horizontal` or `Wrap` [layout](http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/AutoCompleteTextView/autocomplete-display-modes#tokens-mode) and can you confirm you are using latest?

**Comment by rdlauer** [comment]
`layoutMode="Horizontal"` is exactly what I was missing! Thanks.
