### ISSUE TITLE
[Feature][AutoComplete] Ability to set hint(placeholder) to the AutoComplete TextField 

### ISSUE THREAD

**Issue by tsonevn** [telerik/nativescript-ui-feedback#282]
Ability to add hint text to the component similar to the NativeScript TextField.
```
<au:RadAutoCompleteTextView hint="Hint test" >
```

**Comment by Natalia-Hristova** [comment]
This feature is implemented and will be available in our next official release. If you want to test it out before that you can use the "next" version of the plugin.

**Comment by Sharique-Hasan** [comment]
This is not available for angular in "next" version
