### ISSUE TITLE
Refresh issue with RadListView on iOS

### ISSUE THREAD

**Issue by sserdyuk** [telerik/nativescript-ui-feedback#289]
I am using RadListView with ObservableArray of Observables. The list item contains a Switch that changes the observable, and it then changes the list item view. What I noticed that is that any changes that result in changes of the view layout don't show because the layout doesn't change. For example, if I had a Label with empty text when the list item view was loaded, the text isn't visible if added to the observable later. The same is with binding `visibility` to observable. If I scroll away and return, the views are presented properly as they are reloaded. I've tried to call `requestLayout` on the item view after the change, but that didn't help.

The Android version works as expected.

Is this expected behavior? Should I manually force layout changes in the view? If so, how?

**Comment by ginev** [comment]
@sserdyuk - unfortunately this is the expected behavior on iOS. If you want to hide/show elements dynamically there you might find useful applying an explicit size to the element and then use the visibility property.

**Comment by sserdyuk** [comment]
For the record, I ended up binding to opacity on iOS and visibility on Android like this `<Image src="res://star" stretch="none" android:visibility="{{ favorite ? 'visible' : 'collapse' }}" ios:opacity="{{ favorite ? 1 : 0 }}" />`
