### ISSUE TITLE
Cannot read property 'setLayoutParams' of undefined

### ISSUE THREAD

**Issue by terreb** [telerik/nativescript-ui-feedback#293]
### Tell us about the problem
After upgrade from 3.0.1 to 3.1.1 I get the next error once I navigate to a screen with RadList:

TypeError: Cannot read property 'setLayoutParams' of undefined
File: "file:///data/data/com.domain.app/files/app/tns_modules/nativescript-telerik-ui/listview/listview.js, line: 102, column: 42

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
nativescript-telerik-ui 3.1.1
nativescript 3.2.0
tns-core-modules 3.1.1
tns-android  3.2.0 
tns-ios  3.2.0 

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

```xml
                <lv:RadListView items="{{ recipes }}"
                                separatorColor="transparent"
                                row="1" margin="0,6,0,8"
                                itemTap="itemTap">
                    <lv:RadListView.listViewLayout>
                        <lv:ListViewGridLayout scrollDirection="Vertical" itemHeight="150" spanCount="2"/>
                    </lv:RadListView.listViewLayout>
                    <lv:RadListView.itemTemplate>
                        <GridLayout class="grid-item">
                            <Image src="{{ getImagePath(image_filename) || '~/resources/images/placeholder.png' }}"
                                   stretch="aspectFill"/>
                            <GridLayout columns="* auto" class="grid-title-wrapper">
                                <Label text="{{ recipe_name }}" col="0" class="grid-title"/>
                                <Label text="{{ isFavourite ? '&#xf005;' : '&#xf006;' }}"
                                       class= "icon list-favorite-icon"
                                       col="1"/>
                            </GridLayout>
                        </GridLayout>
                    </lv:RadListView.itemTemplate>
                </lv:RadListView>
```

**Comment by NiciiA** [comment]
+1

**Comment by NiciiA** [comment]
in your package.json update your "tns-core-modules" version to "3.2.0".

-> "tns-core-modules": "3.2.0"

**Comment by efgonz** [comment]
Having same issue, help needed!!

**Comment by terreb** [comment]
@NiciiA, thanks man, updating core modules fixed the issue for me.

**Comment by tgpetrov** [comment]
@efgonz, have you tried updating your "tns-core-modules" to version "3.2.0" ?
