### ISSUE TITLE
[RadDataForm] transfer long text on two lines, while using long text for the displayName 

### ISSUE THREAD

**Issue by tsonevn** [telerik/nativescript-ui-feedback#299]
In iOS, the long text used in the dispayNamen will not be fully displayed and will cut it at the end. Example:
```
<TKEntityProperty displayName="testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest" tkPropertyGroupProperties name="email">
			<TKPropertyEditor  tkEntityPropertyEditor type="Email">
				<TKPropertyEditorStyle  tkPropertyEditorStyle strokeColor="#00695c" strokeWidth="2" fillColor="#4db6ac" labelHidden="false"
					labelTextSize="18" ios:labelFontName="Times New Roman" ios:textWrap="true" android:labelFontName="sans-serif-light" labelFontStyle="Italic"
					labelPosition="Top" labelWidth="60" labelTextColor="#00695c"></TKPropertyEditorStyle>
				</TKPropertyEditor>
		</TKEntityProperty>


```
![screen shot 2017-09-21 at 10 20 42 am](https://user-images.githubusercontent.com/17448734/30683561-90c598c8-9eb6-11e7-9894-68fd347860ab.png)

**Comment by sudhanshu-15** [comment]
This is something which we are facing, the forms look great on Android but on iOS our long display names are getting truncated.

**Comment by Bardolos** [comment]
Any updates on this? I will take a look at the source but don't have a lot of time to dedicate to it.

**Comment by tsonevn** [comment]
HI @Bardolos,
This feature is still under review. Please keep track on the issue. We will update its status when we start working on it. 
At this time I could not commit to the exact time when it will be available.

**Comment by Shantanu-Kotambkar** [comment]
@tsonevn Any work around you would suggest?

**Comment by tsonevn** [comment]
Hi @Shantanu-Kotambkar,
Currently, We were unable to find a temporary solution for this feature. I will suggest keeping track on the issue for further info.
