### ISSUE TITLE
Clarification required

### ISSUE THREAD

**Issue by Sharique-Hasan** [telerik/nativescript-ui-feedback#302]
This is not an issue but a clarification requirement.

I have just added this plugin `https://www.npmjs.com/package/nativescript-pro-ui`. Can I use it for my product free of cost? As it is mentioned here on this website: [https://www.nativescript.org/ui-for-nativescript](https://www.nativescript.org/ui-for-nativescript)

**Comment by VladimirAmiorkov** [comment]
Hi @Sharique-Hasan ,

Yes the pro UI plugin is now free of cost and can be used in any production application without any future costs. If you are coming from the previous plugin you can read [this](http://docs.telerik.com/devtools/nativescript-ui/migration) article about the migration process. 

I will close this issue for now, if you have any question do not hesitate to reopen it and post again.
