### ISSUE TITLE
nativescript-pro-ui/calendar event not firing

### ISSUE THREAD

**Issue by glen-stephens** [telerik/nativescript-ui-feedback#305]
Using the nativescript-pro-ui calendar, I have the following XML code.  The inlineEventSelectedEvent does not fire when an inline event is clicked in Month view. Issue is on iOS, have not tested Android at this point.

`
<calendar:RadCalendar 
        eventSource="{{ dates }}"
        selectionMode="Single"
        navigatedToDate="onNavigatedToDate"
        inlineEventSelectedEvent="onInlineEventSelectedEvent"
        id="myCalendar" viewMode="Month" eventsViewMode="Inline" />
`
JS CODE NEVER FIRES: 
`
exports.onInlineEventSelectedEvent = function (args) {
	console.log("MADE IT ON EVENT TAP");
	console.log(JSON.stringify(args));
}
`
Am I doing something wrong or is this a bug?

**Comment by tgpetrov** [comment]
Hi @glen-stephens,

The `inlineEventSelectedEvent` is actually a variable of type `string` which holds the actual name of the event. It is `inlineEventSelected`. So for your snippet, you will need:
```
<calendar:RadCalendar eventSource="{{ dates }}" selectionMode="Single" navigatedToDate="onNavigatedToDate" inlineEventSelected="onInlineEventSelectedEvent" id="myCalendar" viewMode="Month" eventsViewMode="Inline" />
```

I hope this helps.

**Comment by Meikii** [comment]
> Hi @glen-stephens,
> 
> The `inlineEventSelectedEvent` is actually a variable of type `string` which holds the actual name of the event. It is `inlineEventSelected`. So for your snippet, you will need:
> 
> ```
> <calendar:RadCalendar eventSource="{{ dates }}" selectionMode="Single" navigatedToDate="onNavigatedToDate" inlineEventSelected="onInlineEventSelectedEvent" id="myCalendar" viewMode="Month" eventsViewMode="Inline" />
> ```
> 
> I hope this helps.

Thank You So much ...it helped me so much!!!
