### ISSUE TITLE
Can't change the color of indicator on iOS

### ISSUE THREAD

**Issue by Sethiatspace** [telerik/nativescript-ui-feedback#306]
In my latest app, I have a custom-component that is made of a RadRadialGauge with one RadialScale with two indicators. 
In the code-behind, I try to set the indicators fillColor with ".indicatorStyle.fillColor", which works perfectly on Android but has no effect whatsoever on iOS. Once it is inflated from XML and the color is set, nothing can change it, be it a string, Color object, ...
P.S: I'm not even trying to set them throught databinding but accessing the property directly.

Using the latest nativescript and nativescript-pro-ui version.

**Comment by tgpetrov** [comment]
Hi @Sethiatspace,

I have to confirm that your observation is correct that currently the indicator style's properties (including `fillColor`) can only be changed through xml/html in order to have effect on iOS.

**Comment by Sethiatspace** [comment]
Ok, do you need something from my side?

**Comment by cerealexx** [comment]
@tgpetrov Any progress with this issue? I think is crucial to be able to change the color both in iOS and Android...

**Comment by mostafaSYR** [comment]
Hey, anyone found something helpful for this issue?!!
