### ISSUE TITLE
AOT compilation with snapshots fail

### ISSUE THREAD

**Issue by naturalfreak** [telerik/nativescript-ui-feedback#308]
Using this [https://github.com/telerik/nativescript-ui-samples-angular](https://github.com/telerik/nativescript-ui-samples-angular) and modify in package.json

"build-android-bundle": "npm run ns-bundle --android --build-app"
to
"build-android-bundle": "npm run ns-bundle --android  --snapshot --build-app"

Result is:

> An uncaught Exception occurred on "main" thread.
> java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
> 
> Error calling module function 
> 
> Error calling module function 
> 
> Error calling module function 
> 
> Error calling module function 
> 
> Error: Zone already loaded.
> File: "file:///data/data/org.nativescript.sdkAngular/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js, line: 23, column: 8
> 
> StackTrace: 
> 	Frame: function:'ZoneAwareError', file:'<embedded>', line: 54367, column: 33
> 	Frame: function:'', file:'file:///data/data/org.nativescript.sdkAngular/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 23, column: 15
> 	Frame: function:'', file:'file:///data/data/org.nativescript.sdkAngular/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 1321, column: 3
> 	Frame: function:'NO_ZONE.name', file:'file:///data/data/org.nativescript.sdkAngular/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 9, column: 65
> 	Frame: function:'', file:'file:///data/data/org.nativescript.sdkAngular/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 12, column: 2
> 	Frame: function:'require', file:'', line: 1, column: 266
> 	Frame: function:'', file:'file:///data/data/org.nativescript.sdkAngular/files/app/tns_modules/nativescript-angular/platform-common.js', line: 6, column: 1
> 	Frame: function:'require', file:'', line: 1, column: 266
> 	Frame: function:'', file:'file:///data/data/org.nativescript.sdkAngular/files/app/tns_modules/nativescript-angular/platform.js', line: 3, column: 25
> 	Frame: function:'require', file:'', line: 1, column: 266
> 	Frame: function:'', file:'file:///data/data/org.nativescript.sdkAngular/files/app/main.js', line: 2, column: 18
> 	Frame: function:'require', file:'', line: 1, column: 266
> 
> 
> Error: Zone already loaded.
> File: "<unknown>, line: 1, column: 265
> 
> StackTrace: 
> 	Frame: function:'ZoneAwareError', file:'<embedded>', line: 54367, column: 33
> 	Frame: function:'', file:'file:///data/data/org.nativescript.sdkAngular/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 23, column: 15
> 	Frame: function:'', file:'file:///data/data/org.nativescript.sdkAngular/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 1321, column: 3
> 	Frame: function:'NO_ZONE.name', file:'file:///data/data/org.nativescript.sdkAngular/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 9, column: 65
> 	Frame: function:'', file:'file:///data/data/org.nativescript.sdkAngular/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 12, column: 2
> 	Frame: function:'require', file:'', line: 1, column: 266
> 	Frame: function:'', file:'file:///data/data/org.nativescript.sdkAngular/files/app/tns_modules/nativescript-angular/platform-common.js', line: 6, column: 1
> 	Frame: function:'require', file:'', line: 1, column: 266
> 	Frame: function:'', file:'file:///data/data/org.nativescript.sdkAngular/files/app/tns_modules/nativescript-angular/platform.js', line: 3, column: 25
> 	Frame: function:'require', file:'', line: 1, column: 266
> 	Frame: function:'', file:'file:///data/data/org.nativescript.sdkAngular/files/app/main.js', line: 2, column: 18
> 	Frame: function:'require', file:'', line: 1, column: 266
> 
> 
> Error: Zone already loaded.
> File: "<unknown>, line: 1, column: 265
> 
> StackTrace: 
> 	Frame: function:'ZoneAwareError', file:'<embedded>', line: 54367, column: 33
> 	Frame: function:'', file:'file:///data/data/org.nativescript.sdkAngular/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 23, column: 15
> 	Frame: function:'', file:'file:///data/data/org.nativescript.sdkAngular/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 1321, column: 3
> 	Frame: function:'NO_ZONE.name', file:'file:///data/data/org.nativescript.sdkAngular/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 9, column: 65
> 	Frame: function:'', file:'file:///data/data/org.nativescript.sdkAngular/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 12, column: 2
> 	Frame: function:'require', file:'', line: 1, column: 266
> 	Frame: function:'', file:'file:///data/data/org.nativescript.sdkAngular/files/app/tns_modules/nativescript-angular/platform-common.js', line: 6, column: 1
> 	Frame: function:'require', file:'', line: 1, column: 266
> 	Frame: function:'', file:'file:///data/data/org.nativescript.sdkAngular/files/app/tns_modules/nativescript-angular/platform.js', line: 3, column: 25
> 	Frame: function:'require', file:'', line: 1, column: 266
> 	Frame: function:'', file:'file:///data/data/org.nativescript.sdkAngular/files/app/main.js', line: 2, column: 18
> 	Frame: function:'require', file:'', line: 1, column: 266
> 
> 
> Error: Zone already loaded.

**Comment by VladimirAmiorkov** [comment]
Hi @naturalfreak ,

I tested using both AoT and android snapshot with the latest release branch of the sdkAngular repository and was not able to observe the described issue. There was an issue with an old unit test plugin that has been removed from the repository package.json but after that running the newly added script that enabled AoT + snapshot no android there was not issue running the app.

Can you get it a go with the latest release branch https://github.com/telerik/nativescript-ui-samples-angular and let me know if you continue seeing that error. Also make sure you clean the project by removing both the platforms and node_modules folders.

**Comment by naturalfreak** [comment]
It's working now.

**Comment by VladimirAmiorkov** [comment]
@naturalfreak Good to know, I will close this issue for now. If notice any such issues please let us know.
