### ISSUE TITLE
[Feature] Make android Swipe area still intereactive like iOS

### ISSUE THREAD

**Issue by NathanaelA** [telerik/nativescript-ui-feedback#31]
On iOS if you swipe to the right/left the template is still interactive, so if you change the data in the observable during the swipe on iOS the listview cell updates.  On Android the minute you start a swipe the entire cell turns static and no updates can occur to it.

**Comment by VladimirAmiorkov** [comment]
Hi @NathanaelA ,

As mentioned by my response to your other feature question https://github.com/telerik/nativescript-ui-feedback/issues/32#issuecomment-260291252 we have been working on getting this functionality working correctly on both iOS and Android in the past weeks and our next official release (1.5.1) is expected to bring this new functionality to the Android side of RadListView. Stay tuned.

**Comment by ginev** [comment]
This is now available via the Swipe Actions behavior:

http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/ListView/swipe-actions
