### ISSUE TITLE
[Feature] Make swiped cell/template intractable

### ISSUE THREAD

**Issue by NathanaelA** [telerik/nativescript-ui-feedback#32]
On iOS and Android when you swipe the cell to the left/right, the cell is no longer interactive.
My template was ([B] = Button]:
| Some Text   [B] [B] | 
When I swipe to the Left it looks like this:
| me Text   [B] [B] | [B]
I would still like all there buttons to be clickable.  However, the Two buttons in the swiped cell are no longer responsive.

**Comment by VladimirAmiorkov** [comment]
Hi @NathanaelA ,

This is a great feature request and is one that we have already worked on and its expected to be available in our next official release (1.5.0). We are introducing a separate "swipe behavior" which will allow for this sort of interactions.
