### ISSUE TITLE
DateTimeContiniousAxis with majorStep Hour and large items source freezes the app (Android)

### ISSUE THREAD

**Issue by NickIliev** [telerik/nativescript-ui-feedback#321]
Setting `majorStep` with value `Hour` to `DateTimeContiniousAxis` is causing the application to Freeze and crash on Android (works on iOS).

Steps to reproduce:
- use [this application ](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/others/t_1133112)
- start the application - the app freezes on startup due to [this line](https://github.com/NickIliev/NativeScript-Issues-2017/blob/master/others/t_1133112/app/main-page.xml#L25) (remove `majorStep` or set it to `Day` and the application will work as expected)

reported via t. 1133112

**Comment by yyankov** [comment]
Upvote
Turns out to be a blocker issue with majorStep="Hour" on android

**Comment by ritualz** [comment]
My experience is that ``majorStep=Hour`` can't handle large periods between points (max ~six hours) and when the clock passes midnight (00:00).

**Comment by zbranzov** [comment]
Fixed in nativescript-ui-chart 3.6.1
