### ISSUE TITLE
DataForm Boolean field not works properly

### ISSUE THREAD

**Issue by manigorsh** [telerik/nativescript-ui-feedback#324]
There was similar problem http://www.telerik.com/forums/check-and-switch-never-moves-to-false but I think that it isn't solved yet.

The problem is when I change boolean field of DataForm it changes visually, but actually not.

I can solve it by adding next code 

```
if (typeof oldValue == "boolean") {
    that.get().source[property.name()] = !that.get().source[property.name()];
}
else {
    that.get().source[property.name()] = newValue;
}
```
instead of
`that.get().source[property.name()] = newValue;`

in `RadDataForm.prototype._addCommitListener in onAfterCommit
`
in file `data /node_modules/nativescript-pro-ui/dataform/dataform.android.js`

Maybe you know more efficient way to fix this?

Tested on Android Virtual Device.

**Comment by tgpetrov** [comment]
Hi @manigorsh,

Yes, this issue is still present in the latest official release. We have already planned the fix for the next version which you can "sneak-peek" by changing the referenced plugin version in your `package.json` to:
```
"nativescript-pro-ui": "next"
```
Looking at your solution, it also seems to be efficient.

**Comment by manigorsh** [comment]
I updated to "nativescript-pro-ui": "^3.1.4" and this bug still present. So why did you closed this issue?

**Comment by tgpetrov** [comment]
Hi @manigorsh,

Our policy is to close the issue that we have fixed and mark their milestone (that is the version when the fix will be available). For this issue the milestone is 3.2.0, which was released a few ours ago. I hope when you update you will no longer encounter this issue. Please accept my apologies in case I caused confusion with the closing of the issue.
