### ISSUE TITLE
DataForm [Angular] setting Stepper and Slider  minimum, maximum and step values

### ISSUE THREAD

**Issue by bori87** [telerik/nativescript-ui-feedback#338]
How to set max value in Stepper? I am able to pick a number in a range between 1-10

**Comment by nmongiya** [comment]
this is the number that you provide as the source for the dataform

**Comment by bori87** [comment]
This is not working...

**Comment by nmongiya** [comment]
Can you share your code snippet ?

**Comment by bori87** [comment]
![stepper](https://user-images.githubusercontent.com/29092029/31600023-255ce94e-b255-11e7-8a46-6eaaad561a57.png)
![stepper_](https://user-images.githubusercontent.com/29092029/31600024-25756f00-b255-11e7-801c-09a701e072f6.png)

**Comment by nmongiya** [comment]
You need to set property people = 25 in NpuFormOrder

**Comment by bori87** [comment]
This is what i am doing. 
![form](https://user-images.githubusercontent.com/29092029/31600844-33c15922-b258-11e7-97ba-3c9ec142e20c.png)

**Comment by NickIliev** [comment]
You can use minimum and maximum properties with PropertyEditorsParams to set the range of your Stepper editor.
```
<df:PropertyEditor type="Stepper">
    <df:PropertyEditor.params>
        <df:PropertyEditorParams minimum="2" maximum="25" step="1"/>
    </df:PropertyEditor.params>
</df:PropertyEditor>
```

Based on [this example](https://github.com/telerik/nativescript-ui-samples/blob/release/sdk/app/dataform/editors/editors.xml#L36-L40).

**Comment by NickIliev** [comment]
@bori87 thank you for reporting this issue! 
Indeed there is no exposed directive to set the `minimum`, `maximum` and `step` values of your `Stepper` editor. Logging this as a bug - keep track of this issue for possible workarounds and fix.

**Comment by MuhammadTahir92** [comment]
Any updates on it?

**Comment by noumaans** [comment]
@tsonevn Please update title of this issue to indicate this impacts Slider as well.

For a non 0-1 range slider support, e.g. 2-10 range slider should I log a different issue as feature request, or is it already part of team's backlog?

**Comment by tsonevn** [comment]
Hi @nmongiya,
You do not need to open a new issue. The feature for changing the range of the Slider is part of implementing the functionality for setting the max and min value.

**Comment by noumaans** [comment]
Would be happy to test this out if there is a beta build available.

**Comment by noumaans** [comment]
@DimitarTachev / @DimitarTodorov 
Step value on slider is not working on iOS - can you please confirm?
Here is my slider code:
```html
<TKPropertyEditor tkEntityPropertyEditor type="Slider">
  <TKPropertyEditorParams tKEditorParams minimum="5" maximum="50" step="1"> 
  </TKPropertyEditorParams>
</TKPropertyEditor>
```

On iOS this still yield floating point values in propertyCommitted event.

**Comment by DimitarTachev** [comment]
@noumaans, the `step` property is meant to be used in a Stepper. The Slider is respecting only the `minimum` and `maximum` properties. This issue was related to the Angular usage of these properties. Please open a new one if you need the step property in a Slider.

**Comment by yoat** [comment]
@DimitarTachev Can you confirm, are minimum and maximum supported in Angular Slider controls currently? (nativescript-ui-dataform version 3.7.1)

The minimum and maximum are working on Android but not in iOS.  I am not sure if I should open a new bug or if I'm missing something.

**Comment by tgpetrov** [comment]
Hi @yoat,
Yes minimum and maximum are supported for the Slider editor in both android and iOS.
I updated the code for the Slide in [this example](https://github.com/telerik/nativescript-ui-samples-angular/blob/master/dataform/app/examples/styling/advanced/dataform-styling-advanced.component.html#L12) with:
```
<TKPropertyEditor tkEntityPropertyEditor type="Slider">
    <TKPropertyEditorParams tKEditorParams minimum="50" maximum="200"></TKPropertyEditorParams>
</TKPropertyEditor>
```
and the updated range was visible in the example (as the initial value of the slider is 70)
