### ISSUE TITLE
No way of access value from textfield of RadAutoCompleteTextView?

### ISSUE THREAD

**Issue by tsonevn** [telerik/nativescript-ui-feedback#339]
_From @SamBaqai94 on October 14, 2017 5:5_

is there any way we can access value or text from RadAutoCompleteTextView? if not then can you suggest me any other way of implementing Google Place Autocomplete

_Copied from original issue: NativeScript/NativeScript#4949_

**Comment by nmongiya** [comment]
@tsonevn I think we already have an issue open there for this. https://github.com/telerik/nativescript-ui-feedback/issues/320

**Comment by tsonevn** [comment]
Hi  @SamBaqai94, @nmongiya
Thank you for your feedback,
I reviewed the case and unfortunately, at this time, the text can't be accessed. However, this issue is already logged [here ](https://github.com/telerik/nativescript-ui-feedback/issues/320) and you could keep track on it for further info.

In the meantime, you could access for android the NativeView and to overwrite `textChangedListener`. For example:
```
var autocmp = args.object; // get reference to your RadAutoCompleteTextView either via loaded or via getViewById
 
console.log("autocmp: " + autocmp) // RadAutoCompleteTextView
 
var nativeTField = autocmp.android.getTextField();
console.log("nativeTextField: " + nativeTField) // android.widget.EditText
 
nativeTField.addTextChangedListener(new android.text.TextWatcher({
 
    afterTextChanged(s) {
        console.log("afterTextChanged");
        console.log(s);
    },
    beforeTextChanged(s, start, count, after) {
        console.log("beforeTextChanged");
        console.log(s);
        console.log(start);
        console.log(count);
        console.log(after);
    },
    onTextChanged(s, start, before, count) {
        console.log("onTextChanged");
        console.log(s);
        console.log(start);
        console.log(before);
        console.log(count);
    }
}));

```

**Comment by nmongiya** [comment]
@tsonevn When I tried to use setText method in nativeTField(https://developer.android.com/reference/android/support/v7/widget/AppCompatEditText.html
 ), it is giving me below error 
`ERROR Error: java.lang.Exception: Failed resolving method setText on class android.widget.EditText
    com.tns.Runtime.resolveMethodOverload(Runtime.java:1045)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
    com.tns.Runtime.callJSMethod(Runtime.java:953)
    com.tns.Runtime.callJSMethod(Runtime.java:937)
    com.tns.Runtime.callJSMethod(Runtime.java:929)
    com.tns.FragmentClass.onCreateView(FragmentClass.java:35)
    android.app.Fragment.performCreateView(Fragment.java:2353)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:995)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
    android.app.BackStackRecord.run(BackStackRecord.java:815)
    android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
    android.app.FragmentManagerImpl$1.run(FragmentManager.java:483)
    android.os.Handler.handleCallback(Handler.java:751)
    android.os.Handler.dispatchMessage(Handler.java:95)
    android.os.Looper.loop(Looper.java:154)
    android.app.ActivityThread.main(ActivityThread.java:6077)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)`

**Comment by tsonevn** [comment]
Hi @nmongiya,
I tested the described scenario with the setText method, however, I was unable to recreate this problem and the text waas applied properly. Regarding that could you provide some sample code, which shows, how you use setText method in your code? Also I am attaching sample code from my test project

HTML
```
<StackLayout tkExampleTitle tkToggleNavButton ios:backgroundColor="#CDCECE" padding="5">
    <Label text="Select country"></Label>
<!-- >> angular-autocomplete-getting-started-html -->
    <RadAutoCompleteTextView (loaded)="atcomloaded($event)" #autocmp [items]="dataItems" suggestMode="Suggest" displayMode="Tokens">
        <SuggestionView tkAutoCompleteSuggestionView>
            <ng-template tkSuggestionItemTemplate let-item="item">
                <StackLayout orientation="vertical" padding="10">
                    <Label [text]="item.text"></Label>
                </StackLayout>
            </ng-template>
        </SuggestionView>
    </RadAutoCompleteTextView>
<!-- << angular-autocomplete-getting-started-html -->
    <Label text="SUGGEST MODES" marginTop="5"></Label>
    <StackLayout orientation="horizontal">
        <Button margin="5" text="Suggest" (tap)="onSuggestSelected($event)"></Button>
        <Button margin="5" text="Append" (tap)="onAppendSelected($event)"></Button>
        <Button margin="5" text="Suggest-Append" (tap)="onSuggestAppendSelected($event)"></Button>
    </StackLayout>
    <Label text="COMPLETION MODES"></Label>
    <StackLayout orientation="horizontal">
        <Button margin="5" text="StartsWith" (tap)="onStartsWithSelected($event)"></Button>
        <Button margin="5" text="Contains" (tap)="onContainsSelected($event)"></Button>
    </StackLayout>
    <Label text="DISPLAY MODES"></Label>
    <StackLayout orientation="horizontal">
        <Button margin="5" text="Plain" (tap)="onPlainSelected($event)"></Button>
        <Button margin="5" text="Tokens" (tap)="onTokensSelected($event)"></Button>
    </StackLayout>
</StackLayout>
```
TypeScript
```
atcomloaded(args){
        console.log("auto comp loaded");
        var autocmp = args.object; 
        var nativeTField = autocmp.android.getTextField();
        nativeTField.setText("test setText method")
}
```
