### ISSUE TITLE
RadChart w/live data for iOS10 is rendered twice on real device

### ISSUE THREAD

**Issue by NickIliev** [telerik/nativescript-ui-feedback#34]
When using RadChart with live data the chart is rendered twice.
Reproducible ONLY on **iOS10** wand only with **real device** (lower iOS versions and  iOS10 simulator are working as expected)

Code to reproduce:: 
https://github.com/NickIliev/NativeScript-issues/tree/master/admin/ticket_1073176/chart-double-draw-test-src

result: when tapping on "Show Chart" the chart is displayed initially, then deleted and then the expected behavior is triggered (the chart data is displayed gradually)

related to ticket 1073176

**Comment by skarlatov** [comment]
Can't run the project. No profiles for 'fi.rentoinnovations.leaf' were found: Xcode couldn't find a provisioning profile matching 'fi.rentoinnovations.leaf'.

**Comment by NickIliev** [comment]
The problem is reproducible only with real device and you will need to build with your team id [in this file](https://github.com/NickIliev/NativeScript-issues/blob/master/admin/ticket_1073176/chart-double-draw-test-src/app/App_Resources/iOS/build.xcconfig#L5)
