### ISSUE TITLE
Picker SelectedValueChange RadDataForm

### ISSUE THREAD

**Issue by brunaaanayara** [telerik/nativescript-ui-feedback#346]
Let's say I have the dataform source below.

```
export class Animal {
    public name: string;
    public type: string; //dog, cat, fish etc.
    public maxAge: number;
}
```

The 'type' property is a picker.
When I change the animal type I want to update the maxAge property so for that I need something like a method that get calls when the animal type selectedValueChange and on that method I can set a new maxAge to my animal. Is there a way I can do that using RadDataForm? How can I do that?

**Comment by tsonevn** [comment]
Hi @brunaaanayara,
Thank you for your interest in UI for NativeScript.
In your case, you could use `propertyCommitted` event, which will be fired, when the value for the picker is changed. For example:
XML
```
<navigation:ExamplePage xmlns:navigation="navigation/example-page" loaded="onPageLoaded" xmlns:df="nativescript-pro-ui/dataform" xmlns="http://www.nativescript.org/tns.xsd">
    <df:RadDataForm id="myDataForm" source="{{ ticketOrder }}" propertyCommitted="dfPropertyCommitted">
        .....
    </df:RadDataForm>
</navigation:ExamplePage>
```
TypeScript
```
import viewModel = require("./../view-models/ticket-order-model");
export function onPageLoaded(args) {
    var page = args.object;
    page.bindingContext = new viewModel.TicketViewModel();
}

export function dfPropertyCommitted(args) {
    console.log("dfPropertyCommitted");
    var text = "LastEvent: " + args.propertyName + " property committed";
    console.log(text);
}
```
About the second question, to be able to change the some of the property values, you should change the source for the RadDataForm. More info about changing the source and sample code could be found in issue #344.
