### ISSUE TITLE
RadDataForm propertyConverter not updating view.

### ISSUE THREAD

**Issue by bori87** [telerik/nativescript-ui-feedback#349]
Converter is working but the view is not updating.

```javascript
ngOnInit(){
  this.currencyConverter = new CurrencyConverter();
  ...
}

export class CurrencyConverter implements PropertyConverter {
    constructor() { }

    convertFrom(input: number) {
        console.log(input * 4);
        return input * 4;
    }

    convertTo(output: number) {
        console.log(input * 2);
        return output * 2;
    }
}
```

```html
<TKEntityProperty tkPropertyGroupProperties name="price" displayName="Wynagrodzenie" index="1" columnIndex="1" [converter]="currencyConverter">
  <TKPropertyEditor tkEntityPropertyEditor type="Decimal"></TKPropertyEditor>
</TKEntityProperty>
```

**Comment by NickIliev** [comment]
@bori87 the converter is not accepting any `input` value in its constructor so it does not "know' what to convert.

```
constructor(input: number) { }
```

And then pass the value you want to convert when initializing your `new Converter`
```
this.currencyConverter = new CurrencyConverter(myValue);
```

**Comment by bori87** [comment]
Is not working. I want the user to input price like '1,21' then convert to 1.21. Also the keyboard should be numeric.

**Comment by bori87** [comment]
![ns](https://user-images.githubusercontent.com/29092029/32159443-dad83848-bd4d-11e7-9cce-143e80a124df.png)

**Comment by bhcuong2008** [comment]
Current dataform Decimal editor does not allow to input negative number. So could I use converter to convert between source object number and text input on UI? I try but not know how to do that. When specifying tkEntityPropertyEditor of type Text with source object number field, then it shows error, 
===
ERROR Error: java.lang.Error: DataFormTextEditor does not support properties of type Integer.  Please specify a value converter for your property.
===

I already created converter for that field property. But error is the same as above.
