### ISSUE TITLE
 nativescript-fingerprint-auth and nativescript-barcodescanner

### ISSUE THREAD

**Issue by manigorsh** [telerik/nativescript-ui-feedback#354]
I use both nativescript-fingerprint-auth and nativescript-barcodescanner.
They are used in separate components and are in no way connected with each other.

If I do not use fingerprint before scanning all works fine. But if before using barcodescanner I use fingerprint, my barcodescanner doesn't return any value. It's Promise doesn't return either success, neither error.

**Comment by NickIliev** [comment]
@manigorsh this repository is for logging issues, bugs and feature requests related to nativescript-pro-ui plugin. For issues related to third-party plugins please post in the respective plugin's repositories or one of the community channels like [https://discourse.nativescript.org/](https://discourse.nativescript.org/) or [SO](https://stackoverflow.com/questions/tagged/nativescript)
