### ISSUE TITLE
RadListView crush on swiping on a footer

### ISSUE THREAD

**Issue by tigrenok00** [telerik/nativescript-ui-feedback#357]
Hi,
I have a RadListView with a footer with swipe actions enabled.
When swiping on a footer, there is a crush.
How can we prevent it or prevent swiping actions to be triggered at all on the footer section?
Thanks!

![image](https://user-images.githubusercontent.com/23075641/31890829-38e980fe-b80d-11e7-91b8-b13ae3dd8fd2.png)

These are the versions I'm using:
Android
Progress NativeScript UI version: "3.1.1",
CLI: 3.2.0
Cross-platform modules: 3.2.0

**Comment by tsonevn** [comment]
Hi @tigrenok00,
Thank you for reporting this issue.
I tested this case on my side and was able to recreate the issue. For your convenience, I am attaching sample project which could be used for debugging.
![screencast 2017-10-25 at 5 35 39 pm](https://user-images.githubusercontent.com/17448734/32004729-2267e240-b9ab-11e7-8072-ea8cfa1edad6.gif)

At this time there is no functionality, which allows disabling the gestures for the footer or header. I would suggest keeping track on the issue for further info.
[Archive.zip](https://github.com/telerik/nativescript-ui-feedback/files/1414952/Archive.zip)

**Comment by zbranzov** [comment]
The 'next' version of pro-ui seems to fix the issue. I've tested it with the applied project and no crash appears anymore.
