### ISSUE TITLE
Calendar(iOS) In DayView  showWeekNumbers="true" doesn't apply 

### ISSUE THREAD

**Issue by Natalia-Hristova** [telerik/nativescript-ui-feedback#366]
### Tell us about the problem
WeekNumbers are not shown in DayView

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** next

### Please tell us how to recreate the issue in as much detail as possible.
1. Start sdkAngular -> Calendar -> CellStyling
2. From "Options" menu select "Day"

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
Code from the example
```html
<rc:RadCalendar.dayViewStyle>
<rc:CalendarDayViewStyle backgroundColor="#dd855c" showTitle="true" showWeekNumbers="true" showDayNames="true" >
        <rc:CalendarDayViewStyle.todayCellStyle>
            <rc:DayCellStyle cellBackgroundColor="#dd855c" cellBorderWidth="1" cellBorderColor="#f1e8ca" cellTextColor="#745151" cellTextFontName="Times New Roman" cellTextFontStyle="Bold" cellTextSize="14" />
        </rc:CalendarDayViewStyle.todayCellStyle>
..
```

**Comment by tgpetrov** [comment]
This is what I see when I follow the steps:

![screen](https://user-images.githubusercontent.com/6085251/32100190-d4ab796e-bb1b-11e7-84f5-3c37b009ec03.png)

WeekNumbers seem visible. Are you using latest?

P.S. The code you pasted is definitely not taken from sdkAngular.
