### ISSUE TITLE
Nativescript financial charts - DateTimeCategoricalAxis - date time axis accuracy

### ISSUE THREAD

**Issue by morzyns** [telerik/nativescript-ui-feedback#370]
Simple question here,
Does CandleStick Chart support more accurate time plots? I need to present data points lets say for 30 min intervals. i Try to give it a date format `dateFormat="hh:mm:ss"` but it doesn't seem to work.

How can i configure the chart to present the points on the dateTimeCategorial axis with let's say 30min offsets?

Documentation doesn't specify what are the dataFormat options, in practice plotting data by day is not enough to use this component in production.

**Comment by tsonevn** [comment]
Hi @morzyns,
Thank you for your interest in UI for NativeScript.

Something that I would suggest is to use the `CategoricalAxis` and to specify the [majorTickInterval ](http://docs.telerik.com/devtools/nativescript-ui/api/classes/categoricalaxis.html#majortickinterval) property. For example:
```
<chart:RadCartesianChart row="1" id="cartesianChart">
    <chart:RadCartesianChart.series>
          <chart:CandlestickSeries
            items="{{ candleStickSourceItems }}">
              <chart:CandlestickSeries.horizontalAxis>
                <chart:CategoricalAxis majorTickInterval="1"/>
              </chart:CandlestickSeries.horizontalAxis>
              <chart:CandlestickSeries.verticalAxis>
                <chart:LinearAxis/>
              </chart:CandlestickSeries.verticalAxis>
            </chart:CandlestickSeries>
        </chart:RadCartesianChart.series>
        <!-- >> chart-trackball-property-xml -->
        <chart:RadCartesianChart.trackball>
            <chart:Trackball/>
        </chart:RadCartesianChart.trackball>
        <!-- << chart-trackball-property-xml -->
    </chart:RadCartesianChart>
```

Regarding the reported case, there is another axis,  called `DateTimeContinuousAxis`, which allows deeper control on the `dateFormat ` and also set up the [majorStep](http://docs.telerik.com/devtools/nativescript-ui/api/modules/datetimecomponent.html). However, at this point, the majorStep property could not be bind. This is already reported [here ](https://github.com/telerik/nativescript-ui-feedback/issues/136) and you could keep track on the issue for further info.

**Comment by morzyns** [comment]
Hey @tsonevn,
it's good to know - i can use CategoricalAxis. Good news, thanks!
