### ISSUE TITLE
RadSideDrawer with TabView (Angular)

### ISSUE THREAD

**Issue by Meyer-dev** [telerik/nativescript-ui-feedback#376]
Hi Guys my problem is occurring with the latest versions of the CLI etc. (nativescript -angular)

I believe i may have made a mistake with the code as it appears unclear how to integrate the radsidedrawer as well as tabview to a page.Any help would be greatly appreciated.here is the html below.
<ActionBar title="frame 10" class="action-bar">
    
</ActionBar>
<RadSideDrawer tkExampleTitle tkToggleNavButton>
    <StackLayout tkDrawerContent class="sideStackLayout">
        <StackLayout class="sideTitleStackLayout">
            <Label text="Navigation Menu"></Label>
        </StackLayout>
        <StackLayout class="sideStackLayout">
            <Label text="Primary" class="sideLabel sideLightGrayLabel"></Label>
            <Label text="Social" class="sideLabel"></Label>
            <Label text="Promotions" class="sideLabel"></Label>
            <Label text="Labels" class="sideLabel sideLightGrayLabel"></Label>
            <Label text="Important" class="sideLabel"></Label>
            <Label text="Starred" class="sideLabel"></Label>
            <Label text="Sent Mail" class="sideLabel"></Label>
            <Label text="Drafts" class="sideLabel"></Label>
        </StackLayout>
        <Label text="Close Drawer" color="lightgray" padding="10"  (tap)="onCloseDrawerTap()"></Label>
    </StackLayout>
    <StackLayout tkMainContent>
        <Label [text]="mainContentText" textWrap="true" class="drawerContentText"></Label>
        <Button text="OPEN DRAWER" (tap)="openDrawer()" class="drawerContentButton"></Button>     
        
        <TabView selectedIndex="0" (selectedIndexChange)="onIndexChanged($event)" sdkExampleTitle sdkToggleNavButton class=intabbtn>
            <StackLayout *tabItem="{title: 'Groceries',  iconSource: 'res://logo_white_bg'}">
                <label text="hello"></label>
            </StackLayout>
        
            <StackLayout *tabItem="{title: 'Recipes',  iconSource: 'res://logo_white_bg'}">
            </StackLayout>
        
            <StackLayout *tabItem="{title: 'Household',  iconSource: 'res://logo_white_bg'}">
            </StackLayout>
        
            <StackLayout *tabItem="{title: 'Health & Beauty',  iconSource: 'res://logo_white_bg'}">
            </StackLayout>
        
            <StackLayout *tabItem="{title: 'Electricity',  iconSource: 'res://logo_white_bg'}">
            </StackLayout>
        
        </TabView>

    </StackLayout>
</RadSideDrawer>

I would preferably have the link to the side drawer from the action-bar :)

**Comment by tsonevn** [comment]
Hi @Meyer-dev,
Thank you for contacting us.
In your case, you should setup the TabView component inside the Layout which has `tkMainContent` directive. This is the place, which you should display the content for your page as it is described [here ](http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/SideDrawer/getting-started#radsidedrawer-getting-started) in the docs. For example:
HTML
```
<RadSideDrawer tkExampleTitle tkToggleNavButton>
    <StackLayout tkDrawerContent class="sideStackLayout">
        <StackLayout class="sideTitleStackLayout">
            <Label text="Navigation Menu"></Label>
        </StackLayout>
        <StackLayout class="sideStackLayout">
            <Label text="Primary" class="sideLabel sideLightGrayLabel"></Label>
            <Label text="Social" class="sideLabel"></Label>
            <Label text="Promotions" class="sideLabel"></Label>
            <Label text="Labels" class="sideLabel sideLightGrayLabel"></Label>
            <Label text="Important" class="sideLabel"></Label>
            <Label text="Starred" class="sideLabel"></Label>
            <Label text="Sent Mail" class="sideLabel"></Label>
            <Label text="Drafts" class="sideLabel"></Label>
        </StackLayout>
        <Label text="Close Drawer" color="lightgray" padding="10" style="horizontal-align: center" (tap)="onCloseDrawerTap()"></Label>
    </StackLayout>
    <StackLayout tkMainContent>
        <GridLayout rows="" columns="">
                <TabView selectedIndex="0" (selectedIndexChange)="onIndexChanged($event)" sdkExampleTitle sdkToggleNavButton class=intabbtn>
                        <StackLayout *tabItem="{title: 'Groceries'}">
                            <label text="hello"></label>
                        </StackLayout>
                    
                        <StackLayout *tabItem="{title: 'Recipes'}">
                        </StackLayout>
                    
                        <StackLayout *tabItem="{title: 'Household'}">
                        </StackLayout>
                    
                        <StackLayout *tabItem="{title: 'Health & Beauty'}">
                        </StackLayout>
                    
                        <StackLayout *tabItem="{title: 'Electricity'}">
                        </StackLayout>
                    
                    </TabView>
        </GridLayout>
        <Label [text]="mainContentText" textWrap="true" class="drawerContentText"></Label>
        <Button text="OPEN DRAWER" (tap)="openDrawer()" class="drawerContentButton"></Button>
    </StackLayout>
</RadSideDrawer>
```
TypeScript
```
import { Component, ViewChild, OnInit, AfterViewInit, ChangeDetectorRef } from "@angular/core";
import { Page } from "ui/page";
import { ActionItem } from "ui/action-bar";
import { Observable } from "data/observable";
import { RadSideDrawerComponent, SideDrawerType } from "nativescript-pro-ui/sidedrawer/angular";
import { RadSideDrawer } from 'nativescript-pro-ui/sidedrawer';

@Component({
    moduleId: module.id,
    selector: "tk-sidedrawer-getting-started",
    templateUrl: 'getting-started.component.html',
    styleUrls: ['getting-started.component.css']
})
export class SideDrawerGettingStartedComponent implements AfterViewInit, OnInit {
    private _mainContentText: string;

    constructor(private _changeDetectionRef: ChangeDetectorRef) {
    }

    @ViewChild(RadSideDrawerComponent) public drawerComponent: RadSideDrawerComponent;
    private drawer: RadSideDrawer;

    ngAfterViewInit() {
        this.drawer = this.drawerComponent.sideDrawer;
        this._changeDetectionRef.detectChanges();
    }

    ngOnInit() {
        this.mainContentText = "SideDrawer for NativeScript can be easily setup in the HTML definition of your page by defining tkDrawerContent and tkMainContent. The component has a default transition and position and also exposes notifications related to changes in its state. Swipe from left to open side drawer.";
    }

    get mainContentText() {
        return this._mainContentText;
    }

    set mainContentText(value: string) {
        this._mainContentText = value;
    }

    public openDrawer() {
        this.drawer.showDrawer();
    }

    public onCloseDrawerTap() {
       this.drawer.closeDrawer();
    }

    public onIndexChanged(args){
        console.log("onIndexChanged");
    }
}
// << sidedrawer-getting-started-angular

```
In case you are having some further issues, please provide sample project, which could be used for debugging.

**Comment by Meyer-dev** [comment]
Hi ,thanks for the help.
I am very new to programming.What would be the easiest way to provide a
sample project...?
I have implemented the above html,here is my typescript file code :

import { Router } from "@angular/router";
import { TabView, SelectedIndexChangedEventData, TabViewItem } from
"ui/tab-view";
import { StackLayout } from "ui/layouts/stack-layout";
import { Component, ViewChild, OnInit, AfterViewInit, ChangeDetectorRef }
from "@angular/core";
import { Page } from "ui/page";
import { ActionItem } from "ui/action-bar";
import { Observable } from "data/observable";
import { RadSideDrawerComponent, SideDrawerType } from
"nativescript-pro-ui/sidedrawer/angular";
import { RadSideDrawer } from 'nativescript-pro-ui/sidedrawer';



@Component({
moduleId: module.id,
selector: "frame_10_groceries",
templateUrl: "pages/frame_10_groceries/f_10_groceries.html",
styleUrls: ["pages/frame_10_groceries/f_10_groceries-common.css",
"pages/frame_10_groceries/f_10_groceries.css"]
})

export class f_10_groceriesComponent implements AfterViewInit, OnInit {
private _mainContentText: string;
constructor(private _changeDetectionRef: ChangeDetectorRef) {
}
@ViewChild(RadSideDrawerComponent) public drawerComponent:
RadSideDrawerComponent;
private drawer: RadSideDrawer;
ngAfterViewInit() {
this.drawer = this.drawerComponent.sideDrawer;
this._changeDetectionRef.detectChanges();
}
ngOnInit() {
this.mainContentText = "SideDrawer for NativeScript can be easily setup in
the HTML definition of your page by defining tkDrawerContent and
tkMainContent. The component has a default transition and position and also
exposes notifications related to changes in its state. Swipe from left to
open side drawer.";
}
get mainContentText() {
return this._mainContentText;
}
set mainContentText(value: string) {
this._mainContentText = value;
}
public openDrawer() {
this.drawer.showDrawer();
}
public onCloseDrawerTap() {
this.drawer.closeDrawer();
}
public onIndexChanged(args){
console.log("onIndexChanged");
}
}

**Comment by Meyer-dev** [comment]
the error I'm getting reads: 
An uncaught Exception occurred on "main" thread. java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference at com.telerik.android.primitives.widget.sidedrawer.RadSideDrawer.handleOnDown(RadSideDrawer.java:460) at com.telerik.android.primitives.widget.sidedrawer.RadSideDrawer.onGesture(RadSideDrawer.java:438) at com.telerik.android.primitives.widget.sidedrawer.RadSideDraw...

**Comment by tsonevn** [comment]
Hi @Meyer-dev,
You could create a new project while using `tns create testProject --ng` and make the needed changes in the sample project, which will allow us to recreate the issue.
Then you could remove `platforms` and `node_modules` folders and attache `ZIP` file with all other projects files.

It would also help if you could give us some more info about the issue, which you are facing.

**Comment by Meyer-dev** [comment]
Thanks again for the response.

My code seems to build fine but the html does not display as intended.I
have attached a test project.Only an action bar with the app name
appears.The button for the sidebar does not appear and when i swipe an
error appears,it reads:

An uncaught Exception occurred on "main" thread.
java.lang.NullPointerException: Attempt to invoke virtual method 'void
android.view.View.setVisibility(int)' on a null object reference
at
com.telerik.android.primitives.widget.sidedrawer.RadSideDrawer.handleOnDown(RadSideDrawer.java:460)
at
com.telerik.android.primitives.widget.sidedrawer.RadSideDrawer.onGesture(RadSideDrawer.java:438)
at
com.telerik.android.primitives.widget.sidedrawer.RadSideDrawer.onInterceptTouchEvent(RadSideDrawer.java:420)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2212)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
at
com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:411)
at
com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1810)
at android.app.Activity.dispatchTouchEvent(Activity.java:3061)
at
com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:373)
at android.view.View.dispatchPointerEvent(View.java:10163)
at
android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4434)
at
android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4302)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
at
android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3902)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3868)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3995)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3876)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4052)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
at
android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3902)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3868)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3876)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6210)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6184)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6145)
at
android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6313)
at
android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:323)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:6077)
at java.lang.reflect.Method.invoke(Native Method)
at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

**Comment by Meyer-dev** [comment]
gmail doesnt allow me so send the zip file due to security reasons...?is
this supposed to happen :)

**Comment by Meyer-dev** [comment]
import { NgModule,NO_ERRORS_SCHEMA } from "@angular/core";
import { NativeScriptFormsModule } from "nativescript-angular/forms";
import { NativeScriptHttpModule } from "nativescript-angular/http";
import { NativeScriptModule } from
"nativescript-angular/nativescript.module";
import { NativeScriptRouterModule } from "nativescript-angular/router";
import { AppComponent } from "./app.component";
import { routes, navigatableComponents } from "./app.routing";



@NgModule({
imports: [
NativeScriptModule,
NativeScriptFormsModule,
NativeScriptHttpModule,
NativeScriptRouterModule,
NativeScriptRouterModule.forRoot(routes)
],
declarations: [
AppComponent,
...navigatableComponents
],
bootstrap: [AppComponent],
schemas: [NO_ERRORS_SCHEMA]
})
export class AppModule {}

My module.ts file ,believe i've sent the important ones through now:)

**Comment by tsonevn** [comment]
Hi @Meyer-dev,
Regarding your first question, you should be able to attach a zip of the project in the issue.  If there is a problem with the upload, it might be related to the way how the archive is made.

Regarding the visualization of the RadSideDrawer, I found that in the imports `NativeScriptUISideDrawerModule ` is missing in AppModule, which could be related to the problem. For example:
```
import { NgModule,NO_ERRORS_SCHEMA } from "@angular/core";
import { NativeScriptFormsModule } from "nativescript-angular/forms";
import { NativeScriptHttpModule } from "nativescript-angular/http";
import { NativeScriptModule } from
"nativescript-angular/nativescript.module";
import { NativeScriptRouterModule } from "nativescript-angular/router";
import { AppComponent } from "./app.component";
import { routes, navigatableComponents } from "./app.routing";
import { NativeScriptUISideDrawerModule } from "nativescript-pro-ui/sidedrawer/angular";


@NgModule({
imports: [
NativeScriptModule,
NativeScriptFormsModule,
NativeScriptHttpModule,
NativeScriptRouterModule,
NativeScriptUISideDrawerModule ,
NativeScriptRouterModule.forRoot(routes)
],
declarations: [
AppComponent,
...navigatableComponents
],
bootstrap: [AppComponent],
schemas: [NO_ERRORS_SCHEMA]
})
export class AppModule {}
```
For your convenience, I am attaching a sample project. If the problem persists, please review the project and make the needed changes, which will allow us to recreate the issue.

[Archive.zip](https://github.com/telerik/nativescript-ui-feedback/files/1449609/Archive.zip)
