### ISSUE TITLE
RadListView: Load on demand and multiple templates in iOS

### ISSUE THREAD

**Issue by codeback** [telerik/nativescript-ui-feedback#377]
As @VladimirAmiorkov says here https://github.com/telerik/nativescript-ui-feedback/issues/115#issuecomment-301019609, in iOS you have to set an item height for the template if you want to load on demand items:
```
...
<ListViewLinearLayout *tkIfIOS tkListViewLayout itemHeight="120"></ListViewLinearLayout>
...
```

This issue is a big problem if you want to use multiple templates in the list since each template can have a different height.

Is there any solution or workaround for this use case?

Thanks in advance.

**Comment by codeback** [comment]
Hi @tsonevn, thank you for your answer.

I've just tested on iOS 10.2 and 11 and the problem persists. The Load on demand functionality works (more items are loaded at the end of the list) but it jumps several items. If you do it with the itemHeight, the scroll is smooth and it works well. Did you test it with items of different height?

**Comment by tsonevn** [comment]
Hi @codeback,
I tested again the case with a load on demand and ListViewLinearLayout without itemHeight and in my further research, I found that the problem still exists. 
Regarding that, I would suggest closing this issue in favor of the [old issue ](https://github.com/telerik/nativescript-ui-feedback/issues/115#issuecomment-301019609) and you could leave your additional info in the old one.
