### ISSUE TITLE
Change chart legend

### ISSUE THREAD

**Issue by brunaaanayara** [telerik/nativescript-ui-feedback#381]
Is it possible to format the value of the chart legend as currency or a way where I can set the legend that I want to show?

For now the legend is something like this:

title
300.0 Type1
397.0 Type2
990.2 Type3

but I want to format those numbers as currency 'BRL' so I want something like this 

title
Type1 - R$300,00 
Type2 - R$397,00 
Type3 - R$990,20 

I'm using nativescript + angular.

**Comment by tsonevn** [comment]
Hi @brunaaanayara,
Thank you for your interest in UI for NativeScript.
At this point changing the legend's label format is not supported. This feature is already logged [here ](https://github.com/telerik/nativescript-ui-feedback/issues/250) in this issue. You could keep track on the other issue for further info and also you could leave additional comment in it,
