### ISSUE TITLE
[Feature] Expose clearEvent, textChangeEvent for AutoCompleteTextView

### ISSUE THREAD

**Issue by NickIliev** [telerik/nativescript-ui-feedback#390]
Related to [https://github.com/telerik/nativescript-ui-feedback/issues/320](https://github.com/telerik/nativescript-ui-feedback/issues/320)

Expose events like **clear** and **textChange** for handling the TextView in AutoCompleteTextView.

Requested by t. 1139180

**Comment by tgpetrov** [comment]
With `nativescript-ui-autocomplete` [3.6.0](https://github.com/telerik/nativescript-ui-feedback/blob/master/releases/autocomplete.md#v360) there is a `textChanged` event which can be used to get notified when the `text` is changed including when the X button is pressed.
