### ISSUE TITLE
showOverNavigation = true is rendering the RadSideDrawer n the safe area for iPhone X (iOS 11)

### ISSUE THREAD

**Issue by NickIliev** [telerik/nativescript-ui-feedback#392]
The new iPhone X has the camera placed on the middle top screen and when using 
`RadSideDrawer` with `showOverrNavigation` set to `true` the drawer is rendered in the safe area (but it shouldn't)

Steps to reproduce:
- use [this sample application ](https://github.com/NickIliev/nativescript-ng-cosmos/tree/niliev/frames-modules)(branch niliev/frames-modules)
- open drawer - it will be rendered like in the screenshot below - the drawer renders behind the hardware camera 

![screen shot 2017-11-08 at 4 52 53 pm](https://user-images.githubusercontent.com/18008302/32555533-af02099c-c4a5-11e7-8df2-36d674ba3120.png)

**Comment by evanfuture** [comment]
We got around this by adding a top padding/margin to the drawer contents when we're on iphone X.  Since it won't be the only iphone x adjustment needed, it's probably better just to let the devs do the check/adjust themselves (as opposed to baking it into the plugin).

**Comment by tgpetrov** [comment]
After the [4.0 Release](https://github.com/telerik/nativescript-ui-feedback/blob/master/releases/sidedrawer.md#v400) of SideDrawer and the removal of `showOverNavigation` this seems to be no longer reproducible:

![side](https://user-images.githubusercontent.com/6085251/39424123-c6c39004-4c7d-11e8-8381-675b996dea71.png)
