### ISSUE TITLE
RadCalendar is not working as expected

### ISSUE THREAD

**Issue by masrc** [telerik/nativescript-ui-feedback#398]
I have a calendar that can register events and when the user tap on a date, it should show the events in that specific day, but when I tap on a date, it ever show the current day or the last date selected, not the date tapped.

[calendarDemo.zip](https://github.com/telerik/nativescript-ui-feedback/files/1466894/calendarDemo.zip)

**Comment by NickIliev** [comment]
@masrc to resolve your issue use the displayedDate property and bind it directly to your selected date (in your source code in the component file `this.Date`)

For example based  on  your code just bind the property in the HTML
```
<RadCalendar  id="calendar" locale="pt-BR" 
    [eventSource]="eventSource" 
    (dayViewEventSelected)="onDayViewEventSelected($event)" 
    (cellTap)="onDateSelected($event)" 
    [viewMode]="viewMode" 
    [displayedDate]="Date"></RadCalendar>
```
