### ISSUE TITLE
[Bug Report] RadListView Android spanCount not programatically changeable

### ISSUE THREAD

**Issue by NathanaelA** [telerik/nativescript-ui-feedback#40]
Attempting to change the `listView.listViewLayout.spanCount = "2";` doesn't seem to work if the page has already drawn.  This does work if you set the XML first
```
 <lv:RadListView.listViewLayout>
                <lv:ListViewGridLayout scrollDirection="Vertical" spanCount="2"/>
            </lv:RadListView.listViewLayout>
```
But I can't still change this at runtime on Android.    (iOS appears to work though).

This is making me ship a whole duplicate xml file with spanCount = "2" just to make the display work.

**Comment by Daxito** [comment]
+1
Had the same issue, had to also duplicate stuff
