### ISSUE TITLE
RadCalendar CalendarViewMode.Day

### ISSUE THREAD

**Issue by bnbs** [telerik/nativescript-ui-feedback#401]
I have a radcalendar in my app and I need to change the CalendarViewMode.Month to CalendarViewMode.Day when the user selects a day, and if the CalendarViewMode is CalendarViewMode.Day and the user selects the date that is already selected so CalendarViewMode has to change to CalendarViewMode.Month again. How can I do that? I tried to use cellTap, dateSelected but no success.

**Comment by tsonevn** [comment]
Hi @bnbs,
Thank you for your interest in UI for NativeScript.
The Calendar component supports dateSelected and dateDeselected events. 
XML
```
<navigation:ExamplePage xmlns:navigation="navigation/example-page" xmlns:rc="nativescript-pro-ui/calendar" xmlns="http://www.nativescript.org/tns.xsd">
    <navigation.actionBar>
        <ActionBar title="Events" />
    </navigation.actionBar>
    <!-- >> calendar-handling-events-xml -->
    <rc:RadCalendar id="calendar" 
    viewMode="Day"
	   dateSelected="onDateSelected"
	   dateDeselected="onDateDeselected"
	   navigatedToDate="onNavigatedToDate"
	   navigatingToDateStarted="onNavigatingToDateStarted"
       viewModeChanged="onViewModeChanged" />
     <!-- << calendar-handling-events-xml -->
</navigation:ExamplePage>
```
TypeScript
```
export function onPageLoaded(args){
    var page = args.object;
}

// >> calendar-handling-events

export function onDateSelected(args: calendarModule.CalendarSelectionEventData) {
    console.log("onDateSelected: " + args.date);
}

export function onDateDeselected(args: calendarModule.CalendarSelectionEventData) {
    console.log("onDateDeselected: " + args.date);
}

export function onNavigatedToDate(args: calendarModule.CalendarNavigationEventData) {
    console.log("onNavigatedToDate: " + args.date);
}

export function onNavigatingToDateStarted(args: any) {
    console.log("onNavigatingToDateStarted: " + args.date);
}

export function onViewModeChanged(args: calendarModule.CalendarViewModeChangedEventData) {
    console.log("onViewModeChanged: " + args.newValue);
}
```
Those events will be fired on the first tap on a specific date, however, they will not be executed on the second tap of the selected date.
Regarding that it there is no way at this time to handle the second tap on the Calendar date.
It would help also if you could provide more info about the use case for the similar functionality and what would be the expected result.
