### ISSUE TITLE
License Clarification

### ISSUE THREAD

**Issue by jschwartz73** [telerik/nativescript-ui-feedback#402]
I'm looking for clarification on the licensing terms of nativescript-pro-ui

I know the components were re-licensed as "free", however, looking through the current license in this project (nativescript-ui-feedback), has some confusing sections.  For example, section 2.2 starts with the following:

> 2.2 Scope of Use. The Software is licensed, not sold, on a per-seat basis. The number of Licensed Developers using the Software must correspond to the maximum number of License seats You have obtained from Telerik hereunder. 

With "free" software, Do I have to purchase license seats from Telerik? What about deployment restrictions based on this?

Do you think you could clarify the terms of this "free" software for use in commercial projects?  Is it possible this project can be moved under nativescript and put under the Apache license?

It should be noted - I am not an attorney

Thanks in advance for your assistance.

**Comment by bugventure** [comment]
You don't have to purchase license seats from Telerik, you can use the components freely, as if you have them already purchased. If it's easier to understand, it's like having a price tag of $0. Our legal team did not find a need to update the License Agreement for the moment, as it does not cover any pricing terms.

In the longer term, we're considering our options for putting NativeScript UI under the same Apache v.2 license and completely OSS-ing it.

**Comment by james-criscuolo** [comment]
@bugventure Any chance the move to apache 2 is upcoming? I understand the license is essentially free, but the wording makes this a bit tricky to use without being questioned.
