### ISSUE TITLE
Disable scrolling effect for RadDataForm for iOS

### ISSUE THREAD

**Issue by NickIliev** [telerik/nativescript-ui-feedback#407]
When RadDataForm is wrapped in any NativeScript layout a scrolling effect is always applied on iOS.
The scrolling is not applied on Android (if the data form has enough space to render)

Steps to reproduce based on[ this sample](https://github.com/telerik/nativescript-ui-samples/blob/release/sdk/app/dataform/getting-started/getting-started.xml):
```
<GridLayout rows="*">
    <df:RadDataForm row="0" id="myDataForm" source="{{ person }}" />
</GridLayout>
```

reported via t. 1140360

**Comment by NickIliev** [comment]
@papangproduction this appears to be expected behavior as behind the RadDataForm for iOS the native control is ScrollView which always has the minimum scrolling effect.

**Comment by lblase** [comment]
Hi, 

I don't know why this issue is closed but is not because I'm using NativeScript 6.5.1 with Angular Core and I have this issue on my iOS device.
`RadDataForm` is adding a native scroll inside of it and it's very annoying.

What can I do about it?

Thanks
