### ISSUE TITLE
Using xmlns as shown in snippet 

### ISSUE THREAD

**Issue by sathish331977** [telerik/nativescript-ui-feedback#41]
Can i use the xmlns as shown below.  ( xmlns:lv)

 
[list.txt](https://github.com/telerik/nativescript-ui-feedback/files/626795/list.txt)

**Comment by VladimirAmiorkov** [comment]
Hi @sathish331977 ,

Yes you can declared the xmlns inside the tag which is exposed via that namespace like so:

```
<lv:RadListView xmlns:lv="nativescript-telerik-ui/listview">
</lv:RadListView>
```
