### ISSUE TITLE
SDK - Pie series missing in release

### ISSUE THREAD

**Issue by miroslavaivanova** [telerik/nativescript-ui-feedback#423]
### Tell us about the problem
Build SDK in release and open Chart\Interaction\Pie chart selection. You will see only the legend, the Pie chart is missing

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:next
- **CLI:next
- **Cross-platform modules:next
- **Runtime(s):next

**Comment by tsonevn** [comment]
The same scenario is reproduced for `ScatterBubbleSeries`. the Bubble series will not be rendered while the app is built for release. I am attaching sample project, which could be used for debugging.
![a6010lrx22gntsonev11292017103633](https://user-images.githubusercontent.com/17448734/33365744-db2a298a-d4f1-11e7-8824-284009d721ad.png)
[Archive.zip](https://github.com/telerik/nativescript-ui-feedback/files/1513030/Archive.zip)


t.1142448
