### ISSUE TITLE
RadListView Angular - loadMoreDataRequested crashes the app when is used with itemSelected in iOS

### ISSUE THREAD

**Issue by isaacfi** [telerik/nativescript-ui-feedback#429]
I'm trying to use the itemSelected and loadMoreDataRequested behavior of the RadListView but when I click at "Load More" it crashes the application only in iOS. You can reproduce it using the example code: [Nativescript UI Angular Samples](https://www.github.com/telerik/nativescript-ui-samples-angular) and doing the next:

1. Edit the nativescript-ui-samples-angular/sdkAngular/app/listview/load-on-demand/listview-load-on-demand.component.html adding the itemSelected and the selectionBehavior attributes:

`<RadListView [items]="dataItems" loadOnDemandMode="Manual" (loadMoreDataRequested)="onLoadMoreItemsRequested($event)"
    selectionBehavior="Press" (itemSelected)="alertSelected($event)">`

2. Implement the method alertSelected in the nativescript-ui-samples-angular/sdkAngular/app/listview/load-on-demand/listview-load-on-demand.component.ts

`public alertSelected(args: ListViewEventData) {`
`       var that = new WeakRef(this);`
`        let item = that.get()._dataItems.getItem(args.index);`
`        alert(JSON.stringify(item));`
`}`

This is the log:

1   0x10f83cd4b NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
2   0x10fee028e ffi_closure_unix64_inner
3   0x10fee0bd2 ffi_closure_unix64
4   0x11381dc5f -[UICollectionView _selectItemAtIndexPath:animated:scrollPosition:notifyDelegate:]
5   0x11384ac85 -[UICollectionView touchesEnded:withEvent:]
6   0x1118b4198 -[TKCollectionView touchesEnded:withEvent:]
7   0x112f8a7dd forwardTouchMethod
8   0x112f8a8a7 -[UIResponder touchesEnded:withEvent:]
9   0x11181e153 -[TKListViewCell touchesEnded:withEvent:]
10  0x1117f8591 -[TKListViewLoadOnDemandCell touchesEnded:withEvent:]
11  0x112f8a7dd forwardTouchMethod
12  0x112f8a8a7 -[UIResponder touchesEnded:withEvent:]
13  0x112f8a7dd forwardTouchMethod
14  0x112f8a8a7 -[UIResponder touchesEnded:withEvent:]
15  0x112f8a7dd forwardTouchMethod
16  0x112f8a8a7 -[UIResponder touchesEnded:withEvent:]
17  0x1133461a5 _UIGestureEnvironmentSortAndSendDelayedTouches
18  0x113340045 _UIGestureEnvironmentUpdate
19  0x11333fa17 -[UIGestureEnvironment _deliverEvent:toGestureRecognizers:usingBlock:]
20  0x11333eac3 -[UIGestureEnvironment _updateGesturesForEvent:window:]
21  0x112dd42c8 -[UIWindow sendEvent:]
22  0x112d77e36 -[UIApplication sendEvent:]
23  0x1136ba434 __dispatchPreprocessedEventFromEventQueue
24  0x1136bd089 __handleEventQueueInternal
25  0x114f76231 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
26  0x115015e41 __CFRunLoopDoSource0
27  0x114f5ab49 __CFRunLoopDoSources0
28  0x114f5a12f __CFRunLoopRun
29  0x114f599b9 CFRunLoopRunSpecific
30  0x1164899c6 GSEventRunModal
31  0x112d5b5e8 UIApplicationMain
file:///app/tns_modules/nativescript-pro-ui/listview/listview.js:820:90: JS ERROR Error: Item must be an object from the currently assigned source.

These are the steps:

1. Open the application.
2. Go to ListView/Load on Demand
3. Click at Load More button at the end of the List

- **CLI:** 3.3.1
- **Cross-platform modules:** 3.3.0
- **Runtime(s):** tns-ios 3.3.0

**Comment by isaacfi** [comment]
I found a Workaround, I used the itemTap instead of the itemSelected event

`<RadListView [items]="dataItems" loadOnDemandMode="Manual" (loadMoreDataRequested)="onLoadMoreItemsRequested($event)" (itemTap)="alertSelected($event)">`

**Comment by tsonevn** [comment]
Hi @isaacfi,
Thank you for reporting this issue. 
I tested the described scenario on my side and indeed this is a real issue while using load on demand functionality and itemSelected event.
