### ISSUE TITLE
Day view calendar - setting selectedDate doesn't work

### ISSUE THREAD

**Issue by shabib3** [telerik/nativescript-ui-feedback#438]
Hey guys! :)

I am trying to create a behaviour that the user sees a month view calendar and when he presses any date, the calendar view would change to Day view mode in the same date he clicked.
so the code I am running is this:
HTML:
```
<RadCalendar #calendar [viewMode]="viewMode" [eventSource]="events" (dateSelected)="onDateSelected($event)"></RadCalendar>
```

TS file:
```
public onDateSelected(args: CalendarSelectionEventData) {
    const calendar: RadCalendar = this.radCalendar.nativeElement;

    if (calendar.viewMode == "Month") {
        calendar.viewMode = "Day";
        calendar.selectedDate = args.date;
    }
}
```

there issue is that the dynamic setting of selectedDate seems to work but not completely, the upper weekly calendar section of the Day view change but the day content does not update...

Thanks a lot :)

**Comment by tsonevn** [comment]
Hi @shabib3,
Thank you for reporting this issue. 
I tested this case on my side and indeed the `ViewModel` will be changed, however, the event list will not be loaded. Regarding that, I will log this as a bug and for further info, you could keep track on the issue.

**Comment by tsonevn** [comment]
Hi @shabib3,
We investigated further this behavior and found that actually, this is not a bug. To be able to show the date's event you should also set up the `displayedDate` property, which will trigger the Event List to be refreshed. For example:
HTML
```
<RadCalendar #calendar viewMode="Month" [eventSource]="eventSource" (dateSelected)="onDateSelected($event)"></RadCalendar>
```
TypeScript 
```
public onDateSelected(args: CalendarSelectionEventData) {
        const calendar: RadCalendar = <RadCalendar>args.object;
       
        if (calendar.viewMode == "Month") {
            calendar.viewMode = "Day";
            calendar.selectedDate = args.date;
            calendar.displayedDate = args.date;
        }
    }
```
Let me know if I could assists you further.

**Comment by shabib3** [comment]
@tsonevn - Works like magic! Thanks a lot! :)
