### ISSUE TITLE
RadChart SplineAreaSeries not translucent on Android

### ISSUE THREAD

**Issue by rdlauer** [telerik/nativescript-ui-feedback#439]
### Tell us about the problem
When using `SplineAreaSeries` with multiple series on Android, the fill color is not completely translucent. This leads to one series hiding the other.

### Which platform(s) does your issue occur on?
Android only. iOS looks great. **Examples:**

Android:
![screen shot 2017-12-06 at 3 03 59 pm](https://user-images.githubusercontent.com/1918280/33685443-3a780dc6-da97-11e7-80d5-ed9a1594ce58.png)

iOS:
![screen shot 2017-12-06 at 3 04 07 pm](https://user-images.githubusercontent.com/1918280/33685453-4144cd74-da97-11e7-8b07-69e97a17b5f3.png)

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 3.2.0
- **CLI:** 3.3.1
- **Cross-platform modules:** 3.3.0
- **Runtime(s):** 3.3.0

**Comment by tsonevn** [comment]
Hi @rdlauer,
I tested this scenario on my side on Android API level 23 and 26, however, the SplineAreaSeries seems to be rendered with some transparency. I am attaching screenshots from the devices and the sample code, which I used for testing.
XML
```
<navigation:ExamplePage xmlns:navigation="navigation/example-page" loaded="onPageLoaded" xmlns:chart="nativescript-pro-ui/chart" xmlns="http://www.nativescript.org/tns.xsd">
    <chart:RadCartesianChart id="cartesianChart">
        <chart:RadCartesianChart.series>
            <chart:SplineAreaSeries items="{{ categoricalSource }}" categoryProperty="Country" valueProperty="Amount">
                <chart:SplineAreaSeries.horizontalAxis>
                    <chart:CategoricalAxis/>
                </chart:SplineAreaSeries.horizontalAxis>
                <chart:SplineAreaSeries.verticalAxis>
                    <chart:LinearAxis/>
                </chart:SplineAreaSeries.verticalAxis>
            </chart:SplineAreaSeries>
            <chart:SplineAreaSeries items="{{ categoricalSource2 }}" categoryProperty="Country" valueProperty="Amount">
                <chart:SplineAreaSeries.horizontalAxis>
                    <chart:CategoricalAxis/>
                </chart:SplineAreaSeries.horizontalAxis>
                <chart:SplineAreaSeries.verticalAxis>
                    <chart:LinearAxis/>
                </chart:SplineAreaSeries.verticalAxis>
            </chart:SplineAreaSeries>
        </chart:RadCartesianChart.series>
    </chart:RadCartesianChart>
</navigation:ExamplePage>
```
TypeScript
```
import {ObservableArray} from "data/observable-array"
import {Observable, fromObjectRecursive} from "data/observable"

export function onPageLoaded(args){
    var page = args.object;
    var array1 = new ObservableArray([
        { Country: "Germany", Amount: 15, SecondVal: 14, ThirdVal: 24 },
        { Country: "France", Amount: 13, SecondVal: 23, ThirdVal: 25 },
        { Country: "Bulgaria", Amount: 24, SecondVal: 17, ThirdVal: 23 },
        { Country: "Spain", Amount: 11, SecondVal: 19, ThirdVal: 24 },
        { Country: "USA", Amount: 18, SecondVal: 8, ThirdVal: 21 }
    ]);
    var array2 = new ObservableArray([
        { Country: "Germany", Amount: 29, SecondVal: 14, ThirdVal: 24 },
        { Country: "France", Amount: 32, SecondVal: 23, ThirdVal: 25 },
        { Country: "Bulgaria", Amount: 33, SecondVal: 17, ThirdVal: 23 },
        { Country: "Spain", Amount: 28, SecondVal: 19, ThirdVal: 24 },
        { Country: "USA", Amount: 22, SecondVal: 8, ThirdVal: 21 }
    ]);
    
    page.bindingContext = fromObjectRecursive({categoricalSource:array1, categoricalSource2:array2});
}
```
Regarding that, could you provide some more info about device or simulator and sample project, which could be debugged locally?
![screen shot 2017-12-11 at 3 55 00 pm](https://user-images.githubusercontent.com/17448734/33834543-efca899a-de8b-11e7-86ba-009d73eb2879.png)
![angleropr6 170623 019ntsonev12112017155545](https://user-images.githubusercontent.com/17448734/33834559-ffd95b9a-de8b-11e7-8b85-b0bf36eeb721.png)

**Comment by rdlauer** [comment]
My apologies - it looks like my test case had values that were so close to each other that you couldn't make out the other series. I've re-tested on emulators with API 24 and 26 and do see better colors for that green at least!
