### ISSUE TITLE
[bug] RadSideDrawer, Nativescript, Angular2, Webpack error Unexpected value 'SIDEDRAWER_DIRECTIVES' declared by the module

### ISSUE THREAD

**Issue by newapx** [telerik/nativescript-ui-feedback#44]
I used plugin `nativescript-dev-webpack` and got a error
`Error: Unexpected value 'SIDEDRAWER_DIRECTIVES' declared by the module 'AppModule'`  
in `\node_modules\@angular\compiler\bundles\compiler.umd.js:14722:29`

Here is a link to issue
https://github.com/NativeScript/nativescript-dev-webpack/issues/31

Link to the project
https://github.com/newapx/nativescipt.sidedraw-webpack

**Comment by VladimirAmiorkov** [comment]
Hi @newapx ,

We are aware of this issue and we are doing our best to resolve it and make the fix publicly available  as soon as possible. Stay tuned.

**Comment by imaginationcoder** [comment]
Same here:
`ERROR in Unexpected value 'SIDEDRAWER_DIRECTIVES' declared by the module 'AppModule'`
My 'app.module.ts' includes below
`import {SIDEDRAWER_DIRECTIVES} from "nativescript-telerik-ui/sidedrawer/angular";`
and 
@NgModule 
    ```
declarations: [
        SIDEDRAWER_DIRECTIVES,
        AppComponent 
    ]

```
Can any one please help me here to resolve the issue when using 'nativescript-dev-webpack'

**Comment by VladimirAmiorkov** [comment]
@imaginationcoder Please read [my response](https://github.com/NativeScript/nativescript-dev-webpack/issues/31#issuecomment-271838184) from the other thread you wrote in about this.

**Comment by imaginationcoder** [comment]
@VladimirAmiorkov very thanks for your quick response.
