### ISSUE TITLE
Enable property filteredItems on Android

### ISSUE THREAD

**Issue by NickIliev** [telerik/nativescript-ui-feedback#445]
### Tell us about the problem
te.
Accessing the `filteredItems` property for RadAutocompleteTextView is returning a result on iOS but is not working on Android (always returning a length of 0). 

**Feature request** -make `filteredItems` applicable for both platforms

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:

[Release branch ](https://github.com/telerik/nativescript-ui-samples-angular)for nativescript-ui-samples-angular

### Please tell us how to recreate the issue in as much detail as possible.

- Use [this example](https://github.com/telerik/nativescript-ui-samples-angular/blob/release/sdkAngular/app/autocomplete/events/autocomplete-events.component.ts)

- Introduce the following snippet in the code behind
```
public onSuggestionViewBecameVisible(args) {
    console.log("onSuggestionViewBecameVisible");

    let radAutoComplete = args.object;
    let shownItems = radAutoComplete.filteredItems;
    console.log("shownItems.length: " + shownItems.length); // works on iOS - enable for Android as currently always returing 0
}
```

- Start the application and navigate to AutoComplete >> Events and start typing to show the suggestion view and trigger the `onSuggestionViewBecameVisible` callback.

**Comment by zbranzov** [comment]
The feature is released in nativescript-ui-autocomplete@3.8.0
