### ISSUE TITLE
[4] Migrate to 4.0 (Nested Frames)

### ISSUE THREAD

**Issue by radeva** [telerik/nativescript-ui-feedback#449]

**Comment by VladimirAmiorkov** [comment]
Migrated SDK examples here: https://github.com/telerik/nativescript-ui-samples/pull/196

**Comment by VladimirAmiorkov** [comment]
PR that contains support of 4.0 for the Pro UI plugin can be found here: https://github.com/telerik/nativescript-ui/pull/1285

**Comment by VladimirAmiorkov** [comment]
SDK Angular migration is still under development and we are waiting on any information from the modules and nativescript-angular  teams when they have something ready for us to migrate to.

**Comment by zbranzov** [comment]
Ac:
- sdk, sdkAngular and split sidedrawer samples should support sidedrawer as root e.g. both should have sidedrawer starting from root level.
- OverNavigation property should be omitted
- Root sidedrawer should be working on application.run()
- Sidedrawer as a root should have main content set to frame: 
 <nsDrawer:RadSideDrawer.mainContent>
       <Frame defaultPage="./navigation/main-content-page"></Frame>
    </nsDrawer:RadSideDrawer.mainContent>
- Non root sidedrawer should preserve current behavior
- If you have root and non root, the root one should be accessible from the action bar (swipe)
- the root should be visible over the action bar and non root one under.
- on iPhone X drawer content first child  background should be visible under save area but the actual content like text/drawer items shouldn't
- documentation about the new sidedrawer should be available.

**Comment by VladimirAmiorkov** [comment]
- sdkAngular and split sidedrawer samples should support sidedrawer as root e.g. both should have sidedrawer starting from root level. (DELAYED due to tns-core-modules and nativescript-angular later release)

- 3.5.1 (current) should work with NativeScript 4.0.0

**Comment by VladimirAmiorkov** [comment]
PR in split plugin https://github.com/NativeScript/nativescript-ui-sidedrawer/pull/7

**Comment by VladimirAmiorkov** [comment]
PR for the RadSideDrawer to be a root of the "non split" Angular demo:
https://github.com/telerik/nativescript-ui-samples-angular/tree/amiorkov/migration-4.0
