### ISSUE TITLE
Feature request: RadCalendar `InlineEventCellStyle`, `monthViewStyle`,  `CalendarMonthviewStyle` support for NativeScript Angular 2

### ISSUE THREAD

**Issue by tsonevn** [telerik/nativescript-ui-feedback#45]
`InlineEventCellStyle`, `monthViewStyle`,  `CalendarMonthviewStyle` could not be used for styling the inline event in NativeScirpt Angular 2 project on both iOS and Android. 

At the moment those styling properties could be used only on [non-Angular project](https://github.com/telerik/nativescript-ui-samples/blob/3ca4254f91d6cc2b44972a8ff2f94d177ee083ff/sdk/app/calendar/cell-styling/cell-styles.xml).

**Comment by tsonevn** [comment]
Those styling approaches seem to be already supported by NS Angular projects.
https://github.com/telerik/nativescript-ui-samples-angular/blob/f504d2a3294d971bc49f2f84a5eaca4b9f9f3e7f/sdkAngular/app/calendar/calendar-styles.service.ts
https://github.com/telerik/nativescript-ui-samples-angular/blob/f504d2a3294d971bc49f2f84a5eaca4b9f9f3e7f/sdkAngular/app/calendar/cell-styling/calendar-cell-styling.component.ts

**Comment by beanian** [comment]
@tsonevn The links you provided do not explain how to style InlineEventCellStyle.

using the `[inlineEventCellStyle]="inlineEventCellStyle"` on the RadCalendar control itself or setting it via typescript `this._calendar.nativeElement.inlineEventCellStyle = this.inlineEventCellStyle; `does not work.
I cannot see any way to style inline events using Angular
