### ISSUE TITLE
RadSideDrawer is sluggish when you open/close it slowly

### ISSUE THREAD

**Issue by shiv19** [telerik/nativescript-ui-feedback#465]
When you try to slide out RadSideDrawer slowly, it doesn't open smoothly. There is a jagged effect. 
Steps to reproduce,
Open rad side drawer slowly on any platform and any device.

**Comment by tsonevn** [comment]
Hi @shiv19,
I tested your case with [nativescript-ui-samples](https://github.com/telerik/nativescript-ui-samples) application and was able to recreate similar issue only on Android. For your convenience, I am attaching a video file. 
Regarding that, it would help if you provide some more info about reproducing this case on iOS.
[hammerheadKTU84Pntsonev12182017115705.mp4.zip](https://github.com/telerik/nativescript-ui-feedback/files/1567379/hammerheadKTU84Pntsonev12182017115705.mp4.zip)

**Comment by shiv19** [comment]
[ios-radsidedrawer.zip](https://github.com/telerik/nativescript-ui-feedback/files/1567419/ios-radsidedrawer.zip)
This is for iOS.
It is not as noticeable as in Android though.

**Comment by zbranzov** [comment]
The fix is released in v3.5.1 of nativescript-ui-sidedrawer
