### ISSUE TITLE
Angular 5 - RadListView Error

### ISSUE THREAD

**Issue by mxth** [telerik/nativescript-ui-feedback#468]
### Tell us about the problem
RadListView error after updating `nativescript-angular` to version 5

`CONSOLE ERROR [native code]: ERROR TypeError: this._trackByFn is not a function. (In 'this._trackByFn(index_1, item)', 'this._trackByFn' is an instance of ViewRef_)`

### Which platform(s) does your issue occur on?
_iOS/Android_

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 3.2.0
- **CLI:** 3.4.0
- **Cross-platform modules:** 3.4.0
- **Runtime(s):** 3.4.0

### Please tell us how to recreate the issue in as much detail as possible.
Use the RadListView with newest nativescript-angular

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
See [this link](https://www.lucidchart.com/techblog/2017/04/20/removing-roadblocks-move-angular-4/) for the fix

**Comment by NickIliev** [comment]
@mxth nativescript-pro-ui@next is compatible with Angular 5. 
For testing purposes you can install the next version as follows:

```
rm -rf platforms
npm i nativescript-pro-ui@next --save
tns run ios
```

The official release of nativescript-pro-ui is expected any moment now so stay tuned.
