### ISSUE TITLE
Remove Zebra-Stripe on LineSeries for iOS

### ISSUE THREAD

**Issue by peterkrieg** [telerik/nativescript-ui-feedback#472]
Default styling for iOS `LineSeries` is zebra-stripes, shown below (image taken from [this nativescript blog post](https://www.nativescript.org/blog/a-deep-dive-into-telerik-ui-for-nativescript-s-charts)).

<hr>

<img width="865" alt="screen shot 2018-01-03 at 2 02 35 pm" src="https://user-images.githubusercontent.com/7385488/34535157-1eec106c-f08f-11e7-8755-084f35f1b8ba.png">

<hr>

Is there anyway to remove the alternating white/gray stripes ("zebra stripes") on iOS, and just make it a solid background like on Android?

**Comment by tsonevn** [comment]
Hi @peterkrieg,
At this time similar functionality does not exist for the Chart component. I will log this as a new feature and for further info, I would suggest keeping track on the issue.

**Comment by tgpetrov** [comment]
@peterkrieg You can now use the Grid styling options as demonstrated [here](https://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/Chart/Grid/styling#styling-grid) to hide the striped lines. Just set `horizontalLinesVisible`, `verticalLinesVisible`, `horizontalStripLinesVisible` and `verticalStripLinesVisible` all to `false`.
