### ISSUE TITLE
How to pass in regex pattern into TKRegExValidator dynamically?

### ISSUE THREAD

**Issue by yonghongren** [telerik/nativescript-ui-feedback#475]
I would like to pass in the regex pattern into TKRegExValidator through a variable, but it will never match. For an example, the following changes a line in nativescript-ui-samples-angular to use interpolation like this regEx="{{regEx}}" and it won't match:

```
index dfd932c..5ee4501 100644
--- a/sdkAngular/app/dataform/validation/dataform-validation.component.html
+++ b/sdkAngular/app/dataform/validation/dataform-validation.component.html
@@ -27,7 +27,7 @@
    </TKEntityProperty>
    <!-- >> angular-dataform-validation-regex-html -->
    <TKEntityProperty tkDataFormProperty name="pin" displayName="Enter PIN" index="5">
-       <TKRegExValidator tkEntityPropertyValidators regEx="\d{4}" errorMessage="PIN number should contain 4 digits."></TKRegExValidator>
+       <TKRegExValidator tkEntityPropertyValidators regEx="{{regEx}}" errorMessage="PIN number should contain 4 digits."></TKRegExValidator>
    </TKEntityProperty>
    <!-- << angular-dataform-validation-regex-html -->
    <TKEntityProperty tkDataFormProperty name="agreeTerms" displayName="I agree with terms" index="6">
```
Where regEx is set to `\d{4}'

Is it possible to do this? If so, what's the correct way?  This ability could be quite useful. For example, to validate phone numbers of different countries, different patterns could be passed in based on device.region.

Using:
   "nativescript-pro-ui": "3.2.0",
    "tns-core-modules": "3.3.0",

**Comment by tsonevn** [comment]
Hi @yonghongren,
In case you need to add regEx to the validator dynamically you could use JSON Metadata and to define the needed validation as it is shown [here ](http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/DataForm/Validation/dataform-validation-overview#json-metadata)in the docs.

**Comment by yonghongren** [comment]
Hi @tsonevn, That is a great suggestion. Thank you very much.
