### ISSUE TITLE
RadDataForm: How to set minDate n maxDate for the datePicker editor  

### ISSUE THREAD

**Issue by mhmo91** [telerik/nativescript-ui-feedback#478]

**Comment by mhmo91** [comment]
another question, i'm trying to set the datePicker editor with an initial value as the documentation says "yyyy-DD-MM" but it just doesn't work, if u can elaborate or share an example on that would be grateful

**Comment by mhmo91** [comment]
According to the documentation, the date model should be like "2018-02-11" which works for forms using html, but when i use json style form, it doesn't work and after hours of trials, i figured out that i have to pass it as an integer representing time in milliseconds, and even in both cases the value of the date displayed is incorrect, for year 2017 it display 07 and for the year 2018 it displays 05!!!
![image](https://user-images.githubusercontent.com/3815200/34875694-074c757c-f7a7-11e7-829d-89eb5be42a7a.png)

**Comment by mhmo91** [comment]
https://github.com/telerik/nativescript-ui-feedback/issues/480

**Comment by NickIliev** [comment]
Closing as solved in [Closing as solved in [https://github.com/telerik/nativescript-ui-feedback/issues/480#issuecomment-357269774](https://github.com/telerik/nativescript-ui-feedback/issues/480#issuecomment-357269774)](Closing as solved in [https://github.com/telerik/nativescript-ui-feedback/issues/480#issuecomment-357269774](https://github.com/telerik/nativescript-ui-feedback/issues/480#issuecomment-357269774))
