### ISSUE TITLE
RadCalendar: Can not swipe between months when selectionMode=“Range”

### ISSUE THREAD

**Issue by relvis** [telerik/nativescript-ui-feedback#484]
Hi there, I am trying to get a RadCalendar Range done but I can not switch between months, seems like when the `selectionMode="Range"` is set I can not navigate between months for multiple month selection range. Does anyone has a working example or the swipe gestures are disabled when the Range mode is enabled?

This is my RadCalendar widget:

`<RadCalendar viewMode="Month" selectionMode="Range" (dateSelected)="onDateSelected($event)"></RadCalendar>`

Thanks…

**Comment by tsonevn** [comment]
Hi @relvis,
Thank you for contacting us.
I tested your case, however, was unable to reproduce the similar issue for Android. You could review the attached GIF file.
![screencast 2018-01-18 at 11 00 47 am](https://user-images.githubusercontent.com/17448734/35089226-f8ea4986-fc3e-11e7-820a-9df8c31b53ef.gif)

Also, keep in mind that in iOS changing the viewMode from a month to multiple months should be done via code behind manually.

**Comment by kaspervm** [comment]
We are still having this problem in Ios you cannot apply a range and be able to go to the next month.
