### ISSUE TITLE
RadListView gave a 'extend of undefined' error

### ISSUE THREAD

**Issue by karl-ford** [telerik/nativescript-ui-feedback#493]
> Hi there, I am trying to use RadListView in my demo. The issue occured when the code was livesyncing.

### Android

- Progress NativeScript UI version: ^3.3.0
- CLI: 3.4.1
- Cross-platform modules: ~3.4.0
- Runtime(s): 3.4.1

1. Start the application
2. add the nativescript-pro-ui through `tns add plugin nativescript-pro-ui`
2. import NativeScriptUIListViewModule in app.module.ts
2. use RadListView in html
2. run `tns debug android`
![image](https://user-images.githubusercontent.com/7666278/35081780-10caa5ac-fc51-11e7-90ea-a65d6be22a96.png)
items.component.html
![image](https://user-images.githubusercontent.com/7666278/35081936-e96ba60e-fc51-11e7-92f6-ff3b6dcb61d8.png)

**Comment by NickIliev** [comment]
Hey, @karl-ford I tried to reproduce the issue using [this demo app](https://github.com/NickIliev/NS-Issues-2018/tree/master/nativescript-ui-feedback/issue_493) but to no avail.

Can you provide a sample project or a [Playground demo](https://play.nativescript.org/) that can reproduce the issue so we could investigate further

**Comment by karl-ford** [comment]
The whole project is here : [Practice APP](https://1drv.ms/u/s!AvO-F0w5iqVylW67GBLEwSP_uJrJ)
I ran it on windows 8.1
Sorry for can't provice a Playground demo, because I am been blocked by the GFW

**Comment by NickIliev** [comment]
@karl-ford as you are using Rxjs Observable which loads the data items async I have just introduced the `async` pipe in the `RadListView` and the app worked as expected.
```
<RadListView [items]='items | async'>
```

**Comment by karl-ford** [comment]
Thanks @NickIliev! I've solved the issue when I updated my nativescript. 
I updated it from 3.4.1 to 3.4.2
However, I still don't know what caused the issue.

**Comment by coderaven** [comment]
These errors usually happen when nativescript cli failed to properly add plugin data to platforms folder (when you do a tns plugin install), to correct:
- tns platform remove <ios or android>
- tns platform add <ios or android>
- tns install
- tns run <ios or android>

That solved for me most any ui undefined errors :)

> Thanks @NickIliev! I've solved the issue when I updated my nativescript.
> I updated it from 3.4.1 to 3.4.2
> However, I still don't know what caused the issue.
