### ISSUE TITLE
circle decorator for selected date

### ISSUE THREAD

**Issue by zoeitsolutions** [telerik/nativescript-ui-feedback#50]
<img width="372" alt="screen shot 2017-01-21 at 12 44 08 pm" src="https://cloud.githubusercontent.com/assets/4047916/22173875/cb6e8faa-dfd7-11e6-9eec-6bfffc650781.png">

Hi, I am using the RadCalendar with my typescript/angular project. I have used the style service to change the background colour of the calendar, but I now want to change the color of selected date "dot" to white.

I have tried different style properties for the selected date, but I can't get it right.

Is this possible?

**Comment by PetyaSotirova** [comment]
A possible approach to achieve this in Android is available in this forum thread: http://www.telerik.com/forums/selected-date.
On iOS circular selection is the default behavior but it is stripped when one of the other styling options for the calendar is specified.
Users should be able to specify desired selection shape in the calendar.

**Comment by zoeitsolutions** [comment]
@PetyaSotirova I need this for iOS. Can this be labeled as a bug which requires fixing?

**Comment by PetyaSotirova** [comment]
@zoeitsolutions I would call it a limitation as it seems like a little bit of both to me. 

Regardless of how we label it, @ginev  is already working on it so if everything goes according to plan, we should have this available in the next release.

**Comment by cindy-m** [comment]
What is the state of it? Because want also to change the color of the circular selection for iOS according to whole design of the app.

**Comment by ginev** [comment]
@cindy-m, @zoeitsolutions - this limitation has now been resolved and will be available in the NS UI 3.0 release due to a couple of days.

**Comment by zoeitsolutions** [comment]
Thank you.

**Comment by ginev** [comment]
@zoeitsolutions - we also have another major initiative to align the styles of the way calendar looks on Android and iOS. If you have any further feedback, do let us know so that we act accordingly.

**Comment by zoeitsolutions** [comment]
@ginev  - ok so that will also be available in the next release? will test and give feedback thanks.

**Comment by ginev** [comment]
@zoeitsolutions - that is most probably due to the next iteration which is to be out around the beginning of August.

**Comment by tsonevn** [comment]
This feature is already available in UI for NativeScript - http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/Calendar/Styling/month-view
