### ISSUE TITLE
RadSideDrawer + GridLayout: More than one layout child inside a ContentView [IOS]

### ISSUE THREAD

**Issue by pvcoelho** [telerik/nativescript-ui-feedback#503]
Having inside the component's .html file both RadSideDrawer and GridLayout elements, when trying to run the app in IOS, it fails with the following error:
**More than one layout child inside a ContentView**
Although in Android everything runs fine.

- **Progress NativeScript UI version:** "^3.2.0"
- **CLI:** 4.0.0-2018-01-15-10407
- **Cross-platform modules:** "^4.0.0-2018-01-08-02"
- **Runtime(s):** `"tns-ios"`: "4.0.0-2018-01-17-01"

**Code files:**

**items.component.html:**

[items.component.html.txt](https://github.com/telerik/nativescript-ui-feedback/files/1667675/items.component.html.txt)

**items.component.ts:**

[items.component.ts.txt](https://github.com/telerik/nativescript-ui-feedback/files/1667677/items.component.ts.txt)

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/NativeScript#5350
