### ISSUE TITLE
RadSideDrawer + {N} 4.0: CSS file not respected when using RadSideDrawer as a root element

### ISSUE THREAD

**Issue by ADjenkov** [telerik/nativescript-ui-feedback#507]
The css file fails to apply styles when RadSideDrawer is used as a root view element (wrapping RadSideView inside some layout `<GridLayout>` works) .

See [this test app](https://github.com/ADjenkov/nestedFramesTest1) for reference.

**Comment by ADjenkov** [comment]
Discussed with @VladimirAmiorkov

**Comment by VladimirAmiorkov** [comment]
Waiting on a PR merge in the tns-core-modules that resolves this issue: https://github.com/NativeScript/NativeScript/pull/5466
