### ISSUE TITLE
Screen frozen on sidedrawer selection and navigation with transition (iOS)

### ISSUE THREAD

**Issue by erjdriver** [telerik/nativescript-ui-feedback#51]
I've got 2 pages - a sidedrawer menu option on both pages allows the user to flip between the two.

On the newly navigated-to page, all taps are inactive. I've got to gesture open the sidedrawer and then everything works - until the next time I flip to the other page.

Here's the code

        var page_def =
        {
            moduleName: "page2",
            animated: true,
            clearHistory: true,
            transition:
            {
                name: "flipRight",
                duration: 400,
                curve: "easeOut"
            }
        };
        //(<drawerModule.RadSideDrawer(frameModule.topmost().getViewById("sideDrawer"))).closeDrawer();

        frameModule.topmost().navigate( page_def );
    }`

If I comment out the transition part of the page_def - then everything works as normal.

I also tried closing the drawer before nav - but that didn't help (commented out above).

This is with {N} 2.5 and telerik-ui 1.6 and under iOS only - this problem was present in earlier versions also.

**Comment by tsonevn** [comment]
Hi @erjdriver, 
Are you still able to recreate the issue while using latest NativeScript 3.3 and NativeScript UI version 3.2.
Let me know if I could assist you further.

**Comment by erjdriver** [comment]
I  think it's working with NS 3.3 now - I'm still using the old nativescript ui.
