### ISSUE TITLE
AutoCompleteInline in RadDataForm triggers propertyCommitted on init with empty value

### ISSUE THREAD

**Issue by wendt88** [telerik/nativescript-ui-feedback#524]
trying sample: https://github.com/telerik/nativescript-ui-samples-angular under "DataForm" -> "Editors" -> "AutoComplete"
AutoCompleteInline editor with `autoCompleteDisplayMode="tokens"` triggers the `propertyCommitted` event of its `RadDataForm`, but `args.entityProperty.value` is an empty array, also on clicking "Check values"

**Comment by tsonevn** [comment]
Hi @wendt88,
Thank you for contacting us.
I was able to recreate this issue only on Android, for it seems to work as expected. Is this correct or you can recreate the problem on iOS as well?

**Comment by wendt88** [comment]
on iOS works fine, thats right

**Comment by tgpetrov** [comment]
This issue is a duplicate of [this issue](https://github.com/telerik/nativescript-ui-feedback/issues/738).
