### ISSUE TITLE
[Feature request] Ability to create custom EntityProperty validator 

### ISSUE THREAD

**Issue by tsonevn** [telerik/nativescript-ui-feedback#53]
At the moment, it is possible to use only the available `EntityProperty` validators

* NonEmptyValidator 
* RangeValidator 
* MinimumLengthValidator 
* MaximumLengthValidator 
* EmailValidator 
* PhoneValidator

 and it is not possible to create a custom one.

**Comment by Natalia-Hristova** [comment]
Available in latest version 3.1.0. Here's the [documentation](http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/DataForm/Validation/dataform-validation-custom).
