### ISSUE TITLE
RadListView, setting custom group template

### ISSUE THREAD

**Issue by darxmac** [telerik/nativescript-ui-feedback#531]
Is there a way to change the template for the group headers in RadListView when using [groupingFunction]

http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/ListView/data-operations#grouping

On iOS we can force a template by setting `defaultGroupTemplate` on the RadListView object, but this does not work on Android.

```typescript
    private _listView : any;
    ngOnInit() {
        this._listView = this.myListViewComponent.listView;
        this._listView.defaultGroupTemplate = "<Label text='{{ category }}' height='50' backgroundColor='red' paddingLeft='15'></Label>";
        this._dataItems = new ObservableArray(this._dataItemService.getDataOperationsItems());
    }
```

**Comment by NickIliev** [comment]
@darxmac indeed at this very moment setting group templates is not officially supported and this is the reason the property `defaultGroupTemplate` is only available on iOS and is not public property.

Our developers have plans for extending the group template logic and provide support for both Android and iOS so stay tuned - all updates on that matter will be posted here and in the plugin's roadmap.

**Comment by VladimirAmiorkov** [comment]
Proposed API for next version about this feature:

- Expose new settable template in both iOS and Android: 
In Angular settable via ng-tample with a custom inline directive "tkGroupTemplate"
```
<ng-template tkGroupTemplate let-category="category">
    <StackLayout id="groupStack">
        <Label class="nameLabel" [text]="category" class="groupLabel"></Label>
    </StackLayout>
</ng-template>
```

In Vanila {N} settable via the groupTemplate property:
<lv:RadListView.groupTemplate>
    <GridLayout>
        <Label text="{{ category }}" class="groupLabel"/>
    </GridLayout>
</lv:RadListView.groupTemplate>

**Comment by tigrenok00** [comment]
Hi, what is the status of this feature request? Thanks!

**Comment by DimitarTodorov** [comment]
Hi @tigrenok00 , 

This is impleneted in nativescript-ui-listview since version [3.5.3](https://github.com/NativeScript/nativescript-ui-listview/releases/tag/v3.5.3)
You can update to the latest version of the plugin and use this feature.

Regards,
Dimitar

**Comment by tigrenok00** [comment]
@DimitarTodorov 
Hi, I'm happy to hear! Anywhere to see an example of how to define the template? I could not find an example in documentation so thought it hasn't been implemented yet.

`<ng-template tkListItemTemplate let-item="item">` --> how this row should look?

**Comment by tigrenok00** [comment]
@DimitarTodorov 
I was able to find an example of usage in some other issue, thanks!
How about sticky headers implementation, I saw a request from 2017 about both grouping and sticky group headers, was it implemented as well?

**Comment by Amol-U-Patil** [comment]
@NickIliev 
RadListView custom group filter but after use enableCollapsibleGroups="true" that time not work

[https://play.nativescript.org/?template=play-ng&id=KCpViw&v=18]

we have both required grouping collapsible and custom group filter how to solve issue

**Comment by Amol-U-Patil** [comment]
@NickIliev 
RadListView custom group filter but after use enableCollapsibleGroups="true" that time not work


[here example](https://play.nativescript.org/?template=play-ng&id=KCpViw&v=18)

we have both required grouping collapsible and custom group filter how to solve issue

**Comment by mandar-bhong** [comment]
+1

**Comment by markusmauch** [comment]
As far as I can see, the binding context of the groupTemplate is the same as the binding context of the entire ListView. That makes no sense to me. Wouldn't it make more sense to bind the grouping header template to the return value of the grouping function or some other user defined function? For instance, how can one display a header that depends on the current group?
