### ISSUE TITLE
Vue.js support

### ISSUE THREAD

**Issue by radeva** [telerik/nativescript-ui-feedback#543]
Add wrappers for supporting Vue.js. 
Contact Vasil Trifonov for more details.

This issue is blocker for the Playground!

**Comment by VladimirAmiorkov** [comment]
PRs for VueJS support:
https://github.com/NativeScript/nativescript-ui-sidedrawer/pull/9
https://github.com/NativeScript/nativescript-ui-calendar/pull/6
https://github.com/NativeScript/nativescript-ui-chart/pull/4
https://github.com/NativeScript/nativescript-ui-gauge/pull/4
https://github.com/NativeScript/nativescript-ui-dataform/pull/6
https://github.com/NativeScript/nativescript-ui-autocomplete/pull/9

**Comment by robregonm** [comment]
+1

**Comment by VladimirAmiorkov** [comment]
@DimitarTodorov @zbranzov The above PRs have been updated to include a simple NativeScript Vue demo app. The app only shows in use cases due to an blocking issue with VueRouter not allowing us to fully implement all of our examples + app navigation.

**Comment by VladimirAmiorkov** [comment]
Wrote and made PR for the documentation: https://github.com/telerik/nativescript-ui-docs/pull/40
