### ISSUE TITLE
How can I hide non-current month dates?

### ISSUE THREAD

**Issue by garynhs** [telerik/nativescript-ui-feedback#545]
How can I hide those dates not in current month?

**Comment by NickIliev** [comment]
@garynhs I am not sure I understand what do you mean - can you provide more d3etails and perhaps code involved. Are we talking about RadCalendar in some view mode?

**Comment by nmongiya** [comment]
If I understand correctly, You want to hide the dates from previous month if they are visible for current month and sometime that may be confusing this user. For that I think you can use the styling and change the css for example if today;s date is 28th, you can change the background/foreground color of 29th 30th or 31st of the previous month
