### ISSUE TITLE
Calendar crashes in Year view mode

### ISSUE THREAD

**Issue by zbranzov** [telerik/nativescript-ui-feedback#548]
### Tell us about the problem
Scrolling in Year mode of calendar causes app to crash in iOS. https://screencast.com/t/3FpGOneE

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
nativescript-ui-calendar: 3.5
CLI: 3.4.2
Cross-platform modules: ~3.4.0
Runtime(s): 3.4.0

### Please tell us how to recreate the issue in as much detail as possible.
1. Open nativescript-ui-samples-angular app
2. Navigate to Calendar > View Modes.
3. Select 'Year' from the Options menu.
4. Scroll up.
5. App crashes https://screencast.com/t/3FpGOneE

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
nativescript-ui-samples-angular app

### ERROR
JavaScript error:
file:///app/tns_modules/nativescript-ui-calendar/ui-calendar.js:985:52: JS ERROR RangeError: Maximum call stack size exceeded.

**Comment by lini** [comment]
works in current (3.7.0) version of nativescript-ui-calendar
