### ISSUE TITLE
nataivescript-ui-samples: Remote data fetch demo doesn't work for Android

### ISSUE THREAD

**Issue by DimitarTodorov** [telerik/nativescript-ui-feedback#551]
Demo for async data fetch doesn't work for Android. Data is loading indefinitely.

**Comment by zbranzov** [comment]
It seems to work now (14.05)

**Comment by VladimirAmiorkov** [comment]
This issue is caused by and error in the http module, I logged it here: https://github.com/NativeScript/NativeScript/issues/5982

Also I reworked our example so that such issues cannot hit it with PR: https://github.com/NativeScript/nativescript-ui-autocomplete/pull/20
