### ISSUE TITLE
nativescript-ui-samples-angular: Remote data fetch demo doesn't work for iOS

### ISSUE THREAD

**Issue by DimitarTodorov** [telerik/nativescript-ui-feedback#552]
Demo for async data fetch doesn't work for iOS. Data is loading indefinitely. Console error is logged: 
NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9824)
CONSOLE ERROR file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:571:22: Error: Uncaught (in promise): undefined

**Comment by zbranzov** [comment]
I will raise the priority since we cannot make test for it.
