### ISSUE TITLE
 No example code or samples in Nativescript UI sample apps provided for DateTimeCategoricalAxis.

### ISSUE THREAD

**Issue by chuckmitchell** [telerik/nativescript-ui-feedback#553]
### Tell us about the problem

See the following sources of information, they are missing samples and the example app has no example for this type of chart. Any explanation is very minimal.

I'm specifically looking to use a scatter chart with a linear series but have trouble understanding the docs and my attempts have resulted in strange axis and data point/line behaviour.

http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/Chart/Axes/datetimecategorical#chart-axes-datetimecategoricalaxis
http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/Chart/Axes/datetimecategorical

**The Date axis examples only demonstrate DateTimeContinuousAxis**
https://github.com/telerik/nativescript-ui-samples-angular/tree/release/sdkAngular/app/chart/axes/date-time-axes
https://github.com/telerik/nativescript-ui-samples/tree/release/sdk/app/chart/axes/date-time-axes

### Which platform(s) does your issue occur on?
Both

**Comment by chuckmitchell** [comment]
To add more information, I cannot figure out how to create a scatter series using a DateTimeContinuousAxis or DateTimeCategoricalAxis for the horizontal axis and a LinearAxis for the verticalAxis.

**Comment by tgpetrov** [comment]
Hi @chuckmitchell 

The usage of DateTimeCategoricalAxis is demonstrated in the following examples:
[OHLC Series](https://github.com/telerik/nativescript-ui-samples-angular/blob/d98b5371644d1e34fa5506886dd0ea48b5d35ddb/chart/app/examples/series/financial/chart-series-ohlc.component.html)
[Candlestick Series](https://github.com/telerik/nativescript-ui-samples-angular/blob/d98b5371644d1e34fa5506886dd0ea48b5d35ddb/chart/app/examples/series/financial/chart-series-candlestick.component.html)
[Trackball](https://github.com/telerik/nativescript-ui-samples-angular/blob/d98b5371644d1e34fa5506886dd0ea48b5d35ddb/chart/app/examples/behaviors/chart-behaviors-trackball.component.html)

To your second question about plotting a Scatter Series with DateTimeContinuousAxis - it is not currently supported and this is stated in the article that [you have referenced](http://docs.telerik.com/devtools/nativescript-ui/api/classes/scatterseries.html). It starts with "NOTE: All scatter series are incompatible with all categorical axes". Here's [the list](https://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/Chart/Axes/axes#category-axes) with the category axes which includes both **DateTimeContinuousAxis** and **DateTimeCategoricalAxis**.

[Here's](https://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/Chart/Series/overview#cartesian-series) more information about the Cartesian Series. In short they are divided into two types: **Linear** and **Categorical**. The Linear Series require both axes to be of type LinearAxis (either **LinearAxis**, or **LogarithmicAxis**), while the Categorical Series require one of the axes to be CategoricalAxis (one of **CategoricalAxis**, **DateTimeCategoricalAxis** and **DateTimeContinuousAxis**)
