### ISSUE TITLE
Add shadow for the side drawer for iOS

### ISSUE THREAD

**Issue by tbozhikov** [telerik/nativescript-ui-feedback#557]
Add shadow for the side drawer for iOS to look like:

![ms0cpqvqbt2xcp4opis7s_ocfshc4tmbz1apk0dznmojffauu42n0a_9l_gbj1xi8wqs8ynkgqwmmto3xbhvrd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/5127806/36901883-5ed1b93c-1e31-11e8-8a63-51a05bd854d0.png)

**Comment by balachandran1988** [comment]
Need to add a custom solution for iOS. Could you please share your code here.

**Comment by tbozhikov** [comment]
closing this, will be implemented with #219
