### ISSUE TITLE
Calling `listView.getSelectedItems()` when filtering is enabled and active will not return the actual selected items

### ISSUE THREAD

**Issue by lini** [telerik/nativescript-ui-feedback#558]
### Tell us about the problem

Calling `listView.getSelectedItems()` when filtering is enabled and active will not return the actual selected items.

### Which platform(s) does your issue occur on?

iOS

### Please provide the following version numbers that your issue occurs with:

- **Progress NativeScript UI ListView version:** 3.5.0
- **CLI:** 3.4.2
- **Cross-platform modules:** 3.4.0
- **Runtime(s):** 3.4.0

### Please tell us how to recreate the issue in as much detail as possible.

1. Add a RadListView to a page.
2. Set the `filteringFunction` and `selectionBehavior` properties.
3. Make sure the filtering function will remove some of the items.
4. Select an item and then call  `listView.getSelectedItems()` from the code.
5. Verify that the selected item and the item returned from the call above are different

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

```XML
<RadListView [filteringFunction]="specialtyFilteringFunc" [items]="specialtyItems" selectionBehavior="Press" (itemSelected)="specialtySelected($event)">
...
</RadListView>
```

```TypeScript
    specialtySelected(args: ListViewEventData) {
        const selectedItems = args.object.getSelectedItems();
        // Wrong items returned here: selectedItems 
    }

    specialtyFilteringFunc(item: Specialty): boolean => {
         return item.specialty.indexOf('filtered') !== -1;
    };
```

**Comment by zbranzov** [comment]
Released in v3.5.1
