### ISSUE TITLE
RadListView - LoadOnDemand - iOS- Angular Bindings not working in tkListLoadOnDemandTemplate 

### ISSUE THREAD

**Issue by NickIliev** [telerik/nativescript-ui-feedback#56]
Using angular binding in tkListLoadOnDemandTemplate does not work.
e.g based on [this example](https://github.com/telerik/nativescript-ui-samples-angular/blob/release/sdkAngular/app/listview/load-on-demand/listview-load-on-demand.component.ios.html)

**_listview-load-on-demand.component.ios.html_**
```
<GridLayout *tkListLoadOnDemandTemplate class="loadOnDemandItemGridLayout">
   <Label [text]="loadMore" horizontalAlignment="center" verticalAlignment="center"></Label>
</GridLayout>
```

**_listview-load-on-demand.component.ts_**
```
public loadMore: string = "Load MORE Items";
```

Result: The binding won't apply at all in iOS (working in Android!)

related to **_t 1088654_**

**Comment by VladimirAmiorkov** [comment]
@NickIliev I tested this with the latest **3.0.1**v ersion of the `nativescript-telerik-ui` on both iOS and Android and was not able to reproduce it. 

Can you confirm if this is still an issue with that latest version?

**Comment by NickIliev** [comment]
@VladimirAmiorkov confirming that the issue is no longer reproducible with the latest version of `nativescript-telerik-ui` plugin.
