### ISSUE TITLE
RadDataForm - Android - Angular - Styling Labels for tkEntityPropertyEditor type="Switch" not working

### ISSUE THREAD

**Issue by NickIliev** [telerik/nativescript-ui-feedback#57]
Styling the **labels** for tkEntityPropertyEditor of type **Switch** is not working for **Angular** app in **Android**.
The styling works as expected for all other PropertyEditors.

Code to reproduce with [this example](https://github.com/telerik/nativescript-ui-samples-angular/blob/release/sdkAngular/app/dataform/styling-advanced/dataform-styling-advanced.component.html)

```
<RadDataForm [source]="settings" tkExampleTitle tkToggleNavButton (editorUpdate)="dfEditorUpdate($event)">
	<TKEntityProperty tkDataFormProperty name="onlyOnWiFi" index="0">
		<TKPropertyEditor tkEntityPropertyEditor type="Switch">
                         <!-- labels related styling not working  -->
			<TKPropertyEditorStyle tkPropertyEditorStyle 
			    strokeColor="#6A1B9A" 
			    strokeWidth="2" 
			    fillColor="#E040FB" 
			    labelHidden="false" 
			    labelTextSize="36" 
			    ios:labelFontName="Times New Roman" 
			    android:labelFontName="sans-serif-light" 
			    labelFontStyle="Italic"  
			    labelTextColor="red">
                          </TKPropertyEditorStyle>	
		</TKPropertyEditor>
	</TKEntityProperty>

         <!-- the same styling wotrks as expcted for other PropertyEditors -->
	<TKEntityProperty tkDataFormProperty name="networkLimit" index="1">
		<TKPropertyEditor tkEntityPropertyEditor type="Stepper">
			<TKPropertyEditorStyle tkPropertyEditorStyle 
			    strokeColor="#6A1B9A" 
			    strokeWidth="2" 
			    fillColor="#E040FB" 
			    labelHidden="false" 
			    labelTextSize="36" 
			    ios:labelFontName="Times New Roman" 
			    android:labelFontName="sans-serif-light" 
			    labelFontStyle="Italic"  
			    labelTextColor="red">
                         </TKPropertyEditorStyle>	
		</TKPropertyEditor>
	</TKEntityProperty>
</RadDataForm>
```

related to t 1079880

**Comment by Natalia-Hristova** [comment]
@NickIliev,  the style should apply now.

This will be available in our next official release. If you want to test it out before that you can use the "next" version of the nativescript-telerik-ui-pro plugin. Simply install that version of the plugin: ``` tns plugin add nativescript-telerik-ui-pro@next``` .

**Comment by Natalia-Hristova** [comment]
This issue is fixed and it will be available in our next official release. If you want to test it out before that you can use the "next" version of the nativescript-telerik-ui-pro plugin. Simply install that version of the plugin: ``` tns plugin add nativescript-telerik-ui-pro@next``` .
