### ISSUE TITLE
Item in RadSideDrawer does not respond

### ISSUE THREAD

**Issue by tsonevn** [telerik/nativescript-ui-feedback#575]
_From @ngunhaSO on March 15, 2018 6:48_

I installed the sample app for nativescript-ui-radsidedrawer, however the click event for the close drawer button does not respond. I have to tap multiple times before the event get triggered. 

The sample is downloaded from: https://github.com/telerik/nativescript-ui-samples-angular

Devices used to test:
Device 1:  Samsung galaxy S7, Android version: 7.0
Device 2: Samsung galaxy S5, Android version: 5.0.2
Device 3: Galaxy Tab S, Android version: 6.0.1

Tns version: 3.4.3

Also, tapping outside of the sidedrawer does not close the drawer.

Everything works fine in genymotion emulator though

_Copied from original issue: NativeScript/nativescript-angular#1237_

**Comment by tsonevn** [comment]
_From @ngunhaSO on March 15, 2018 7:7_

When I switched back to nativescript-pro-ui package, the side drawer item respond properly on all devices

**Comment by tsonevn** [comment]
Hi @ngunhaSO,
I tested your case with latest CLI version(3.4.3) and nativescript-ui-samples-angular sample app, however, was unable to recreate similar behaviour. For your convenience, I am attaching sample video.
[android.zip](https://github.com/telerik/nativescript-ui-feedback/files/1818394/android.zip)

Make sure that you are using the latest version of the sample project. 

Also, it would help if you could provide more info about the problem as well as the exact steps, which you follow.

**Comment by merigold** [comment]
I have exacly the  same problem after upgrade from 3.5.0 to 3.5.1. In my case when I tap menu item first slide drawer than menu item taped.

**Comment by ngunhaSO** [comment]
@tsonevn : I only upgrade the nativescript to 3.4.3 (running tns --version, it shows 3.4.3), download the sample app and run it on the above devices.

**Comment by Burgov** [comment]
Same here. Downgrading back to 3.5.0 fixes it. I'm guessing it's related to https://github.com/telerik/nativescript-ui-feedback/issues/465

**Comment by tsonevn** [comment]
HI all,
I was able to recreate the issue while using Samsung S8.
 We will investigate further that case and will provide more info on it.

**Comment by wanpeng2008** [comment]
Same issue on Huawei Mate8. Recovered after downgrading to 3.5.0.

**Comment by krisidmisso** [comment]
same problem here. it seems the tap moves a little the sidebar and detects it as a movement not as a tap

**Comment by jogboms** [comment]
This is true. Reverting back seems to fix the issue.

**Comment by felix-idf** [comment]
@tsonevn ,
Has this issue been fixed?

We are facing the same issue using the latest NativeScript version (**5.1**).
Reverting back to NS 3.5.x is not an option for us, because we want to use the RadSideDrawer in app-root.

**Comment by tsonevn** [comment]
HI @felix-idf,
This issue must be fixed in the latest plugin's version. Can you provide a sample app, which demonstrates the problem, you are facing?

**Comment by felix-idf** [comment]
@tsonevn ,
sorry for the late reply.
As I think that my problems are caused by using a ScrollView within the drawer, I created a new issue [here](https://github.com/telerik/nativescript-ui-feedback/issues/1024).
