### ISSUE TITLE
RadCalendar Non-Current Month Day loses styling when any new style applied, iOS

### ISSUE THREAD

**Issue by cfoulkes** [telerik/nativescript-ui-feedback#576]
In the month view with default styling, any days from the previous and next month are shown as grey, days for the current month are displayed black.

When applying custom styling to any element, the non-current month days are no longer grey.
This is not a desired behaviour and there appears to be no style available to force this back.

Thanks

Colin

Also, is there any documentation describing what the default styles are?

**Comment by tsonevn** [comment]
Hi @cfoulkes, 
Can you send us sample project, which could be used for debugging? Also provide more info about your environment(NativeScript CLI, tns-core-modules, tns-ios, nativescript-ui-calendar versions).

**Comment by cfoulkes** [comment]
Hi Nikolay,

I created a new app this morning,
with element
    <RadCalendar [monthViewStyle]="monthViewStyle" [viewMode]="viewMode"></RadCalendar>   

and in my component:
    viewMode = CalendarViewMode.Month;
    monthViewStyle: CalendarMonthViewStyle;

also 

    ngOnInit() {
        this.monthViewStyle = new CalendarMonthViewStyle();
        this.monthViewStyle.showTitle = false;
    }
With the above code, the days that are not part of the current month lose their (grey) styling.

by playing around I noticed that if I have:
  viewMode = 'month';

then the days keep their styling.
The difference being that the value CalendarViewMode.Month is "Month" (the same as the online documents)

The value that seems to work is "month", lower case "m";

Colin




Nativescript CLI:  3.4.3
"nativescript-ui-calendar": "^3.5.1"

**Comment by cfoulkes** [comment]
Hi, I still have a problem.

If I use a viewMode = 'month' (and not 'Month'), as mentioned above, the styling for the days that are not part of the current month is retained. But then some other month styling settings have no effect.

Such as selectionShapeColor or selectionShapeSize;

But monthViewStyle showTitle works.

Am I missing something here. Or is this a bug.
Thanks

Colin

**Comment by cfoulkes** [comment]
here is a simple test app
run in ios, select a date, then toggle the buttons at the top changing view mode from "month" to "Month"

https://github.com/cfoulkes/RadCalendarStyleIssue.git

**Comment by cfoulkes** [comment]
Do you need any more info?

**Comment by cfoulkes** [comment]
This problem still exists with 

NativeScript 4.1
tns-ios 4.1.0 

It's not marked as a bug yet.  

Thanks

Colin

**Comment by tsonevn** [comment]
Hi @cfoulkes,
The `month` is an invalid value for the Calendar's viewMode property. You can review the documentation [here](https://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/Calendar/view-modes). The all available options are case-sensitive and in this case the value for the viewMode property should be written with a capital first letter.

**Comment by cfoulkes** [comment]
I understand that. I mentioned it in passing as I thought the lower case "month" was being recognized.
But whether or not that is the case, the original issue still exists.

Thats is:
on iOS the days that are not part of the current month (the last days of the previous month, the first days of the next month) that are displayed in month view as lighter grey in default styling, lose this styling when any other styles are applied.


This is the real issue I was reporting.

Thanks

Colin

**Comment by tsonevn** [comment]
Hi @cfoulkes,
We investigated further your case and have to confirm that this is a real issue. I am logging it as a bug, and for now, you can keep track of the problem for further info.

**Comment by tgpetrov** [comment]
Fixed in naitvescript-ui-calendar@3.7.0
