### ISSUE TITLE
RadSideDrawer - issues with theme change (iOS)

### ISSUE THREAD

**Issue by erjdriver** [telerik/nativescript-ui-feedback#58]
I've got a page with a nativescript-theme-core theme installed (w/ SASS).

If I navigate to another page - change the theme and then navigate BACK - the whole page changes to the new theme except the side-drawer.

If I navigate to another page - change the theme and then NAVIGATE TO the first page - then the side-drawer has the new theme.

It's almost as if side-drawer caches the current sidedrawer and uses it if it's navigated back and creates a fresh copy of it's navigated to (as opposed to back).

This problem is only on iOS. Same code works fine on Android.

**Comment by NickIliev** [comment]
We can use nativescript-themes for runtime change of CSS - more details [here](https://github.com/NathanaelA/nativescript-themes/issues/3)
