### ISSUE TITLE
Feature: Expose a way to change the `RadDataForm` font-size

### ISSUE THREAD

**Issue by tsonevn** [telerik/nativescript-ui-feedback#583]
Expose a way to change the text font-size of the editor. Currently, we could change only the label text size(`labelTextSize`).

**Comment by tgpetrov** [comment]
The nativescript-ui-dataform now supports styling with css. This allows changing the font-size to every editor in the form or to just specific editors or their labels. Here's more for the feature in [NativeScript Core](https://docs.nativescript.org/ui/professional-ui-components/DataForm/dataform-styling#css) and in [NativeScript Angular](https://docs.nativescript.org/angular/ui/professional-ui-components/ng-DataForm/dataform-styling#css).

**Comment by Noppey** [comment]
Is this supposed to work with font-size? Because font-size is the only property that doesn't seem to be taken into account when styling a PropertyEditor (Android)

**Comment by bhcuong2008** [comment]
I applied css to tag <TKPropertyEditor> inside form with tag tkDataFormProperty is ok. But when applied to inside group tkPropertyGroupProperties, it had no effect. How to resolve this bug?
