### ISSUE TITLE
Changing from Month to Year viewMode by tapping month name on iOS

### ISSUE THREAD

**Issue by jeffswitzer** [telerik/nativescript-ui-feedback#587]
On android if viewMode = "Month" you can double tap on the month-year heading (i.e. March 2018) and the viewMode will change to "Year". However on IOS tapping on the month-year heading doesn't seem to do anything. I know how to bind the viewMode property, but how to you listen to the tap event on the month-year so that you can then change the viewMode binding? Or whats the method to get from month to year mode on IOS? Thanks!

**Comment by NickIliev** [comment]
@jeffswitzer there are some conceptual differences in the native controls for iOS and Android which are not allowing 100% of the functionalities to be available for both platforms.
On iOS, we can change the view mode from Month to Year programmatically and/or via binding as [shown in this example](https://github.com/telerik/nativescript-ui-samples/blob/release/sdk/app/calendar/view-modes/view-modes-model.ts#L31-L39) but we can't change it with a tap on the month's name.

The documentation article about `viewMode` property and the `[enumeration](http://docs.telerik.com/devtools/nativescript-ui/api/modules/calendarviewmode.html)` of available options can be found [here](http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/Calendar/view-modes)
