### ISSUE TITLE
RadDataForm - iOS - Allow structuring labels and field on separate rows (as in Android)

### ISSUE THREAD

**Issue by NickIliev** [telerik/nativescript-ui-feedback#59]
Allow the iOS implementation for RadDataForm to be organised with labels and fields on separate rows as in the Android implementation shown n the screenshot [here](http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/DataForm/dataform-styling).

Currently, the labels and the fields can only be rendered on a single row.

Client's request from t. 1089413

**Comment by NickIliev** [comment]
+1 request by t.1089290

**Comment by NickIliev** [comment]
+1 requested by t.1105700

**Comment by tsonevn** [comment]
Also allowing the label and the field to be organized on separated columns for Android.
Requested by t.1109593

**Comment by extima** [comment]
+1 This would help a lot!

**Comment by Natalia-Hristova** [comment]
Hi @NickIliev , @tsonevn , @extima 

This feature is implemented and it will be available in our next official release(in a week or two). If you want to test it out before that you can use the "next" version of the nativescript-telerik-ui-pro plugin. Simply install that version of the plugin: ``` tns plugin add nativescript-telerik-ui-pro@next``` .
