### ISSUE TITLE
propertyEdited never fired on Android

### ISSUE THREAD

**Issue by terreb** [telerik/nativescript-ui-feedback#604]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
propertyEdited is never fired on Android

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
cli: 3.4.1
tns-core-modules: 3.4.1
tns-android: 3.4.1
nativescript-ui-dataform: 3.5.2
Genymotion Google Pixel 2.0 Android 8.0

### Please tell us how to recreate the issue in as much detail as possible.
This issue can be reproduce with [nativescript-ui-samples](https://github.com/telerik/nativescript-ui-samples)
1. add the following listener to sdk/app/dataform/events/events-page.xml inside df:RadDataForm
`propertyEdited="dfPropertyEdited"`
2. add the following snippet to the code behind (sdk/app/dataform/events/event-page.ts)
`export function dfPropertyEdited() {
    console.log('property edited')
}`
3. run the app on Android (Genymotion Google Pixel 2.0 Android 8.0) watch the console and edit any property. The console message never appears for me. On iOS though works perfectly.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
Please see above.

**Comment by NickIliev** [comment]
@terreb thank you for reporting this issue.
Confirming this one as unexpected behavior and marking this one as a bug.

Steps to reproduce: 
- use nativescript-ui-sample application and try to trigger the `propertyEdited` event on Android.

**Comment by lini** [comment]
This event is iOS only (https://docs.telerik.com/devtools/nativescript-ui/api/classes/raddataform.html#propertyeditedevent). On Android you can use the `propertyCommitted` event instead - it is fired just after `propertyEdited` is fired on iOS.
