### ISSUE TITLE
RadCalendar extends over the elements above it

### ISSUE THREAD

**Issue by adouglas0363** [telerik/nativescript-ui-feedback#606]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
When using the inline events view mode, selecting a date which has a number of events on it causes the calendar to extend upward and over the elements above it. In the attached example, I added a stack layout with a blue background to demonstrate that it will get covered by the calendar when the inline events are shown. The action bar is also covered at times, but seems to be random as to exactly when. See the screenshots below.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 3.5.2
- **CLI:** 3.4.1
- **Cross-platform modules:** 3.4.0
- **Runtime(s):** 3.4.2

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application
2. Select a date which has events on it (April 18th in the demo application)

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
Attached is a simple demo application to demonstrate the issue.
[DemoApplication.zip](https://github.com/telerik/nativescript-ui-feedback/files/1872691/DemoApplication.zip)

![screenshot_20180403-123329](https://user-images.githubusercontent.com/34551060/38266338-11628f02-373e-11e8-8859-7459e891c262.png)
![screenshot_20180403-123338](https://user-images.githubusercontent.com/34551060/38266344-159947e6-373e-11e8-92df-33de7407c5a0.png)
![screenshot_20180403-123351](https://user-images.githubusercontent.com/34551060/38266346-17df0ad6-373e-11e8-9859-8246a0701dbf.png)

**Comment by tsonevn** [comment]
Hi @adouglas0363,
Thank you for the attached sample project.
We will investigate further this case. Please keep track on the issue for further info.

**Comment by zbranzov** [comment]
This issue should be fixed in nativescript-ui-calendar@3.8.1
