### ISSUE TITLE
Question, still see the nativescript-pro-ui in the plugins list during building even after removing it n upgrading..

### ISSUE THREAD

**Issue by mhmo91** [telerik/nativescript-ui-feedback#607]
I'm just wondering, why do i still see nativescript-pro-ui after uninstalling it n there's no reference to it or whatsoever anywhere in the app!
![image](https://user-images.githubusercontent.com/3815200/38331800-8add206a-3854-11e8-8cfd-e8fb3516d121.png)

**Comment by adouglas0363** [comment]
What version of the nativescript-imagepicker plugin do you have installed? There is a nativescript-pro-ui dependency before version 5.

**Comment by mhmo91** [comment]
@adouglas0363 interesting, i  have:
    "nativescript-imagepicker": "^4.0.1",
However i always run `npm update` n i follow the instructions inhere https://docs.nativescript.org/releases/running-latest every now n then, clearly NS need to provide a better way to auto upgrade the dependencies, otherwise, this will be an endless scream by everyone))

**Comment by mhmo91** [comment]
I found a solution for the update plugins issue here: https://github.com/NativeScript/nativescript-cli/issues/526 , unfortunately i have been working with NS for over 4 months now n never encountered this command anywhere on the website documentation here
https://docs.nativescript.org/releases/upgrade-instructions
https://docs.nativescript.org/releases/running-latest
and  i always run tns update next,  n tns update, seems that the upgrade instructions doesn't update the plugins automatically n it's not mentioned anywhere also that a developer needs to manually upgrade plugins using this command.

**Comment by tgpetrov** [comment]
@mhmo91 Thank you for sharing how you resolved your issue.
