### ISSUE TITLE
"TextChangedListener is not a Constructor" when implementing Autocomplete

### ISSUE THREAD

**Issue by joeytitans** [telerik/nativescript-ui-feedback#608]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
I am trying to create a RadAutoCompleteTextView using the provided documentation, but I receive a TypeError stating that TextChangedListener is not a constructor.

### Which platform(s) does your issue occur on?
Android. Only tested using emulated Nexus 4 version 7.1.1

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** I believe it is ^3.3.0
- **Nativescript-UI-Autocomplete:** ^3.6.0
- **CLI:** 3.4.2
- **Cross-platform modules:** 3.4.0
- **Runtime(s):**3.4.2

### Please tell us how to recreate the issue in as much detail as possible.
I am trying to follow the documentation exactly:
1.  Installed nativescript-ui-autocomplete plugin
2.  Defined XML namespace `xmlns:au=nativescript-ui-autocomplete`
3.  Used the XML code below from the getting started page for the AutoCompleteTextView. 
4.  Added code to create array, get data items, set data items, and init data items within my View Model.
5.  When running the application, it crashes then shows the following error: 
`TypeError: com.telerik.widget.autocomplete.TextChangedListener is not a constructor`

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
` <au:RadAutoCompleteTextView id="autocmp" items="{{ dataItems }}" suggestMode="Suggest" displayMode="Tokens">

            <au:RadAutoCompleteTextView.suggestionView>
                <au:SuggestionView>
                    <au:SuggestionView.suggestionItemTemplate>
                        <StackLayout orientation="vertical" padding="10">
                            <Label text="{{ text }}"></Label>
                        </StackLayout>
                    </au:SuggestionView.suggestionItemTemplate>
                </au:SuggestionView>
            </au:RadAutoCompleteTextView.suggestionView>

 </au:RadAutoCompleteTextView> `

**Comment by tsonevn** [comment]
Hi @joeytitans,
I tested your scenario on my side, however, I was unable to recreate an issue whit the RadAutoCompleteTextView component. 
For your convenience I am attaching sample project, please review it and make the needed changes, which will allow us to recreate the issue.
[Archive.zip](https://github.com/telerik/nativescript-ui-feedback/files/1894102/Archive.zip)

**Comment by joeytitans** [comment]
Hello,
I was never able to recreate the issue with the sample project you attached, unfortunately.  On the bright side, I was able to eventually get the autocomplete text view working by reverting back to 3.5.0 and a few other tweaks with the code.

**Comment by tsonevn** [comment]
Hi @joeytitans,
Thank you for the additional info, however it will be hard to investigate the problem without stable steps for reproducing.

I can suggest to update to latest NativeScript 4.0.0 as follows:
`npm uninstall nativescript --g`
`npm install nativescript --g`
`tns plugin remove tns-core-modules`
`tns plugin add tns-core-modules`
`tns platform remove <platform_name(ios/androdi)>`
`tns platform add <platform_name(ios/androdi)>`
 and to add again `nativescript-ui-autocomplete`(3.6.0).

Let me know if the issue is still reproducible.

**Comment by joeytitans** [comment]
Sorry about the lack of stable steps for replicating, I know I unfortunately did not give a lot of info to go off of.  

I had the nativescript-pro-ui plugin installed along with the nativescript-ui-autocomplete plugin.  Removing the pro-ui plugin allowed for me to successfully use the latest version of the ui-autocomplete plugin.

**Comment by tsonevn** [comment]
HI @joeytitans,
Regarding your last comment, I am assuming that you were able to solve the issue. Is that correct?

**Comment by dwsolutions** [comment]
I'm facing the same issue. I tried to remove the platforms, installed the newest typescript and nativescript, everything is up-to-date but the problem is the same. If I use the "old" autocomplete from the pro UI it's working but there's no textchanged event in that and I really need this unfortunately. :/

Could you help me please?

Thank you!
Attila
