### ISSUE TITLE
SideDrawer Angular over UI dialogs when using showOverNavigation

### ISSUE THREAD

**Issue by balachandran1988** [telerik/nativescript-ui-feedback#616]
HI @davorpeic,
I have sideDrawer showing "logout" button, when pressed I'm showing confirm dialog and in combination with drawer attribute showOverNavigation=true, the dialog goes under the drawer. When I don't show drawer over navigation, then the dialog is presented correct. This is the issue only with iOS and in android it is working fine.
![933833a4-f6be-11e6-978d-bc1b4400fdee](https://user-images.githubusercontent.com/38310453/38660446-dfe86942-3e4a-11e8-9dda-93ebacf8b631.png)

**Comment by tsonevn** [comment]
Hi @balachandran1988,
This behaviour is no longer reproducible with the latest version of `nativescript-ui-sidedrawer`(4.0.0) and NativeScript (4.0.0).
Bear in mind that, the RadSideDrawer no longer has a dedicated showOverNavigation property and the technic, how we could set up the drawer over the navigation bar, has changed. More about the migration the project to the latest version, could be found [here](http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/SideDrawer/show-over-navi-bar#migrating-from-versions-3xx-to-the-latest-version).
