### ISSUE TITLE
Unexpected behaviour in ListView when itemTap & itemSelected are fired

### ISSUE THREAD

**Issue by radeva** [telerik/nativescript-ui-feedback#617]
*Reported from a customer*

Of course, this is not a major feature and can be removed in the future builds, but I wanted to bring to your attention that RadListView still fires itemTapp and itemSelected events after topmost().navigate has been called. So if I tap fast on two different listings on that list, both events do fire, and navigate is called twice. The app doesn't crash anymore, but it goes into an unexpected UI state where navigation stack is like "list -> detail -> another detail", and I have to tap "back" twice to get back to the list. I don't know if there's a certain expectation as far as when exactly events stop firing during a page to page navigation, and I have never seen any documentation on it, but it seems to be a bit odd to me. Of course I can build prevention logic into my model, but I thought you might want to know.

**Comment by etabakov** [comment]
Logged on behalf of @sserdyuk.

**Comment by elena-p** [comment]
Hi @sserdyuk, 

The listview should not interfere with the navigation logic of your app. It would be best if you add the prevention logic into your event handling.
