### ISSUE TITLE
[Feature request] RadAutoCompleteTextView support for NativeScript Angular 2

### ISSUE THREAD

**Issue by tsonevn** [telerik/nativescript-ui-feedback#62]
Ability to use `RadAutoCompleteTextView` in NativeScirpt Angular 2 project

**Comment by Quovadisqc** [comment]
Is there any ETA for the release of this feature?
Thanks!

**Comment by ginev** [comment]
@Quovadisqc, we will most probably release the Angular 2.0 support right after the 3.0 release which is due to in a couple of days.

**Comment by tigrenok00** [comment]
Hi, 
What is the status of this?
Thanks!

**Comment by VladimirAmiorkov** [comment]
The closing of the issue was unintentional and was done automatically. We do plan to include this with our 3.0 release.

**Comment by tigrenok00** [comment]
@VladimirAmiorkov thanks for the quick reply, when is this release planned to be out?

**Comment by VladimirAmiorkov** [comment]
It is planned for the mid to end of next month.
