### ISSUE TITLE
RadSideDrawer iOS issues when changing bindingContext of drawerContent

### ISSUE THREAD

**Issue by felix-idf** [telerik/nativescript-ui-feedback#623]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
_Yes_

### Tell us about the problem
I wanted to take advantage of the latest release of nativescript 4.0 and nativescript-ui-sidedrawer, by sharing one single sidedrawer as the root view of the whole app. Everything seems to work as expected on Android, but I notice some issues on iOS.
Our SideDrawer should have different content for logged-in users and not logged-in users, so we bind the content of our drawer to an observable and by switching the "IsLoggedIn" property there, the content of the drawer should change. This scenario worked on previous versions of NativeScript and the SideDrawer component (where we had to define the Drawer on every single page).

### Which platform(s) does your issue occur on?
_iOS_

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 4.0.0
- **CLI:** (run `tns --version` to fetch it): 4.0.0
- **Cross-platform modules:** 4.0.0
- **Runtime(s):** 4.0.1

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application 
2. Tap the first button to open the drawer: there are just 2 options visible in the drawer
3. Close Drawer
4. Tap the second button to switch the state of the "isLoggedIn" property of the bindingContext of the drawer
4. Tap the first button again to open the drawer and now there are 4 options visible on Android, but still only 2 options on iOS, which is not the expected behaviour
![sidedrawer_issue_4_0](https://user-images.githubusercontent.com/6443021/38815974-62ff0f5a-4195-11e8-9321-bf0889930f57.gif)

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
Sample project can be found here:
[NSIssues4.zip](https://github.com/telerik/nativescript-ui-feedback/files/1915808/NSIssues4.zip)

**Comment by VladimirAmiorkov** [comment]
Hi @felix-idf ,

Thank you for reporting this to us. I will take a closer look and see what may be causing this behavior on iOS. I will update you here once I have more information to share.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/NativeScript#5694
