### ISSUE TITLE
AutoCompleteTextView not working in Angular version of Nativescript

### ISSUE THREAD

**Issue by osmbsrn** [telerik/nativescript-ui-feedback#630]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
I am trying to use "RadAutoCompleteTextView" in Angular. I follow this link http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/AutoCompleteTextView/overview to achive this. But it gives the following error.

```
JS: ERROR Error: Uncaught (in promise): TypeError: com.telerik.widget.autocomplete.RadAutoCompleteTextView is not a constructor
JS: TypeError: com.telerik.widget.autocomplete.RadAutoCompleteTextView is not a constructor
JS:     at RadAutoCompleteTextView.createNativeView (file:///data/data/org.nativescript.MovieRandomizer/files/app/tns_modules/nativescript-ui-autocomplete/ui-autocomplete.js:151:25)
JS:     at RadAutoCompleteTextView.ViewBase._setupUI (file:///data/data/org.nativescript.MovieRandomizer/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:412:35)
JS:     at file:///data/data/org.nativescript.MovieRandomizer/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:456:19
JS:     at StackLayout.LayoutBaseCommon.eachChildView (file:///data/data/org.nativescript.MovieRandomizer/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js:125:26)
JS:     at StackLayout.ViewCommon.eachChild (file:///data/data/org.nativescript.MovieRandomizer/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js:699:14)
JS:     at StackLayout.ViewBase._setupUI (file:///data/data/org.nativescript.MovieRandomizer/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:455:14)
JS:     at file:///data/data/org.nativescript.MovieRandomizer/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:456:19
JS:     at StackLayout.LayoutBaseCommon.eachChildView (file:///data/data/org.nativescript.MovieRandomizer/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js:125:26)
JS:     at StackLayout.ViewCommon.eachChild (file:///data/data/org.nativescript.MovieRandomizer/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js:699:14)
JS:     at StackLayout.ViewBase._setupUI (file:///data/data/org.nativescript.MovieRandomizer/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:455:14)
JS:     at file:///data/data/org.nativescript.MovieRandomizer/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:456:19
JS:     at ProxyViewContainer.LayoutBaseCommon.eachChildView (file:///data/data/org.nativescript.MovieRandomizer/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js:125:26)
JS:     at ProxyViewContainer.ViewCommon.eachChild (file:///data/data/org.nativescript.MovieRandomizer/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js:699:14)
JS:     at ProxyViewContainer.ViewBase._setupUI (file:///data/data/org.nativescript.MovieRandomizer/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:455:14)
JS:     at file:///data/data/org.nativescript.MovieRandomizer/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:456:19
```

### Which platform(s) does your issue occur on?
Android
iOS (Not tested yet!)

### Please provide the following version numbers that your issue occurs with:
 My package.json is below

```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.MovieRandomizer",
    "tns-android": {
      "version": "3.4.2"
    }
  },
  "dependencies": {
    "@angular/animations": "~5.2.0",
    "@angular/common": "~5.2.0",
    "@angular/compiler": "~5.2.0",
    "@angular/core": "~5.2.0",
    "@angular/forms": "~5.2.0",
    "@angular/http": "~5.2.0",
    "@angular/platform-browser": "~5.2.0",
    "@angular/platform-browser-dynamic": "~5.2.0",
    "@angular/router": "~5.2.0",
    "lodash": "^4.17.5",
    "nativescript-angular": "~5.2.0",
    "nativescript-fonticon": "^1.1.1",
    "nativescript-gradient": "^2.0.1",
    "nativescript-ngx-fonticon": "^4.1.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-pro-ui": "^3.4.1",
    "nativescript-ui-autocomplete": "^3.6.0",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.5.2",
    "tns-core-modules": "~3.4.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "^1.3.6",
    "nativescript-dev-typescript": "~0.6.0",
    "typescript": "~2.6.2"
  }
}
```

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application ..
2. Click a button to open a modal that contains AutoCompleteTextBox

**Comment by tsonevn** [comment]
Hi @osti89,
Please provide a sample project, which could be used for debugging.

In the meantime, I would suggest checking if you will have the same issue while using the latest NativeScript 4.0.

**Comment by osmbsrn** [comment]
Hi @tsonevn,

I updated my typescript version, and reinstalled the platforms then AutoComplete was working.

But after this update I was able to set a transparent background to my modal with the following code. But now its not working, my modal has a completely white background. How can I set my modal's background to transparent.

`this.page.on('loaded', args => {
      (<any>args.object).backgroundColor = new Color(0.5, 0,0,0);
    });
`

**Comment by VladimirAmiorkov** [comment]
I see that you are using both nativescript-pro-ui and nativescript-ui-autocomplete, make sure to remove the nativescript-pro-ui, clear the platforms and node_modules folders and rebuild your project.

**Comment by osmbsrn** [comment]
Hi @VladimirAmiorkov,

Thank you for your response. But like I said my previous comment I fixed this issue by removing native-script-pro-ui and reinstalling Nativescrip. There is no problem about it.

But after this update I lost transperancy in modal pages. I can open a new issue about it. But there is also an issue on NativeScript github project. You can find it below.


https://github.com/NativeScript/NativeScript/issues/5554

**Comment by tgpetrov** [comment]
Hi @osmbsrn,
It seems like you have resolved your issue with the exception in AutoComplete. For the issue about the transparency in NativeScript Modal pages, please refer to the issue that you linked in your previous post.
