### ISSUE TITLE
Focus on specific date as start date in Nativescript-ui-calendar

### ISSUE THREAD

**Issue by pankajjjpr** [telerik/nativescript-ui-feedback#634]
Hello all,

I am using Nativecsript-ui-calendar for radcalendar into my Nativecsript-angular app.

I want to set selected date (the square which comes when we see the calendar at first) as tomorrow date but currently it is setting the default selected date as today's date. I even set the Min date as one day greater than today date but  no luck.

Here is the tag I used in html page (please ignore the [visibility] property and (dateSelected) events as they are working as desired):
```
<RadCalendar (dateSelected)="onCheckOutDateSelected($event)" (loaded)="onCheckOutDateCalendarLoaded($event)" height="250" [visibility]="isLoadingSec ? 'visible' : 'collapse'" ></RadCalendar>
```
And the events as are as follows:
```
onCheckOutDateCalendarLoaded(args){
        let CheckOutDateCalendar = <RadCalendar>args.object;
        CheckOutDateCalendar.minDate = this.checkOutDate;
        CheckOutDateCalendar.selectedDate.setDate(CheckOutDateCalendar.minDate);
        CheckOutDateCalendar.goToDate(CheckOutDateCalendar.minDate);
        CheckOutDateCalendar.displayedDate.setDate(this.checkOutDate.getDate());
    }
```
as you can see i tried all three properties in order to set the date but none of them is working as correct.

Another issue is with dateSelected event. this event does not fire when I tap on my minimum set date.
Can anyone have any idea or link where I can take reference or help?

**Comment by tsonevn** [comment]
Hi @pankajjjpr,
You can try setting up the [displayedDate ](https://docs.telerik.com/devtools/nativescript-ui/api/classes/radcalendar.html#displayeddate) and the [selectedDate](https://docs.telerik.com/devtools/nativescript-ui/api/classes/radcalendar.html#selecteddate) properties to the RadCalendar component. 
Also if this does not resolve your case, please provide some more info about your scenario and sample project.

**Comment by tsonevn** [comment]
Hi @pankajjjpr,
Excuse me for that.
I did not notice that you are setting the displayed date via code behind. Did you try binding those properties via the HTML? For example:
HTML
```
<RadCalendar [displayedDate]="disDate" [selectedDate]="sDate" ></RadCalendar>
```

code behind
onCheckOutDateCalendarLoaded(args){
this.disDate = new Date(<the needed date here>);
this.sDate= new Date(<the needed date here>);
}

Also if this does not help in your case, please provide a sample project, which could be used for debugging.

**Comment by pankajjjpr** [comment]
Hi tsonevn,

As a matter of fact I have applied what you mentioned like below:

<RadCalendar (dateSelected)="onCheckInDateSelected($event)" (loaded)="onCheckInDateCalendarLoaded($event)" [displayedDate] = "checkInDate" [selectedDate] = "checkInDate" height="250" [visibility]="isLoading ? 'visible' : 'collapse'"></RadCalendar>
                                <RadCalendar (dateSelected)="onCheckOutDateSelected($event)" (loaded)="onCheckOutDateCalendarLoaded($event)" [displayedDate] = "checkOutDate" [selectedDate] = "checkOutDate" height="250" [visibility]="isLoadingSec ? 'visible' : 'collapse'" ></RadCalendar>

and from code behind:
public ngOnInit() {
        this.checkInDate = new Date();
        this.checkOutDate = new Date();
        this.checkOutDate.setDate(this.checkInDate.getDate() + 1)
    }

onCheckInDateCalendarLoaded(args){
        let CheckInDateCalendar = <RadCalendar>args.object;
        CheckInDateCalendar.minDate = new Date();
    }

    onCheckOutDateCalendarLoaded(args){
        let CheckOutDateCalendar = <RadCalendar>args.object;
        CheckOutDateCalendar.minDate = this.checkOutDate;
    }

public onCheckInDateSelected(args) {
        const calendar: RadCalendar = <RadCalendar>args.object;
        this.checkInDate = calendar.selectedDate;
        if(this.checkInDate>=this.checkOutDate)
        {
            this.checkOutDate.setMonth(this.checkInDate.getMonth());
            this.checkOutDate.setDate(this.checkInDate.getDate()+1);
        }
    }

public onCheckOutDateSelected(args) {
        const calendar: RadCalendar = <RadCalendar>args.object;
        this.checkOutDate = CheckOutDatecalendar.selectedDate;
        if(this.checkOutDate<=this.checkInDate)
        {
            this.checkInDate.setMonth(this.checkOutDate.getMonth());
            this.checkInDate.setDate(this.checkOutDate.getDate()-1);
        }
    }

but its still giving me same result.

May be I am doing something wrong. I will create a sample project and upload it.

**Comment by pankajjjpr** [comment]
I am not able to upload the project as it is more than 10 MB. Is there any way I can share that project?

**Comment by isaacfi** [comment]
Does any update about this feature request?
