### ISSUE TITLE
RadListView is slow displaying 500+ items

### ISSUE THREAD

**Issue by tbozhikov** [telerik/nativescript-ui-feedback#641]
## Please, provide the details below
RadListView's virtualization seems not to work. There is ~5sec delay when try to display 500+ items.

### Tell us about the problem
_Please, ensure your title is less than 63 characters long and starts with a capital
letter._

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- "nativescript-ui-listview": "^3.5.5"
- CLI: 4.0.0
- "tns-core-modules": "4.0.0"
- "tns-ios": {
      "version": "4.0.1"
    },
    "tns-android": {
      "version": "4.0.1"
    }
### Please tell us how to recreate the issue in as much detail as possible.
Any RadListView with bigger number of items is slow

**Comment by VladimirAmiorkov** [comment]
Made PR, awaiting review.

**Comment by xnramx** [comment]
Do you know when this will be released?

**Comment by zbranzov** [comment]
@xnramx We are going to release the fix at the end of the week at the latest so stay tuned.

Regarding the fix itself, it seems that the first data item itemLoading event is triggered twice so we have to consider that and try to resolve it.

**Comment by zbranzov** [comment]
The fix is available in v3.5.10
