### ISSUE TITLE
RadListView item :highlighted or onItemTouchEvent

### ISSUE THREAD

**Issue by webleaf** [telerik/nativescript-ui-feedback#649]
There are only `onItemTapEvent`.
To emulate `:highlighted` pseudo selector, i need touch event for item of RadListView.

**Comment by webleaf** [comment]
Oh, ok, i understand. The problem looks like about how to determine is it `RadListView` scrolling or `touch.move` for item. So for ListView only `tap` and `swipe` make sense.

**Comment by webleaf** [comment]
In example below (`page1.xml`), if i click on any Label `tap` event **NOT** fire. In this case `itemTap` fire. Why?
```
<!--page1.xml-->

<Page class="page"
    navigatingTo="onNavigatingTo"
    xmlns="http://schemas.nativescript.org/tns.xsd"
    xmlns:lv="nativescript-ui-listview"
    loaded="onLoaded">

    <lv:RadListView items="{{ dataItems }}" itemTap="onItemTap">
        <lv:RadListView.itemTemplate>
            <StackLayout orientation="vertical" tap="onTap">
                <Label fontSize="20" text="{{ itemName }}"/>
                <Label fontSize="14" text="{{ itemDescription }}"/>
                <Button text="Btn" tap="onButtonTap" />
                <StackLayout height="1" backgroundColor="lightgray"/>
            </StackLayout>
        </lv:RadListView.itemTemplate>
    </lv:RadListView>
</Page>
```
In example below (`page2.xml`), if i click on any Label `tap` event **fire**.

```
<!--page2.xml-->

<Page class="page"
    navigatingTo="onNavigatingTo"
    xmlns="http://schemas.nativescript.org/tns.xsd"
    xmlns:lv="nativescript-ui-listview"
    loaded="onLoaded">

    <lv:RadListView items="{{ dataItems }}" itemTap="onItemTap">
        <lv:RadListView.itemTemplate>
            <StackLayout orientation="vertical" tap="onTap">
                <Label fontSize="20" text="{{ itemName }}"/>
                <Label fontSize="14" text="{{ itemDescription }}"/>
                <!--<Button text="Btn" tap="onButtonTap" />-->
                <StackLayout height="1" backgroundColor="lightgray"/>
            </StackLayout>
        </lv:RadListView.itemTemplate>
    </lv:RadListView>
</Page>
```

In example below (`page3.xml`), if i click on any Label `touch` event **fire**.

```
<!--page3.xml-->

<Page class="page"
    navigatingTo="onNavigatingTo"
    xmlns="http://schemas.nativescript.org/tns.xsd"
    xmlns:lv="nativescript-ui-listview"
    loaded="onLoaded">

    <lv:RadListView items="{{ dataItems }}" itemTap="onItemTap">
        <lv:RadListView.itemTemplate>
            <StackLayout orientation="vertical" touch="onTouch">
                <Label fontSize="20" text="{{ itemName }}"/>
                <Label fontSize="14" text="{{ itemDescription }}"/>
                <Button text="Btn" tap="onButtonTap" />
                <StackLayout height="1" backgroundColor="lightgray"/>
            </StackLayout>
        </lv:RadListView.itemTemplate>
    </lv:RadListView>
</Page>
```

Summary:

1) Why `tap` event don't fire, when `StackLayout` contain `Button` and I click out of `Button`? But if instead `tap` i try catch `touch` event, then it works. I think, it's bug.
2) `touch` event for `StackLayout` inside `RadListView.itemTemplate` works as expected, so my subject feature request still actual (because I see, it's possible, and make sense). RadListView need `onItemTouch` event.
3) `itemTap` - in fact is `touch.ACTION_UP` (but NOT `touch.ACTION_DOWN` as expected for `tap` event). Ok, i could understand it, because it more useful for determining was item selected or not. But in `page2.xml` example, `tap` event of `StackLayout` in fact is `touch.ACTION_UP` too. It's not what expected.

**Comment by NickIliev** [comment]
@webleaf there is a conceptual difference in how iOS and Android are handling the event propagation (see [here](https://github.com/NativeScript/NativeScript/issues?utf8=%E2%9C%93&q=event+propagation)) In my opinion the tap event get's "consumed' by the most inner element and this is the reason why the `touch` would work while the tap won't

Regarding the third point:

> itemTap - in fact is touch.ACTION_UP (but NOT touch.ACTION_DOWN as expected for tap event). Ok, i could understand it, because it more useful for determining was item selected or not. But in page2.xml example, tap event of StackLayout in fact is touch.ACTION_UP too. It's not what expected.

I would go with the inner tap event for more complext tempalte logic and this way avoid using `itemTap`. However, there might be a better approach - @VladimirAmiorkov ^
