### ISSUE TITLE
[RadListView] How to get the first item showing on the screen

### ISSUE THREAD

**Issue by wanpeng2008** [telerik/nativescript-ui-feedback#651]
I want to get the first item index in RadListView after some scrollings.
It is used for the pagination status. But i can't find any related APIs. 
Any help is appreciated.

**Comment by NickIliev** [comment]
@wanpeng2008 you can use [`itemLoading`](http://docs.telerik.com/devtools/nativescript-ui/api/classes/radlistview.html#itemloadingevent) event with [`ListViewEventData`](http://docs.telerik.com/devtools/nativescript-ui/api/classes/listvieweventdata.html) and get the index of the loaded elements.

For example (NativeScript Core but Angular is the same principle only a bit different syntax):
```XML
<lv:RadListView items="{{ dataItems }}" itemLoading="onItemLoading" >
```

and then in the callback (TypeScript)
```TypeScript
export function onItemLoading(args: ListViewEventData) {
    console.log("Item Loading with index: ", args.index);
}
```

**Comment by wanpeng2008** [comment]
@NickIliev Wonderful solution.
By analyzing the itemLoading index data stream, i finally get the scrolled item count.
