### ISSUE TITLE
Getting this error and app crashing for iOS : undefined is not an object (evaluating 'owner.suggestionView.ios.items')

### ISSUE THREAD

**Issue by JaganJonnala** [telerik/nativescript-ui-feedback#652]
I am using nativescript-ui-autocomplete plugin. For whatever i have written code the android app will be working fine.
But from the iOS i am getting the above one.

Query related to nativescript-ui-autocomplete

**Comment by NickIliev** [comment]
@JaganJonnala can you isolate the case in a sample application or [Playground demo](https://play.nativescript.org/) so we could investigate further. Also along the code base consider posting as much as possible information about the used version of the plugin and NativeScript

**Comment by stephanegg** [comment]
@NickIliev please see this [playground demo](https://play.nativescript.org/?template=play-ng&id=l89XGf&v=5).

**Some investigation:**
- If you comment out the autocomplete in dog.component, the error disappear and it works on cat tab.
- If you change _router-outlet_ to _page-router-outlet_ in tabs.component, it works on cat tab and dog tab but then the error appears in detail.component 

**Behavior expected**: autocomplete working on main, dog tab, cat tab and dog-detail.

As @JaganJonnala said, this problem appears only on iOS. TabView is vital in most of the apps, any investigation and explanations of what is wrong here would be very helpful.

**Comment by spmamidi** [comment]
+1 We are also facing same issue.

**Comment by NickIliev** [comment]
Duplicate to [https://github.com/telerik/nativescript-ui-feedback/issues/636](https://github.com/telerik/nativescript-ui-feedback/issues/636)
