### ISSUE TITLE
Question: is it possible to fire event when tapping on already selected day

### ISSUE THREAD

**Issue by jeffswitzer** [telerik/nativescript-ui-feedback#653]
I'm trying to popup a modal whenever the user taps a day in the calendar month view (even if the day the user taps on is the currently selected date). The following code works, except the onDateSelected event doesn't fire if the user taps on the day that is currently selected.

```
onDateSelected(args: CalendarSelectionEventData) {
        console.log('a date was tapped');
}

<RadCalendar #myCalendar id="myCalendar"
                     [monthViewStyle]="monthViewStyle"
                     [viewMode]="viewMode"
                     [eventSource]="_events"
                     [selectedDate]="curDate"
                     (dateSelected)="onDateSelected($event)"
                     (navigatedToDate)="onNavigatedToDate($event)"
                     (navigatedToDateEvent)="onViewModeChanged($event)">
```

So I don't want the event to only fire when the date changes, but would like it to fire every time a day is tapped. Maybe I should be using a different event? Is such behavior possible?

**Comment by tgpetrov** [comment]
@jeffswitzer There is actually a [cellTap](http://docs.telerik.com/devtools/nativescript-ui/api/classes/radcalendar.html#celltapevent) event that you can use, which is fired when the user taps on the day even if it is already selected.

**Comment by jeffswitzer** [comment]
@tgpetrov thanks, works great!
