### ISSUE TITLE
RadListView: module not found for element 'nativescript-ui-listview:RadListView'.

### ISSUE THREAD

**Issue by mkrawiec** [telerik/nativescript-ui-feedback#654]
I'm unable to follow along [Getting Started](http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/ListView/getting-started) tutorial for `RadListView` getting this runtime exception:

```
Error: Building UI from XML. @file:///app/app-root.xml:1:1
 > Building UI from XML. @file:///app/main-page.xml:2:5
   > Module '/data/data/org.nativescript.nativescript/files/app/nativescript-ui-listview' not found for element 'nativescript-ui-listview:RadListView'.
   > com.tns.NativeScriptException: Failed to find module: "/data/data/org.nativescript.nativescript/files/app/nativescript-ui-listview", relative to: app//
      com.tns.Module.resolvePathHelper(Module.java:146)
    com.tns.Module.resolvePath(Module.java:55)
    com.tns.Runtime.callJSMethodNative(Native Method)
[...]
```

Steps to reproduce on clean project:
- `tns create --template tsc nativescript`
- `cd nativescript`
- `npm install --save-dev nativescript-dev-webpack`
- `tns plugin add nativescript-ui-listview`
- open `app/main-page.xml` replace contents with:
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" xmlns:lv="nativescript-ui-listview" navigatingTo="navigatingTo" class="page">
    <lv:RadListView items="{{ dataItems }}" >
        <lv:RadListView.itemTemplate>
            <StackLayout orientation="vertical">
                <Label fontSize="20" text="{{ itemName }}"/>
                <Label fontSize="14" text="{{ itemDescription }}"/>
            </StackLayout>
        </lv:RadListView.itemTemplate>
    </lv:RadListView>
</Page>
```
- run the app with `tns run android --watch --bundle`

Nativescript: 4.0.0, nativescript-ui-listview 3.5.5

**Comment by NickIliev** [comment]
@mkrawiec you need to manually register the plugin in your bundle-config as done [here](https://github.com/telerik/nativescript-ui-samples/blob/release/sdk/app/bundle-config.ts#L11-L18).

For example, it should look like this
bundle-config.ts
```TypeScript
if ((<any>global).TNS_WEBPACK) {
    require("bundle-entry-points");

    const context = (<any>require).context("~/", true, /(root|page|fragment)\.(xml|css|js|ts|scss|less|sass)$/);
    global.registerWebpackModules(context);

    // HERE
    global.registerModule("nativescript-ui-listview", () => require("nativescript-ui-listview"));
}

```

**Comment by AshleyCao** [comment]
Hi @NickIliev , do we need to manually register module for all ui plugins?
I have exact same error on android.

**Comment by handoyo** [comment]
Sorry to hijack this thread. Do we need to use to use --bundle in order to use RadListView? I tried to reference the plugin via bundle-config.js, and then i run the app. Yet i still get the same warning message. Thanks.

**Comment by AshleyCao** [comment]
@handoyo seems like we need. 
I got listview in my project initial page,
in bundle-config.ts, I added 
`  global.registerModule("nativescript-ui-listview",
        () => require("../node_modules/nativescript-ui-listview"));`

**Comment by handoyo** [comment]
@AshleyCao thanks for info. I will try to use the bundle then.
