### ISSUE TITLE
AutoComplete - How to color the edit text field.

### ISSUE THREAD

**Issue by davidjiangAR** [telerik/nativescript-ui-feedback#660]
I am using nativescript-pro-ui/autocomplete. Set the css class to RadAutoCompleteTextView element, the color has applied to the suggestion view, but not applied to the edit text field. Please let me know how to color the edit text field.

**Comment by tsonevn** [comment]
related to issue [#63](https://github.com/telerik/nativescript-ui-feedback/issues/63)
