### ISSUE TITLE
Event pullToRefreshInitiated binding function call twice 

### ISSUE THREAD

**Issue by OPADA-Eng** [telerik/nativescript-ui-feedback#665]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
_Yes_

### Tell us about the problem
Event pullToRefreshInitiated binding function call twice 

### Which platform(s) does your issue occur on?
_iOS_

### Please provide the following version numbers that your issue occurs with:
- "nativescript-ui-listview": "^3.5.6"
- **CLI:** "4.0.0"
- **Cross-platform modules:"~4.0.0"
- **Runtime(s):** 
```
"tns-ios": {
      "version": "4.0.1"
    },
    "tns-android": {
      "version": "4.0.1"
    }
```
### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application ..
2. trigger the event using the ui.

**Comment by tsonevn** [comment]
Hi @OPADA-Eng, 
I tested your case with the [natiescript-ui-samples](https://github.com/telerik/nativescript-ui-samples/tree/release/sdk/app/listview/pull-to-refresh), however, I was unable to recreate this behaviour on my side. Can you provide sample project, which could be used for debugging?

**Comment by OPADA-Eng** [comment]
Hi @tsonevn 
Thank you for your assistance, I attached a demo app you can see the log in the console and see.
[NewApp.zip](https://github.com/telerik/nativescript-ui-feedback/files/2025665/NewApp.zip)
Thanks!

**Comment by tsonevn** [comment]
Hi @OPADA-Eng,
Thank you for the attached project. 
We will investigate further this problem and will check what is causing the issue.

**Comment by OPADA-Eng** [comment]
Hi @tsonevn 
I appreciate that, I hope you find the solution asap because it's a main feature in my app.
Many thanks.

**Comment by tsonevn** [comment]
Hi @OPADA-Eng,
This issue seems to be related to #523. I am closing this one in favour of issue #523. You can keep track on it for further info.

**Comment by VladimirAmiorkov** [comment]
Hi @OPADA-Eng ,

Can you make sure that the platforms is cleared after upgrading to the 3.6.0 version. Sometimes the NativeScript CLI caches the native libraries/frameworks. Regarding the https://github.com/telerik/nativescript-ui-feedback/issues/523 issue , can you make sure that you are not hitting this scenario as explained in my comment here https://github.com/telerik/nativescript-ui-feedback/issues/496#issuecomment-405536861 . If your scenario is different can you give us more details?

**Comment by OPADA-Eng** [comment]
Thanks for your efforts!
I'm waiting the new release.

**Comment by OPADA-Eng** [comment]
The problem still happening in the new release !!
Please find me a solution, Thanks
