### ISSUE TITLE
RadDataForm "Cannot read property 'toString' of null"

### ISSUE THREAD

**Issue by connor-sleight** [telerik/nativescript-ui-feedback#670]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
The RadDataForm doesnt render my data and throws an error.

### Which platform(s) does your issue occur on?
Android 7.0
Not tested on IOS

### Please provide the following version numbers that your issue occurs with:
- nativescript-ui-dataform - 3.6.0
- **CLI:** 4.0.1
- **Cross-platform modules:** 4.0.1
- **Runtime(s):** android: 4.0.1, ios: not installed

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
I have the following code within a gridlayout within a listview. If one of the properties has a blank value, it throws an error. I am unable to loop through all my data to make sure they have blank values.

    <RadDataForm tkExampleTitle tkToggleNavButton [source]="item">
      <TKPropertyGroup tkDataFormGroups collapsible="true" [name]="cProductCode">
        <TKEntityProperty tkPropertyGroupProperties name="cProductCode" displayName="Product Code">
          <TKPropertyEditor tkEntityPropertyEditor type="Text"></TKPropertyEditor>
        </TKEntityProperty>
        <TKEntityProperty tkPropertyGroupProperties name="cSpec" displayName="Spec">
           <TKPropertyEditor tkEntityPropertyEditor type="Text"></TKPropertyEditor>
         </TKEntityProperty>
      </TKPropertyGroup>
    </RadDataForm>

Is there anyway i can get the plugin to allow blank values so that it doesnt error? Shouldnt there be a handler in place for blank data to become false/""/0, etc?

Something I found out after, if i comment out all of the `TKEntityProperty` tags, all the data shows fine, its only when i manually define the properties

**Comment by tsonevn** [comment]
Hi @connor-sleight,
Can you provide sample project, which demonstrates your problem and can be used for debugging?

**Comment by connor-sleight** [comment]
Hi @tsonevn,
Its to do with the data that's received from the server rather than an error in the app. But i believe that there should be more error handling to account for null values. I wrote a temporary fix within the plugin but cant find the code anymore
