### ISSUE TITLE
RadCartesianChart Automatic Redraw Disable?

### ISSUE THREAD

**Issue by JakeAi** [telerik/nativescript-ui-feedback#672]
**Playground Link**
[https://play.nativescript.org/?template=play-js&id=khsTvB&v=5](https://play.nativescript.org/?template=play-js&id=khsTvB&v=5)

> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

## Please, provide the details below:
When pushing a new item to an observablearray, the chart redraws everytime.

### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
When pushing a new item to an observablearray, the chart redraws everytime. This makes a live/realtime chart useless since it redraws every second or so.

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 3.6.1
- **CLI:** 4.0.2
- **Cross-platform modules:** 4.0.1
- **Runtime(s):** 4.0.1

### Please tell us how to recreate the issue in as much detail as possible.
1. **Playground Link**
[https://play.nativescript.org/?template=play-js&id=khsTvB&v=5](https://play.nativescript.org/?template=play-js&id=khsTvB&v=5)

1. Use code below
2. Add new item to array
3. Chart redraws everytime

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
```xml
 <chart:RadCartesianChart tap="{{hi}}" class="m-t-10" height="200">
            <chart:RadCartesianChart.series>
                <chart:LineSeries seriesName="Total" items="{{ data2 }}" stackMode="Stack" categoryProperty="key" valueProperty="value">
                    <chart:LineSeries.verticalAxis>
                        <chart:LinearAxis horizontalLocation="Right"/>
                    </chart:LineSeries.verticalAxis>
                </chart:LineSeries>
                <chart:LineSeries seriesName="RateA" items="{{ data }}" stackMode="Stack" categoryProperty="key" valueProperty="value">
                    <chart:LineSeries.verticalAxis>
                        <chart:LinearAxis horizontalLocation="Left"/>
                    </chart:LineSeries.verticalAxis>
                </chart:LineSeries>
            </chart:RadCartesianChart.series>
            <chart:RadCartesianChart.horizontalAxis>
                <chart:CategoricalAxis allowPan="true" verticalLocation="Down" />
            </chart:RadCartesianChart.horizontalAxis>
        </chart:RadCartesianChart>
```
```js
 public data: ObservableArray<any> = new ObservableArray([
        { key: 1, value: 0 }, { key: 2, value: 0 }, { key: 3, value: 0 }, { key: 4, value: 1500 }, { key: 5, value: 4500 }, { key: 6, value: 6500 }, { key: 7, value: 8000 }, { key: 8, value: 7800 }, { key: 9, value: 7900 }, { key: 10, value: 8000 }, { key: 11, value: 8100 }, { key: 12, value: 8200 }, { key: 13, value: 8000 }, { key: 14, value: 8050 }, { key: 15, value: 8000 }, { key: 16, value: 8000 }, { key: 17, value: 8050 }, { key: 18, value: 8000 }, { key: 19, value: 7950 }, { key: 20, value: 7800 },
    ]);
    
    public data2: ObservableArray<any> = new ObservableArray([
        { key: 1, value: 0 }, { key: 2, value: 0 }, { key: 3, value: 0 }, { key: 4, value: 5 }, { key: 5, value: 15 }, { key: 6, value: 40 }, { key: 7, value: 60 }, { key: 8, value: 42 }, { key: 9, value: 35 }, { key: 10, value: 30 }, { key: 11, value: 31 }, { key: 12, value: 32 }, { key: 13, value: 30 }, { key: 14, value: 31 }, { key: 15, value: 30 }, { key: 16, value: 30 }, { key: 17, value: 31 }, { key: 18, value: 30 }, { key: 19, value: 31 }, { key: 20, value: 30 },
    ])
    
```

**Comment by tsonevn** [comment]
Hi @JakeAi,
Currently, there is no option that allows drawing only the newly added items in Chart. I am logging this as a new feature request. You can keep track on it for further info.

**Comment by JakeAi** [comment]
@tsonevn Great! I did find a hacky fix but I don't want it to be hacky. 

```JS
onChartTap(args) {
    let chart = <RadCartesianChart>args.object
    chart = chart.ios
    chart['animationDuration'] = 0
}
```

**Comment by JakeAi** [comment]
@tsonevn I migrated to angular and now my hacky fix doesn't work. Is there any movement on this? The chart redraws 10 times per second.

**Comment by tsonevn** [comment]
Hi @JakeAi,
The feature request related to this issue is still under review. Regarding that, I can not commit to the exact time when this functionality will be available. Also, can you provide sample project or at least some extended code snippets, which shows, how you are accessing the chart via code-behind and how you set up the needed properties?

**Comment by JakeAi** [comment]
@tsonevn,
Currently I'm using ngAfterViewInit(). I commented out the two lines so they dont execute. What you 
would do is tap the button over and over and it would do the graph draw animation on every tap because a new point was added. So I turn it off in ngAfterViewInit but you can also tap the chart and it would run fixMe()
```HTML

<StackLayout>
    <GridLayout class="header-container" colSpan="4" columns="*,*,*,*" rows="auto, auto, auto, auto, auto, auto" #chartContainer>
        <RadCartesianChart height="500" id="deviceChart" #deviceChart (tap)="fixMe()" row="0" col="0" colSpan="4">
            <LineSeries allowPan="true" allowZoom="true" [verticalAxis]="linearAxisZoom2" tkCartesianSeries seriesName="Total" [items]="selectedDevice.voltageHistory" stackMode="Stack" categoryProperty="key" valueProperty="value"></LineSeries>
            <LineSeries allowPan="true" allowZoom="true" [verticalAxis]="linearAxisZoom" tkCartesianSeries seriesName="RateA" [items]="selectedDevice.rpmHistory" stackMode="Stack" categoryProperty="key" valueProperty="value"></LineSeries>
            <CategoricalAxis allowPan="true" allowZoom="true" [horizontalAxis] tkCartesianHorizontalAxis verticalLocation="Bottom"></CategoricalAxis>
            <RadLegendView tkCartesianLegend position="Top" title="Chart Legend" height="150" enableSelection="true"></RadLegendView>
        </RadCartesianChart>
    </GridLayout>
    <Button row="1" col="0" colSpan="4" text="Add Data Point" (tap)="addPoint()" class="button button-danger"></Button>
</StackLayout>
```
```TS
// This function/button mimicks the bluetooth notify event which happens 10x per second. 
addPoint() {
    let min = 1;
    let max = 12000;
    this.selectedDevice.rpmHistory.push( { key: this.timer, value: Math.floor( Math.random() * ( max - min + 1 ) ) + min } );
    this.selectedDevice.voltageHistory.push( { key: this.timer, value: Math.floor( Math.random() * ( 120 - 1 + 1 ) + 1 ) } );
    this.timer++;
}


fixMe(  ) {
    let RadChart: RadCartesianChart = <RadCartesianChart>this.myId.nativeElement;
    RadChart.nativeViewProtected.animationDuration = 0;
    RadChart.nativeViewProtected.allowAnimations = false;
}

ngAfterViewInit() {
    let RadChart: RadCartesianChart = <RadCartesianChart>this.myId.nativeElement;
    setTimeout( () => {
        console.log( RadChart.series );
        // RadChart.nativeViewProtected.animationDuration = 0;
        // RadChart.nativeViewProtected.allowAnimations = false;
    }, 10 );
}
```

**Comment by tgpetrov** [comment]
Since [nativescript-ui-chart@3.10.0](https://github.com/telerik/nativescript-ui-feedback/blob/master/releases/chart.md#v3100-2018-november-20), there is an `allowAnimations` [property](https://github.com/telerik/nativescript-ui-feedback/blob/master/releases/chart.md#v3100-2018-november-20) that can be used to disable the redrawing.
