### ISSUE TITLE
RadListView throwing an error NullInjectorError: No provider for RadListViewComponent!

### ISSUE THREAD

**Issue by spmamidi** [telerik/nativescript-ui-feedback#675]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
RadListView throwing an error when showing modal dialog by tap of item.

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version: latest version**
- **CLI: 4.0.2** (run `tns --version` to fetch it)
- **Cross-platform modules: latest** (the version of tns-core-modules in the `package.json`)
- **Runtime(s): 4.0.1** (the `"tns-android"` and `"tns-ios"` properties in the `package.json`)

### Please tell us how to recreate the issue in as much detail as possible.
1. By Clicking on item, we are showing modal dialog using modal dialog component. We had listview it's working fine with listview.

> StaticInjectorError(AppModule)[TKListViewItemDirective -> RadListViewComponent]: \n  StaticInjectorError(Platform: core)[TKListViewItemDirective -> RadListViewComponent]: \n    NullInjectorError: No provider for RadListViewComponent!

Stack trace:
get@file:///app/tns_modules/@angular/core/bundles/core.umd.js:1041:28 [angular]\nresolveToken@file:///app/tns_modules/@angular/core/bundles/core.umd.js:1339:27 [angular]\ntryResolveToken@file:///app/tns_modules/@angular/core/bundles/core.umd.js:1281:28 [angular]\nget@file:///app/tns_modules/@angular/core/bundles/core.umd.js:1149:35 [angular]\nresolveToken@file:///app/tns_modules/@angular/core/bundles/core.umd.js:1339:27 [angular]\ntryResolveToken@file:///app/tns_modules/@angular/core/bundles/core.umd.js:1281:28 [angular]\nget@file:///app/tns_modules/@angular/core/bundles/core.umd.js:1149:35 [angular]\ncreateClass@file:///app/tns_modules/@angular/core/bundles/core.umd.js:12521:39 [angular]\ncreateDirectiveInstance@file:///app/tns_modules/@angular/core/bundles/core.umd.js:12364:48 [angular]\ncreateViewNodes@file:///app/tns_modules/@angular/core/bundles/core.umd.js:13822:76 [angular]\ncallViewAction@file:///app/tns_modules/@angular/core/bundles/core.umd.js:14256:28 [angular]\nexecComponentViewsAction@file:///app/tns_modules/@angular/core/bundles/core.umd.js:14165:27 [angular]\ncreateViewNodes@file:///app/tns_modules/@angular/core/bundles/core.umd.js:13850:29 [angular]\ncreateRootView@file:///app/tns_modules/@angular/core/bundles/core.umd.js:13711:20 [angular]\ncallWithDebugContext@file:///app/tns_modules/@angular/core/bundles/core.umd.js:15136:47 [angular]\ncreate@file:///app/tns_modules/@angular/core/bundles/core.umd.js:11316:60 [angular]\ncreateComponent@file:///app/tns_modules/@angular/core/bundles/core.umd.js:11513:68 [angular]\nloadInLocation@file:///app/tns_modules/nativescript-angular/common/detached-loader.js:21:61 [angular]\nloadComponent@file:///app/tns_modules/nativescript-angular/common/detached-loader.js:38:35 [angular]\nshowDialog@file:///app/tns_modules/nativescript-angular/directives/dialogs.js:67:49 [angular]\nfile:///app/tns_modules/nativescript-angular/directives/dialogs.js:32:53 [angular]\nonInvokeTask@file:///app/tns_modules/@angular/core/bundles/core.umd.js:4789:43 [angular]\ninvoke@file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:460:45 [angular]\ntimer@file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:1636:34 [angular]\ninvoke@file:///app/tns_modules/tns-core-modules/timer/timer.js:54:53 [angular]\nonInvoke@file:///app/tns_modules/@angular/core/bundles/core.umd.js:4798:39 [angular]\ntick@file:///app/tns_modules/tns-core-modules/timer/timer.js:19:26 [<root>]\nUIApplicationMain@[native code] [<root>]\nstart@file:///app/tns_modules/tns-core-modules/application/application.js:264:26 [<root>]\nbootstrapApp@file:///app/tns_modules/nativescript-angular/platform-common.js:86:28 [<root>]\nbootstrapModule@file:///app/tns_modules/nativescript-angular/platform-common.js:72:26 [<root>]\nanonymous@file:///app/main.js:34:57 [<root>]\nevaluate@[native code] [<root>]\nmoduleEvaluation@[native code] [<root>]\n[native code] [<root>]\npromiseReactionJob@[native code] [<root>]

**Comment by tsonevn** [comment]
Hi @spmamidi,
Can you check if you will have the same issue while using the latest NativeScript 4.1? You can review our [update instructions](https://docs.nativescript.org/releases/upgrade-instructions). If the problem persists, please provide sample project, which could be used for debugging.

**Comment by erkanarslan** [comment]
@spmamidi I also have this problem. How did you fix it?
I use Nativescript 4.1 btw.

**Comment by erkanarslan** [comment]
I found the problem. Documentation [in this link](http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/ListView/item-layouts) is not clear enough. I though that I need to replace RadListView tag with ListViewGridLayout as it looks like a different element. Instead this element should be placed inside the RadListView tag:

<ListViewStaggeredLayout tkListViewLayout scrollDirection="Vertical" spanCount="1"></ListViewStaggeredLayout>

This is not very intuitive and documentation is not clear enough.
