### ISSUE TITLE
[Feature request] Option to change the fillColor for each Bar in the series

### ISSUE THREAD

**Issue by tsonevn** [telerik/nativescript-ui-feedback#679]
Ability to change the fillColor of each bar in the series individually. Currently, we can change the colour of the whole series.
![series_styling_android](https://user-images.githubusercontent.com/17448734/40642800-cf0acc90-6326-11e8-9c87-eebaa57f2104.png)

Edit:
The suggestion is to have a collection of colours, which can be used for specifying the colour of each bar. Similar to the [RadPieChart](https://github.com/telerik/nativescript-ui-samples/blob/master/chart/app/examples/styling/styling-pie-series-page.xml#L32-L42) and the way how the `fillColor` is defined for each piece of it.

t.1169389

**Comment by tgpetrov** [comment]
Released in nativescript-ui-chart@3.11.0
NativeScript Core: [docs](https://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/Chart/Series/styling#palettemode), [sample](https://github.com/telerik/nativescript-ui-samples/blob/master/chart/app/examples/styling/styling-bar-series-page.xml)
NativeScript Angular: [docs](https://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/Chart/Series/styling#palettemode), [sample](https://github.com/telerik/nativescript-ui-samples-angular/blob/master/chart/app/examples/styling/chart-styling-bar-series.component.html)
