### ISSUE TITLE
Can't unselect (out of focus) from DataForm elements: picker, date, time

### ISSUE THREAD

**Issue by Nogostradamus** [telerik/nativescript-ui-feedback#684]
### Did you verify this is a real problem by searching the [NativeScript Forum]
Yes

### Tell us about the problem
I'm using DataForm with different types of fields. Some fields like DatePicker, TimePicker, Picker when selected occupy whole data form and there is no way to choose/unselect/go back to the form. This is happening only on iOS. Android is just fine. Looks like bottom page native controls are missing. When I use simple text I see that bar with next/previous but it's not working for the types I mentioned above. Do I need to enable that? Strange that I haven't found similar issue on the forum. Maybe I miss something.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** nativescript-ui-dataform": 3.6.0
- **CLI:** 4.1.0
- **Cross-platform modules:** 4.0.1
- **Runtime(s):** "version": "4.1.0"

### Please tell us how to recreate the issue in as much detail as possible.
Just implement one of the data types in form and test on ios.

<img width="284" alt="screen shot 2018-06-02 at 14 47 04" src="https://user-images.githubusercontent.com/11678754/40877152-e5d0b87c-6673-11e8-995c-d626ec61bf9a.png">

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
```
<StackLayout class="form" padding="15">
                <RadDataForm #myEventDataForm [source]="input" (editorUpdate)="dfEditorUpdate($event)"
                             propertyCommitted="dfPropertyCommitted">
                    <TKEntityProperty tkDataFormProperty name="date" index="0">
                        <TKPropertyEditor tkEntityPropertyEditor type="DatePicker">
                            <TKPropertyEditorStyle tkPropertyEditorStyle labelTextSize="16" labelTextColor="#FBBE07"
                                                   fillColor="#3E3E3E"></TKPropertyEditorStyle>
                        </TKPropertyEditor>
                    </TKEntityProperty>
                    <TKEntityProperty tkDataFormProperty name="time" index="1">
                        <TKPropertyEditor tkEntityPropertyEditor type="TimePicker">
                            <TKPropertyEditorStyle tkPropertyEditorStyle labelTextSize="16" labelTextColor="#FBBE07"
                                                   fillColor="#3E3E3E"></TKPropertyEditorStyle>
                        </TKPropertyEditor>
                    </TKEntityProperty>
                </RadDataForm>
                <ActivityIndicator id="myIndicator" *ngIf="isBusy" busy="true"></ActivityIndicator>
                <Button class="btn btn-primary w-full" [isEnabled]="!isBusy" *ngIf="!edit_mode" text="Create" (tap)="create()"></Button>
            </StackLayout>
```

```
private setup_input(event) {
            this._input = new EventCrud(moment(), moment());
    }
    get input(): EventCrud {
        return this._input;
    }
dfEditorUpdate(data) {
        if (applicationModule.android) {
            const textAndroid = data.editor.getEditorView();
        const color = new Color("#fff");
        const textSize = 18;
        textAndroid.setTextColor(color.android);
        textAndroid.setTextSize(textSize);
        }
    }
```

**Comment by Nogostradamus** [comment]
I found a problem. I wrapped my RadDataForm with StackLayout. For plain Form only like in the examples it's working just fine. So how would you add a button to submit the form at the bottom of the form? And some other elements to the same page?
Also, FlexboxLayout flexDirection="column" has the same effect.
Do I need to specify min-height for RadDataForm? Is there a way to make that dynamic?

**Comment by shivgolani** [comment]
@Nogostradamus facing similar issue with RadDataForm height. Did you manage to find any solution.

**Comment by tsonevn** [comment]
Hi @Nogostradamus,
To display the DataForm properly, while using it inside a StackLayout, you should specify the component height. For example:
```
<RadDataForm #myUserDataForm row="0" height="200" [source]="user_input">
...
                    </RadDataForm>
```
Another option is, as you already did, to use GridLayout.
