### ISSUE TITLE
change fillcolor of indicator from js code (Gauge)

### ISSUE THREAD

**Issue by giorgi-abashidze** [telerik/nativescript-ui-feedback#688]
I want to change fillcolor of indicator depending on data,

```
let gaugeView = page.getViewById("gaugeView");
let scale = gaugeView.scales.getItem(0);
let barIndicator = scale.indicators.getItem(0);
barIndicator.indicatorStyle.fillColor='#008489';
```
after this when I log fillColor of indicator I see its changed but in the view there is still old color

there is no redraw or refresh?

**Comment by tsonevn** [comment]
Duplicate of #639
