### ISSUE TITLE
[Bug report] RadListView with `loadOnDemandMode`  will crash after navigation back from details page

### ISSUE THREAD

**Issue by tsonevn** [telerik/nativescript-ui-feedback#69]
While using RadListView with `loadOnDemandMode` setup and navigate back from the details page, the app will crash with the following error:
```
file:///app/tns_modules/nativescript-telerik-ui-pro/listview/listview.js:868:31: JS ERROR TypeError: undefined is not an object (evaluating 'value.view.itemView')
```
This behavior has been reproduced on NativeScirpt Angular 2 project.
Sample project could be found [here](https://github.com/skywidesoft/ns-radlistview-test.git).

**Comment by tushar-1health** [comment]
I am also facing the same issue. Need help to fix this.
+1

**Comment by ginev** [comment]
@tushar-1health, we have put this on our TODO list for the upcoming release.

**Comment by RyanSMurphy** [comment]
this is an issue. Paying for the pro version of telerik ui this should be prioritised.
