### ISSUE TITLE
Dataform Error after upgrading to Angular 6

### ISSUE THREAD

**Issue by yonkoGH** [telerik/nativescript-ui-feedback#690]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
after upgrading my project to angular 6 running a page with ui RadDataForm give me this  

"CONSOLE ERROR file:///app/tns_modules/@angular/core/bundles/core.umd.js:1682:24: ERROR Error: Uncaught (in promise): TypeError: null is not an object (evaluating 'this.page.ios')
createNativeView@file:///app/tns_modules/nativescript-ui-dataform/ui-dataform.js:665:36"

### Which platform(s) does your issue occur on?
ios Only

### Please provide the following version numbers that your issue occurs with:
-     Progress NativeScript UI version: nativescript-ui-dataform": "^3.6.0"
-     CLI: 4.1.0
-     Cross-platform modules: 4.1.0
-     Runtime(s): 4.1.0

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

```
<RadDataForm #addInvoiceDataForm commitMode="Immediate">
            <TKEntityProperty tkDataFormProperty name="invoiceNo" displayName="رقم الفاتورة" index="0">
                <TKPropertyEditor tkEntityPropertyEditor type="Text">
                    <TKPropertyEditorStyle tkPropertyEditorStyle labelPosition="Top"></TKPropertyEditorStyle>
                </TKPropertyEditor>
            </TKEntityProperty>
        </RadDataForm>
```

**Comment by tsonevn** [comment]
Hi @yonkoGH,
Please try the below-described steps and check if you will have the same issue:

1. remove the platform with `tns platform remove ios `;
2. delete `node_modules`, `hooks` and `package-lock.json` from the project.
3. remove the app from the device or simulator, which you are using for testing.
4. build again the app `tns run ios`

If the problem persists, please send us the project, which will allow us to recreate the issue.

**Comment by yonkoGH** [comment]
Still getting the same error
To be more specific the error occurs  when I try opening a modal page that contains a RadDataForm

thank you for your help

**Comment by simonettoa** [comment]
@yonkoGH yeah, same error! android works fine; I'm in the same situation using a modal page to show a data form, using for example the nativescript-ui-calendar works fine in both o.s. - waiting for a fix

**Comment by wanpeng2008** [comment]
same error on ios

**Comment by yonkoGH** [comment]
any news ??

**Comment by mhmo91** [comment]
any updates?

**Comment by mhmo91** [comment]
Hey team, ETA? 
we have an app to go live very soon n this issue is breaking most of our ios build, thanks!

**Comment by DimitarTodorov** [comment]
The issue is fixed with the latest release of nativescript-ui-dataform.
https://github.com/NativeScript/nativescript-ui-dataform/releases/tag/v3.6.2
