### ISSUE TITLE
[RadListView] [ios] App crashes when grouping is set and data is loaded async

### ISSUE THREAD

**Issue by PeterStaev** [telerik/nativescript-ui-feedback#696]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
When data is loaded async, the listview crashes the app if it has grouping set. When there is no grouping or the data is known beforehand it works as expected. 

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 3.5.7
- **Cross-platform modules:** 4.1
- **Runtime(s):** 4.1

### Please tell us how to recreate the issue in as much detail as possible.
1. Open the following playground: https://play.nativescript.org/?template=play-tsc&id=okC07h
2. There is a 2sec timeout that simulates async loading
3. After 2 secs the app will crash.

**Comment by punj** [comment]
Hello! 
Please confirm if new version is released and bug is solved. I am using "nativescript-ui-listview": "^8.1.2" but it crashes the same way.
