### ISSUE TITLE
RadListView iOS UI components not refreshing.

### ISSUE THREAD

**Issue by JaganJonnala** [telerik/nativescript-ui-feedback#697]
Hi,
Issue with iOS is that not refreshing the ui components as expected whereas the same code base is working fine with Android Platform. Checkout my below reference playground project try to select the items who are in Horizontal ScrollView.
Expected behavior is css and ui elements need to refresh its working fine with Android.

Help me out.
here is the sample playground project.

https://play.nativescript.org/?template=play-ng&id=rGobsZ

**Comment by tsonevn** [comment]
Hi @JaganJonnala,
I would suggest checking if the issue will be reproduced while using [ObservableArray](https://docs.nativescript.org/api-reference/classes/_data_observable_array_.observablearray). The pure JavaScript array most probably will not trigger the change detection.
