### ISSUE TITLE
[Bug Report] RadListView memory leak in NativeScirpt Angular2 project 

### ISSUE THREAD

**Issue by tsonevn** [telerik/nativescript-ui-feedback#70]
I tested this case with [nativescript-ui-samples-angular](https://github.com/telerik/nativescript-ui-samples-angular) app. 
When you navigate several times to `listview/item-layouts/listview-item-layouts-grid` the memory will not be released and will lead to crash after some period of time.
This issue could be reproduced only on iOS.

**Comment by VladimirAmiorkov** [comment]
Happens to [nativescript-ui-samples](https://github.com/telerik/nativescript-ui-samples) also so it is not an Angular only issue.

**Comment by ginev** [comment]
Can you check the same scenario using the following build:
[nativescript-ui-debug-dev-pro.zip](https://github.com/telerik/nativescript-ui-feedback/files/824369/nativescript-ui-debug-dev-pro.zip)

**Comment by sinzii** [comment]
Hi there,
Any update on this issue, my app's using RadListView and the memory leak issue still there.

Thank you.
