### ISSUE TITLE
RadListView iOS LoadOnDemandTemplate Broken

### ISSUE THREAD

**Issue by Ericky14** [telerik/nativescript-ui-feedback#701]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
When using the tkListLoadOnDemandTemplate for a custom template, the original loader is still displayed under the list when you pull it up.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 3.5.7
- **CLI:** 4.0.0
- **Cross-platform modules:** 4.0.1
- **Runtime(s):** 4.1.2

### Please tell us how to recreate the issue in as much detail as possible.
Use the custom template for loader on demand Auto mode on iOS.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
```
    <GridLayout backgroundColor="transparent" *tkListLoadOnDemandTemplate>
      <StackLayout backgroundColor="transparent">
      </StackLayout>
    </GridLayout>
```

**Comment by tsonevn** [comment]
HI @Ericky14,
Can you provide sample project, where the issue can be reproduced?
