### ISSUE TITLE
RadAutoCompleteTextView disable filtering suggestion

### ISSUE THREAD

**Issue by jannotabamo** [telerik/nativescript-ui-feedback#702]
Is there anyway to disable filtering suggestion? I want to display all the result fetch remotely. Without filtering it.

**Comment by NickIliev** [comment]
@jannotabamo [currently there are only two modes](https://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/AutoCompleteTextView/autocomplete-completion-modes) `contains` and `startsWith`as described here and all suggestions will be filtered based on these modes. There is no option to skip the filtering.

**Comment by joshcomley** [comment]
One year later, is this now possible? As fetching data remotely is supported, surely it follows that such a function would provide its own searching capabilities?

**Comment by uzarsalan** [comment]
Yes, it's possible. I've achieved it with this solution

First defined custom TokenModel class

```javascript 
class CustomTokenModel extends TokenModel {
  constructor(text, displayText, image) {
    super(text, image);
    this.displayText = displayText;
  }
}
```

Then we should add SuggestionView with displayText prop

```xml
<RadAutoCompleteTextView
ref="autocompleteView"
  >
    <SuggestionView ~suggestionView suggestionViewHeight="51">
      <StackLayout v-suggestionItemTemplate orientation="vertical">
        <v-template>
          <StackLayout>
            <Label :text="item.displayText"></Label>
          </StackLayout>
        </v-template>
      </StackLayout>
    </SuggestionView>
  </RadAutoCompleteTextView>
```
and last, loadAsyncSuggestions function

```javascript
async getSuggestions(text) {
      let suggestionsData = await this.getSuggestions(text);
      let suggestions = suggestionsData.map(item => new CustomTokenModel(text, item.someProp))
      return suggestions;
}
```
