### ISSUE TITLE
Iphone 5 OSX: 10.3.3 sidedrawer and listview crash the app

### ISSUE THREAD

**Issue by PraktikerNeosoft** [telerik/nativescript-ui-feedback#703]
When I upgrade depricated nativescript-pro-ui plugin to nativescript-ui-listview and nativescript-ui-siderawer then I have a problem with my app.
When I play with xcode then iphone 5 is ok no error.
When I publish tetflight or start app from phone then crash the app.
I cant get error only quit the app.

**Comment by NickIliev** [comment]
@PraktikerNeosoft is there an error log that you can share with us?
