### ISSUE TITLE
RadListView StaggeredLayout No Height

### ISSUE THREAD

**Issue by Ericky14** [telerik/nativescript-ui-feedback#704]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
When using StaggeredViewLayout and adding/removing items, all of the items collapse together at the top and then expand again, which means they are having no height. If I set an itemHeight, it will work, but I need the heights to vary.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 3.5.7
- **CLI:** 4.0.0
- **Cross-platform modules:** 4.0.1
- **Runtime(s):** 4.1.0

### Please tell us how to recreate the issue in as much detail as possible.
Have the RadListView with any layout without a fixed height and add more items using an observable array.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
```
  <RadListView #recentContactsList class="card-list" scrollPosition="Top" backgroundColor="transparent" (itemLoading)="onItemLoading($event)" [items]="recentContacts"
      selectionBehavior="None" swipeActions="true" (itemSwipeProgressChanged)="onCellSwiping($event, true)" (itemSwipeProgressStarted)="onSwipeCellStarted($event, true)">
      <ListViewStaggeredLayout tkListViewLayout scrollDirection="Vertical" spanCount="1"></ListViewStaggeredLayout>

      <ng-template tkListItemTemplate let-item="item">
        <GridLayout class="card">
          <ink-card [card]="item?.otherCard"></ink-card>
          <StackLayout (tap)="viewContact(item?.otherCard.username, item?.otherCard.id)"></StackLayout>
        </GridLayout>
      </ng-template>

      <ng-template tkListViewFooter>
        <GridLayout backgroundColor="transparent">
          <Button class="action-button" [class.hidden]="!canLoadMoreRecentContacts || !recentContactsLoaded" text="View More" (tap)="getRecentContacts(false)"></Button>
        </GridLayout>
      </ng-template>

      <GridLayout *tkListItemSwipeTemplate columns="auto">
        <GridLayout id="button-view" (tap)="deleteConnection($event)">
          <Label class="btn icon" [text]="'\ue81c'" verticalAlignment="center"></Label>
        </GridLayout>
      </GridLayout>
    </RadListView>
```

**Comment by NickIliev** [comment]
@Ericky14 this is a known limitation on iOS where the cells should have a predefined size (which is the reason why 'itemHeight' exists for async data). As the items in the list will be recycled and virtualized it seems that on iOS the table view controlled needs a predefined size for each of its cells. So using the 'itemHeight' is the way to go. There is no option to vary the size of the cells when the `itemHeight` is set.
