### ISSUE TITLE
ui-listview load-on-demand auto scroll to top

### ISSUE THREAD

**Issue by bhavincb** [telerik/nativescript-ui-feedback#706]
when loading items on demand in RadListView. adding more item automatically scrolls to the top.
here is playground demo:[https://play.nativescript.org/?template=play-ng&id=E2d9wx&v=2](https://play.nativescript.org/?template=play-ng&id=E2d9wx&v=2)

**Comment by cnoter** [comment]
same here~

**Comment by nmongiya** [comment]
Even though I am using
`get dataItems(): ObservableArray<OrderInfo> {
        return this._dataItems;
    }`
I am facing the same issue.

**Comment by cnoter** [comment]
@nmongiya so now I'm just using nativescript listview(not rad listview) :)

**Comment by NickIliev** [comment]
+1 Reported via t-1340205 @VladimirAmiorkov @tgpetrov  let me know if you need a reproducible scenario

**Comment by suisseworks** [comment]
I'm using RadListView in my proyect and I have problems with this Issue.
