### ISSUE TITLE
bar chart series all values starting from min value from data not from 0 (ios)

### ISSUE THREAD

**Issue by NickIliev** [telerik/nativescript-ui-feedback#709]
_From @giorgi-abashidze on June 22, 2018 13:2_

in bar chart series all values starting from min value of data not from 0, on IOS only, on android it's ok.

it looks like this: [https://ibb.co/ksfVuo](https://ibb.co/ksfVuo)

I want to show data like this: [https://ibb.co/ii3NQT](https://ibb.co/ii3NQT)

maybe its not a bug and it have option for this, I don't know.

_Copied from original issue: NativeScript/NativeScript#5984_

**Comment by giorgi-abashidze** [comment]
ok I achieve this with minimum and maximum properties I'm finding minimum and maximum from data and i'm seting it to chart  

`<chart:LinearAxis maximum="{{topChartMAx}}" minimum="{{topChartMin}}" />`

but now problem is data change, on data change the lienear axis not updating correctly,
its look like this:
[https://ibb.co/kAaGC8](https://ibb.co/kAaGC8)

**Comment by NickIliev** [comment]
@giorgi-abashidze consider providing a sample project or Playground so that the issue can be debugged with the actual code used.
