### ISSUE TITLE
pie chart legend height are not updating on data change

### ISSUE THREAD

**Issue by giorgi-abashidze** [telerik/nativescript-ui-feedback#710]
pie chart legend height are not updating on data change, for example if I have data with 2 legend and then update to more big data with 8 legends

the legend container have same height after update, it shows only 2 legend names

**Comment by tsonevn** [comment]
Hi @giorgi-abashidze,
Can you isolate the issue in a sample project? It will help if you send us a sample, which can be used for debugging.

**Comment by kalininskiy** [comment]
same problem

**Comment by tsonevn** [comment]
HI @kalininskiy,
Can you provide a sample project, which can be used for recreating the issue? I will reopen the issue if we have a sample, which we can review and can be used for confirming that there is a real problem.

**Comment by danouche93** [comment]
Hi, I have the same problem on iOS. Has any have found a solution ???
