### ISSUE TITLE
[nativescript-ui-listview] Tapping the default group header throws exception

### ISSUE THREAD

**Issue by VladimirAmiorkov** [telerik/nativescript-ui-feedback#712]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
Getting this error when tapping the default group item:

> An uncaught Exception occurred on “main” thread.
> com.tns.NativeScriptException: 
> Calling js method onItemIsSelectedChanged failed
> 
> Error: Item must be an object from the currently assigned source.
> File: “file:///data/data/org.nativescript.demo/files/app/tns_modules/nativescript-ui-listview/ui-listview.js, line: 646, column: 12
> 
> StackTrace: 
>     Frame: function:‘RadListView.getViewForItem’, file:‘file:///data/data/org.nativescript.demo/files/app/tns_modules/nativescript-ui-listview/ui-listview.js’, line: 646, column: 19
>     Frame: function:‘onItemIsSelectedChanged’, file:‘file:///data/data/org.nativescript.demo/files/app/tns_modules/nativescript-ui-listview/ui-listview.js’, line: 1352, column: 41

### Which platform(s) does your issue occur on?
Android

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the "grouping-multiple-templates" [example](https://github.com/telerik/nativescript-ui-samples-angular/tree/master/listview/app/examples/grouping-multiple-templates) 
2. Tap the "Category 1" label

**Comment by zbranzov** [comment]
The fix is available in v3.5.10
