### ISSUE TITLE
multiple selection on the list editor of the dataform

### ISSUE THREAD

**Issue by joey0xx** [telerik/nativescript-ui-feedback#722]
Is it possible to do multiple selection on the list editor of the dataform?

**Comment by NickIliev** [comment]
@joey0xx I guess that we are talking about the `Picker` type for a `PropertyEditor` and the thing is that the native controls that are used behind this editor are not allowing multiple selections (I guess from UX perspective it would be hard to make multiple selection on a mobile phone from a drop-down list ..perhaps the better solution is to use a list of checkboxes or similar)

**Comment by joey0xx** [comment]
Hello @NickIliev thank you for the response.

I was talking about the `List` type.

**Comment by cparkinsonMYCM** [comment]
@NickIliev ditto, can we select multiple options from a _list _editor__ in the RadDataForm?
