### ISSUE TITLE
[RadListView] [Android] App crashes when grouping is set and data is loadedOnDemand

### ISSUE THREAD

**Issue by nmongiya** [telerik/nativescript-ui-feedback#723]
"tns-android": {"version": "4.1.3"}
"nativescript-ui-listview": "^3.5.8",

**Comment by tsonevn** [comment]
HI @nmongiya,
Can you provide sample project, which demonstrates the issue?

**Comment by nmongiya** [comment]
Hi @tsonevn I have realised that crash was because of our code issue. 
I have set the loadOnDemandMode="Auto" and when user scrolls very fast app makes couple of calls to onLoadMoreItemsRequested function and our Server was returning some messed up data. 
So the question here can we control the number of onLoadMoreItemsRequested calls if loadmoredemand is Auto

**Comment by tsonevn** [comment]
Hi @nmongiya,
In this case, I would suggest to set up the `loadOnDemandMode` to `Manual `. This will allow executing the [loadOnDemand](https://github.com/telerik/nativescript-ui-samples-angular/blob/master/listview/app/examples/load-on-demand/dynamic-size-manual/listview-dynamic-size-manual.component.html) only when the user reaches the end of the ListView and tap on the Button for loading more items.

**Comment by nmongiya** [comment]
thanks @tsonevn
