### ISSUE TITLE
RadListView crashing when pushing items too quickly one after another

### ISSUE THREAD

**Issue by NordlingArt** [telerik/nativescript-ui-feedback#73]
_Copy of: https://github.com/telerik/nativescript-ui-samples/issues/176_

**Platform:** iOS
**TNS:** 2.5.1

This fatal error appears quite frequently when pushing items one after another asynchronously:

`*** Assertion failure in -[TKCollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3600.6.21/UICollectionView.m:5634`

This means I cannot animate incoming items because I have to avoid this error by loading every items synchronously and THEN attach the items ObservableArray to the RadListView.

I have seen people getting this problem before, but recently the support for nativescript-telerik-ui has been near non-existent. Can this be fixed somehow?

Thanks in advance

**Comment by ginev** [comment]
@NordlingArt,

is there a way for you to isolate the issue in a separate project so that we can directly take a look at the code and see what we can do? There is a known case in which UICollectionView throws similar errors with dynamic item updates and animations but we need to reproduce it to see how we can help.

Thanks!

**Comment by NordlingArt** [comment]
@ginev - Seems like a cannot replicate the issue in another project. Apparently this is happening when a certain plugin ([nativescript-dev-sass](https://github.com/toddanglin/nativescript-dev-sass)) runs its hooks which initiates multiple livesync instances. Don't know if it's an exclusive issue for that plugin, or if all hooks trigger this issue.

To clarify, this issue happens when there are multiple livesync instances to the same project. It might be a bug in the CLI, but I also think RadListView should be doing a double check somehow so it doesn't its code multiple times at the same time.

**Comment by tsonevn** [comment]
I tested this case with https://github.com/telerik/nativescript-ui-samples/tree/release/sdk/app/listview/observable-array sample and was unable to recreate this behavior. 
If the problem still persists, please provide sample app and I will reopen it.
