### ISSUE TITLE
AutoCompleteTextView - modify array of tokens if a token is selected / removed

### ISSUE THREAD

**Issue by suparnavg** [telerik/nativescript-ui-feedback#735]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
_Please, ensure your title is less than 63 characters long and starts with a capital
letter._
AutoCompleteTextView should dynamically change the list of available tokens.

### Which platform(s) does your issue occur on?
Android 

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version: 3.6.0
- **CLI:** 4.1.0
- **Cross-platform modules:** 4.2.0-2018-06-29-01
- **Runtime(s):** '"tns-android"` "version": "4.1.3"

### Please tell us how to recreate the issue in as much detail as possible.
1. Include the `RadAutoCompleteTextView` component in your application, load with data items (normal implementation).
On selecting a token, it should get removed from the array of available tokens (so it cannot be selected again). On removing a token, it should get added back into the array of available tokens.

I tried to do this with the following snippet to filter the ObservableArray<TokenModel> on the token added / removed events with the following error:

Snippet:
```
public onTokenAdded(args) {
        // Do something with the args
        // Filter the ObservableArray
        this._items = this.filterTokenArray(args.token.text);
}

filterTokenArray(compare): ObservableArray<TokenModel> {
        return this._items().map(items => items.filter(item => item.text !== compare));
}

```

Error: Cannot invoke an expression whose type lacks a call signature. Type 'ObservableArray<TokenModel>' has no compatible call signatures

Opening this as a potential feature here because this seems like a pretty common requirement.. dynamically changing the array of available tokens will make for a better UX. Maybe there can be flag in the RadAutoCompleteTextView to turn this feature on / off.

**Comment by NickIliev** [comment]
@suparnavg what is `this.items()` in your code? Is that a **method** from the view model or a **`property`**. The error indicates that the you are propbely misusing the items property (which is of type ObesrvableArray)

If this is a property the expresion should be rewruitten as follows:
```
 this.items.map(items => items.filter(item => item.text !== "Bulgaria"));
```

**Comment by suparnavg** [comment]
@NickIliev sorry for that mistake on my part. It is in fact a property of type ObservableArray<TokenModel> and I made the change you suggested.

For future readers, I implemented this like so:

```
public onTokenAdded(args) {
        // Do something
        this.filterTokenArray(args.token.text);
    }
filterTokenArray(compare) : void {
        var array : ObservableArray<TokenModel> = new ObservableArray();
        this._items.map(item => {
            if (item.text !== compare) {
                array.push(new TokenModel(item.text, null));
            }
        });
        this._items = array;
    }
```

And a similar map function to add the token back to _items when it is deselected. Thanks @NickIliev !
