### ISSUE TITLE
RadDataForm AutoCompleteInline Works differently by platform iOS/Android

### ISSUE THREAD

**Issue by marcelomiranda90** [telerik/nativescript-ui-feedback#738]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
AutoCompleteInline works differently on each platform.

In iOS, plain mode returns no value to the model and in tokens mode always returns a string of the last value entered.

In android the plain mode returns a string as expected and in token mode no value is returned.

This causes you to have to use code for each platform, not giving you the confidence that it will work well in the next updates.

### Which platform(s) does your issue occur on?
Both
iOS 11 and Android 7.0

### Please provide the following version numbers that your issue occurs with:
{
    "tns-android": {
      "version": "4.1.3"
    },
    "tns-ios": {
      "version": "4.1.1"
    }
  },
  "dependencies": {
    "@angular/common": "~6.0.6",
    "@angular/compiler": "~6.0.6",
    "@angular/core": "~6.0.6",
    "@angular/forms": "~6.0.6",
    "@angular/http": "~6.0.6",
    "@angular/platform-browser": "~6.0.6",
    "@angular/platform-browser-dynamic": "~6.0.6",
    "@angular/router": "~6.0.6",
    "nativescript-angular": "^6.0.6",
    "nativescript-cardview": "^3.0.1",
    "nativescript-iqkeyboardmanager": "^1.3.0",
    "nativescript-plugin-firebase": "^5.3.1",
    "nativescript-ratings": "^1.0.1",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-toast": "^1.4.6",
    "nativescript-ui-chart": "^3.6.1",
    "nativescript-ui-dataform": "~3.5.2",
    "nativescript-ui-listview": "^3.5.8",
    "nativescript-ui-sidedrawer": "^4.1.1",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~6.0.0 || >=6.1.0",
    "tns-core-modules": "^4.1.0",
    "zone.js": "^0.8.20"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~6.1.0-beta.3",
    "@ngtools/webpack": "6.1.0-rc.0",
    "babel-traverse": "6.18.0",
    "babel-types": "6.18.0",
    "babylon": "6.13.1",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-typescript": "^0.7.1",
    "nativescript-dev-webpack": "^0.14.4",
    "typescript": "~2.7.2"
  }
}

### Please tell us how to recreate the issue in as much detail as possible.

You can test this project on NS Playground on each platform and check how it works differently, I do not know if I need to change anything in my code.

https://play.nativescript.org/?template=play-ng&id=AacR7f

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
https://play.nativescript.org/?template=play-ng&id=AacR7f
![whatsapp image 2018-07-16 at 21 21 08 1](https://user-images.githubusercontent.com/30594073/42790162-e01a8b30-893f-11e8-9065-3d0b277e62f2.jpeg)
![whatsapp image 2018-07-16 at 21 21 08](https://user-images.githubusercontent.com/30594073/42790163-e03db3b2-893f-11e8-8b00-ca06992cfbc8.jpeg)

**Comment by NickIliev** [comment]
Confirming this behavior as unexpected and marking this one as a bug. Apart from the Playground provided by @marcelomiranda90 the issue can be tested with [this application](https://github.com/NickIliev/NS-Issues-2018-II/tree/master/nativescript-ui-feedback/issue-738).

Result:: on iOS from both inline editors only the value of the second one can be obtained (token mode) via `getPropertyByName` (works as expected on Android where both values can be accessed)

**Comment by DimitarTodorov** [comment]
The issue is fixed with the latest release of nativescript-ui-dataform.
https://github.com/NativeScript/nativescript-ui-dataform/releases/tag/v3.6.2

**Comment by gomeschristopher** [comment]
I still have the same problem in IOS
