### ISSUE TITLE
Allow RadAutoCompleteTextView to remove the clear button ("X") [Android]

### ISSUE THREAD

**Issue by NickIliev** [telerik/nativescript-ui-feedback#74]
Client request from t.1094932

Currently, we have exposed a **showCloseButton** boolean property for RadAutoCompleteTextView but at this point, it is only supported in iOS (according to the API reference). 
Explore the opportunities **for enabling this functionality for Android** as well (for both Plain and Token modes) and also validate how it works in **Plain** mode for iOS as of this moment it only works in **Token** mode (with explicitly set close image source)

**Comment by Natalia-Hristova** [comment]
This feature will be available in our next official release. If you want to test it out before that you can use the "next" version of the nativescript-telerik-ui-pro plugin. Simply install that version of the plugin: ``` tns plugin add nativescript-telerik-ui-pro@next``` . 

**NOTE** that the next version is updated on daily/hourly basis from our current development brach which makes it not a good option for production applications but it is a great way to verify fixes and test new functionality.
