### ISSUE TITLE
iOS: incorrect item sizes with horizontal RadListView (>= 3.5.10)

### ISSUE THREAD

**Issue by felix-idf** [telerik/nativescript-ui-feedback#740]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
_Yes_

### Tell us about the problem
Our horizontal RadListView does not work properly on iOS anymore since the latest version (3.5.10), as the items have a wrong itemWidth (or they are overlapping each other?):

![screen shot 2018-07-18 at 15 51 13](https://user-images.githubusercontent.com/6443021/42887568-8963c974-8aa6-11e8-8470-598b1669e648.png)

This is what I am doing:
```
<lv:RadListView
                height="50"
                items="{{ myItems }}"
                itemLoading="onItemLoading">
            <lv:RadListView.listViewLayout>
                <lv:ListViewLinearLayout scrollDirection="Horizontal"/>
            </lv:RadListView.listViewLayout>
            <lv:RadListView.itemTemplate>
                <StackLayout orientation="horizontal">
                    <Button text="{{ name }}" color="yellow" backgroundColor="blue" margin="5" ios:borderRadius="5"/>
                </StackLayout>
            </lv:RadListView.itemTemplate>
</lv:RadListView>
```

```
myItems: new observableArrayModule.ObservableArray([
        { id: "1", name: "Item 1"},
        { id: "2", name: "Second item"},
        { id: "3", name: "Item No 3"},
        { id: "4", name: "A very long item"},
        { id: "5", name: "Item 5"}
])
```

Note, that this issue does not occur, when the button texts are hardcoded in the xml (without any binding to the name property).

The issue also did not occur on previous RadListView version:
![screen shot 2018-07-18 at 16 15 32](https://user-images.githubusercontent.com/6443021/42888002-8729275c-8aa7-11e8-9c9c-56fbfc92dd45.png)

### Which platform(s) does your issue occur on?
_iOS_ (tested with iOS 10 & 11)

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** nativescript-ui-listview 3.5.10
- **CLI:** 4.1.2
- **Cross-platform modules:** 4.1.0
- **Runtime(s):** tns-android 4.1.3, tns-ios 4.1.2

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
[RadListViewHorizontalIOS.zip](https://github.com/telerik/nativescript-ui-feedback/files/2206203/RadListViewHorizontalIOS.zip)

**Comment by VladimirAmiorkov** [comment]
Hi @felix-idf ,

thank you for reporting this. I will take a look and update you once I have more information.

**Comment by VladimirAmiorkov** [comment]
Made PR, awaiting review.
