### ISSUE TITLE
Why do i have to struggle to change the color of an editor!

### ISSUE THREAD

**Issue by mhmo91** [telerik/nativescript-ui-feedback#742]
The issue is there's an issue that was not suppose to be an issue, whoever designed this directive TKPropertyEditorStyle, why would u give me the option to change everything except the color of the values? why do i have to struggle for hours just to change the color of the editor? 

Everyday i struggle with pro ui components, simple functionalities available in NS ui components are missing, n i have to struggle to get them working, and when it works on android, it's broken on ios, basic practical use cases have never been tested!!!

That's just a sample of tons of challenges everyday!

Me as a developer, this is by far the worst development experience i got so far using your PRO KIT, issues n basic functionalities missing or either reported months ago n no one is doing anything.

your components are free, but not open source, so i'm not paying for a premium reliable service that i can have the right to complain when it's broken, nor i get something for free that works, nor it's open source so everyone can contribute to it... 

thanks NS pro for wasting our time n money!

**Comment by mhmo91** [comment]
Look at this!!!!
over 1 n half year ago!!!
https://www.telerik.com/forums/custom-styling-of-tkpropertyeditor-text

**Comment by mhmo91** [comment]
Hey team, sorry for leashing out, i was so frustrated the other day, i appreciate all the work you are doing, i'm just saying the pro ui should be open source se everyone can improve them ))

**Comment by leocrawf** [comment]
It appears you have to be great at java to make these changes. Just forget about the dataForm and build your own form components. At least you can style it however you want though you have to manually validate but you can use something like https://github.com/jquense/yup for validation.

**Comment by NickIliev** [comment]
@mhmo91 sorry to hear that you have troubles while applying some features that are not yet accessible out-of-the-box for nativescript-ui-dataform. The UI team is constantly working on a number of features. triaging and fixing bugs and implementing new functionalities.  Our current process is to plan the most wanted features and work on them with priority. 

For your convenience, I am opening [this feature request ](https://github.com/telerik/nativescript-ui-feedback/issues/763) where you could upvote the wanted feature
