### ISSUE TITLE
Support different text sizes inside SegmentedEditor

### ISSUE THREAD

**Issue by yoat** [telerik/nativescript-ui-feedback#743]
First, I know this may not be possible and it won't be straightforward to implement or use in any case. Close if that's appropriate, I just wanted to bring it up.

Here's my example code:
```
<TKEntityProperty tkDataFormProperty name="type" displayName="Type" index="1" valuesProvider="Any, Thing1, Thing2, Thing3, Thing4">
    <TKPropertyEditor tkEntityPropertyEditor type="SegmentedEditor">
      <TKPropertyEditorStyle tkPropertyEditorStyle labelTextSize="6" textSize="6"></TKPropertyEditorStyle>
    </TKPropertyEditor>
  </TKEntityProperty>
```

The labelTextSize does give us complete control of the size of the label above the control.  The textSize is a non-existent field but the idea is that it would control the size of the elements inside the segmented editor.  For my example with 5 options there isn't room on normal portrait screens; the text gets wrapped even though it's single words.

The problem is that I have several options and I want (but don't need - I'll use something else) to use SegmentedEditor to display this list and have it look "good."  To look good I need to be able to fit the text by reducing the size.  I can't reduce the size.

On Android NativeScript uses the radio button control, which doesn't take specific sizes but has an enum of options (https://stackoverflow.com/questions/28178789/android-how-can-i-change-the-text-size-of-dynamically-created-radio-buttons). We'd either give numbers that translate to enum values, or provide the enum values, so not straightforward to use.

On iOS NativeScript uses UISegmentedControl, which doesn't appear to have any size control at all (https://developer.apple.com/documentation/uikit/uisegmentedcontrol/1618570-settitletextattributes?changes=_3). That might be a dealbreaker.

Thanks for your time!

**Comment by tgpetrov** [comment]
Hi @yoat 
The nativescript-ui-dataform now supports css styling. You can use it to customize the size of any editor. [Here's more](https://docs.nativescript.org/angular/ui/professional-ui-components/ng-DataForm/dataform-styling#css) about this feature.
