### ISSUE TITLE
RadListView ng-template broken on 3.5.10.

### ISSUE THREAD

**Issue by nickcabral** [telerik/nativescript-ui-feedback#745]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
nativescript-ui-listview version 3.5.10 breaks ng-template bindings on iOS with NS-angular.
More info can be seen here: [link](https://github.com/NativeScript/NativeScript/issues/6087).

### Which platform(s) does your issue occur on?
iOS (haven't yet investigated android)

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 3.5.10
- **CLI:** 4.1.2
- **Cross-platform modules:** 4.1.1
- **Runtime(s):** ios: 4.1.0 android: 4.1.3

### Please tell us how to recreate the issue in as much detail as possible.
1. Clone the [NS UI angular samples repo](https://github.com/telerik/nativescript-ui-samples-angular/tree/master/listview).
2. Run the listview sample with `tns run ios`.
3. Observe broken `nsRouterLinks`, slow list performance, unpredictable list contents, and console output similar to:
```
CONSOLE ERROR [native code]: ERROR TypeError: undefined is not an object (evaluating '_v.context.item')
CONSOLE ERROR [native code]: ERROR CONTEXT {
"view": {
"def": {
"nodeFlags": 1,
"rootNodeFlags": 1,
...
```

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
See steps above.

**Comment by anuragd7** [comment]
+1 . Am experiencing this too.

**Comment by anuragd7** [comment]
Hi  @VladimirAmiorkov , Thanks for the update. Can confirm that switching to 3.5.9 resolves this issue. However 3.5.10 contained [this important fix](https://github.com/telerik/nativescript-ui-feedback/issues/496) that I have been waiting for, so would be great if we could have a new fix soon. Thanks.

**Comment by VladimirAmiorkov** [comment]
Hi @anuragd7 ,

Thank for testing the previous version. we understand you and we will do our best to resolve this issue and the related https://github.com/telerik/nativescript-ui-feedback/issues/740 as soon as possible. Stay tuned for the next version.

**Comment by rchougui** [comment]
I was having same issue and lag on ios, rolling back to nativescript-ui-listview v3.5.9  fixed it

**Comment by VladimirAmiorkov** [comment]
Made PR, awaiting review.
