### ISSUE TITLE
 itemReorderStartingEvent or itemReorderStartedEvent do note fire

### ISSUE THREAD

**Issue by bradrice** [telerik/nativescript-ui-feedback#749]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Did you verify this is a real problem by searching the [NativeScript Forum]
Yes and I asked for help there

### Tell us about the problem
Cannot get those two events to fire in an Angular application

### Which platform(s) does your issue occur on?
iOS, haven't tried Android

### Please provide the following version numbers that your issue occurs with:
Telerik package
"nativescript-ui-listview": "3.5.9",
- **CLI:** 
4.1.2
- **Cross-platform modules:** 
"tns-core-modules": "^4.1.1",
- **Runtime(s):** 
"tns-ios": {
      "version": "4.1.1"
    }

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application ..
2. Try to reorder items with the about event handlers

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
I’ve tried and can’t seem to get that event to fire.

<RadListView #dragList [items]="dataItems" 
			itemReorder="true" 
			(itemReordered)="onItemReordered($event)" 
			(itemReorderStartingEvent)="onItemReorderStarted($event)"
			[itemTemplateSelector]="templateSelector"
			reorderMode="Drag"
			>
public onItemReorderStarted(args: ListViewEventData){
        let item = this._dataItems.getItem(+args.index);
        console.log("On Item Reorder Started");
        if (item['key'] === 'category'){
            return args.returnValue = false;
        }
    }
I never see a console.log in my terminal when I start reordering.

**Comment by tsonevn** [comment]
HI @bradrice,
You should remove `Event` from the event listener name. The listener should e register as follow:
```
<RadListView #dragList [items]="dataItems"
itemReorder="true"
(itemReordered)="onItemReordered($event)"
(itemReorderStarting)="onItemReorderStarted($event)"
[itemTemplateSelector]="templateSelector"
reorderMode="Drag"
>
```
