### ISSUE TITLE
[RadCalendar]: Is there any way to pass dates and prevent to be selected?

### ISSUE THREAD

**Issue by relez** [telerik/nativescript-ui-feedback#756]
Hi there, I am using Calendar in my projects and somehow I need to disable certain dates to prevent to be selected by the user. Is there any way to get to this approach or at least to highlight those dates?

Thanks!

**Comment by NickIliev** [comment]
@relez you could use the `dateSelected` event to implement additional logic (e.g. UI that shows that the date can't be added to selection). Styling and disabling are logged sa features

Selection styling - Logged as feature [here](https://github.com/telerik/nativescript-ui-feedback/issues/574)
Slelection control - Logged as feature request [here](https://github.com/telerik/nativescript-ui-feedback/issues/476),

Closing as related to the above feature requests.
