### ISSUE TITLE
RadListView: Scroll lost on Android navigation

### ISSUE THREAD

**Issue by Natalia-Hristova** [telerik/nativescript-ui-feedback#76]
From @ignaciolarranaga

**Tell us about the problem**

If you navigate to a page and go back on Android you lost the current scroll on your navigation (i.e. you return to the top of the list instead of your scrolled position).
On iOS it does work properly but not on Android.

**Which platform(s) does your issue occur on?**

Android

**Please provide the following version numbers that your issue occurs with:**

CLI: 2.4.2
Cross-platform modules: 2.4.4
Runtime(s): (look for the 2.4.0
Plugin(s): "nativescript-telerik-ui": "next" (because already handling unpublished fixes),

**Please tell us how to recreate the issue in as much detail as possible.**

Easy, just do it and will see it.

**Comment by ginev** [comment]
@ignaciolarranaga, can you please check if you are not resetting the bindingContext of your page when navigating back? This will cause a `refresh()` call for `RadListView` and will reload the data thus resetting the scroll position.

**Comment by ignaciolarranaga** [comment]
Hey @ginev, nop, I'm not doing that because it is an Angular implementation, once I navigate back (using the page-router), it just show the same component that I started the navigation from.
Just in case you have the code in #115, it is the same component.

**Comment by ginev** [comment]
@ignaciolarranaga can you ZIP and send a project - this is the easiest way for us to debug and provide a fix.
