### ISSUE TITLE
Add color property (and/or additional styling options) for RadDataForm text editor

### ISSUE THREAD

**Issue by NickIliev** [telerik/nativescript-ui-feedback#763]
Requested via issue report and requested on several community threads.

Related to 
- [https://discourse.nativescript.org/t/raddataform-text-field-color-change/4847/3](https://discourse.nativescript.org/t/raddataform-text-field-color-change/4847/3)

- [https://www.telerik.com/forums/custom-styling-of-tkpropertyeditor-text](https://www.telerik.com/forums/custom-styling-of-tkpropertyeditor-text)

- [https://github.com/telerik/nativescript-ui-feedback/issues/742](https://github.com/telerik/nativescript-ui-feedback/issues/742)

**Comment by tgpetrov** [comment]
The nativescript-ui-dataform now supports styling with css. This allows changing the color to every editor in the form or to just specific editors or their labels. Here's more for the feature in [NativeScript Core](https://docs.nativescript.org/ui/professional-ui-components/DataForm/dataform-styling#css) and in [NativeScript Angular](https://docs.nativescript.org/angular/ui/professional-ui-components/ng-DataForm/dataform-styling#css).
