### ISSUE TITLE
iOS picker value alignment again

### ISSUE THREAD

**Issue by 18clans** [telerik/nativescript-ui-feedback#766]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes.  This was a previous issue https://github.com/telerik/nativescript-ui-feedback/issues/165 but was fixed from reading the thread.

### Tell us about the problem
The same issue is happening again with nativescript-ui-dataform version 3.6.1 on iOS.  
![ios dataform](https://user-images.githubusercontent.com/41965764/43478004-509484d2-94c2-11e8-83d5-130980c257cd.gif)

### Which platform(s) does your issue occur on?
_iOS/Android/Both (if applicable tell us the specific version of the platform)_
iOS 11.4 simulator
Android works great.

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** (the version of nativescript-telerik-ui/-pro in the `package.json`)
- **CLI:** (run `tns --version` to fetch it)
4.1.2
- **Cross-platform modules:** (the version of tns-core-modules in the `package.json`)
~4.1.0
- **Runtime(s):** (the `"tns-android"` and `"tns-ios"` properties in the `package.json`)
tns-ios: 4.1.1
tns-android: 4.1.3
		

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application ..
2. Install tns plugin add nativescript-ui-dataform
2. Add NativeScriptUIDataFormModule to app.module.ts
3. Add TkEntityProperty type picker in .html
4. Once picker is loaded in the emulator, click on the picker and it'll scroll down.  You will not be able to see the options until you scroll up.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
_(You can paste entire code snippets or attach a runnable project)_

**Comment by tsonevn** [comment]
HI, @18clans. 
I tested your case with our sample project, however, was unable to recreate the similar problem. You can check the sample [here](https://github.com/telerik/nativescript-ui-samples-angular/blob/master/dataform/app/examples/editors/dataform-editors.component.html#L2). It will help if you provide sample project, which can be used for debugging.

**Comment by tsonevn** [comment]
Hi @18clans,
I tested the demo project, mentioned in my previous comment with the latest official version of `nativescript-ui-dataform` -> `3.6.1`. Regarding your scenario, I notice that you are using a StackLayout as a parent container of the DataForm, which will prevent the proper measuring the component's height. To solve the case, I would suggest using a GridLayout or to specify the component's height.
Option 1:
```
<GridLayout>
  <RadDataForm backgroundColor="green"  [source]="myRadiusSelection">

    <TKEntityProperty tkDataFormProperty name="radius" displayName="Radius" index="0" [valuesProvider]="radiusName">
      <TKPropertyEditor tkEntityPropertyEditor type="Picker">
        <TKPropertyEditorStyle tkPropertyEditorStyle ios:editorHorizontalOffset="4">
        </TKPropertyEditorStyle>
      </TKPropertyEditor>

    </TKEntityProperty>
  </RadDataForm>
</GridLayout>
```
Option 2:
```
<RadDataForm backgroundColor="green" height="300" [source]="myRadiusSelection">

    <TKEntityProperty tkDataFormProperty name="radius" displayName="Radius" index="0" [valuesProvider]="radiusName">
      <TKPropertyEditor tkEntityPropertyEditor type="Picker">
        <TKPropertyEditorStyle tkPropertyEditorStyle ios:editorHorizontalOffset="4">
        </TKPropertyEditorStyle>
      </TKPropertyEditor>

    </TKEntityProperty>
  </RadDataForm>
```

**Comment by 18clans** [comment]
I just tried this and it's working correctly on iOS.  Thank you for the quick help.
