### ISSUE TITLE
RadListView - How to customize styling of selected items?

### ISSUE THREAD

**Issue by VeeK727** [telerik/nativescript-ui-feedback#773]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
When I select an item it shows a grey border around the item. How do I change the colors or remove it altogether? I tried setting `background: transparent;` on all the child items but it didn't have any effect.

### Which platform(s) does your issue occur on?
Android 7.1.1

**Comment by VeeK727** [comment]
Can I share it with you privately?

**Comment by tsonevn** [comment]
Hi @VeeK727,
You can send it to me in private message via [our community Slack](https://nativescriptcommunity.slack.com/). My nickname is `nikts`.

**Comment by VeeK727** [comment]
Could you explain how to do that. I signed up and it asked me to create a workspace. But I still can't login to your given link. Also I can't find you from the PM search in the left sidebar.

**Comment by tsonevn** [comment]
You can find more about joining workspace in Slack [here.](https://get.slack.help/hc/en-us/articles/212675257-Join-a-Slack-workspace). Also, [here](https://get.slack.help/hc/en-us/articles/212281468-Direct-messages-and-group-DMs) you will find, how to send a direct message.

**Comment by VeeK727** [comment]
Sorry to bother you but I can't make it work. I follow the help section, but there's no way its showing noativescript's workspace. I think you need an invitaion to do that. I also can't find you for sending DM with nikts username. Can you provide another method?

**Comment by tsonevn** [comment]
Try to send me the project via email: nikolay.tsonev@progress.com

**Comment by VeeK727** [comment]
Sent

**Comment by tsonevn** [comment]
Hi @VeeK727,
The changed your case and found that the change of the background color when an item is selected is something expected while the RadListView's `multipleSelection` option is enabled. To solve this, you can set up a root container with a custom background for each item as it is shown in the example [here](https://github.com/telerik/nativescript-ui-samples/blob/master/listview/app/examples/selection-states/selection-states-page.xml#L9).

**Comment by VeeK727** [comment]
Hi @tsonevn , sorry for the late reply. I already had a root container with a class that applies transparent background. In fact, I tried to apply it on every element and the background color still showed up. THats what confused me the most.

Anyways I tried your idea too, but that didn't work either. DId it work for you?
```
<lv:RadListView items="{{ purities }}" selectionBehavior="Press" multipleSelection="true" itemSelected="onItemSelected" itemDeselected="onItemDeselected" id="selectionList">
	<lv:RadListView.listViewLayout>
		<lv:ListViewGridLayout scrollDirection="Vertical" spanCount="2" />
	</lv:RadListView.listViewLayout>

	<lv:RadListView.itemTemplate>
		<GridLayout rows="auto,auto" class="m-r-10 m-b-10 bg-trans" backgroundColor="{{ selected ? 'red' : 'transparent' }}"> //red color didn't show up
			 ...
		</GridLayout>
	</lv:RadListView.itemTemplate>
</lv:RadListView>
```

**Comment by tsonevn** [comment]
Hi @VeeK727,
I noticed that you are setting up margins to the main GridLayout, that might take effect in setting up the background. Regarding that, you can try setting up a StackLayout, where you can define the colour:
```
<lv:RadListView items="{{ purities }}" selectionBehavior="Press" multipleSelection="true" itemSelected="onItemSelected" itemDeselected="onItemDeselected" id="selectionList">
	<lv:RadListView.listViewLayout>
		<lv:ListViewGridLayout scrollDirection="Vertical" spanCount="2" />
	</lv:RadListView.listViewLayout>

	<lv:RadListView.itemTemplate>
          <StackLayout backgroundColor="white">
		<GridLayout rows="auto,auto" class="m-r-10 m-b-10 bg-trans" > //red color didn't show up
			 ...
		</GridLayout>
           </StackLayout>
	</lv:RadListView.itemTemplate>
</lv:RadListView>
```

**Comment by VeeK727** [comment]
That worked. Thanks a lot.
