### ISSUE TITLE
[RadListView] capability to show custom message when items are empty with pullToRefresh

### ISSUE THREAD

**Issue by Liooo** [telerik/nativescript-ui-feedback#775]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
_Yes_

### Tell us about the problem

I want to do the following using RadListView, which is quite basic:
- show a custom message when the items are empty
- pullToRefresh to fetch the latest data no matter what the current items count is (empty or not)

is this achievable with current RadListView implementation?

### Which platform(s) does your issue occur on?
_Both_

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 3.4.1
- **Cross-platform modules:** 4.3.0-2018-08-02-06
- **Runtime(s):** ios: 4.1.0 android: 4.1.3

**Comment by tsonevn** [comment]
HI @Liooo,
About your first question, you can use a GridLayout with a Label and RadListView. When there are no items in the ListView, the Label can be displayed. After the component is populated with items, you can hide the Label. For example:
```
<GridLayout orientation="vertical" rows="auto, *">
     <!-- >> listview-pull-to-refresh-xml -->
      
        <lv:RadListView items="{{ dataItems }}" pullToRefresh="true" row="1" pullToRefreshInitiated="{{onPullToRefreshInitiated}}">
     <!-- << listview-pull-to-refresh-xml -->
            <lv:RadListView.itemTemplate>
              <StackLayout orientation="vertical" padding="5 10 5 10"  style="background-color: #7fff7f;">
                <StackLayout orientation="horizontal" padding="10" style="background-color: #65a565;">
                    <Image src="{{ image + '.jpg'}}" stretch="aspectFit" height="100" width="100"/>
                   <StackLayout orientation="vertical" marginLeft="15">
                    <Label fontSize="20" text="{{ name }}" marginBottom="8"/>
                    <Label fontSize="14" text="{{ title }}" style="font-weight: bold;" textWrap="true"/>
                    <Label fontSize="12" text="{{ text }}" color="White" textWrap="true"/>
                </StackLayout>
                </StackLayout>
                </StackLayout>
            </lv:RadListView.itemTemplate>
            <lv:RadListView.pullToRefreshStyle>
                <lv:PullToRefreshStyle indicatorColor="red" indicatorBackgroundColor="blue"/>
            </lv:RadListView.pullToRefreshStyle>
        </lv:RadListView>
        <Label visibility="{{ isItemVisible ? 'visible' : 'collapsed' }}" text="{{'No Date'+isItemVisible}}" row="0" textWrap="true" />
    </GridLayout>
```
Regarding the second question. I tested the scenario, where the Empty ListView is used, and the pull to refresh functionality is set up,  with [our sample project](https://github.com/telerik/nativescript-ui-samples/tree/master/listview/app/examples/pull-to-refresh). It seems that the pull to refresh will work as expected and will populate the component with items event if it is empty on the initial time.

**Comment by Liooo** [comment]
@tsonevn 
Thanks for the answer

> About your first question, you can use a GridLayout with a Label and RadListView

I've tried this but pull to refresh won't work this way when there's no item because RadListView itself is hidden. I've also tried using RadListView's header and footer but wasn't able to accomplish what's written above.

> It seems that the pull to refresh will work as expected and will populate the component with items event if it is empty on the initial time.

Yes, I've confirmed this behavior as well.

**Comment by mhlulani** [comment]
This works fine, But more often than not you'd want to wrap your list in a `ScrollView` so that you can scroll passed the overflowing items, this presents a problem. only the last component is displayed.
How can I fix this?
```xml
    <DockLayout>
        <GridLayout dock="top" columns="auto, *, auto" rows="auto, 25" verticalAlignment="top">
            <Image src="{{product.imagePath}}" stretch="aspectFit" rowSpan="2" width="72" height="72" margin="3" verticalAlignment="top" />
            <Label text="{{product.title}}" textWrap="true" col="1" colSpan="2" minHeight="50" fontSize="20" margin="3" />
            <Label text="{{product.contributors}}" col="1" row="1" fontSize="14" horizontalAlignment="left" verticalAlignment="bottom" margin="3"></Label>
            <Label text="{{product.type}}" col="1" row="1" fontSize="14" horizontalAlignment="left" verticalAlignment="bottom" margin="3" />
            <Label text="{{product.price}}" col="2" row="1" color="#10C2B0" fontSize="14" verticalAlignment="bottom" margin="3" />
        </GridLayout>
        <ScrollView dock="bottom" marginLeft="10" marginRight="10">
            <lv:RadListView id="lvItems" row="0" itemTap="gotoItem" height="100%" items="{{ products }}" selectionBehavior="None" multipleSelection="true">
                <lv:RadListView.itemTemplate>
                    <GridLayout rows="auto, auto" columns="90, 120, auto" paddingTop="10" paddingBottom="10">
                        <Image src="{{avatarUrl}}" col="0" row="0" horizontalAlignment="center" width="50" height="50" borderRadius="50" stretch="aspectFill"></Image>
                        <Label text="{{username}}" col="0" row="1" textAlignment="center"></Label>
                        <Label col="1" row="0" verticalAlignment="center">
                            <FormattedString>
                                <Span text="{{price}}" fontWeight="bold"></Span>
                            </FormattedString>
                        </Label>
                        <Button stockItem="{{ $value }}" tap="likeItem" text="Like" rowSpan="2" col="2" horizontalAlignment="right" />
                    </GridLayout>
                </lv:RadListView.itemTemplate>
            </lv:RadListView>
            <Button tap="gotoCreate" visibility="{{ products.length === 0 ? 'visible' : 'collapsed' }}" row="1" text="Create" />
        </ScrollView>
    </DockLayout>
```

**Comment by mrpaaske** [comment]
@Liooo I know it's late, and you probably have found a solution, but in case someone else is looking for one, I used the tkListViewFooter to achieve this:

	<RadListView>
		...
		<ng-template tkListViewFooter>️️️
			<StackLayout>
				<Label text="🤷‍♀️"></Label>
			</StackLayout>
		</ng-template>
	</RadListView>

**Comment by jscti** [comment]
> @Liooo I know it's late, and you probably have found a solution, but in case someone else is looking for one, I used the tkListViewFooter to achieve this:
> 
> ```
> <RadListView>
> 	...
> 	<ng-template tkListViewFooter>️️️
> 		<StackLayout>
> 			<Label *ngIf="listData.length === 0" text="🤷‍♀️"></Label>
> 		</StackLayout>
> 	</ng-template>
> </RadListView>
> ```

Nop it doesn't work. Fun fact : it worked only with `tkListViewHeader` -_-
