### ISSUE TITLE
RadCalendar's reload function is not resetting the selected dates in range selection mode

### ISSUE THREAD

**Issue by rajesh-95** [telerik/nativescript-ui-feedback#776]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
_I was trying to reset the selected dates on calendar with click of a button and still the calendar is retaining the dates_

### Which platform(s) does your issue occur on?
_Android_

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 3.6.0
- **CLI:** 4.1.0
- **Cross-platform modules:**4.1.0
- **Runtime(s):**  `"tns-android"` 4.1.3
### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application ..
2. select the start and end date of the range in calendar.
3. have a button to reset the calendar.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
home.component.html
<StackLayout>
	<RadCalendar #cal selectionMode="Range" height="1000px"></RadCalendar>
	<Button  text="Button" (tap)="onButtonTap()"></Button>
</StackLayout>

home.component.ts

import { Component, OnInit, ViewChild } from "@angular/core";
import { RadCalendarComponent } from 'nativescript-ui-calendar/angular';
import { RadCalendar, CalendarEvent, CalendarSelectionEventData, DateRange } from 'nativescript-ui-calendar'; 

@Component({
    selector: "Home",
    moduleId: module.id,
    templateUrl: "./home.component.html",
    styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
    
    @ViewChild("cal") _calendar: RadCalendarComponent;

    constructor() {
    }

    ngOnInit(): void {
    }
    onButtonTap(): void {
        console.log("Button was pressed");
        this._calendar.nativeElement.reload(); // even i have tried with this._calendar.calendar.reload();
        console.log(this._calendar.calendar.selectedDateRange.startDate);
        console.log(this._calendar.calendar.selectedDateRange.endDate);
        // even after calling reload function, selected dates are printed on console.
    }
}

**Comment by tsonevn** [comment]
Hi @rajesh-95,
For restarting the selected range in the Calendar, you should first set up the selection mode to `None` before reloading the Calendar. For example:
```
export class CalendarSelectionModesComponent extends OptionsExampleBase {
    private _optionsParamName: string;
    private _selectionMode;
    constructor(private _page: Page, private _router: Router, private _optionsService: OptionsService) {
       .........
    }


    @ViewChild("myCalendar") _calendar: RadCalendarComponent;

   
    onRestart(args){
        this._calendar.nativeElement.selectionMode="None";
        this._calendar.nativeElement.reload();
        this._calendar.nativeElement.selectionMode="Range";
    }
}
```

**Comment by rajesh-95** [comment]
this._calendar.nativeElement.selectionMode="None";
this._calendar.nativeElement.reload();
this._calendar.nativeElement.selectionMode="Range";
Still the calender is retaining the dates of selected date range after executing the above lines

**Comment by tsonevn** [comment]
Hi @rajesh-95,
please provide sample project, which can be used for debugging.

**Comment by rajesh-95** [comment]
Hi @tsonevn 

Here is the code 

home.component.html
<StackLayout>
    <RadCalendar #cal selectionMode="Range" height="1000px"></RadCalendar>
    <Button text="Button" (tap)="onButtonTap()"></Button>
</StackLayout>

home.component.ts

import { Component, OnInit, ViewChild } from "@angular/core";
import { RadCalendarComponent } from 'nativescript-ui-calendar/angular';
import { RadCalendar, CalendarEvent, CalendarSelectionEventData, DateRange } from 'nativescript-ui-calendar';

@component({
selector: "Home",
moduleId: module.id,
templateUrl: "./home.component.html",
styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

@ViewChild("cal") _calendar: RadCalendarComponent;

constructor() {
}

ngOnInit(): void {
}
onButtonTap(): void {
    console.log("Button was pressed");
    this._calendar.nativeElement.selectionMode="None";
    this._calendar.nativeElement.reload();
    this._calendar.nativeElement.selectionMode="Range";
    console.log(this._calendar.calendar.selectedDateRange.startDate);
    console.log(this._calendar.calendar.selectedDateRange.endDate);
    
}

The calendar still retains the selectedDate Range even though the view is updated.

**Comment by tsonevn** [comment]
Hi @rajesh-95,
I tested the provided code snippets in a sample project, however, was unable to recreate the problem. For your convenience, I am attaching the project. You can review it and make the needed changes, which will allow me to recreate the issue. 
[Archive.zip](https://github.com/telerik/nativescript-ui-feedback/files/2305969/Archive.zip)

**Comment by rajesh-95** [comment]
It was no where mentioned in the documentation on how to reset the calendar in range mode.
Why not add it to the documentation ??
