### ISSUE TITLE
Using labelFormat crashes app with %s

### ISSUE THREAD

**Issue by raygerrard** [telerik/nativescript-ui-feedback#779]
Using %s as the labelFormat causes the application to crash. My Labels are the string "Monday", "Tuesday" etc. I want to be able to format this to just display the first character of each but using the %s crashes immediately with no error.

`<CategoricalAxis labelFormat="%s" labelMargin="10" labelTextColor="#999999" tkCartesianHorizontalAxis></CategoricalAxis>`

I can use %d with no issue.

**Comment by tsonevn** [comment]
Hi @raygerrard,
Can you provide more info about the problem and the exact error, which is thrown while using `%s` in the `labelFormat`? Also, It will help if you send us a sample project, where the issue can be reproduced.
