### ISSUE TITLE
DataForm Picker from VueJS Examples Needed 

### ISSUE THREAD

**Issue by VladimirAmiorkov** [telerik/nativescript-ui-feedback#784]
Moving from: https://github.com/NativeScript/playground-feedback/issues/64

## Please, provide the details below:
When using the Playground with Vue, it is possible to drag a DataForm to the project. It creates a test object album. If the object property is a string, then a text input field is rendered. If the object property is true/false a checkbox is rendered.

How can a picker be rendered which allows for a choice of items? 

I cant see any way to add groups, validators or custom inupt types.

Since I am asking, is it possible to load the picker data dynamically?

### Did you search for the problem in [other open issues in this repo](https://github.com/NativeScript/playground-feedback/issues)?
Yes

### Tell us about the problem
DataForm Picker from VueJS Examples Needed

### Did you try it outside of {N} Playground?
- No

### Which browser are you using?
Chrome

### Are there any errors/warnings logged in your browser console?
NA cant run

### Which platform(s) does your issue occur on?
- Both

### Are there any entries logged in the Device Logs tab?
NA

### Please provide the following information shown in devices tab in the playground:
NA

### Please tell us how to recreate the issue with as much detail as possible.
Add a DataForm to your project and then add an entry that is to act like a Picker

**Comment by VladimirAmiorkov** [comment]
The current state of the VueJS support for nativescript-ui-dataform does not support the addition of list (picker) editors.

**Comment by msn444** [comment]
Any timeline on this, or any of the other editors, being implemented for Vue?

**Comment by msaelices** [comment]
@msn444 It's implemented. You can check this demo app: https://github.com/msaelices/ns-ui-vue-demo/

If you read the [DataForm.vue component](https://github.com/msaelices/ns-ui-vue-demo/blob/master/app/views/DataForm.vue), you can see this fragment:

```
...
        'propertyAnnotations':
        [
          {
            'name': 'movie',
            'displayName': 'Movie Name',
            'index': 0,
            'editor': 'Picker',
            'valuesProvider': movies.map((value) => value.name),
            'converter': new MovieConverter(movies),
          },
...
```

This sample define the form using the `propertyAnnotations` configuration, but you can also set the picker editor in the markup like this:

```
<RadDataForm
      :source="ticket">
      <TKEntityProperty v-tkDataFormProperty
                        name="movie"
                        displayName="Movie Name"
                        index="0"
                        :converter="movieConverter"
                        :valuesProvider="movieNames">
        <TKPropertyEditor v-tkEntityPropertyEditor type="Picker"></TKPropertyEditor>
      </TKEntityProperty>
      ...
</RadDataForm>
```

**Comment by elena-p** [comment]
DataForm vue demos can be found [here](https://github.com/telerik/nativescript-ui-samples-vue/blob/master/dataform)
[How to run the app](https://github.com/telerik/nativescript-ui-samples-vue#running-progress-nativescript-ui-sample-app)

**Comment by prashantnirgun** [comment]
Its in typescript can anyone explain how to convert this to javascript also as documentation its showing converter code which is class implements PropertyConverter.

**Comment by eso0o** [comment]
Hi, iam using converter for dataform's picker which is not working , discovered that convert from & convert to are not working , as i have object with values which passed to data form , list picker not show previously selected option(value) so is there any better solution for that , what is best solution as value provider for data form's picker editor
