### ISSUE TITLE
v3.5.11 RadListView with Staggered Layout have offset applied to each item

### ISSUE THREAD

**Issue by gogoout** [telerik/nativescript-ui-feedback#788]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
<img width="250" alt="screen shot 2018-08-12 at 14 46 00" src="https://user-images.githubusercontent.com/7570175/43997992-4afdd8da-9e3f-11e8-90bf-e5fdde775ab8.png">
v3.5.7

<img width="250" alt="screen shot 2018-08-12 at 14 51 11" src="https://user-images.githubusercontent.com/7570175/43997993-4b51b702-9e3f-11e8-9277-5de0fce412e5.png">
v3.5.11

As you can see, Staggered Layout in v3.5.11 have weird offset applied to each item. 

### Which platform(s) does your issue occur on?
_iOS/Android/Both (if applicable tell us the specific version of the platform)_
IOS (haven't test on Android)

### Please provide the following version numbers that your issue occurs with:

- nativescript-ui-listview 3.5.11
- tns --version
4.3.0-2018-08-03-12074
- "tns-core-modules": "^4.1.1",
-  "tns-ios": {
      "version": "4.1.0"
    }

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application .

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
https://play.nativescript.org/?template=play-ng&id=AJaSPY
I've created a demo here which is basically paste from the staggered demo which is working fine in the playground since the ListView playground using is 3.5.7. I've tested on my own app, when switching the version to 3.5.7, the problem disappeared.

**Comment by tsonevn** [comment]
Hi, @gogoout,
Can you provide some more info about the issue, which you are facing? We reviewed the images, however, was unable to find the difference. In the provided screenshots we also cannot distinguish the items in The ListView. Can you apply some borders to the items in your project, which will allow us to see the difference? It will help if you show us where is the exact difference. I have tested the attached sample project, however, was unable to recreate the problem as well.

**Comment by gogoout** [comment]
Hi @tsonevn ,
I've added borders to the item and background color to the list, so it should be really obvious now. Please note that only staggered layout have this issue. 
<img width="250" alt="screen shot 2018-08-16 at 21 48 08" src="https://user-images.githubusercontent.com/7570175/44201867-71be4600-a19e-11e8-8ab1-498582c5b267.png">

**Comment by racknoris** [comment]
occurs also v3.7.1

**Comment by LSmint** [comment]
May i know any update on this issue? I would like to upgrade from v3.5.9 to v3.7.1 to resolve memory leak issue (which already fixed in the latest version) but this is another obstacle that cause i can't upgrade to the new version now.

**Comment by racknoris** [comment]
@tsonevn Is there a workaround for that in version 3.8.0?

**Comment by tsonevn** [comment]
Hi @racknoris,
Currently, there is no workaround, that can solve this problem. I would suggest keeping track of the issue here. We will update its status when a new `naitvescript-ui-listview` version with the appropriate fix is available.
