### ISSUE TITLE
Calendar UI Disabling Default Double Tap

### ISSUE THREAD

**Issue by throwingdarts** [telerik/nativescript-ui-feedback#791]
I found [this article](https://www.telerik.com/forums/remove-gesture-of-calendar) about disabling the double-tap gesture that changes the view mode to year view. There is a suggestion for android but then states “a similar approach can be applied to iOS as well”. Can someone point me to the available docs on how to achieve same in iOS? Thanks.

**Comment by tsonevn** [comment]
HI @throwingdarts,
In iOS by design, there is no double tap gesture. There is no functionality, which will change the viewMode on double tap. You can check our sample project [here](https://github.com/telerik/nativescript-ui-samples-angular/tree/master/calendar/app/calendar/getting-started).
