### ISSUE TITLE
Calendar UI Week View Mode

### ISSUE THREAD

**Issue by throwingdarts** [telerik/nativescript-ui-feedback#792]
On Android devices when the **viewMode** is set to _Week_ and the UI Calendar's **height** property is set the calendar row (the week) doesn't fill the allotted space as it does in iOS making the date cells partially hidden.

See [this example](https://play.nativescript.org/?template=play-js&id=Cfv3rB&v=19).

Is there a way around this?

**Comment by throwingdarts** [comment]
This [doc](https://www.telerik.com/forums/changing-display-modes-leaves-blank-space-below-calendar) for _UI for Android_ suggests to use the **setInOriginalSizeForAllModes** function explicitly setting it to _false_ but this doesn't seem to make a difference in the current UI Calendar version. According to [this doc](https://docs.telerik.com/devtools/android/AndroidControlsDoc/com/telerik/widget/calendar/RadCalendarView.html) the default value is _false_.

**Comment by elena-p** [comment]
@throwingdarts, we just released a fix for this issue with nativescript-ui-calendar@3.10.0

Please, note that in order to have the Week view the same height in android, you need to call `setInOriginalSizeForAllModes(true);`

**Comment by Adambs** [comment]
Hi Elena, 
Can you show an example of how to use this function (setInOriginalSizeForAllModes)? 
I'm new to nativescript, I try to move my project from angular 5 to nativescript. 
I use nativescript-ui-calendar import

Tnx

**Comment by throwingdarts** [comment]
@Adambs  - see this [article](https://www.telerik.com/forums/changing-display-modes-leaves-blank-space-below-calendar) which may help.

**Comment by Adambs** [comment]
Hi,
It didn't help.
I'd like to see the implementation of the solution in nativescript/angular
project.

Tnx

בתאריך יום ב׳, 1 באפר׳ 2019, 17:27, מאת Mark Bulleit ‏<
notifications@github.com>:
