### ISSUE TITLE
App is crashing with listview 3.6.0 and tns-core 4.2

### ISSUE THREAD

**Issue by nmongiya** [telerik/nativescript-ui-feedback#799]
I tried with "tns-android": { "version": "**4.2.0**" } "tns-core-modules": "**^4.2.0**", & "nativescript-ui-listview": "**^3.6.0**", and notice that couple of time app is crashing with below error.

> An uncaught Exception occurred on "main" thread. com.tns.NativeScriptException: Attempt to use cleared object reference id=199792 at com.tns.Runtime.getJavaObjectByID(Runtime.java:923) at com.tns.Runtime.callJSMethodNative(Native Method) at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116) at com.tns.Runtime.callJSMethodImpl(Runtime.java:996) at com.tns.Runtime.callJSMethod(Runtime.java:983) at com.tns.Runtime.callJSMethod(Runtime.java:967) at com.tns.Runtime.callJSMethod(Runtime.java:959) at com.tns.gen.com.telerik.widget.list.ListViewDataSourceAdapter_listview_272_32_ListViewDataSourceAdapter.onCreateItemViewHolder(ListViewDataSourceAdapter_listview_272_32_ListViewDataSourceAdapter.java:42) at com.telerik.widget.list.ListViewDataSourceAdapter.onCreateViewHolder(ListViewDataSourceAdapter.java:430) at com.telerik.widget.list.ListViewWrapperAdapter.onCreateListViewHolder(ListViewWrapperAdapter.java:465) at com.telerik.widget.list.ListViewAdapterBase.onCreateViewHolder(ListViewAdapterBase.java:145) at com.telerik.widget.list.ListViewAdapterBase.onCreateViewHolder(ListViewAdapterBase.java:22) at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6367) at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5555) at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440) at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436) at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224) at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551) at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511) at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595) at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583) at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312) at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844) at com.telerik.widget.list.RadListView.onLayout(RadListView.java:589) at android.view.View.layout(View.java:20854) at android.view.ViewGroup.layout(ViewGroup.java:6401) at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:636) at android.view.View.layout(View.java:20854) at android.view.ViewGroup.layout(ViewGroup.java:6401) at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323) at android.widget.FrameLayout.onLayout(FrameLayout.java:261) at android.view.View.layout(View.java:20854) at android.view.ViewGroup.layout(ViewGroup.java:6401) at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222) at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353) at android.view.View.layout(View.java:20854) at android.view.ViewGroup.layout(ViewGroup.java:6401) at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222) at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353) at android.view.View.layout(View.java:20854) at android.view.ViewGroup.layout(ViewGroup.java:6401) at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222) at org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:169) at org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:123) at android.view.View.layout(View.java:20854) at android.view.ViewGroup.layout(ViewGroup.java:6401) at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323) at android.widget.FrameLayout.onLayout(FrameLayout.java:261) at android.view.View.layout(View.java:20854) at android.view.ViewGroup.layout(ViewGroup.java:6401) at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323) at android.widget.FrameLayout.onLayout(FrameLayout.java:261) at android.view.View.layout(View.java:20854) at android.view.ViewGroup.layout(ViewGroup.java:6401) at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222) at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353) at android.view.View.layout(View.java:20854) at android.view.ViewGroup.layout(ViewGroup.java:6401) at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222) at org.nativescript.widgets.ContentLayout.onLayout(ContentLayout.java:73) at android.view.View.layout(View.java:20854) at android.view.ViewGroup.layout(ViewGroup.java:6401) at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323) at android.widget.FrameLayout.onLayout(FrameLayout.java:261) at android.view.View.layout(View.java:20854) at android.view.ViewGroup.layout(ViewGroup.java:6401) at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791) at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635) at android.widget.LinearLayout.onLayout(LinearLayout.java:1544) at android.view.View.layout(View.java:20854) at android.view.ViewGroup.layout(ViewGroup.java:6401) at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323) at android.widget.FrameLayout.onLayout(FrameLayout.java:261) at com.android.internal.policy.DecorView.onLayout(DecorView.java:945) at android.view.View.layout(View.java:20854) at android.view.ViewGroup.layout(ViewGroup.java:6401) at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2912) at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2599) at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1743) at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7773) at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911) at android.view.Choreographer.doCallbacks(Choreographer.java:723) at android.view.Choreographer.doFrame(Choreographer.java:658) at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897) at android.os.Handler.handleCallback(Handler.java:789) at android.os.Handler.dispatchMessage(Handler.java:98) at android.os.Looper.loop(Looper.java:164) at android.app.ActivityThread.main(ActivityThread.java:6949) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by NickIliev** [comment]
@nmongiya is there some specific code involved that you can share with us - for example are you using some of the listview features like pull-to-refresh or similar? Let me know if you have a sample project that can reproduce the issue.

**Comment by nmongiya** [comment]
@NickIliev There are no specific steps to reproduce this. But mostly I was using pull to refresh. I have tried to update **`tns-core-modules": "^4.3.0-2018-08-17-04",`** and unfortunately faced this issue again. It's a very rare but yes, it is happening.

**Comment by nmongiya** [comment]
[Log-2018-09-10-10-48-30.txt](https://github.com/telerik/nativescript-ui-feedback/files/2364836/Log-2018-09-10-10-48-30.txt)
Faced this issue again with "tns-core-modules": "^4.2.0", "nativescript-ui-listview": "^3.6.0", & "tns-android": { "version": "4.2.0" }
I am attaching the logcat report for your reference.

**Comment by larssn** [comment]
We also saw this today, from a normal `<ListView>`. Attaching logcat.

[Log-2018-12-05-14-30-08.txt](https://github.com/telerik/nativescript-ui-feedback/files/2649063/Log-2018-12-05-14-30-08.txt)

We're using the following version:
```
"nativescript-angular": "^7.0.2",
"tns-core-modules": "^5.0.5",
"tns-android": {
      "version": "5.0.0"
    },
```

**Comment by elena-p** [comment]
Hi @nmongiya,

Do you use [markingMode:none](https://docs.nativescript.org/core-concepts/android-runtime/advanced-topics/memory-management#markingmode-none) in your app? 
There are fixes regarding the usage of that option in nativescript-ui-listview@5.1.0.
