### ISSUE TITLE
Docs: Provide some examples how users can create custom Annotations

### ISSUE THREAD

**Issue by PeterStaev** [telerik/nativescript-ui-feedback#8]
On the main site for the chart http://www.telerik.com/nativescript-ui/chart it is said that users can create custom annotations. Yet in the docs I cannot find any reference or hints how to achieve this.

**Comment by ginev** [comment]
http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/Chart/Behaviors/annotations

Feel free to reopen if API is not useful.
