### ISSUE TITLE
Chart: snapMode property does nothing

### ISSUE THREAD

**Issue by tgpetrov** [telerik/nativescript-ui-feedback#818]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
_Yes_

### Tell us about the problem
The trackball has a `snapMode` property mentioned [here](https://docs.telerik.com/devtools/nativescript-ui/api/classes/trackball.html#snapmode), which has no effect.

### Which platform(s) does your issue occur on?
_Both_

### Please provide the following version numbers that your issue occurs with:
- **NativeScript UI Chart version:** 3.6.0
- **CLI:** 4.2.2
- **Cross-platform modules:** 4.2.0
- **Runtime(s):** 4.2.0

### Please tell us how to recreate the issue in as much detail as possible.
1. In the Styling Series example of the [demo-angular](https://github.com/telerik/nativescript-ui-samples-angular/blob/master/chart/app/examples/styling/chart-styling-series.component.html) add trackball:
```
<Trackball tkCartesianTrackball snapMode="ClosestPoint"></Trackball>
```
2. Run the example and hold on the chart to show the Trackball - on iOS the trackball will show info for only one point, while on android it will show info for points from all series
3. Change the snapMode to "AllClosestPoints" - the same happens on both android and iOS
4. The expected is that the current android behavior is observed on both platforms when snapMode is "AllClosestPoints" and the current iOS behavior is observed on both platforms when snapMode is "ClosestPoint"

**Comment by zbranzov** [comment]
Fixed in nativescript-ui-chart@3.9.0
