### ISSUE TITLE
Still the "index" of elements in all events is incorrect if grouping, filtering and/or sorting is enabled ?

### ISSUE THREAD

**Issue by MopheusDG** [telerik/nativescript-ui-feedback#821]
Hi, I've update to nativescript-ui-listview@3.6.1 and I still do get index 0 after a group separator is added or a filter applied. Do I need to update anything else ? This is related to issue #804 now closed.

My tested behaviour is apply FILTER via SearchBar and then, itemSelected gets args.index 0 for the first filtered item instead of the right index of the item. Basically the issues is that after Filtering or using a Group Separator (don't tested any further than that), the index starts again from 0.

Ideas ? Thanks.

This is my Package.json just in case:

`  "nativescript": {
    "id": "org.nativescript.forum",
    "tns-android": {
      "version": "4.2.0"
    },
    "tns-ios": {
      "version": "4.2.0"
    }
  },
  "scripts": {
    "lint": "eslint \"app/**/*.js\""
  },
  "dependencies": {
    "nativescript-theme-core": "^1.0.4",
    "nativescript-ui-listview": "^3.6.1",
    "nativescript-ui-sidedrawer": "^4.3.0",
    "rxjs": "~6.1.0",
    "tns-core-modules": "^4.2.0"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "eslint": "~4.19.0",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "~1.6.0",
    "nativescript-dev-webpack": "~0.14.0"
  }
}
`

**Comment by MopheusDG** [comment]
NVM, I had to remove platform, add platform and make a full rebuild, but seems to be working now.... not sure why, but mostly add/remove is just enough. Sorry.

I'll keep testing but seems to be ok with 3.6.1, thanks !

**Comment by VladimirAmiorkov** [comment]
Hi @MopheusDG ,

We are glad you were able to resolve this issue. As we try to improve the user experience while upgrading to newer versions and we have already made a fix inside the NativeScript CLI for scenario where the native library associated with a plugin has been changed between version can I ask you to verify which version of NativeScript you are using ? Simply do `tns --version`, thank you.

**Comment by MopheusDG** [comment]
Sure, I'm running NS version 4.2.2.  Do you think I need to update to 4.2.3 ? My index issue was fix only after I did a "tns build ios", I tried remove platform and run ios --clean, but wasn't working, then I build, and problem was fixed. Strange thing is that this was ok from the beggining on Android.
