### ISSUE TITLE
Another RLV memory leak

### ISSUE THREAD

**Issue by NathanaelA** [telerik/nativescript-ui-feedback#822]
### Did you verify this is a real problem by searching 
yes - this is related to #748 ; however this has to do with the memory left over after the item is mostly disposed of.  Unfortunately the memory left over adds up quickly based on how many objects you have in your RLV.   (This might also be related to https://github.com/NativeScript/NativeScript/issues/6111)

### Tell us about the problem
RLV is continuing to leak many objects during a refresh.  Wasting precious memory that eventually caused the application to become unresponsive.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.2.0
- Cross-platform modules: 4.2.0
- Runtime(s): 4.2.0
- Plugin(s): 
        "dependencies": {
                "nativescript-theme-core": "~1.0.4",
                "nativescript-ui-listview": "^3.6.1",
                "tns-core-modules": "^4.2.0",
                "tns-core-modules-widgets": "^4.3.0-2018-08-24-01"
        },

Latest ui-listview and the fixed widgets (from #748 ).

### Please tell us how to recreate the issue in as much detail as possible.
 You can use the same test app as in #748 and then you need to use `tns debug android` and then start the chrome debugger after the app has start.
take a heap snap shot after it finished loading.
Here is the screen shot after first starting up, nothing but taking a snap shot immediately.

![image](https://user-images.githubusercontent.com/850871/44968704-fa631300-af0e-11e8-94b7-47bc05e368a1.png)
Snapshot is 7.8 megs; Labels that exist are 25

Refresh 3 times; and take another snapshot:
![image](https://user-images.githubusercontent.com/850871/44968487-ebc82c00-af0d-11e8-9f46-d65049b5315d.png)
Snapshot is now 8.1 megs; Labels that exist are 81.

Refresh 3 more times, take another snapshot:
![image](https://user-images.githubusercontent.com/850871/44968538-216d1500-af0e-11e8-936a-776f223e0240.png)
Snapshot is still 8.1 megs; Labels that exist are 78 (it went down by 3)--- HOWEVER a GC occurred; so the snapshot stayed approx the same as the last time.

Refresh another 6 times; hit the GC button to force a GC; take another snapshot:
![image](https://user-images.githubusercontent.com/850871/44968630-8f194100-af0e-11e8-8c75-3576be179b7b.png)
Snapshot is at 8.4 megs; Labels are at 115.

Heap tree for a Valid label currently being used:
![image](https://user-images.githubusercontent.com/850871/44969056-ef10e700-af10-11e8-9d12-b00009845101.png)

Heap tree for a Destroyed Label, but the Label memory is retained:
![image](https://user-images.githubusercontent.com/850871/44969123-4616bc00-af11-11e8-9b41-c43772468f9d.png)

A few things to notice; because this seems to effect multiple items; the real issue is that it appears 
The label object is held onto by the GridLayout which is held onto by the StackLayout, which is held onto by the RLV's _viewHolderChildren -- This is I believe a large part of the key; I believe if this, possibly the Stacklayout's `cssStyle.view` and `Style.view` gets cleared correctly the rest of the chain should get cleared properly.
![image](https://user-images.githubusercontent.com/850871/44969314-3d72b580-af12-11e8-9d0c-46fa254b8114.png)
Looking at the _viewHolderChildren you can see several items have been nulled out; and this is an invalid _viewHolderChildren object.   But because it is retained; everything else is retained causing a memory leak that adds up quickly if you are using more than a couple labels...

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
You may use the same testlist.zip app in #748 , you will need to update the resources to use the latest widgets and latest core, runtime, and ui-listview.

**Comment by VladimirAmiorkov** [comment]
Hi @NathanaelA ,

Our internal testing regarding the previous issue concluded that the leaked UI elements was resolved. Using the mentioned app https://github.com/telerik/nativescript-ui-feedback/issues/748 does not show any leaks with the current version of nativescript-ui-listview + @next tns-core-modules-widgets. Can you verify that that test app does to have any changes on your side just to make sure we are testing the same scenario. Also what is the version of the runtime that you are using?

**Comment by NathanaelA** [comment]
@VladimirAmiorkov - The previous leak is mostly fixed; you are now actually having the deallocation called.  That was a excellent improvement!    Which is freeing up the native elements and actually clearing part of the JS object.   With that fix you are not leaving a fully constructed JS element around, which is what #748 dealt with.     

However since each element is still a JS object, this is where the leak is now occurring.  So the "Label" object in memory is a JS object now in a partially **destructed** state.   So things like the `native` are now null, and many other pieces have been nulled out; allowing those things to be freed and GC'd.   However the actual "Label" JS object still contains valid links to its CSSStyle, Style, and a other JS sub-objects that are created when it is created.     Because the actual "Label" object is retained by the GridLayout, and the GridLayout is retained by the StackLayout, and the StackLayout is retained by the `_viewHolderChildren`.   Each of these partially deconstructed JS objects are retained in memory (and anything they are touching, events, data, text, Colors, etc).  are NOT freed. 

So the leak is basically all the now partially deconstructed JS objects that are retained because they are held by another object.   In my clients app; we are leaking 200k (yes 200k) in memory for just the LABEL alone each refresh.     As you might guess since it is a master-detail; they are going in and out of the detail screen, and making memory grow a lot until the app becomes non-responsive from too much wasted memory...

So the core of this is that all these partially deconstructed JS objects are what are hanging around because they are retained by some other JS object that is retained by something farther up the tree in the RLV.

I'm using stock runtime 4.2, stock tns code modules 4.2 (w/ the minor label allocation/deallocation notice to verify the last issue was fixed).   I'm using the latest standard ui-listview and the only piece that is @next is the widgets.

The app I uploaded in the #748 is unmodified.  It is set to use the RLV in my copy; (the app supports both RLV and Listview for these memory tests, you just have to comment/uncomment the screen code in the main XML for which control you want to use.)    The JS code is completely unmodified.

All I did was nuke my platforms folder; upgrade each of the pieces to the latest and then do those steps outlined above; launch the new copy; Grab a snapshot from the chrome.   Refresh 3 times; grab another snapshot.   If you dig into the snapshot 2 and compare them; you can find the JS objects that are deconstructed and easily trace the tree like I did to the holding object when appears to be the `_viewHolderChildren` object.

**Comment by VladimirAmiorkov** [comment]
Hi @NathanaelA ,

Thank you for the description. The mentioned _viewHolderChildren is being cleared correctly on any changed in the RadListView that would lead to its refresh method being called or to a native reload of its data (so pull to refresh with new items added/removed etc.). 

Just a quick question, after the step:

> Refresh 3 more times, take another snapshot:

> Snapshot is still 8.1 megs; Labels that exist are 78 (it went down by 3)--- HOWEVER a GC occurred; so the snapshot stayed approx the same as the last time.

I see in the screenshot that the Label objects are actually 73, meaning that 8 Label objects have been GC by the V8 GC. To me this looks very strange as if there is an actual leak that number should not go down at all. Note that the V8 GC is somewhat a tricking thing to force to collect objects that otherwise should be collected, that is just an FYI.

When you say:

> As you might guess since it is a master-detail; they are going in and out of the detail screen, and making memory grow a lot until the app becomes non-responsive from too much wasted memory...

has this been reproduced in an actual app. If yes is it possible you can share this app with us so we can test a real world scenario that causes a crash due to memory leaks?

**Comment by NathanaelA** [comment]
@VladimirAmiorkov - 

> I see in the screenshot that the Label objects are actually 73, meaning that 8 Label objects have been GC by the V8 GC. To me this looks very strange as if there is an actual leak that number should not go down at all. Note that the V8 GC is somewhat a tricking thing to force to collect objects that otherwise should be collected, that is just an FYI.

Yep, I misread the screen shot.  LOL; yes it dropped by 8.    And that was an interesting data point.  I had assumed it was caused by a viewHolderChildren object that may not have been fully built and been linked to whatever was holding the other items.    But it looks like that assumption was wrong.

I also just added `System.gc` to my gc button, and it actually does seem to cause the Labels (and other items) count to stabilize (a bit higher than I would have guessed, but nothing that causes any issues); so I assume that something native was holding the `viewHolderChildren ` so once I was able to tell the app to run a native gc, it freed the item and caused the JS to be able to free it.

So this report is un-duplicatable with my test project.

**Comment by NathanaelA** [comment]
Ok, so I'm going to close this bug; and open a new bug elsewhere. 

The actual underlying issue actually appears to be caused by Angular; Angular is creating a _nativeNodeToDebugNode tracking map structure and not clearing any of the references it appears.  So this is causing the memory leak in my clients app; because that reference is not cleared; it never clears anything that is linked to the label that would normally be freed.

I'll link to that issue from here once I create it.
