### ISSUE TITLE
Radlistview not rendering item templates inside Tab View on Android. Working fine on iOS. Need help

### ISSUE THREAD

**Issue by dexter2019** [telerik/nativescript-ui-feedback#829]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
_Yes

### Tell us about the problem
Radlist Listview Grid Layout is not rendering its items inside a tab view in Android. It is absolutely working fine on iOS.  Also, it is working fine outside tabview on andoid but not inside tab view.

### Which platform(s) does your issue occur on?
Android
### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 3.6.1
- **CLI:**  4.2.3
- **Cross-platform modules:**  4.2.3
- **Runtime(s):** 4.2.0

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application ..
2. tns run android

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

PFB XML file below. The same is working fine with iOS

<Page loaded="pageLoaded" class="page" xmlns="http://www.nativescript.org/tns.xsd" xmlns:lv="nativescript-ui-listview">

		<TabView height="100%" androidTabsPosition= "bottom">
			<TabView.items>
				<TabViewItem title="Home">
					<TabViewItem.view>

						<GridLayout rows="100,*">

               <GridLayout  row="0" rows="20,*" width="100%"  xmlns:lv="nativescript-ui-listview" backgroundColor="Red">

                    <Label row="0" text="Your favourite clubs" class="countryName" />
                    <lv:RadListView row="1" id="list-view" items="{{ countries }}" backgroundColor="Blue"  style="height: 500px"  >
                            <lv:RadListView.listViewLayout backgroundColor="Green">
                                    <lv:ListViewGridLayout scrollDirection="Horizontal" itemWidth="80"  spanCount="1" />
                             </lv:RadListView.listViewLayout>
                               <lv:RadListView.itemTemplate>

                                    <Label text="{{name}}" row="0" col="0" backgroundColor="red" />

                            </lv:RadListView.itemTemplate>
             </lv:RadListView>

            </GridLayout>

						<GridLayout row="1">

						</GridLayout>

					</GridLayout>

		</TabViewItem.view>
				</TabViewItem>
				<TabViewItem title="Tab 2">
					<TabViewItem.view>
						<GridLayout columns="60, auto, *" rows="60, auto, *" width="230" height="230" backgroundColor="lightgray">
							<Label text="Label 1" row="0" col="0" backgroundColor="red" />
							<Label text="Label 2" row="0" col="1" colSpan="2" backgroundColor="green" />
							<Label text="Label 3" row="1" col="0" rowSpan="2" backgroundColor="blue" />
							<Label text="Label 4" row="1" col="1" backgroundColor="yellow" />

						</GridLayout>
					</TabViewItem.view>
				</TabViewItem>

				<TabViewItem title="Tab 2">
					<TabViewItem.view>
						<GridLayout columns="60, auto, *" rows="60, auto, *" width="230" height="230" backgroundColor="lightgray">
							<Label text="Label 1" row="0" col="0" backgroundColor="red" />
							<Label text="Label 2" row="0" col="1" colSpan="2" backgroundColor="green" />
							<Label text="Label 3" row="1" col="0" rowSpan="2" backgroundColor="blue" />
							<Label text="Label 4" row="1" col="1" backgroundColor="yellow" />

						</GridLayout>
					</TabViewItem.view>
				</TabViewItem>
				<TabViewItem title="Tab 2">
					<TabViewItem.view>
						<GridLayout columns="60, auto, *" rows="60, auto, *" width="230" height="230" backgroundColor="lightgray">
							<Label text="Label 1" row="0" col="0" backgroundColor="red" />
							<Label text="Label 2" row="0" col="1" colSpan="2" backgroundColor="green" />
							<Label text="Label 3" row="1" col="0" rowSpan="2" backgroundColor="blue" />
							<Label text="Label 4" row="1" col="1" backgroundColor="yellow" />

						</GridLayout>
					</TabViewItem.view>
				</TabViewItem>
				<TabViewItem title="Tab 2">
					<TabViewItem.view>
						<GridLayout columns="60, auto, *" rows="60, auto, *" width="230" height="230" backgroundColor="lightgray">
							<Label text="Label 1" row="0" col="0" backgroundColor="red" />
							<Label text="Label 2" row="0" col="1" colSpan="2" backgroundColor="green" />
							<Label text="Label 3" row="1" col="0" rowSpan="2" backgroundColor="blue" />
							<Label text="Label 4" row="1" col="1" backgroundColor="yellow" />

						</GridLayout>
					</TabViewItem.view>
				</TabViewItem>
			</TabView.items>
		</TabView>

</Page>

**Comment by tsonevn** [comment]
Hi @dexter2019,
I tested the described scenario in a sample project, however, was unable to recreate an issue the RadListView rendering. For your convenience, I am attaching a sample project. Please review it and make the needed changes, which will allow us to recreate the problem. 
[Archive.zip](https://github.com/telerik/nativescript-ui-feedback/files/2369513/Archive.zip)

Also, can you provide more info about the Android device/emulator, which you are using for testing?

**Comment by dexter2019** [comment]
hello, sir thanks a lot for your fast reply and help. I just found out that the issue was with "loaded"  event. when I changed the event to "navingatingto" the item templates were successfully loaded. I am a beginner to entire full stack coding. Perhaps tav view was getting loaded before Radlist View items and hence was the issue. Still thanks a lot. Looking forward to your help in the future.
