### ISSUE TITLE
Rad List View - Selection with Header, Select all, Total popup 1 times, Separator.

### ISSUE THREAD

**Issue by Natalia-Hristova** [telerik/nativescript-ui-feedback#83]
from @Zengratul 

>I have 4 problems with Telerik Rad List View which need your help. I tried on Android.
>
>1- The highlight of selection shows mistake location if I set it with header.
>
>2- May Rad List View have error with multi-tasking?! The layout is broken when I use multi-tasking.
>![problem 2](https://cloud.githubusercontent.com/assets/7825869/22136440/339f9ac8-df07-11e6-9ba0-590edfceeac7.gif)
>
>3- I use Toast from Android to show popup, but when I choose "select all" on top right corner, I >show a countable. Can I get a total number of files immediately?!
>
>4- I can not insert separator line. I try as below code in my Grid Layout but it's not working.
><StackLayout height="2" backgroundColor="black"></StackLayout>
>![problem 4](https://cloud.githubusercontent.com/assets/7825869/22136448/3aae6dee-df07-11e6-928d-875218a3a681.gif)
>
>This is my package, please check it.
>[Rad List View.zip](https://github.com/telerik/nativescript-ui->samples/files/718458/Rad.List.View.zip)

**Comment by rajasekarsp** [comment]
Anyone working on it yet ?

**Comment by VladimirAmiorkov** [comment]
@rajasekarsp There have been many fixes and changes to the RadListView since this thread was first reported. Can you verify that you are experiencing any of the mentioned issues with the latest 2.0.1 version of nativescript-telerik-ui ? Also could share with is a project or the needed code snippets in reproducing the issue?

**Comment by rajasekarsp** [comment]
I have an issue

RadListView normally works fine, but when i include  header for it, the selection highlight behaves differently. When i select on an item, its 'isSelected' property is set true, but the previous item gets the grey highlight.

**My View**
`<RadListView [items]="statusLookupList" row="1" selectionBehavior="Press" multipleSelection="true" (itemSelected)="filterItemSelected($event, statusLookupList)" (itemDeselected)="filterItemDeselected($event, statusLookupList)" (loaded)="filterCategoryLoaded($event, statusLookupList)">
                        <ng-template tkListItemTemplate let-item="item" let-i="index">
                            <GridLayout columns="*, 15" rows="*" [class.selected]="item.isSelected===true" class="selectControl">
                                <Label [class.selected]="item.isSelected===true" col="0"  [text]="item.text"></Label>
                                <Image [visibility]="item.isSelected===true ? 'visible' : 'collapsed'" src="~/images/check.png" col="1"></Image>
                            </GridLayout>
                        </ng-template>
                        <ng-template tkListViewHeader>
                            <GridLayout backgroundColor="#65a565">
                                <Label text="This is the list header"></Label>
                            </GridLayout>
                        </ng-template>
                    </RadListView>`



**My Typescript code:**

`public filterItemSelected(args, lookupList){
        var listView = args.object;
        lookupList[args.itemIndex].isSelected = true;
        listView.selectItemAt(args.itemIndex);
    }

    public filterItemDeselected(args, lookupList){
        lookupList[args.itemIndex].isSelected = false;
    }

    public filterCategoryLoaded(args, lookupList){
        var listView = args.object;
        lookupList.forEach((item, index) => {
            if(item.isSelected){
                listView.selectItemAt(index);
            }
        });
    }`

**Comment by VladimirAmiorkov** [comment]
@rajasekarsp I was able to reproduce this issue on our end and logged it in a separate issue for better tracking. You can follow it [here](https://github.com/telerik/nativescript-ui-feedback/issues/194).
