### ISSUE TITLE
Question: How to style dataform picker selected item text color in Android

### ISSUE THREAD

**Issue by handoyo** [telerik/nativescript-ui-feedback#836]
Hi, i'm trying to style DataForm text color for selected text item color in Android. I have looked at the advanced sample code, but can't find any example. Here is my sample code in JS. Which function should I use? Thanks a lot.

[Styling Data Form Picker selected item text color in Android](url)

**Comment by handoyo** [comment]
Hi @tsonevn , sorry. 
Here's the URL [https://play.nativescript.org/?template=play-js&id=bm4ARL&v=22](url)

**Comment by tgpetrov** [comment]
Hi @handoyo 

In order to change the style of the Picker editor on android, you need to provide an xml resource with the desired style:
1) in <app_root>/app/App_Resources/Android/layout add a new xml file containing the TextView that you would like to use and name it for example custom_spinner_editor_text.xml with the following content:
```
<?xml version="1.0" encoding="utf-8"?>
<TextView xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@android:id/text1"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:padding="0dp"
    android:textColor="#ff0000"
    android:singleLine="true"
    android:ellipsize="marquee"
    style="?android:attr/spinnerItemStyle"/>
```
2. Use the editorUpdate event of the dataform:
```
dfEditorUpdate(args: DataFormEventData) {
    let editor = args.editor;
    let androidContext = editor.getEditorView().getContext();
    let customLayoutResourceId = androidContext.getResources().getIdentifier("custom_spinner_editor_text", "layout", androidContext.getPackageName());

    editor.setSpinnerItemLayoutId(customLayoutResourceId);
}
```

**Comment by handoyo** [comment]
Hi @tgpetrov ,

Thanks a lot for the example. I will try it. Another question, how about changing the picker listbox text color? Should i use the same method?
