### ISSUE TITLE
License clarification / Copyright information

### ISSUE THREAD

**Issue by lambourn** [telerik/nativescript-ui-feedback#838]
The [LICENSE.md](https://github.com/telerik/nativescript-ui-feedback/blob/master/LICENSE.md) contains the generic license agreement between Telerik and software developers that use the nativescript-ui components in their apps.

I've got two questions regarding this license:

> 2.3.2.4 You must include a valid copyright message in Your Integrated Products in a location viewable by Authorized End-Users (e.g. “About” box) that will serve to protect Telerik’s copyright and other intellectual property rights in the Software.

fair enough. But how exactly should this copyright message look like? Are there any suggestions/templates?

> 8. Collection and Use of Data
> Telerik uses tools to deliver certain Software features and extensions [...]

does this apply to the deployed nativescript-ui components at runtime as well? Or is this just meant to be activated at development time?

**Comment by etabakov** [comment]
The guidance from our legal team about the copyright message is as follows:

> Telerik’s standard notice requirement is for the following language to be included in the About Box (or absent the availability of an About Box, such other prominent location viewable by Authorized End-Users where such messages are customarily located):
>  
> [Certain Portions*] Copyright © [20xx – 20xx**] Telerik EAD, All rights reserved.
>  
> (* you can use the term “Certain Portions” or identify the actual portions of the software that embody Telerik’s copyright(s)).
> (** please refer to the copyright notice provided with each Telerik product for the applicable date range).

About the "Collection and Use of Data" point - this is a general statement about all Telerik products. The nativescript-ui components specifically are distributed through npm and we are not pushing or gathering any additional data in regards to this neither runtime nor at development time.

I hope this sheds some light, but if you have further questions or concerns - do not hesitate to drop a line.
