### ISSUE TITLE
Feature: adding `viewModeChange` event for RadCalendar

### ISSUE THREAD

**Issue by miroslavaivanova** [telerik/nativescript-ui-feedback#84]
To be able to use two way binding for viewMode property in NativeScirpt Angular 2 project, we should have both viewMode property and viewModeChange event.

https://angular.io/docs/ts/latest/guide/template-syntax.html#!#two-way

### Which platform(s) does your issue occur on?

Both

**Comment by tgpetrov** [comment]
As of now, both are available: [viewMode](http://docs.telerik.com/devtools/nativescript-ui/api/classes/radcalendar.html#viewmodeproperty) property & [viewModeChanged](http://docs.telerik.com/devtools/nativescript-ui/api/classes/radcalendar.html#viewmodechangedevent) event.
