### ISSUE TITLE
[LinearAxis] Documentation shows plotMode documentation for DateTimeCategoricalAxis

### ISSUE THREAD

**Issue by cmckni3** [telerik/nativescript-ui-feedback#848]
## Please, provide the details below:

https://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/Chart/Axes/linear

>Plot Mode
The DateTimeCategoricalAxis allows you to define how exactly the axis will be plotted on the viewport of the chart. The possible values are:
BetweenTicks: Points are plotted in the middle of the range, defined between each two ticks.
OnTicks: Points are plotted over each tick.
OnTicksPadded: Points are plotted over each tick with half a step padding applied on both ends of the axis.
You can get and set the current value with the plotMode property.

**N.B.** plotMode does not appear to do anything when used on a `LinearAxis`.

**N.B.** The Angular documentation for Axes does not match up to the NativeScript documentation. https://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/Chart/Axes/axes

### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?

Yes

### Tell us about the problem

Documentation is outdated/inaccurate.

### Which platform(s) does your issue occur on?

Both

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** ~2.0.0
- **CLI:** 4.2.4
- **Cross-platform modules:** ~4.2.0
- **Runtime(s):** 4.2.0

### Please tell us how to recreate the issue in as much detail as possible.

Go to docs pages at https://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/Chart

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

No

**Comment by tgpetrov** [comment]
Hi @cmckni3 
Thank you for your report. The`plotMode` is now removed from the `LinearAxis` page and the Axes articles on the Angular section have been updated to match the articles on the NativeScript Core section.
