### ISSUE TITLE
Cannot type space in RadAutoCompleteTextView in Angular app running on Android

### ISSUE THREAD

**Issue by IRCraziestTaxi** [telerik/nativescript-ui-feedback#850]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
Cannot type space in RadAutoCompleteTextView in Angular app running on Android

### Which platform(s) does your issue occur on?
Android (platform version 4.2.1)

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version: (do not see it in package.json)
- **CLI: 4.2.1
- **Cross-platform modules: ^4.2.0
- **Runtime(s): tns-android: 4.2.0

### Please tell us how to recreate the issue in as much detail as possible.
1. Register RadAutoCompleteTextView element in file with Angular component
2. Include element in template
3. Run the app (tns run android)
4. Type some letters followed by a space (space is not inserted)
5. Space is not applied in text box
6. Notice also that a space is allowed if no other characters have been typed, but typing another space clears out the text box

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
```ts
import { RadAutoCompleteTextView } from "nativescript-ui-autocomplete";
// And other stuff

registerElement("RadAutoCompleteTextView", () => RadAutoCompleteTextView);

@Component({
    // ...
})
export class MyComponent implements OnInit {
    @ViewChild("autocompleteSearch")
    private readonly _search: ElementRef<RadAutoCompleteTextView>;

    // ...

    public ngOnInit(): void {
        this._search.nativeElement.loadSuggestionsAsync = (search: string) => {
            // I can also replace this with a simple promise that logs the search string
            // and returns an empty array; nothing changes.
            return this.searchPlaces(search);
        };
    }

    // ...
}
```

**Comment by tsonevn** [comment]
Hi @IRCraziestTaxi,
I have tested the described scenario with the [nativescript-ui-samples-angular](https://github.com/telerik/nativescript-ui-samples-angular/tree/master/autocomplete/app/examples/getting-started) app, however, was unable to recreate an issue with typing spaces in the `RadAutoCompleteTextView` component.

Can you provide sample project, where the issue can be reproduced?

**Comment by IRCraziestTaxi** [comment]
Sorry, I have been pretty busy and was just now able to copy over the project with all but pertinent code included and ensure that the copied project reproduces the error.

Repo is here:

https://github.com/IRCraziestTaxi/nativescript-ui-autocomplete-google-places

If it helps, I am running the project on an LG V20 running Android 8.0.0.

**Comment by IRCraziestTaxi** [comment]
Is this being investigated? If not, when will somebody be able to get around to looking at it?

**Comment by tsonevn** [comment]
Hi @IRCraziestTaxi,
We investigated further your case and found that you have written `suggest` with a lowercase first letter, which is an invalid value for the `suggestMode` property. In this scenario the `RadAutoCompleteTextView` will set its default value (`SuggestAppend`). To solve the issue in your project, you should set up the suggesttMode as follow ->`suggestMode="Suggest"`.

**Comment by IRCraziestTaxi** [comment]
@tsonevn Thank you for the reply. I will change `suggest` to `Suggest` as suggested. However, I will say that, even using the default `SuggestAppend`, I do not feel like being unable to type a space should be acceptable behavior.
