### ISSUE TITLE
Vue.js support and docs for DataForm

### ISSUE THREAD

**Issue by msaelices** [telerik/nativescript-ui-feedback#851]
The current Vue support is poor.

- [x] Refactor current support to be a Vue plugin
- [x] Complete examples
- [x] validation
- [x] validation modes
- [x] validation events
- [x] custom validation
- [x] editors
- [x] custom editors
- [x] groups
- [x] Complete docs

**Comment by prashantnirgun** [comment]
Its still are very basic introduction We feel lost as its not in Javascrpt all examples are in Typescript. That makes our life more difficult. But its just a small introduction as compared to Angular

**Comment by kan202** [comment]
??
