### ISSUE TITLE
Empty array for valuesProvider crashes in iOS

### ISSUE THREAD

**Issue by Mitko-Kerezov** [telerik/nativescript-ui-feedback#862]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
_Yes_

### Tell us about the problem
In case the `valuesProvider` is assigned to some provider which returns an empty array the behavior for Android and iOS differs heavily.
On Android it works as expected - an empty `Picker` is displayed and nothing can be selected from the dropdown
On iOS however the application crashes

### Which platform(s) does your issue occur on?
_iOS_

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI Dataform:** 3.7.3

**Comment by zbranzov** [comment]
The fix is released in nativescript-ui-dataform@3.8.
