### ISSUE TITLE
RadListView ListViewStaggeredLayout and spanCount of 2 in iOS

### ISSUE THREAD

**Issue by racknoris** [telerik/nativescript-ui-feedback#864]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
Using `ListViewStaggeredLayout` with `spanCount="2"` on iOS creates 2 columns that are not aligned and get out of the screen as we scroll down on iOS

### Which platform(s) does your issue occur on?
iOS
iPhone 6 with iOS 12.0

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** (the version of nativescript-telerik-ui/-pro in the `package.json`)
- **CLI:** 4.2.0
- **Cross-platform modules:** 4.2.0
- **Runtime(s):** 4.2.0

### Please tell us how to recreate the issue in as much detail as possible.
1. `tns create sampleApp --ng`
2. Go to the sdk sample of `ListViewStaggeredLayout` [here](https://github.com/telerik/nativescript-ui-samples-angular/tree/release/sdkAngular/app/listview/item-layouts) and copy listview-item-layouts-staggered.component.html/ts/css to your new app
3. Scroll to the bottom and up: see that the columns are aligned properly and it scrolls smoothly
4. Change the `spanCount` in `listview-item-layouts-staggered.component.html` to "2"
5. Scroll to the bottom and up, see that the columns are not aligned and get out of the screen as we scroll to the bottom

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
Yes, playground example:
https://play.nativescript.org/?template=play-ng&id=IQUQ9U

**Comment by VladimirAmiorkov** [comment]
This is a known issue https://github.com/telerik/nativescript-ui-feedback/issues/788 . Closing this issue, please follow the other one.
