### ISSUE TITLE
showOverNavigation not working on home page

### ISSUE THREAD

**Issue by miroslavaivanova** [telerik/nativescript-ui-feedback#87]
from @shlomiassaf

> Hi,

Created an app with 2 routes pointing at the same component.

First route setup is /
2nd route setup is feed (same component as in route 1)

The component has a drawer with a button that opens it, showOverNavigation is set to true.

When entering the app and tapping the button drawer opens below the ActionBar.
The drawer has a link to the 2nd route, clicking on it.
In 2nd route, tapping on the button opens the drawer above the ActionBar as expected.

More info:
On bootstrap: startPageActionBarHidden: false

Template structure:
**Root component**

`<ActionBar title="">
        
        </ActionBar>
<page-router-outlet></page-router-outlet>`

**Page Component**

`<RadSideDrawer #drawerComponent showOverNavigation="{{true}}">
    <StackLayout tkDrawerContent>
        <StackLayout class="drawer-header">
            <Label text="Menu"></Label>
        </StackLayout>
        <ScrollView class="drawer-content">
            <StackLayout class="drawer-links" orientation="vertical">
                <StackLayout class="drawer-link"
                             orientation="horizontal">
                    <Button [nsRouterLink]="['/']" text="Home"></Button>
                </StackLayout>
                <StackLayout class="drawer-link"
                             orientation="horizontal">
                    <Button [nsRouterLink]="['/feed']" text="FEED"></Button>
                </StackLayout>
            </StackLayout>
        </ScrollView>
    </StackLayout>
    <StackLayout tkMainContent>
        <Label text="Hello World"></Label>
        <Button (tap)="drawerComponent.sideDrawer.toggleDrawerState()">TAP</Button>
    </StackLayout>
</RadSideDrawer>`
Can't seem to get the home page of the app to show drawer on top of ActionBar.

Thanks!

https://github.com/telerik/nativescript-ui-samples-angular/issues/26

**Comment by VladimirAmiorkov** [comment]
Hi all,

This is a duplicated issue so please continue any discussions [here](https://github.com/telerik/nativescript-ui-feedback/issues/61).
