### ISSUE TITLE
RadListView : List components are recreated when state changes

### ISSUE THREAD

**Issue by plduhoux** [telerik/nativescript-ui-feedback#875]
Every update (push or splice for example) on the state list array used to show RadListView  generates a **recreation of all the components in the list**.

### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes, I searched everywhere, found memory leak issues which may be related (as this behavior may generate memory leaks) but I never found this precise issue.

### Tell us about the problem
The issue may not be very easy to observe because the components are recreated so fast that there is in general cases no glitch on the UI (perhaps a small latency if the list is huge) but if you start using images and complex components on each line of the RadListView and you have frequent updates to the list structure, the app starts being unusable.

To illustrate this issue, I created a sample in the playground : 
https://play.nativescript.org/?template=play-vue&id=qYJBWS&v=2

In this sample, a list is initiated with 3 items, you can add an item or remove the last one using buttons at the top. Each entry in the RadListView is a RadListItem custom component which triggers an incrementation of a counter on the state list when it is created (through the vue `created() {...}` method)
At start, each counter's value is 1 because each component has been created only once.
Click on "Add item" and the first three item's counter becomes 2 !

When testing, you can see in the console all these components being recreated each time
All the examples that I found online (for example https://github.com/msaelices/ns-ui-vue-demo/tree/master/app) have the same issue, if you look at the console when a new entry is created, a whole bunch of createElement appear and the list goes back to top

This issue comes from RadListView, you can test this other sample which is exactly the same except that RadListItem are rendered within a standard ListView, counters are staying at 1 implying that the component is only created once : https://play.nativescript.org/?template=play-vue&id=f522qC&v=1

In VueJs, when using a v-for, you need to v-bind a key attribute which must be unique among all list items. Vue is using this key to know if a component must be recreated or not, the same must be done for the RadListView to avoid recreating everything each time.

### Which platform(s) does your issue occur on?
I only tested it on Android

### Please provide the following version numbers that your issue occurs with:
- nativescript-vue 2.0.0
- nativescript-ui-listview 3.7.1

### Please tell us how to recreate the issue in as much detail as possible.
Here is a NativeScript Playground sample illustrating the issue
https://play.nativescript.org/?template=play-vue&id=qYJBWS&v=2

**Comment by msaelices** [comment]
@plduhoux It's difficult the logic of detecting changes to the Vue instance `items` list without recreating the entire list except if we use an `ObservableArray` object for the `items` attribute.

BTW in the `3.7.1` version, even using  `ObservableArray`, the list is recreated again. I did a Pull Request  with the fix in the `RadListView` code but there is no new release yet.

With the new code, you can use `ObservableArray` and the list will be not recreated anymore. Look at this sample code:

```
import Vue from 'nativescript-vue';
import * as frameModule from 'tns-core-modules/ui/frame';
import { ObservableArray } from 'tns-core-modules/data/observable-array';

const getObservableList = () => {
  return new ObservableArray([
    0,
    1,
    2,
  ]);
};

const getList = () => {
  return [
    0,
    1,
    2,
  ];
};

const RadListItem = {
  name: 'RadListItem',
  template: `
    <Label class="p-10"
           :text="itemText"
           col="0" textWrap="true" verticalAlignment="center"/>
  `,
  props: ['prefix', 'item'],
  created() {
    setTimeout(() => {
      this.$emit('create-item');
    }, 100);
  },
  computed: {
    itemText () {
      return `${this.prefix}: ${this.item}`;
    }
  }
};

export default {
  template: `
  <Page>
    <ActionBar title="Observable items">
      <NavigationButton text="Back" android.systemIcon="ic_menu_back" @tap="onNavigationButtonTap"></NavigationButton>
      <ActionItem text="Observable items" android.position="popup" @tap="onSelectObservable()"></ActionItem>
      <ActionItem text="Non observable items" android.position="popup" @tap="onSelectNonObservable()"></ActionItem>
    </ActionBar>
    <StackLayout orientation="vertical">
      <GridLayout columns="*, *" rows="auto">
        <Button text="Add item" @tap="addItem" col="0" />
        <Button text="Remove last item" @tap="deleteItem" col="1" />
      </GridLayout>
      <GridLayout columns="*, *" rows="auto">
      <RadListView for="r in currentList" col="0">
        <v-template>
          <RadListItem prefix="Item" :item="r" @create-item="markCreation(r)" />
        </v-template>
      </RadListView>
      <RadListView ref="counterlist" for="r in createsCounter" col="1">
        <v-template>
          <RadListItem prefix="Create counter" :item="r" />
        </v-template>
      </RadListView>
    </GridLayout>
  </StackLayout>
  </Page>
  `,
  data() {
    return {
      title: description,
      currentList: getObservableList(),
      createsCounter: [0, 0, 0],
    };
  },
  components: { RadListItem },
  methods: {
    onNavigationButtonTap() {
      frameModule.topmost().goBack();
    },
    addItem() {
      this.currentList.push(this.currentList.length);
    },
    deleteItem() {
      if (this.currentList.length === 0) {
        return;
      }
      const index = this.currentList.length - 1;
      this.currentList.splice(
        this.currentList.length - 1, 1);

      this.createsCounter.splice(
        this.currentList.length - 1, 1);
    },
    markCreation(item) {
      console.log(`mark item creation for ${item}...`);
      while (this.createsCounter.length <= item) {
        this.createsCounter.push(0);
      }
      this.createsCounter[item]++;
      this.$refs.counterlist.refresh();
    },
    onSelectObservable() {
      this.currentList = getObservableList();
      this.createsCounter = [0, 0, 0];
    },
    onSelectNonObservable() {
      this.currentList = getList();
      this.createsCounter = [0, 0, 0];
    },
  }
};
```

This sample is based on yours, and you can check the difference between using plain arrays and `ObservableArray`. See this screencast:

![items-recreated](https://user-images.githubusercontent.com/136875/46964784-432eef80-d0a9-11e8-9ad1-feec3ac9ead3.gif)

**Comment by msaelices** [comment]
1. `RadListView` is not an open source library.
2. I cannot answer the question, as I worked mainly on the Vue binding, and I have no expertise in the `RadListView` internals. But you are right: it works on regular `ListView`. So I asked the same to the NS UI core dev. I guess there are a lot of features in the `RadListView` so the internal code is very different, and the logic for re-use the item created should be different.

**Comment by bugventure** [comment]
@plduhoux NativeScript UI was a commercial suite of components that Progress decided to give away for free as a token of contribution to the open-source NativeScript community. It is governed by a [non-OSS license](https://github.com/telerik/nativescript-ui-feedback/blob/master/LICENSE.md), but the license grants "free for commercial usage" rights to anyone, except CMS or component vendors. While technically the source code is still closed and proprietary, the longer-term vision for this component library is to go fully open-source under the Apache 2.0 license. Just not there yet.

So, yes, you can use it as part of a commercial application, unless this application is a CMS or a component suite. And yes, we'd ultimately want to change the license, but change it to Apache 2.0, not make it more restrictive.

**Comment by plduhoux** [comment]
Wow ! Thanks for the details ! 

Nativescript-ui components are awesome, would be great to have them open sourced !

**Comment by plduhoux** [comment]
nativescript-ui-listview 3.7.2 has just been published, I tried with this version and ObservableArray but it seems that the problem is still there.

Was your PR shipped in 3.7.2 ?

**Comment by VladimirAmiorkov** [comment]
Hi @plduhoux ,

No the 3.7.2 version does not resolve this issue. You can follow the status of any issue and if it is still in "open" state than it has not been resolved. You can also follow our release notes here: https://github.com/telerik/nativescript-ui-feedback/blob/master/releases/listview.md

**Comment by plduhoux** [comment]
ok thanks

**Comment by msaelices** [comment]
@plduhoux I've just tested that the 5.0.0 version fixes the problem. Of course, you need to use `ObservableArray` objects.

**Comment by plduhoux** [comment]
Thanks !
