### ISSUE TITLE
Nativescript RadDataForm MultilineText not working on Android

### ISSUE THREAD

**Issue by keerl** [telerik/nativescript-ui-feedback#877]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
I am using RadDataForm in my Nativescript Angular project and when I try to use "MultilineText" it doesn't work on Android, it just appears as a normal "Text" box. I am not able to enter multiple lines. Works fine on iOS.

### Which platform(s) does your issue occur on?
Android
### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** nativescript-ui-dataform 3.7.3
- **CLI:** 4.2.4
- **Cross-platform modules:** 4.2.0
- **Runtime(s):** 4.2.0

<img src="https://i.stack.imgur.com/RjH8n.png" width="200" />

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
**add-store.model.ts**

    export class AddStore {
        public name: string;
        public description: string;

        constructor(name: string, description: string,) {
            this.name = name;
            this.description = description;
        }
    }

**add-store-metadata-validation.json**

    {
        "isReadOnly": false,
        "commitMode": "immediate",
        "validationMode": "immediate",
        "propertyAnnotations":
        [
            {
                "name": "name",
                "displayName": "Store Name",
                "index": 1,
                "editor": "Text"
            
            },
            {
                "name": "description",
                "displayName": "Description",
                "index": 2,
                "editor": "MultilineText"
            
            }
        
        ]
    }

**add-store.component.ts**

    import { Component, AfterViewInit } from "@angular/core";
    import { RouterExtensions } from "nativescript-angular/router";
    import { UtilitiesService } from "~/services/utils.service";
    import { AddStore } from "./add-store.model";

    @Component({
        selector: "add-store",
        moduleId: module.id,
        templateUrl: "./add-store.component.html"
    })

    export class AddStoreComponent implements AfterViewInit {
    
        store: AddStore;
        metadata;

        constructor(private router:RouterExtensions) {
            this.store = new AddStore("test name" , "test\nsdfgfsdf");
            this.metadata = require("./add-store-metadata-validation.json");
        }

        ngAfterViewInit(): void { 
        
        }

        goBack() {
            this.router.back();
        }
    }

**add-store.component.html**

    <ActionBar class="action-bar" title="Store Setup">
        <NavigationButton android.systemIcon="ic_menu_back" (tap)="goBack()"></NavigationButton>
    </ActionBar>
    <GridLayout rows="*">
            <StackLayout row="0" class="page page-content" height="100%">
                <RadDataForm [source]="store" [metadata]="metadata"></RadDataForm>
            </StackLayout>  
    </GridLayout>

**Comment by tsonevn** [comment]
HI @keerl, 
I was able to recreate the issue with our [sample project](https://github.com/telerik/nativescript-ui-samples/tree/master/dataform/app/examples/metadata). The problem can be recreated while defining a Dataform with JSON metadata. 
Meanwhile, you can define the DataForm's editors via XML.

**Comment by zbranzov** [comment]
The fix is released in nativescript-ui-dataform@3.8.
