### ISSUE TITLE
RadPieChart visual discrepancy between Android and iOS

### ISSUE THREAD

**Issue by Mitko-Kerezov** [telerik/nativescript-ui-feedback#879]
### Tell us about the problem
There is a visual discrepancy between Android and iOS legend labels. On Android the numbers from `valueProperty` are appended to the text from `legendLabel` whereas this is not the case with iOS.
Visual [here](https://www.screencast.com/t/QwGbxunpf)
I consider this a bug on the Android side because one can always add information on each label but subtracting information is not possible. If I wanted the same behavior on iOS I could do it with code, whereas if I wanted only the labels on Android there isn't a way right now.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
[NS Playground Repro](https://play.nativescript.org/?template=play-ng&id=XdvRnt)

**Comment by zbranzov** [comment]
The fix is released in nativescript-ui-chart@3.9.1. Enjoy!
