### ISSUE TITLE
Is there a way to display same items on the horizontal axis?

### ISSUE THREAD

**Issue by janossuta** [telerik/nativescript-ui-feedback#881]
Hi!

In my app the users can add items to the chart and I'm showing that item with the time and I would like to show the different items but if they are adding items in the same time only one item added to the chart. Is there a way to add items to the chart by ID but not showing that ID but another display text?

sorry for the bad drawing :)
![chart](https://user-images.githubusercontent.com/16418295/47038339-82307400-d181-11e8-9ea3-3295caf7a738.png)

Here is a simple example:
https://play.nativescript.org/?template=play-ng&id=P8WPCT&v=3

**Comment by tsonevn** [comment]
Hi @janossuta,
You can define another `AreaSeries`, where you can display a second source array and use the `PaletteEntry` to set up different fillColor for each of the series. Check out the example [here](https://play.nativescript.org/?template=play-ng&id=P8WPCT&v=5).

**Comment by janossuta** [comment]
Hi @tsonevn,

I don't want to display multiple arrays I would like to show every item in one array even if they are same, so I don't want to stack the items with same ID but I want to display them on a separate position on the horizontal axis.

```
{id:1,time:10:23,value:10},
{id:2,time:11:45,value:12},
{id:3,time:12:30,value:34},<- show this two item on different position on the chart
{id:4,time:12:30,value:23},<- show this two item on different position on the chart
{id:5,time:13:45,value:11},
{id:6,time:18:20,value:23},
{id:7,time:20:30,value:45}
````

![image](https://user-images.githubusercontent.com/16418295/47084362-8a38f400-d213-11e8-9897-bdace86a602c.png)

**Comment by tsonevn** [comment]
Hi @janossuta,
To achieve this you can set up the `categoryProperty` to use the `id` property, however, in this case, the ids will be displayed instead of the time. Currently, there is no functionality, which allows to set up which property to be used for the labels in the axes.
