### ISSUE TITLE
Autocomplete TokenModel is add  only two values ,how can i add multiple values add in TokenModel

### ISSUE THREAD

**Issue by yogapriyaK** [telerik/nativescript-ui-feedback#882]
Autocomplete TokenModel is add  only two values ,how can i add multiple values add in TokenModel

**Comment by progressify** [comment]
I think he means: the only value accepted by TokenModel is a string. 
Can be comfortable store in TokenModel an Object, for example

**Comment by tgpetrov** [comment]
Closing as a duplicate of https://github.com/telerik/nativescript-ui-feedback/issues/65
