### ISSUE TITLE
[Bug] [Vue] [RadListView] object.notifySwipeToExecuteFinished()  doesn't work.

### ISSUE THREAD

**Issue by mathieutu** [telerik/nativescript-ui-feedback#883]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
On the swipe events, a SwipeActionsEventData event is supposed thrown, with a key object.

```ts
    /**
    * The object that fires the event.
    */
    object: RadListView;
```

When I'm trying to use `object.notifySwipeToExecuteFinished()` I've a `NativeScript encountered a fatal error: TypeError: undefined is not an object (evaluating 'this._nativeView.endSwipe')` message.

I can get rid of the issue by making a ref, but the object returned should be the RadListView instance according to the doc. 

The same process works well with `pullToRefreshInitiated` event and `object.notifyPullToRefreshFinished();`

### Which platform(s) does your issue occur on?
Both 

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** "nativescript-ui-listview": "^3.7.1"
- **CLI:** 5.0.0-2018-10-16-12488
- **Cross-platform modules:** "tns-core-modules": "^4.2.0"
- **Runtime(s):** 4.2.0

### Please tell us how to recreate the issue in as much detail as possible.
- Execute a swipe action on a RadListView

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
```ts
onSwipeEnded({ object }: SwipeActionsEventData) {
      object.notifySwipeToExecuteFinished();    
},
```

Thanks ! 

PS: pinging @rigor789 on it, as I've already showed it to him on slack.

**Comment by mathieutu** [comment]
Hi @msaelices, it was exactly the same as yours. 

I've not used nativescript for months, so I can't say if it's working with last versions. Maybe has it been fixed now?

**Comment by msaelices** [comment]
No doubt that is fixed then.
