### ISSUE TITLE
RadCartesianChart: Nothing showing on the page

### ISSUE THREAD

**Issue by anaszgh** [telerik/nativescript-ui-feedback#893]
### Did you verify this is a real problem by searching the [NativeScript Forum]?
Yes

### Which platform(s) does your issue occur on?
`Both`

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** (the version of nativescript-telerik-ui/-pro in the `package.json`) 
`"nativescript-ui-chart": "^3.9.0",`
- **CLI:** (run `tns --version` to fetch it) 4.2.3
- **Cross-platform modules:** (the version of tns-core-modules in the `package.json`)
`"tns-core-modules": "^4.3.0-2018-10-08-112346-02",`
- **Runtime(s):** (the `"tns-android"` and `"tns-ios"` properties in the `package.json`)
```
"tns-android": {
      "version": "4.2.0"
    },
    "tns-ios": {
      "version": "4.2.0"
    }
```

### Please tell us how to recreate the issue in as much detail as possible.
1. Import UIChart module in app.module.ts
2. add imported module to the import section
3. try to use the BarSeries in any page

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

I prepared a playground example, i copied the code from the angular chart example
`https://play.nativescript.org/?template=play-ng&id=Q11HWJ`

**Comment by tsonevn** [comment]
Hi @anaszgh,
When you are using RadChart component inside a ScrollView, you should specify the height of the Chart or the height of its parent. For example:
```
<GridLayout>
	<ScrollView class="page">
		<StackLayout   class="home-panel">
			<RadCartesianChart height="200" tkExampleTitle tkToggleNavButton>
				<CategoricalAxis tkCartesianHorizontalAxis verticalLocation="Bottom" labelSize="11"></CategoricalAxis>
				<LinearAxis tkCartesianVerticalAxis tkCartesianVerticalAxis horizontalLocation="Left" labelSize="11"></LinearAxis>
				<BarSeries tkCartesianSeries [items]="categoricalSource" categoryProperty="Country" valueProperty="Amount"></BarSeries>
			</RadCartesianChart>
		</StackLayout>
	</ScrollView>
</GridLayout>
```
or
```
<GridLayout>
	<ScrollView class="page">
		<StackLayout  height="200" class="home-panel">
			<RadCartesianChart  tkExampleTitle tkToggleNavButton>
				<CategoricalAxis tkCartesianHorizontalAxis verticalLocation="Bottom" labelSize="11"></CategoricalAxis>
				<LinearAxis tkCartesianVerticalAxis tkCartesianVerticalAxis horizontalLocation="Left" labelSize="11"></LinearAxis>
				<BarSeries tkCartesianSeries [items]="categoricalSource" categoryProperty="Country" valueProperty="Amount"></BarSeries>
			</RadCartesianChart>
		</StackLayout>
	</ScrollView>
</GridLayout>
```
