### ISSUE TITLE
Frame content disappear on pause, reload on resume

### ISSUE THREAD

**Issue by tsonevn** [telerik/nativescript-ui-feedback#902]
_From @farfromrefug on October 27, 2018 20:13_

**Describe the bug**
Kind of related to https://github.com/NativeScript/NativeScript/issues/6188
Happening with 4.1.2 and 5.0.0 (next)

**To Reproduce**
https://play.nativescript.org/?template=play-tsc&id=VNkHaw&v=4
Scroll a bit,
Open recent apps,
Resume,
The scroll goes back to 0
**Expected behavior**
It should not move

**Sample project**
https://play.nativescript.org/?template=play-tsc&id=VNkHaw&v=4

**Additional context**

First i discovered that bug with nativescript Mapbox and nativescript Cart (Carto Mobile SDK).
When using fragments, and pausing (recent apps) while seeing the map, you see the app activity getting black. It redraws while resuming the app.

Can't post a playground sample with mabpox though as it is native. 

_Copied from original issue: NativeScript/NativeScript#6468_

**Comment by farfromrefug** [comment]
@tsonevn why do you put that here? It is not telerik UI related. This is an issue with android Fragments. As i mentioned this is not only an issue with the radlistview, radilistview is just a simple way to show it!

**Comment by tsonevn** [comment]
Hi @farfromrefug,
This issue seems to be related to the `RadListView` component. This issue cannot be recreated while using the ListView provided by the `tns-core-modules`.

**Comment by farfromrefug** [comment]
@tsonevn I am sure it is Fragment related! Once again this does not happen when not using fragment (thus frame). Maybe i should have shown an example with mapbox which gets black (any opengl es view) @manoldonev found that issue with tabview. But it is not only happening with tabview!.
You see it with radilistview and maybe not the listview because the radlistview is recreated somehow and somewhere in the radlistview code, the content offset is put back to 0.
I hope

**Comment by tsonevn** [comment]
Hi @farfromrefug,
There was an issue with the Fragment, which was related to some changes made for the upcoming version of the NativeScript for using the new **support library**. This problem **should be fixed** with the **latest next version**. Regarding that, make sure that you are using the **most recent published next version** of the `tns-core-modules`. The issue, which you are facing with the official version might be different because the changes made for the **new support library** are not included in version `4.2`.

If you still think that this is a bug with the **Fragment in tns-core-modules**, please provide a sample project, where the issue can be recreated while using the **components provided by `tns-core-modules`**.

Thank you in advance for your cooperation.

**Comment by farfromrefug** [comment]
@tsonevn i am using next version as explained in my issue. And i can't provide a sample which fails with the tns-core-modules because it wont fail! The best way to see it is with GLTextureView which get destroyed on pause (Mapbox nativescript plugin for example). It wont fail with tns-core-modules because you wont see any issue even if the view is recreated on resume.

**Comment by tsonevn** [comment]
Hi @farfromrefug, 
Regarding the resetting offset of the RadListView.  This is happening, because you are loading the items on `loaded` event.  You can check that when you set up the source to the component on page `navigatedTo` event the scroll position will not be reset and the RadListView will restore its state properly. When you are using the `loaded` event for populating the data, the items will be set again on every app resume and will make the illusion that something is recreated. [Example](https://play.nativescript.org/?template=play-tsc&id=VNkHaw&v=102).

**Comment by farfromrefug** [comment]
@tsonevn thanks for the explanation. But "loaded" should not be called again on resume! Why would a view be recreated on resume? 
```callLoaded``` is called when ```_setupUI``` is called, or in our case when ```onCreateView``` is called on a fragment.
This should not happen on fragment resume. And this is my bug report :D 

Your solution of using ```navigatedTo``` works but is just "masking" the original issue.

**Comment by tsonevn** [comment]
HI @farfromrefug,
After discussing your case with the dev team it seems that calling the `loaded` event on app resume is expected behaviour, This is also described in NativeScript docs. Check out the article [here](https://docs.nativescript.org/core-concepts/navigation#loaded).

**Comment by farfromrefug** [comment]
@tsonevn can you explain why the views are recreated on app resume? Does not really make sense to me. It would mean that any state is lost between pause and resume.
See the [android lifecycle](https://developer.android.com/guide/components/activities/activity-lifecycle). ```onCreate```, which is where views are supposed to be created, is not called when resuming

**Comment by manoldonev** [comment]
@farfromrefug loaded event is fired for NativeScript views on app resume but that is the JavaScript layer -- native Android / iOS view instances are not recreated on app resume (you can check it with debugger).

**Comment by farfromrefug** [comment]
@manoldonev i see now in the call that you can call ```onUnloaded``` and ``` onLoaded``` without actually destroying the native views. But i can't find where  there are called for pause/resume.
I dont even see any reference to onResume/onPause

**Comment by manoldonev** [comment]
On suspend/resume the chain of events is triggered by Android calling NativeScriptActivity.onStart(), then in our ActivityCallbacksImplementation.onStart(...) we call loaded on the rootView https://github.com/NativeScript/NativeScript/blob/6531d7aa238014f217ac0ac8948663b18f3f5150/tns-core-modules/ui/frame/frame.android.ts#L968 (in VSCode you can see the stack trace with debugger breakpoints).

**Comment by farfromrefug** [comment]
@manoldonev that s what i was afraid of. Why is ```onStart``` called? I am almost sure this should not be called while resuming app put in background. The app should got directly to onResume without going through onStart. That might be the reason of the bug i am seeing with fragments.
![image](https://user-images.githubusercontent.com/655344/48209106-a3e1dd00-e374-11e8-961e-60431b8b49d0.png)

**Comment by manoldonev** [comment]
@farfromrefug I don't think we are doing anything to tamper with the Android lifecycle -- NativeScriptActivity is basically an android.support.v7.app.AppCompatActivity.

As far as I can tell when suspending / resuming the app it is normal for OnStop() / OnStart() to get called -- see discussion for OnPause / OnStop here: https://stackoverflow.com/questions/9266417/difference-between-onpause-and-onstop. Should be the same for OnResume / OnStart.

**Comment by farfromrefug** [comment]
@manoldonev i have run some tests and indeed onStop is called on recent apps or home button. Seems weird to me.... I was almost sure.
So it explains the loaded event. So that telerik issue can be claused. I mean it explains the scrolling going back to 0.

The main issue though (for which i though the scroll change was the reason) is still here. 
With what you said it makes me think that one thing which changed between 4.2.0 and 5.0.0 is the use of the compat lib for activities and fragments. 
That might be where the error started.

Did you have time to try the mapbox example?

**Comment by manoldonev** [comment]
Just ran the demo at https://github.com/EddyVerbruggen/nativescript-mapbox/tree/master/demo with 5.0 dependencies for modules / runtime but other than the problem described in the Readme ("4.4.0 may crash on Android when pausing and resuming the app") the demo app seems to be working as expected with version 4.3.1 of the plugin.

**Comment by manoldonev** [comment]
Also, initially you mentioned that you are experiencing the problem with tns-core-modules@4.1.2 -- if that is the case, it cannot be related to the recent support library changes.

**Comment by farfromrefug** [comment]
@manoldonev i.might be wrong bit I think that sample does not use fragments ? (frame)

**Comment by manoldonev** [comment]
@farfromrefug it has an implicit root frame (fragment) as [it uses](https://github.com/EddyVerbruggen/nativescript-mapbox/blob/master/demo/app/app.ts) the [now deprecated] application.start(...) api that automatically created a Frame for you prior to NativeScript 4.0. It is practically equivalent to calling application.run(...) and placing a root Frame in the xml so I did not find it necessary to update the demo.

**Comment by farfromrefug** [comment]
@manoldonev let me prepare a sample that fails. And i can show that without frame it works, without it wont
