### ISSUE TITLE
Selecting an item on Android resets scroll position to the first item

### ISSUE THREAD

**Issue by zbranzov** [telerik/nativescript-ui-feedback#906]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
_Yes
### Tell us about the problem
Selecting an item on Android resets scroll position to the first item

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** nativescript-ui-listview commit 818f5b69830814c57b5b3fbde6984c401996fcde
- **CLI:** "^4.2.0"
- **Cross-platform modules:** "^4.2.0"
- **Runtime(s):** "4.2.0"

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the vue demo > Item selection example
2. Selecting an item resets scroll position to first item https://screencast.com/t/rlzPR1XmR

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
repository's demo-vue

**Comment by VladimirAmiorkov** [comment]
CC @msaelices 
Mentioning you because I am moving this into "Testing" phase.
