### ISSUE TITLE
JS ERROR ReferenceError: Can't find variable: TKSideDrawerDelegate

### ISSUE THREAD

**Issue by Natalia-Hristova** [telerik/nativescript-ui-feedback#91]
@soeyanmin :
>Still having this issue even after applied suggested above in iOS but android is working fine.
>JS ERROR ReferenceError: Can't find variable: TKSideDrawerDelegate.
>
>Thanks for the help

**Comment by surpi** [comment]
Can you tell me how you solved this? Facing the same issue atm.
