### ISSUE TITLE
autoCompleteDisplayMode is ignored if set in the propertyAnnotations data 

### ISSUE THREAD

**Issue by msaelices** [telerik/nativescript-ui-feedback#921]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
_No_

### Tell us about the problem
_The `autoCompleteDisplayMode` value has no effect if is set in the `propertyAnnotations` data in the `RadDataForm.metadata_

### Which platform(s) does your issue occur on?
_Android_

Not tested on iOS.

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 3.7.4
- **CLI:** 4.3.0-2018-09-14-12226
- **Cross-platform modules:** 4.2.0
- **Runtime(s):** 4.2.0

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application
2. Go to the page with the autocomplete editor.
3. You will not see any tokens after completion.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

Attached a Vue example, but it is also not working on Angular:

```
import { AutoCompleteDisplayMode } from 'nativescript-ui-dataform'

export class Booking {
  public from: string = '';
  public to: string = '';
}

export default {
  template: `
  <Page>
    <StackLayout>
      <RadDataForm
        :source="booking"
        :metadata="bookingMetadata">
      </RadDataForm>
    </StackLayout>
  </Page>
  `,
  data () {
    return {
      booking: new Booking(),
      bookingMetadata: {
        'isReadOnly': false,
        'commitMode': 'Immediate',
        'validationMode': 'Immediate',
        'propertyAnnotations':
        [
          {
            'name': 'from',
            'displayName': 'From:',
            'index': 0,
            'editor': 'AutoCompleteInline',
            // >>>>> This does not have any effect
            'autoCompleteDisplayMode': AutoCompleteDisplayMode.Tokens,
            'valuesProvider': ["New York", "Washington", "Los Angeles", "Madrid"],
          },
        ]
      }
    };
  },
};
```

Also, as a side effect of that issue, if you define a default value with more than one String, it will raises an error because the `Tokens` mode is not applied. So you cannot change the `Booking` object to that:

```
export class Booking {
  public from: string = Array<String> = new Array('New York', 'Washington'),
  public to: string = '';
}
```

**Comment by zbranzov** [comment]
The fix is released in nativescript-ui-dataform@3.9.0
