### ISSUE TITLE
RadListView - tkListLoadOnDemandTemplate - Label property binding not works

### ISSUE THREAD

**Issue by miroslavaivanova** [telerik/nativescript-ui-feedback#93]
## Please, provide the details below:

I am using RadListView with tkListLoadOnDemandTemplate directive for load more action. When I want to use property binding to set the "Load More" label in my component, it fails and only shown blank label on page.

**Which platform(s) does your issue occur on?**

iOS/Android/Both
iOS: show blank label
Android: always show "LOAD MORE" in label

**Please provide the following version numbers that your issue occurs with:**

│ Component │ Current version │ Latest version │ Information │
│ nativescript │ 2.4.2 │ 2.4.2 │ Up to date │
│ tns-core-modules │ 2.4.3 │ 2.4.3 │ Up to date │
│ tns-android │ 2.4.1 │ 2.4.1 │ Up to date │
│ tns-ios │ 2.4.0 │ 2.4.0 │ Up to date │

nativescript-telerik-ui-pro: 1.5.1_184

**Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.**

Component template:

```html
<GridLayout>

    <RadListView id="testList" [items]="contacts | async" loadOnDemandMode="Manual" (loadMoreDataRequested)="onLoadMoreItemsRequested($event)" [listViewLayout]="layout">

        <template tkListItemTemplate let-contact="item">
            <StackLayout (tap)="toDetail()">
                <Label [text]="contact.name"></Label>
            </StackLayout>
        </template>

        <GridLayout *tkListLoadOnDemandTemplate class="loadOnDemandItemGridLayout">
            <Label [text]="loadMoreLabel" horizontalAlignment="center" verticalAlignment="center"></Label>
        </GridLayout>

    </RadListView>

</GridLayout>
```
Component code:
```type script
export class ItemListComponent implements OnInit {

    itemList: RadListView;

    loadMoreLabel = 'Load More Items';

...
```

iOS:
<img width="374" alt="image1" src="https://cloud.githubusercontent.com/assets/4198315/23705995/06639090-0415-11e7-95bb-baa8dc30deed.png">

Android:
<img width="593" alt="image2" src="https://cloud.githubusercontent.com/assets/4198315/23706014/16d864d2-0415-11e7-9859-e11291c75b7b.png">

**Comment by VladimirAmiorkov** [comment]
Duplicated with https://github.com/telerik/nativescript-ui-feedback/issues/56
