### ISSUE TITLE
RadDataForm does not reliably update source object

### ISSUE THREAD

**Issue by stefan-kolb** [telerik/nativescript-ui-feedback#932]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
RadDataForm does not reliably update the source object with default commit mode immedately.
I'm using RadDataForms 3.8.0.
Sometimes only an external trigger like console logging of the underlying source object triggers the commit of the changes.

### Which platform(s) does your issue occur on?
Android (only tested Android)

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 3.8.0
- **CLI:** 5.0.0
- **Cross-platform modules:** 5.0.2
- **Runtime(s):** 5.0.0

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application
2. Toggle switch
3. Untoggle switch
4. Sometimes the submit button does not get disabled or enabled

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

See Playground app:
https://play.nativescript.org/?template=play-ng&id=YCOcMi&v=11

**Comment by stefan-kolb** [comment]
Possibly related? #625.
Also, the boolean property of the Switch only gets updated once and stays true forever aftwerwards.
However, the validations are fine, but the button still does not update its enabled state based on the validation method.

**Comment by stefan-kolb** [comment]
Or is this a change detection problem and I need to manually update a property that contains the validation status via the propertyValidated events?

**Comment by tsonevn** [comment]
Hi @stefan-kolb,
Thank you for the provided sample project.
I tested it on my side on a device with Android 8, however, was unable to recreate the reported issue(the change detection of the switch and submit buttons work as expected).  Regarding that, can you provide more info about the device you are using?

**Comment by stefan-kolb** [comment]
Does the Submit button automatically toggle its enabled state correctly for you? It only works when I manually use the Update button. I expect the Submit button to automatically change on detected Validation state!

**Comment by tsonevn** [comment]
Hi @stefan-kolb,
Excuse me for the delayed reply.
I reviewed your case again and would suggest using the RadDataForm's `propertyValidate` and `propertyValidated` while validating the data in the component. You can check the example [here](https://github.com/telerik/nativescript-ui-samples-angular/blob/master/dataform/app/examples/validation/validation-events/dataform-validation-events.component.html) and the attached project.
[Archive.zip](https://github.com/telerik/nativescript-ui-feedback/files/2685892/Archive.zip)

**Comment by stefan-kolb** [comment]
Thanks for your info. I hoped that this would work out of the box, tho.
