### ISSUE TITLE
JavaScript error: undefined:7:68: JS ERROR TypeError: undefined is not an object (evaluating 'b.prototype')

### ISSUE THREAD

**Issue by loqinyahuive** [telerik/nativescript-ui-feedback#935]
When I use the sidedrawer component, I get an error. Here is my app.module.tns.ts file and error message, need help.
app.module.tns.ts

`import { NgModule, NO_ERRORS_SCHEMA, NgModuleFactoryLoader } from '@angular/core';
import { NativeScriptModule } from 'nativescript-angular/nativescript.module';
import { StoreModule } from '@ngrx/store';
import * as fromState from './store';
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { LoginComponent } from './components/login/login.component';
import { EffectsModule } from '@ngrx/effects';
import { AppEffects } from './app.effects';
import * as fromUser from './reducers/user.reducer';
import * as fromProfile from './reducers/profile.reducer';
import * as fromMessage from './reducers/message.reducer';
import { UserEffects } from './effects/user.effects';
import { SelfHttp } from './api/http.service';
import { HomeComponent } from './components/home/home.component';
import { ChatComponent } from './components/chat/chat.component';
// import { ProfileEffects } from './effects/profile.effects';
import { MessageEffects } from './effects/message.effects';

// Uncomment and add to NgModule imports if you need to use two-way binding
import { NativeScriptFormsModule } from 'nativescript-angular/forms';
import { NativeScriptCommonModule } from "nativescript-angular/common";
// Uncomment and add to NgModule imports  if you need to use the HTTP wrapper
import { NativeScriptHttpClientModule } from 'nativescript-angular/http-client';
import { RadSideDrawerComponent } from "nativescript-ui-sidedrawer/angular";

@NgModule({
  declarations: [
    AppComponent,
    LoginComponent,
    HomeComponent,
    ChatComponent
  ],
  imports: [
    NativeScriptModule,
    NativeScriptCommonModule,
    NativeScriptFormsModule,
    RadSideDrawerComponent,
    AppRoutingModule,
    NativeScriptHttpClientModule,
    StoreModule.forRoot({}),
    StoreModule.forFeature('state', fromState.reducers, { metaReducers: fromState.metaReducers }),
    EffectsModule.forRoot([AppEffects,UserEffects, MessageEffects]),
    StoreModule.forFeature('user', fromUser.reducer),
    StoreModule.forFeature('profile', fromProfile.reducer),
    StoreModule.forFeature('message', fromMessage.reducer)
  ],
  providers: [SelfHttp],
  bootstrap: [AppComponent],
  schemas: [NO_ERRORS_SCHEMA]
})
export class AppModule { }
`
error: 
`***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x105d4d2c1 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool, bool)
2   0x105d89a5f -[TNSRuntime executeModule:referredBy:]
3   0x10575ba83 main
4   0x109b8e575 start
5   0x1
JavaScript stack trace:
1   @undefined:7:68
2   __extends@[native code]
3   @file:///app/vendor.js:92683:14
4   ../node_modules/nativescript-ui-sidedrawer/ui-sidedrawer.common.js@file:///app/vendor.js:92859:2
5   __webpack_require__@file:///app/bundle.js:76:34
6   ../node_modules/nativescript-ui-sidedrawer/ui-sidedrawer.js@file:///app/vendor.js:92880:29
7   __webpack_require__@file:///app/bundle.js:76:34
8   @file:///app/vendor.js:92431:30
9   ../node_modules/nativescript-ui-sidedrawer/angular/side-drawer-directives.js@file:///app/vendor.js:92636:34
10  __webpack_require__@file:///app/bundle.js:76:34
11  ./app/app.module.ts@file:///app/bundle.js:1014:112
12  __webpack_require__@file:///app/bundle.js:76:34
13  ./main.ns.ts@file:///app/bundle.js:2175:92
14  __webpack_require__@file:///app/bundle.js:76:34
15  checkDeferredModules@file:///app/bundle.js:45:42
16  @file:///app/bundle.js:149:38
17  anonymous@file:///app/bundle.js:150:12
18  evaluate@[native code]
19  moduleEvaluation@[native code]
20  promiseReactionJob@[native co<…>
JavaScript error:
undefined:7:68: JS ERROR TypeError: undefined is not an object (evaluating 'b.prototype')`

**Comment by tsonevn** [comment]
Hi @loqinyahuive,
We reviewed your case, however, the given information is not enough to investigate further the issue. Please provide a sample project, which can be used for debugging.

**Comment by loqinyahuive** [comment]
hi @tsonevn, thank you for seeing my question and replying to me.
This is my demo about nativescript-ui-demo:  https://github.com/liutao0617/nativescript-ui-demo.
When the 'nativescript-ui-sidedrawer' component is injected into the app.module.tns.ts page, the startup will fail.
Start command:  npm run ios.

**Comment by loqinyahuive** [comment]
> Hi @loqinyahuive,
> We reviewed your case, however, the given information is not enough to investigate further the issue. Please provide a sample project, which can be used for debugging.

hi, can my problem be solved? I need you help.

**Comment by VladimirAmiorkov** [comment]
@loqinyahuive Can you update that project to use the latest tns-core-modules and runtimes. I see that you have referenced the latest 5.0.0 version of nativescript-ui-sidedrawer but the tns-core-modules are referenced as 4.2.0 [here](https://github.com/liutao0617/nativescript-ui-demo/blob/master/package.json#L37). The 5.0.0 version of nativescript-ui-sidedrawer has been designed to work with the 5.x.x version of NativeScript.

**Comment by loqinyahuive** [comment]
@VladimirAmiorkov  now my project can run. thank you for your help.
