### ISSUE TITLE
[iOS] RadListView: Items are overlapping each other

### ISSUE THREAD

**Issue by VeeK727** [telerik/nativescript-ui-feedback#936]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes. Could not find anything on this topic

### Tell us about the problem
I have my list two columns and the items are overlapping each other vertically. I tried applying height on many elements but it makes no difference. Check screenshot.

### Which platform(s) does your issue occur on?
_iOS 12.1 (Real device)

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 3.8.0
- **CLI:** 5.0.1
- **Cross-platform modules:** ^5.2.0-2018-11-15-221043-02
- **Runtime(s):** "tns-ios" - 5.0.0

### Please tell us how to recreate the issue in as much detail as possible.
Use the code below

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
XML
```
<lv:RadListView items="{{ categories }}" height="{{ listHeight }}">
	<lv:RadListView.listViewLayout>
		<lv:ListViewGridLayout scrollDirection="Vertical" itemHeight="{{width}}" spanCount="2" />
	</lv:RadListView.listViewLayout>
	<lv:RadListView.itemTemplate>
		<GridLayout rows="auto,auto" class="m-r-10 m-b-10" catId="{{ id }}" tap="toPurities" height="{{width}}">
			<i:ImageCacheIt row="0" stretch="aspectFit" width="{{ width }}" height="{{width}}" placeHolder="~/images/loading.jpg" errorHolder="~/images/loading.jpg" imageUri="{{ image }}" />
			<!-- <Image src="{{image}}" /> -->
			<StackLayout row="0" verticalAlignment="bottom" class="cat-caption">
				<Label text="{{ name }}" verticalAlignment="center" />
			</StackLayout>
		</GridLayout>
	</lv:RadListView.itemTemplate>
</lv:RadListView>
```

JS
```
http.request({
  url: config.apiUrl+"get.php",
  method: "POST",
  headers: { "Content-Type": "application/json" },
  content: JSON.stringify({
    auth: config.apiAuth,
    fields: "id, name, icon",
    table: "product_category",
    conditionsAnd: {
      type: (prodSearchCriteria.superCat == "silver" ? 1 : 2),
      status: 2
    }
  })
}).then(function(request){
  var response = JSON.parse(request.content);
  for (var i = 0; i < response.data.length; i++) {
  	categories.push({
  		id: response.data[i].id,
  		name: response.data[i].name,
  		image: config.siteUrl+"/img/icons/"+response.data[i].icon,
  		width: boxWidth
  	});
  }
  catVM.set("listHeight", boxWidth*response.data.length/2);
  console.log(categories);
}, function(error){
    console.log(JSON.stringify(error));
});
```
Screenshot
![img_0011](https://user-images.githubusercontent.com/11595460/48753676-e381c080-ecb4-11e8-9b51-7ceab7713ce6.jpg)

**Comment by VladimirAmiorkov** [comment]
Hi @VeeK727 ,

Can you provide us with a runnable project that showcases this issue. You can use the playground if it is easer. Also I see that you are using a custom component that shows images (`i:ImageCacheIt`), can you share with us what that component is?

**Comment by jkulubya** [comment]
I'm seeing similar issues with radlistview after upgrading to NS 5
![img_0fc6adbff54e-1](https://user-images.githubusercontent.com/7911793/48821060-bee72080-ed68-11e8-9cad-60c54fe4bf00.jpeg)

**Comment by tsonevn** [comment]
related to https://github.com/telerik/nativescript-ui-feedback/issues/846
