### ISSUE TITLE
[Feature request] RadCartesianChart two axis.

### ISSUE THREAD

**Issue by Kraften** [telerik/nativescript-ui-feedback#939]
Hi i'm working on a project using Nativescript and Telerik ui. I would like to request a feature that lest you add two y-axis to the chart. The feature would allow users of the chart to compare two different data series with different units of measurement. We are doing this now with the company's web page using Highcharts.
![dsc_0618 1](https://user-images.githubusercontent.com/15447708/48825620-349ebc80-ed68-11e8-8ddc-948aa72192c2.JPG)
 
Thanks for listening and keep up the great work!

**Comment by tgpetrov** [comment]
Hi @Kraften 
Thank you for the kind words.
The nativescript-ui-chart already supports having two axes. Here's an [example](https://github.com/telerik/nativescript-ui-samples/tree/master/chart/app/examples/axes/multiple). And here's a screenshot of the running app:
<img src="https://user-images.githubusercontent.com/6085251/53226929-62f0a880-3685-11e9-97cd-66154c3bda7e.png" width="300px"/>

**Comment by Kraften** [comment]
Wow this is amazing news to me! I will look through your example when i get the time, thanks a lot!
