### ISSUE TITLE
Fatal JavaScript exception - application has been terminated. [TNSRuntime executeModule:referredBy:

### ISSUE THREAD

**Issue by miroslavaivanova** [telerik/nativescript-ui-feedback#95]
from @Yamilquery

This app only works when running on the iPhone simulator, however, it does not work when I run it on my iPhone 7 Plus device.

My tns version: 2.5.2
Node version: v7.6.0
npm version: 4.3.0
IOS device version: 10.2.1

`$tns run ios --log trace`

I get the following error:
```terminal
BeforeHookName for command watch is before-watch
Executing before-watch hook from /Users/yamildiazaguirre/Documents/node/LAaps/tagger/nativescript-ui-samples-angular/sdkAngular/hooks/before-watch/nativescript-dev-typescript.js
Executing before-watch hook at location /Users/yamildiazaguirre/Documents/node/LAaps/tagger/nativescript-ui-samples-angular/sdkAngular/hooks/before-watch/nativescript-dev-typescript.js in-process
Validating before-watch arguments.
Found peer TypeScript 2.1.5
/usr/local/bin/node --max_old_space_size=4096 /Users/yamildiazaguirre/Documents/node/LAaps/tagger/nativescript-ui-samples-angular/sdkAngular/node_modules/typescript/lib/tsc.js --project /Users/yamildiazaguirre/Documents/node/LAaps/tagger/nativescript-ui-samples-angular/sdkAngular --watch --inlineSourceMap --inlineSources
Hook promises to signal completion
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x100545e20 -[TNSRuntime executeModule:referredBy:]
2   0x100051324 main
3   0x18385d5b8 <redacted>
JavaScript stack trace:
1   @file:///app/tns_modules/tns-core-modules/ui/core/dependency-observable.js:73:28
JavaScript error:
file:///app/tns_modules/tns-core-modules/ui/core/dependency-observable.js:73:28: JS ERROR Error: Property scrollDirection already registered for type ListViewLayoutBase.
```

**Comment by simonettoa** [comment]
I am in a similar situation, the error is a little different but similar.
I've just open an issue, see if someone will help and if it will be useful for us.

Below the error:

> Executing before-watch hook from /Users/asimonetto/Progetti/NativeScript/Progetti/TruckMe/hooks/before-watch/nativescript-dev-typescript.js
Found peer TypeScript 2.1.6
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x100639e20 -[TNSRuntime executeModule:referredBy:]
2   0x1000e5324 main
3   0x18932c5b8 <redacted>
JavaScript stack trace:
1   @file:///app/tns_modules/tns-core-modules/ui/core/dependency-observable.js:73:28
JavaScript error:
file:///app/tns_modules/tns-core-modules/ui/core/dependency-observable.js:73:28: JS ERROR Error: Property showOverNavigation already registered for type RadSideDrawer.

The issue that I opened is this: 
[https://github.com/telerik/nativescript-ui-feedback/issues/137](url)

**Comment by NickIliev** [comment]
Reported also via t.1100388

**Comment by ginev** [comment]
@NickIliev this should be addressed with 3.0.

**Comment by Habeeb-mohamed** [comment]
If i want continue working, What is the latest minimum working version(cli as well as nativescript-ui)?

**Comment by Habeeb-mohamed** [comment]
@NickIliev & @ginev . Even i tried to downgrade the cli,core,native ui. still i am getting error.
Is there any work around?

**Comment by ginev** [comment]
@Habeeb-mohamed the minimum version in which this will be working is NativeScript 3.0 and NativeScript UI 1.7.0 (due to a couple of days). NativeScript 3.0 is already available with @rc tag on NPM. We will soon upload the NativeScript UI 1.7.0 bits under this tag as well.

**Comment by Habeeb-mohamed** [comment]
@ginev Sounds good.

**Comment by Habeeb-mohamed** [comment]
Can i use @rc tag? Kindly let us know when we have a fix.

**Comment by ginev** [comment]
@Habeeb-mohamed we need to address a couple of issues and are aiming to release today or tomorrow. I will make sure to update you here.

**Comment by ginev** [comment]
@Habeeb-mohamed you can now use the rc tag to install the preview version of UI for NativeScript which targets NativeScript 3.0. Note that the public npmjs.com version of UI for NativeScript Pro displays a trial message but is not limited in functionality so you can use it for testing and prototyping until the official release is out.

**Comment by Habeeb-mohamed** [comment]
@ginev After upgrade, I am getting below error
```
tns info
All NativeScript components versions information
┌──────────────────┬────────────────────────┬────────────────┬───────────────┐
│ Component        │ Current version        │ Latest version │ Information   │
│ nativescript     │ 3.0.0-rc.1             │ 2.5.3          │ Up to date    │
│ tns-core-modules │ 3.0.0-rc.2             │ 2.5.2          │ Up to date    │
│ tns-android      │                        │ 2.5.0          │ Not installed │
│ tns-ios          │ 3.0.0-rc.1-2017-3-28-2 │ 2.5.0          │ Up to date    │
└──────────────────┴────────────────────────┴────────────────┴───────────────┘
```
**Error**
```
Found peer TypeScript 2.2.2
node_modules/nativescript-telerik-ui-pro/calendar/index.d.ts(4,10): error TS2305: Module '"/Users/x/x/node_modules/tns-core-modules/ui/core/bindable/bindable"' ha
s no exported member 'Bindable'.

node_modules/nativescript-telerik-ui-pro/chart/index.d.ts(5,10): error TS2305: Module '"/Users/x/x/node_modules/tns-core-modules/ui/core/bindable/bindable"' has n
o exported member 'Bindable'.

node_modules/nativescript-telerik-ui-pro/listview/index.d.ts(302,56): error TS2339: Property 'Bindable' does not exist on type 'typeof "/Users/x/x/node_modules/tn
s-core-modul...'.
```

**Package JSON**

```
"nativescript": {
    "id": "com.x.x",
    "tns-ios": {
      "version": "3.0.0-rc.1-2017-3-28-2"
    }
  },
  "dependencies": {
    "@angular/animations": "4.0.0",
    "@angular/common": "4.0.0",
    "@angular/compiler": "4.0.0",
    "@angular/core": "4.0.0",
    "@angular/forms": "4.0.0",
    "@angular/http": "4.0.0",
    "@angular/platform-browser": "4.0.0",
    "@angular/platform-browser-dynamic": "4.0.0",
    "@angular/router": "4.0.0",
    "libphonenumber-js": "^0.3.5",
    "nativescript-angular": "rc",
    "nativescript-calendar": "^1.2.1",
    "nativescript-cardview": "^1.3.2",
    "nativescript-fresco": "^1.0.16",
    "nativescript-i18n": "^0.1.6",
    "nativescript-iqkeyboardmanager": "^1.0.1",
    "nativescript-orientation": "^1.6.1",
    "nativescript-push-notifications": "^0.1.2",
    "nativescript-social-share": "^1.3.2",
    "nativescript-telerik-ui-pro": "next",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-xmlobjects": "^1.1.4",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.2.0",
    "tns-core-modules": "rc",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "~0.4.0",
    "typescript": "~2.2.1"
  }
```
Is there anything missing?

**Comment by ginev** [comment]
@Habeeb-mohamed, yes, as I mentioned, you must use the `rc` tag for `nativescript-telerik-ui-pro`. Right now you are using the `next` which is incompatible with NativeScript 3.0. Just change `next` to `rc` and delete the `node_modules` and `platforms` folders.
