### ISSUE TITLE
iOS: Missing listview header on ios when grouping is enabled

### ISSUE THREAD

**Issue by uzarsalan** [telerik/nativescript-ui-feedback#950]
When i enabled grouping in listview, there is no header anymore on ios

https://play.nativescript.org/?template=play-js&id=1PZKeM&v=18

**Comment by jonasjensen-brolstark** [comment]
Is there any news on this issue or any known workarounds?

**Comment by dottodot** [comment]
I'm having the same issue, any solutions please.

**Comment by tbozhikov** [comment]
Closing as this has been fixed in v 6.2.0
