### ISSUE TITLE
Using root RadSideDrawer together with `flat=true` ActionBar will add blank to each page

### ISSUE THREAD

**Issue by gogoout** [telerik/nativescript-ui-feedback#952]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
When using ng project and having a RadSideDrawer in the root. Set ActionBar `flat=true` will cause page having a strange offset.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:**   "nativescript-ui-sidedrawer": "5.0.0",
- **CLI:** (run `tns --version` to fetch it)
- **Cross-platform modules:** 5.0.1
- **Runtime(s):** 5.0.0

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application
![img_1136](https://user-images.githubusercontent.com/7570175/49254594-762d1700-f48e-11e8-936b-39a1bfa9ee2d.PNG)

2. Click Toggle flat, See a blank offset applied to page
![img_1137](https://user-images.githubusercontent.com/7570175/49254603-7e855200-f48e-11e8-977c-728ab2770d3a.PNG)

3. Click Toggle flat again, See the offset still there, but the blank are covered with color
![img_1138](https://user-images.githubusercontent.com/7570175/49254617-8513c980-f48e-11e8-8654-58e16748955b.PNG)

**Note** this issue is more noticeable with Iphone X, the bigger the safe area is, the more the offset is.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

https://play.nativescript.org/?template=play-ng&id=gD6Uo5&v=2

**Comment by gogoout** [comment]
Maybe related to https://github.com/NativeScript/NativeScript/issues/6063 . Please close the issue if this is not a RadSideDrawer issue

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#1638
