### ISSUE TITLE
Tokens are duplicated when screen is switched of

### ISSUE THREAD

**Issue by JackPoteYes** [telerik/nativescript-ui-feedback#959]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Did you verify this is a real problem by searching the [NativeScript Forum]
Yes

### Tell us about the problem
Tokens are duplicated when screen is switched of.

### Which platform(s) does your issue occur on?
Android@5.0.0

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** No such entry in package.json
- **CLI:** 5.0.3
- **Cross-platform modules:** ~5.0.2
- **Runtime(s):** Android 5.0.0
- **nativescript-ui-autocomplete**: 3.10.3

### Please tell us how to recreate the issue in as much detail as possible.
1. [Get this repo](https://github.com/JackPoteYes/autocomplete-issue-report)
2. tns platform add android@5.0.0
3. npm i
4. tns run android
5. Click button "Edit languages"
6. In the Edit languages modal, switch the screen off and then get back to the app.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
Runnable project: [https://github.com/JackPoteYes/autocomplete-issue-report](https://github.com/JackPoteYes/autocomplete-issue-report)

**Comment by tsonevn** [comment]
HI @JackPoteYes,
This seems to be expected behaviour when you are loading the Autocomplete items on `shownModally` event. To solve the case on your side, you can try calling `initAutoCompleteComponentData` on page's loaded event. For example:
languages-modal.xml
```
<Page shownModally="onShowModal" loaded="onloaded" xmlns="http://www.nativescript.org/tns.xsd" xmlns:au="nativescript-ui-autocomplete">
.......
</Page>
```
languages-modal.ts
```
exports.onloaded = function(args){
  console.log("on page loaded")
  page = args.object;
  autoCompleteTextViewComponent = page.getViewById("autoCompleteTextViewComponent");
  setTimeout(() => {
    initAutoCompleteComponentData();
  }, 100);
  
}
```

**Comment by tsonevn** [comment]
Hi @JackPoteYes,
I tested the `loaded` event on my side in our [sample project](https://github.com/NativeScript/nativescript-sdk-examples-js/blob/master/app/ns-ui-category/modal-view/basics/modal-view-page.xml), however, was unable to recreate an issue with the event execution. The loaded event will be executed on every opening of the modal view.
Can you try clearing up the project by deleting `node_modules`, `platforms`, `hooks`, `package-lock.json` and then rebuild it `tns run <platfrm_name>`?
