### ISSUE TITLE
RadList disappeared when scrollview is appiled top of it in IOS.

### ISSUE THREAD

**Issue by gopalshimpi** [telerik/nativescript-ui-feedback#963]
Hello every one...
I have created RadList  for my home page. It displayed on IOS & andoird both. But When I adds scrollview for scrolling whole page, RadList disappeared  from page. This happens only in ios. In android its working fine. How to fix this?

## category-list-component.html ( child component)
```
<GridLayout>
  <RadListView [items]="taxonomies">
    <ListViewGridLayout tkListViewLayout itemHeight=150% margin="1" spanCount="2"></ListViewGridLayout>
    <ng-template let-category="item" let-i="index" let-odd="odd">
      <StackLayout orientation="Vertical">
        <Label class="box" [backgroundImage]="categories[category.name].imageUrl" [text]="category.name"></Label>
      </StackLayout>
    </ng-template>
  </RadListView>
</GridLayout>
```
## homecomponent.html (parent component)

```
<GridLayout rows=" *, 40">
  <StackLayout row="0">
    <ScrollView>
      <FlexboxLayout flexDirection="column">
      <!-- child component -->
        <StackLayout categoryList [taxonomies]="taxonomies"></StackLayout>
      </FlexboxLayout>
    </ScrollView>
  </StackLayout>
  <StackLayout row="1" orientation="horizontal">
    <Label textWrap="true" class="login-label" (tap)="goToLogin()" text="Sign in"> </Label>
  </StackLayout>
</GridLayout>
```

**Comment by tsonevn** [comment]
Hi @gopalshimpi,
You can try to specify the height of the RadListView. For example:
```
<RadListView height="200" [items]="taxonomies">
    <ListViewGridLayout tkListViewLayout itemHeight=150% margin="1" spanCount="2"></ListViewGridLayout>
    <ng-template let-category="item" let-i="index" let-odd="odd">
      <StackLayout orientation="Vertical">
        <Label class="box" [backgroundImage]="categories[category.name].imageUrl" [text]="category.name"></Label>
      </StackLayout>
    </ng-template>
  </RadListView>
```
Note: it is not recommended nesting the ListView inside a ScrollView as it will create two elements, which using a scroll - as a result, this can slow down the app and also confuse the user.

**Comment by gopalshimpi** [comment]
Thanks for your replay @tsonevn.
 My application  dose not required use of RadListview,  but as i want to display grid using array so I choose to go with radListview beacause its ability to make gird using array with spanCount property.  Do you have any idea that how to create grid dynamically for one dimensional array without radLlist?
