### ISSUE TITLE
RadAutocompleteTextView fetch async data - when i call resolve() or reject() I see the loader rotate

### ISSUE THREAD

**Issue by progressify** [telerik/nativescript-ui-feedback#969]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
_No, I have searched only in the GitHub issues: https://github.com/telerik/nativescript-ui-feedback/issues_

### Tell us about the problem
_Please, ensure your title is less than 63 characters long and starts with a capital
letter._

### Which platform(s) does your issue occur on?
_I have tested only on Android_

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** (the version of nativescript-telerik-ui/-pro in the `package.json`)
"nativescript-ui-autocomplete": "^3.10.2",
- **CLI:** (run `tns --version` to fetch it) 
4.2.4
- **Cross-platform modules:** (the version of tns-core-modules in the `package.json`)
- **Runtime(s):** (the `"tns-android"` and `"tns-ios"` properties in the `package.json`) 
tns-android: 5.0.0
tns-ios: 4.2.0

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application
2. in the autocomplete text write  # and appear the loader (I expect I see "Inserisci #", the text in the noResultsText attribute)
3. if I write another character work perfectly 
4. if I delete the character after the # you can see this (I expect I see "Inserisci #" again):
![screenshot_20181219-193415](https://user-images.githubusercontent.com/11472632/50240502-473afe80-03c5-11e9-92a1-77976b12bbb7.png)
(the loader is on the list, the list is not cleared)
5. if I click on one element of this list the application crash.
![screenshot_20181219-193706](https://user-images.githubusercontent.com/11472632/50240621-89fcd680-03c5-11e9-94ae-3bed53c762b8.png)

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

```
<RadAutoCompleteTextView #autocompleteTag
                                     hint="Massimo 6"
                                     noResultsText="Inserisci #"
                                     (tokenAdded)="onTagTokenAdded($event.text)"
                                     (tokenRemoved)="onTagTokenRemoved($event.text)"
                                     suggestMode="Suggest" displayMode="Tokens">
                <SuggestionView tkAutoCompleteSuggestionView suggestionViewHeight="100">
                    <ng-template tkSuggestionItemTemplate let-item="item">
                        <StackLayout orientation="horizontal" padding="10">
                            <Label text="&#xf292;" class="font-awesome m-r-8"></Label>
                            <Label verticalAlignment="center" class="h3" [text]="item.text"></Label>
                        </StackLayout>
                    </ng-template>
                </SuggestionView>
            </RadAutoCompleteTextView>
```

```
this.autocompleteTag.autoCompleteTextView.loadSuggestionsAsync = function (txt) {
            const promise = new Promise(function (resolve, reject) {
                if (txt[0] == "#") {
                    MyClass.staticService.getTag(txt).subscribe(
                        (response) => {
                            const items: Array<TokenModel> = [];
                            for (let obj in response) {
                                items.push(new TokenModel(response[obj]['tag'], null));
                            }
                            resolve(items);
                        },
                        (error) => {
                            console.log(error);
                            reject();
                        }
                    );
                } else {
                    // when this is called the loader is showed
                    resolve([]);
                    // reject(); 
                }
            });

            return promise;
        };
```

**Comment by tsonevn** [comment]
Hi @progressify,
I have tested the described scenario within a sample app, and the Autocomplete component seems to work as expected. It is expected the loading indicator to be shown while the fetch request is executed. The text declared with the `noResultsText` property (in your case - `Inserisci #`) will be shown when the Promise has been resolved with empty array(when no results have been found). In the else statement, you can set the `resolve([])` in a timeout of 100 milliseconds. This will return the result properly from the promise, and the `noResultsText` message will be shown. For example:
```
else {
                    // when this is called the loader is showed
                    setTimeout(() => {
                        resolve([])
                    }, 100);
                    // reject(); 
                }
```
> Note: I was unable to recreate the crash. I am attaching the project that I have used for testing. Please review it and make the needed changes, which will allow us to reproduce the issue.

[Archive.zip](https://github.com/telerik/nativescript-ui-feedback/files/2698529/Archive.zip)

**Comment by lokeshkandala** [comment]
Hi @tsonevn , i have a similar issue . but my api will give 400 error when search results are empty. so spinner is still loading even after entering reject() callback and modal is still open

**Comment by progressify** [comment]
Hi, thanks for your reply
I have downloaded your code, and now I check what can be my error
I give you feedback later

**Comment by progressify** [comment]
Hi, @tsonevn I have used your code (with setTimeout in else statement) and now it's work good.
thanks a lot <3
