### ISSUE TITLE
Radlistview is not sliding horizontally

### ISSUE THREAD

**Issue by miroslavaivanova** [telerik/nativescript-ui-feedback#97]
from @SumanSingh4

Output is
![image4](https://cloud.githubusercontent.com/assets/4198315/23711194/d4f7dad0-0427-11e7-98e1-4ab56c2983e9.png)

slider is not sliding left or right. Any help

**Comment by VladimirAmiorkov** [comment]
@SumanSingh4 Can you comment on this issue as it was moved from our previous sdk repository and it was missing any other information that could help us further investigate it on our side.

**Comment by DimitarTodorov** [comment]
closing due to inacivity
