### ISSUE TITLE
RadPieChart whitout documentation to use events

### ISSUE THREAD

**Issue by mitscker** [telerik/nativescript-ui-feedback#979]
There's not documentation, to use events, when on any RadPieChart is tapped, i'll was searched, but without found anything. 

I want use un event to execute a method, after extract the selected data.

code:
```
<chart:RadPieChart id="piechart" height="300" allowAnimation="false" row="0">
            <chart:RadPieChart.series>
                <chart:PieSeries selectionMode="DataPoint" expandRadius="0.3" outerRadiusFactor=".7" items="{{ pieSource }}" valueProperty="Amount" legendLabel="Brand">
                </chart:PieSeries>
            </chart:RadPieChart.series>

            <chart:RadPieChart.legend>
                <chart:RadLegendView position="Right" title="Brands" offsetOrigin="TopRight" width="110" enableSelection="true"/>
            </chart:RadPieChart.legend>
        </chart:RadPieChart>

```

**Comment by tsonevn** [comment]
Hi @mitscker,
Check out the link [here](https://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/Chart/Behaviors/selection#handling-selection-events). In the article, you will find the supported RadChart's **selection** events and examples, that shows their usage.

Let me know if I can assist you further.
