### ISSUE TITLE
[iOS] RadListView. Scrolling breaks layout.

### ISSUE THREAD

**Issue by trunkovich** [telerik/nativescript-ui-feedback#988]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

## Please, provide the details below:

After some scrolling up and down I got broken layout for items, where we have *ngIf directive.
https://play.nativescript.org/?template=play-ng&id=jq0KuQ
scroll down, to the end of the list. After that scroll up and you will probably see a bug, when "book now" label "jump" up onto "title" label

### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
RadListView + *ngIf inside item breaks layout on iOS device after scrolling.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
nativescript-ui-listview: 5.0.1
tns: 5.1.0
tns-core-modules: 5.1.0
tns-ios: 5.1.0

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application
2. Scroll list down
3. You will see `Book now` Labels above several items (*ngIf used).
4. Scroll to the end of the list.
5. Scroll back to block with `Book now`.
6. Some `Book now` Labels will be on the `title` label.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
https://play.nativescript.org/?template=play-ng&id=jq0KuQ

**Comment by tsonevn** [comment]
Hi @trunkovich,
Thank you for the provided sample project.
I was able to recreate the issue on my side and will mark it as a bug. As a temporary solution, I would suggest to set up the label inside a GridLayout with specified rows height. For example:
```
<GridLayout rows="50 50" columns="">
                    <StackLayout row="0">
                        <Label [text]="bid.title"></Label>
                    </StackLayout>

                    <GridLayout row="1" *ngIf="bid.show">
                        <Label [text]="'Book now'"></Label>
                    </GridLayout>
</GridLayout>
```

**Comment by tsonevn** [comment]
Hi @trunkovich,
To workaround the issue you can try setting up the `itemHeight` property for the RadListView items. Check out the demo [here](https://play.nativescript.org/?template=play-ng&id=jq0KuQ&v=3).
