### ISSUE TITLE
RadlistView feature request - to be able to stop a reorder

### ISSUE THREAD

**Issue by Natalia-Hristova** [telerik/nativescript-ui-feedback#99]
from @sflament

>Hello,
>
>I don't know if it's already possible.
>
>I would like to stop an reorder attempt on some items in the list.
>To check if the item is authorized or not to be moved, I think to throw a stop reorder action inside >the ReorderStartEvent function. I don't know how to abort the ongoing reorder.
>
>Stéphane

**Comment by dunqan** [comment]
I'm also looking for a solution on this.
There is canReorder method in  Telerik UI for Android in ListViewAdapter. Maybe it can be exposed or accessed somehow in nativescript radlistview?

**Comment by ginev** [comment]
@dunqan - the `canReorder` method does exactly that, however there's no similar functionality for iOS and we will have to implement it to expose it universally through `RadListView` for NativeScript. We will log this in our TODO list for the next iteration. Thanks!

**Comment by Natalia-Hristova** [comment]
@dunqan this is implemented and it will be available in our next official release. If you want to test it out before that you can use the "next" version of the nativescript-telerik-ui-pro plugin. Simply install that version of the plugin: ``` tns plugin add nativescript-telerik-ui-pro@next``` . 

**NOTE** that the next version is updated on daily/hourly basis from our current development brach which makes it not a good option for production applications but it is a great way to verify fixes and test new functionality.
