### ISSUE TITLE
Outdated getting started docs for NS-UI with Vue 

### ISSUE THREAD

**Issue by msaelices** [telerik/nativescript-ui-feedback#990]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
_Yes_

### Tell us about the problem
_The getting started doc in https://docs.telerik.com/devtools/nativescript-ui/Controls/Vue/getting-started is outdated, compared with the Chart doc https://docs.telerik.com/devtools/nativescript-ui/Controls/Vue/Chart/getting-started_

### Which platform(s) does your issue occur on?
N/A

**Comment by tgpetrov** [comment]
The updated docs have been published.
