### ISSUE TITLE
[NS-Vue] RadListView Height calculation issue when the item has vertical margin and there is a pull-to-refresh action

### ISSUE THREAD

**Issue by msaelices** [telerik/nativescript-ui-feedback#992]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
_Yes_

### Tell us about the problem

![pull-to-refresh](https://user-images.githubusercontent.com/136875/51129747-87a66480-182b-11e9-893b-d5e11e647869.gif)

### Which platform(s) does your issue occur on?
_iOS_

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 5.1.0
- **CLI:** 5.1.0
- **Cross-platform modules:** 5.1.0
- **Runtime(s):** 5.1.0

### Please tell us how to recreate the issue in as much detail as possible.

1. Open the `PullToRefresh.ts` file in the `demo-vue` app.
2. Put a `style="margin:16"` attribute in the `item` element, like this:
```
    <StackLayout class="item" orientation="vertical" style="margin: 16">
       ...
    </StackLayout>
```
3. Start the demo-vue application
4. Trigger a Pull-to-refresh event.

**Comment by msaelices** [comment]
I will write down my further investigations...

After the pull-to-refresh trigger, it seems to ignore the needed height to show the entire cell, even when I put `height: 50` in the `style` attribute but it keeps the other styles (i.e. background color).

You can see it in action here:

![pull-to-refresh-2](https://user-images.githubusercontent.com/136875/51180712-61cf9d00-18c9-11e9-9791-231ab3937270.gif)

All my attempts of calling `refresh()`, `clearCellsAndUpdateHeaderFooter()`, `clearRealizedCells()`, etc. simply do not work.

The only way to fix it is deleting the `RadListView` node from the template and re-adding it again, like this:

```
export default {
  ...
  template: `
  ...
  <RadListView v-if="show"
               ...
               @pullToRefreshInitiated="onPullToRefreshInitiated">
    ...
  </RadListView>
  ...`,
  methods: {
    onPullToRefreshInitiated ({ object }) {
      ...
      this.fruitList.push({
        name: 'Berry',
      });
      object.notifyPullToRefreshFinished();

      // delete the RadListView node entirely
      this.show = false;
      this.$nextTick(() => {
        // re-add the RadListView node
        this.show = true;
      });
    },
  },
```

**Comment by msaelices** [comment]
Great news. It's working on the latest master branch

**Comment by msaelices** [comment]
I will leave this issue open until the next NPM version of `nativescript-ui-listview` was released.

**Comment by zbranzov** [comment]
It works in 5.1.1
