### ISSUE TITLE
RadListView.notifyLoadOnDemandFinished is not a function

### ISSUE THREAD

**Issue by krgolovan** [telerik/nativescript-ui-feedback#995]
I have an error RadListView.notifyLoadOnDemandFinished is not a function (tried both Android / iOS). Wrapped listView.notifyLoadOnDemandFinished() in a setTimeout as it advised in [this issue](https://github.com/telerik/nativescript-ui-feedback/issues/511) but it didn't help. Here is a link to [playground](https://play.nativescript.org/?template=play-vue&id=BgquKt&v=4).

**Comment by tsonevn** [comment]
Hi @krgolovan,
From your very last comment, I am assuming that you were able to fix the issue on your side. I think that we can close this issue.
